aws-amplify/amplify-js

media/storage_guide.md

chore(storage_guide.md): Fix grammatical error

---

happy-npm-build

Deletes happy-npm-build

---

packages/aws-amplify-react-native/dist/Analytics/Analytics.js
packages/aws-amplify-react-native/src/Analytics/Analytics.js

Pinpoint region

---

media/api_guide.md

As per #123, there's a small typo / syntax error, which this PR fixes.

Fix syntax error - as per #123

---

packages/aws-amplify/package.json

fix aws-sdk package

---

packages/aws-amplify-react-native/package.json

 fix aws-sdk package

---

packages/aws-amplify-react-native/src/components/auth/Authenticator.js
packages/aws-amplify/src/API/RestClient.ts
packages/aws-amplify/src/Common/index.ts

fix RN props

---

media/api_reference.md

Hi guys,
As I see the old link is broken.
Please let me know if I set the correct link.
Thanks

Fix API reference link api_reference.md 

---

packages/aws-amplify/src/Cache/StorageCache.ts

For issue https://github.com/aws/aws-amplify/issues/208

cache config minor fix

---

docs/media/analytics_guide.md
docs/media/quick_start.md

- fix a typo
- update quick start with cli instructions

minor documentation updates

---

docs/media/quick_start.md

update quickstart for Expo language and save deps for react native packager

Update quickstart doc

---

packages/aws-amplify-react-native/dist/index.js
packages/aws-amplify-react-native/src/index.js

Output warning message to console if calling Amplify.configure() on aws-amplify-react-native

rn configure deprecate warning

---

docs/media/authentication_guide.md

Fixes #282
Update docs to include how to retrieve current session

update how to return a session

---

packages/aws-amplify-react/__tests__/Storage/__snapshots__/S3Album-test.js.snap
packages/aws-amplify-react/dist/Auth/AuthPiece.js
packages/aws-amplify-react/dist/Auth/ConfirmSignIn.js
packages/aws-amplify-react/dist/Auth/ConfirmSignUp.js
packages/aws-amplify-react/dist/Auth/ForgotPassword.js
packages/aws-amplify-react/dist/Auth/RequireNewPassword.js
packages/aws-amplify-react/dist/Auth/SignIn.js
packages/aws-amplify-react/dist/Auth/SignUp.js
packages/aws-amplify-react/dist/Auth/VerifyContact.js
packages/aws-amplify-react/src/Auth/AuthPiece.jsx
packages/aws-amplify-react/src/Auth/ConfirmSignIn.jsx
packages/aws-amplify-react/src/Auth/ConfirmSignUp.jsx
packages/aws-amplify-react/src/Auth/ForgotPassword.jsx
packages/aws-amplify-react/src/Auth/RequireNewPassword.jsx
packages/aws-amplify-react/src/Auth/SignIn.jsx
packages/aws-amplify-react/src/Auth/SignUp.jsx
packages/aws-amplify-react/src/Auth/VerifyContact.jsx

Copy the change in pr #199 to aws-amplify-react to keep synced.

A duplicate for pr #199

---

docs/media/storage_guide.md
packages/aws-amplify/__tests__/Storage/Storage-unit-test.ts
packages/aws-amplify/src/Storage/Storage.ts

Hello guys,
Here is a PR for issue #280 
Please let me know what you think on this.
Thank you!

Add expires key to s3.get()

---

packages/amazon-cognito-identity-js/index.d.ts

They were failing in TypeScript strict mode

Fix amazon-cognito-identity-js typings

---

packages/aws-amplify/__tests__/Auth/auth-unit-test.ts
packages/aws-amplify/src/Auth/Auth.ts

*Issue #328 
Make sure always check for user in Auth.currentUserInfo()

currentUserInfo should check for user if no credentials source

---

packages/aws-amplify-react/src/Auth/index.jsx

Hello guys,
Here is a PR for issue #363
Please check
Thanks

Export VerifyContact

---

docs/media/authentication_guide.md
packages/aws-amplify/__tests__/Auth/auth-unit-test.ts
packages/aws-amplify/src/Auth/Auth.ts

Hello guys,
Here is my attempt to close the issue #252
Please let me know if I'm in the right direction :)
Thanks

Add a method to change password for currently authenticated user

---

docs/media/push_notifications_setup.md

update push language

---

packages/amazon-cognito-identity-js/README.md

doc update

---

packages/aws-amplify/src/Storage/Storage.ts

Fixes #395
Make options parameter optional in Storage.put

Make options parameter optional in Storage.put

---

docs/media/analytics_guide.md

Fixed a grammatical error in the documentation.  Just doing my part to help the community.

fixed grammatical error in analytics guide

---

docs/media/authentication_guide.md

Giving an example of how to produce a string which can be used to generate the qr code

Totp doc update

---

docs/media/storage_guide.md

Fixes syntax error

---

packages/aws-amplify/src/Auth/Auth.ts

#510 
Users will get error when signing out if their identity pool doesn't allow unauthenticated access.

Sign out fix

---

docs/media/authentication_guide.md
packages/aws-amplify/src/Auth/Auth.ts

N/A
This will add support for custom federated providers

Adding custom federated auth provider

---

CHANGELOG.md
packages/amazon-cognito-identity-js/es/CognitoUser.js
packages/amazon-cognito-identity-js/lib/CognitoUser.js
packages/amazon-cognito-identity-js/package.json
packages/aws-amplify/src/Auth/Auth.ts

Publish new version of Cognito to include the ```es``` folder

cognito republish

---

docs/media/authentication_guide.md

Trivial typo
Fixed spelling of the word behaviour, keeping the British spelling since it already had a u in it.

Fixed incorrect spelling

---

packages/aws-amplify/__mocks__/paho-mqtt.js
packages/aws-amplify/__tests__/Common/Polyfills-test.ts
packages/aws-amplify/__tests__/PubSub/PubSub-unit-test.ts
packages/aws-amplify/src/Common/Polyfills/Polyfills.ts
packages/aws-amplify/src/Common/Polyfills/index.ts
packages/aws-amplify/src/PubSub/PubSub.ts

#588 fix issue
Increasing test coverage
Adding Polyfills.js 

Increase test coverage for PubSub and adding Polyfills.js to fix issue #588

---

packages/amazon-cognito-identity-js/README.md

#574
This change to the documentation adds clarity to the alerts displayed when an error occurs. 
Only affects the Amazon Cognito Identity SDK for JavaScript.

Clarify alert message error

---

packages/aws-amplify-react/__tests__/Auth/RequireNewPassword-test.js
packages/aws-amplify-react/package-lock.json
packages/aws-amplify-react/package.json
packages/aws-amplify-react/src/Auth/RequireNewPassword.jsx

set user to authData after new password set

---

packages/aws-amplify/src/Auth/Auth.ts

Typo Hanlder -> Handler in Auth.ts

---

packages/aws-amplify-react/src/Auth/Greetings.jsx
packages/aws-amplify/src/Common/Parser.ts

Google signout fix

---

packages/aws-amplify/src/PubSub/PubSub.ts

Don't add AppSync PubSub provider more than once

---

packages/aws-amplify-react/.babelrc
packages/aws-amplify-react/package.json

N/A
Fix problem when building aws-amplify-react

Fix build amplify-react

---

docs/_config.yml

doc menu update

---

docs/media/angular_guide.md

angular doc update

---

.github/CODEOWNERS
README.md
docs/media/angular_guide.md
docs/media/authentication_guide.md
docs/media/install_n_config.md
docs/media/quick_start.md

Angular documentation updates/additions

update angular docs

---

packages/aws-amplify/src/Auth/Auth.ts

Allow user sign in by Cognito hosted ui without credentials

---

README.md

N/A
Proposed updates to Readme

Proposed updates to readme with some new methods & added logo 

---

packages/aws-amplify-react/__tests__/Auth/RequireNewPassword-test.js
packages/aws-amplify-react/src/Auth/RequireNewPassword.jsx
packages/aws-amplify/__tests__/Auth/auth-unit-test.ts
packages/aws-amplify/src/Auth/Auth.ts

Fix Auth completeNewPassword

---

packages/aws-amplify-angular/src/components/authenticator/require-new-password.component.ts
packages/aws-amplify-angular/src/components/authenticator/sign-in.component.ts

#751 
Check for MFA after sign in.

angular sign in mfa check

---

docs/media/push_notifications_setup.md

*Issue 
fixes #798*
Current Firebase setup in the docs seems out of date. These changes bring the docs up-to speed.

Update firebase setup docs

---

packages/aws-amplify-react-native/package.json
packages/aws-amplify-react/package.json
packages/aws-amplify-react/src/API/GraphQL/Connect.js

Add peerDependencies for graphql

---

docs/_config.yml
docs/media/sample/service-worker.md
docs/media/service_workers_guide.md

service workers guide

---

packages/aws-amplify/__tests__/Common/ServiceWorker-test.ts
packages/aws-amplify/src/Common/Amplify.ts
packages/aws-amplify/src/Common/ServiceWorker/ServiceWorker.ts
packages/aws-amplify/src/Common/ServiceWorker/index.ts
packages/aws-amplify/src/Common/index.ts
packages/aws-amplify/src/index.ts

feat: Add ServiceWorker utility class

---

docs/media/quick_start.md

*Description of changes:* AppSync is missing from the list of features in the Quick Start guide. This pull request adds it to the list.

Add appsync to features in Quick Start

---

docs/media/storage_guide.md

The code sample as it is currently on `master` contains errors. This commit makes minor syntax changes to get it to run without errors.

Documentation: Fix code for sample S3ImageUpload component

---

packages/amazon-cognito-identity-js/README.md

This updates the README.md to more up-to-date configurations to allow new people to immediately be able to use this package.
If not updated the error you get is:
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
- configuration.module has an unknown property 'loaders'. These properties are valid:
object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, noParse?, rules?, defaultRules?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, unsafeCache?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp?, strictExportPresence?, strictThisContextOnImports? }
-> Options affecting the normal modules …
```

[amazon-cognito-identity-js] Update Webpack instructions

---

CHANGELOG.md
packages/aws-amplify-react/package.json
packages/aws-amplify-react/src/API/GraphQL/Connect.js

Revert a change in the API/Graphql/connect.js

deploy: aws-amplify-react-0.1.46

---

docs/media/api_guide.md
packages/aws-amplify/__tests__/API/API-test.ts
packages/aws-amplify/src/API/API.ts

OPENID Connect support for graphql

OIDC support for graphql 

---

CHANGELOG.md
packages/amazon-cognito-identity-js/package.json
packages/aws-amplify-react/package.json
packages/aws-amplify/package.json

Deploy: aws-amplify@0.4.1

---

docs/media/angular_guide.md

Revert "Ang6"

---

packages/aws-amplify-react-native/src/Auth/Authenticator.js

To fix the logic problem of function `checkUser` which will lead all unauth user jumping to the signIn page automatically.

Fix: component Authenticator checkUser logic

---

docs/media/api_guide.md
packages/aws-amplify/__tests__/API/API-test.ts
packages/aws-amplify/src/API/API.ts
packages/aws-amplify/src/API/RestClient.ts

#515 #697 
Adding custom headers callback function on API category on configure

Custom headers for API on configure

---

packages/aws-amplify-react-native/package.json

aws-amplify-react-native version bump

---

package.json

Update package.json [ci skip]

---

docs/media/authentication_guide.md

How to get a jwt token with federatedSignIn

---

packages/aws-amplify-angular/src/providers/auth.decorator.ts

Cognito HostedUI Auth State Change Listener for AWS Amplify Angular.
Fixes #922
Added an Event Listener using Hub middleware to Listen to the Auth events and triggered and Auth State Change to support Cognito Hosted UI state changes.

fix(aws-amplify-angular):Cognito HostedUI Auth State Change for Angular

---

docs/media/hub_guide.md

Previous exemple was 1) long and confusing, 2) didn't work out of the box, 3) was set to "debug" mode so it didn't appear in the console, 4) built a class for no apparent reason, 5) had misleading variable names

Update Hub's example for auth event tracking

---

packages/amazon-cognito-identity-js/package.json
packages/aws-amplify-react-native/package.json
packages/aws-amplify-react/package.json
packages/aws-amplify/package.json
yarn.lock

Fix npm versions [ci skip]

---

packages/aws-amplify-react/__tests__/Auth/AuthPiece-test.js
packages/aws-amplify-react/__tests__/Auth/ConfirmSignIn-test.js
packages/aws-amplify-react/__tests__/Auth/RequireNewPassword-test.js
packages/aws-amplify-react/__tests__/Auth/TOTPSetup-test.js
packages/aws-amplify-react/__tests__/Auth/VerifyContact-test.js
packages/aws-amplify-react/__tests__/Auth/__snapshots__/Authenticator-test.js.snap
packages/aws-amplify-react/__tests__/Auth/__snapshots__/ConfirmSignIn-test.js.snap
packages/aws-amplify-react/__tests__/Auth/__snapshots__/ConfirmSignUp-test.js.snap
packages/aws-amplify-react/__tests__/Auth/__snapshots__/FederatedSignIn-test.js.snap
packages/aws-amplify-react/__tests__/Auth/__snapshots__/ForgotPassword-test.js.snap
packages/aws-amplify-react/__tests__/Auth/__snapshots__/RequireNewPassword-test.js.snap
packages/aws-amplify-react/__tests__/Auth/__snapshots__/SignIn-test.js.snap
packages/aws-amplify-react/__tests__/Auth/__snapshots__/SignUp-test.js.snap
packages/aws-amplify-react/__tests__/Auth/__snapshots__/TOTPSetup-test.js.snap
packages/aws-amplify-react/__tests__/Storage/__snapshots__/S3Album-test.js.snap
packages/aws-amplify-react/__tests__/Storage/__snapshots__/S3Image-test.js.snap
packages/aws-amplify-react/__tests__/Storage/__snapshots__/S3Text-test.js.snap
packages/aws-amplify-react/__tests__/Widget/__snapshots__/PhotoPicker-test.js.snap
packages/aws-amplify-react/__tests__/Widget/__snapshots__/SelectMFAType-test.js.snap
packages/aws-amplify-react/__tests__/Widget/__snapshots__/TOTPSetupComp-test.js.snap
packages/aws-amplify-react/__tests__/Widget/__snapshots__/TextPicker-test.js.snap
packages/aws-amplify-react/src/Auth/AuthPiece.jsx
packages/aws-amplify-react/src/Auth/ConfirmSignIn.jsx
packages/aws-amplify-react/src/Auth/Greetings.jsx
packages/aws-amplify-react/src/Auth/RequireNewPassword.jsx
packages/aws-amplify-react/src/Auth/TOTPSetup.jsx
packages/aws-amplify-react/src/Auth/VerifyContact.jsx
packages/aws-amplify/src/Auth/Auth.ts

fix(aws-amplifyr-react): Verify contact before signed in

---

packages/aws-amplify/src/Auth/Auth.ts

Auth update user attributes fix

---

packages/aws-amplify-react/__tests__/Auth/ConfirmSignUp-test.js
packages/aws-amplify-react/__tests__/Auth/SignIn-test.js
packages/aws-amplify-react/__tests__/Auth/SignOut-test.js
packages/aws-amplify-react/__tests__/Auth/SignUp-test.js
packages/aws-amplify-react/__tests__/Auth/__snapshots__/ConfirmSignUp-test.js.snap
packages/aws-amplify-react/__tests__/Auth/__snapshots__/Greetings-test.js.snap
packages/aws-amplify-react/__tests__/Auth/__snapshots__/SignIn-test.js.snap
packages/aws-amplify-react/__tests__/Auth/__snapshots__/SignOut-test.js.snap
packages/aws-amplify-react/__tests__/Auth/__snapshots__/SignUp-test.js.snap
packages/aws-amplify-react/src/Auth/SignOut.jsx
packages/aws-amplify-react/src/Auth/index.jsx

For issue #630 
Remove unnecessary wrappings from Greetings component, to provide a simple SignOut button

add SignOut component

---

packages/amazon-cognito-identity-js/src/Client.js

Cognito client x-amzn-errortype fix

---

packages/aws-amplify/__tests__/Interactions/Interactions-unit-test.ts
packages/aws-amplify/src/Common/Amplify.ts
packages/aws-amplify/src/Common/Facet.ts
packages/aws-amplify/src/Interactions/Interactions.ts
packages/aws-amplify/src/Interactions/Providers/AWSLexProvider.ts
packages/aws-amplify/src/Interactions/Providers/InteractionsProvider.ts
packages/aws-amplify/src/Interactions/Providers/index.ts
packages/aws-amplify/src/Interactions/index.ts
packages/aws-amplify/src/Interactions/types/Interactions.ts
packages/aws-amplify/src/Interactions/types/Provider.ts
packages/aws-amplify/src/Interactions/types/Response.ts
packages/aws-amplify/src/Interactions/types/index.ts
packages/aws-amplify/src/index.ts

feat(interactions): Interactions category

---

package.json

Lerna publish fix for change log

---

packages/aws-amplify-react/package.json
packages/aws-amplify-react/src/Auth/ConfirmSignIn.jsx
packages/aws-amplify-react/src/Auth/ConfirmSignUp.jsx
packages/aws-amplify-react/src/Auth/ForgotPassword.jsx
packages/aws-amplify-react/src/Auth/VerifyContact.jsx

Fixes #1044 
Disabling browser autocomplete for all code fields.

Issue 1044

---

packages/aws-amplify/package.json

Fixes #1003 
Downgrades GraphQL from 0.13.0 to 0.11.7

fix(graphql): Downgrades GraphQL from 0.13.0 to 0.11.7

---

packages/amazon-cognito-identity-js/CHANGELOG.md
packages/aws-amplify-react-native/CHANGELOG.md
packages/aws-amplify-react/CHANGELOG.md
packages/aws-amplify/CHANGELOG.md

Fixes #1087 
Old lingering merge conflicts in changelogs.  Resolved by accepting both changes.

removing conflicts from change log

---

.circleci/config.yml

Circleci cache ssh

---

packages/aws-amplify-react/src/Interactions/ChatBot.jsx
packages/aws-amplify/src/Interactions/index.ts
packages/aws-amplify/src/PubSub/index.ts
packages/aws-amplify/src/index.ts

Import regenerator-runtime in ChatBot

---

packages/aws-amplify-react/__tests__/Analytics/trackLifecycle-test.js
packages/aws-amplify-react/__tests__/Auth/Authenticator-test.js
packages/aws-amplify-react/__tests__/Auth/ConfirmSignIn-test.js
packages/aws-amplify-react/__tests__/Auth/ConfirmSignUp-test.js
packages/aws-amplify-react/__tests__/Auth/FederatedSignIn-test.js
packages/aws-amplify-react/__tests__/Auth/ForgotPassword-test.js
packages/aws-amplify-react/__tests__/Auth/Greetings-test.js
packages/aws-amplify-react/__tests__/Auth/Provider/withAmazon-test.js
packages/aws-amplify-react/__tests__/Auth/Provider/withFacebook-test.js
packages/aws-amplify-react/__tests__/Auth/Provider/withGoogle-test.js
packages/aws-amplify-react/__tests__/Auth/Provider/withOAuth-test.js
packages/aws-amplify-react/__tests__/Auth/RequireNewPassword-test.js
packages/aws-amplify-react/__tests__/Auth/SignIn-test.js
packages/aws-amplify-react/__tests__/Auth/SignOut-test.js
packages/aws-amplify-react/__tests__/Auth/SignUp-test.js
packages/aws-amplify-react/__tests__/Auth/TOTPSetup-test.js
packages/aws-amplify-react/__tests__/Auth/VerifyContact-test.js
packages/aws-amplify-react/__tests__/Auth/__snapshots__/ConfirmSignIn-test.js.snap
packages/aws-amplify-react/__tests__/Auth/__snapshots__/ConfirmSignUp-test.js.snap
packages/aws-amplify-react/__tests__/Auth/__snapshots__/ForgotPassword-test.js.snap
packages/aws-amplify-react/__tests__/Auth/__snapshots__/VerifyContact-test.js.snap
packages/aws-amplify-react/__tests__/Storage/S3Album-test.js
packages/aws-amplify-react/__tests__/Storage/S3Image-test.js
packages/aws-amplify-react/__tests__/Storage/S3Text-test.js
packages/aws-amplify-react/__tests__/Widget/SelectMFAType-test.js
packages/aws-amplify-react/__tests__/Widget/TOTPSetupComp-test.js
packages/aws-amplify-react/package.json
packages/aws-amplify-react/src/Storage/S3Image.js
packages/aws-amplify-react/src/Storage/S3Text.js

Amplify v1

---

packages/pushnotification/src/PushNotification.ts

Expose whole context to the notification object

---

packages/api/src/API.ts
packages/aws-amplify-react/package.json
packages/aws-amplify-react/src/API/GraphQL/Connect.js

amplify-v1: Remove graphql dependency from aws-amplify-react

---

packages/amazon-cognito-identity-js/src/CognitoUser.js

fix(amazon-cognito-identity-js): NEW_PASSWORD_REQUIRED not handled when using USER_PASSWORD_AUTH

---

packages/analytics/src/Analytics.ts
packages/auth/src/Auth.ts

revert back break changes

---

package.json
packages/analytics/src/index.ts
packages/api/src/API.ts
packages/api/src/index.ts
packages/auth/src/index.ts
packages/aws-amplify-react/src/Categories.js
packages/aws-amplify/src/index.ts
packages/cache/src/index.ts
packages/cache/src/reactnative.ts
packages/core/__tests__/Amplify-test.ts
packages/core/src/index.ts
packages/interactions/src/index.ts
packages/pubsub/src/index.ts
packages/pushnotification/src/PushNotification.ts
packages/pushnotification/src/index.ts
packages/storage/src/index.ts

minor change

---

packages/core/src/Amplify.ts

Fix logger

---

packages/aws-amplify-react/src/Auth/SignIn.jsx

fix(aws-amplify-react): wrong behavior after hitting enter when signing in

---

README.md

READ.ME update

---

.circleci/config.yml

Make integration tests only triggered when merging to master or release branch

Update circle ci configuration

---

packages/aws-amplify-angular/src/components/interactions/chatbot/chatbot.component.core.ts
packages/aws-amplify-angular/src/components/interactions/chatbot/chatbot.component.ionic.ts

#1297 
Adds parameters to submit function.

fixes(#1297)

---

packages/amazon-cognito-identity-js/android/build.gradle

provide support for RN 0.56.0

---

docs/media/angular_guide.md
docs/media/ionic_guide.md

NA
Adds documentation for interactions to angular and ionic documentation.

Documentation interactions

---

docs/amplify-theme/_includes/google-analytics.html

tracking code changed for docs

---

packages/auth/__tests__/totp-unit-test.ts
packages/auth/src/Auth.ts

fix(@aws-amplify/auth): revert break changes in currentAuthenticatedUser

---

docs/_config.yml
docs/media/angular_guide.md
docs/media/ionic_guide.md
docs/media/react_guide.md
docs/media/react_native_guide.md
docs/media/test.html

Docs: page content updated for supported frameworks

---

docs/amplify-theme/_includes/site-header.html
docs/amplify-theme/assets/js/scripts.js

site notification for Ionic tutorial added

---

packages/aws-amplify-react-native/src/Auth/ConfirmSignIn.js

fix(aws-amplify-react-native): fix the footer of confirmSignIn component

---

package.json
packages/analytics/tsconfig.json
packages/api/tsconfig.json
packages/auth/tsconfig.json
packages/aws-amplify/tsconfig.json
packages/cache/tsconfig.json
packages/core/tsconfig.json
packages/interactions/tsconfig.json
packages/pubsub/tsconfig.json
packages/pushnotification/tsconfig.json
packages/storage/tsconfig.json

fix integration tests

---

packages/amazon-cognito-identity-js/src/Client.js

fix(amazon-cognito-identity-js): throw network error if in the offline

---

docs/media/authentication_guide.md
docs/media/hub_guide.md
docs/media/i18n_guide.md
packages/auth/src/Auth.ts

fix(@aws-amplify/auth): dispatching failure event when hosted UI and documentation enhancement for hosted UI

---

packages/aws-amplify-react-native/src/Auth/Authenticator.js

fixes #1012 
also releated to #1444 

fix(aws-amplify-react-native): fix the Authenticator to only call async functions when mounted

---

packages/cache/src/AsyncStorageCache.ts

I'm removing a `console.log` and replace it with the logger class instead to avoid polluting your console.

Remove console.log

---

packages/amazon-cognito-identity-js/package.json
packages/analytics/package.json
packages/api/package.json
packages/auth/package.json
packages/aws-amplify-angular/package.json
packages/aws-amplify-react-native/package.json
packages/aws-amplify/package.json
packages/cache/package.json
packages/core/package.json
packages/interactions/package.json
packages/pubsub/package.json
packages/pushnotification/package.json
packages/storage/package.json

fix version numbers

---

packages/core/src/Parser.ts

fixes(#1574 )
Parser creates an .Auth config object if id pool OR userpool exists, in accordance with new Amplify CLI.

fixes(#1574)

---

packages/api/src/API.ts
packages/pubsub/src/Providers/AWSAppSyncProvider.ts
packages/pubsub/src/Providers/MqttOverWSProvider.ts
packages/pubsub/src/PubSub.ts

fix(pubsub): Better handling of multiple AppSync subscriptions

---

packages/api/__tests__/API-test.ts
packages/api/src/RestClient.ts

Wrong replacement of init params overwriting headers.

Fix issue with body when using headers on API

---

packages/api/package.json
packages/api/src/API.ts
packages/pubsub/src/Providers/AWSAppSyncProvider.ts
packages/pubsub/src/Providers/MqttOverWSProvider.ts

fix(pubsub,api,appsync): Use subscriber-id header (AppSync subscription)

---

.circleci/config.yml
packages/aws-amplify-vue/README.md
packages/aws-amplify-vue/package.json
packages/aws-amplify-vue/src/Amplify.vue
packages/aws-amplify-vue/src/components/authenticator/Authenticator.vue
packages/aws-amplify-vue/src/components/authenticator/SignUp.vue

Dynamic signup

---

packages/aws-amplify-vue/README.md
packages/aws-amplify-vue/__tests__/ConfirmSignIn.test.js
packages/aws-amplify-vue/__tests__/ConfirmSignUp.test.js
packages/aws-amplify-vue/__tests__/ForgotPassword.test.js
packages/aws-amplify-vue/__tests__/SetMFA.test.js
packages/aws-amplify-vue/src/components/authenticator/ConfirmSignIn.vue
packages/aws-amplify-vue/src/components/authenticator/ConfirmSignUp.vue
packages/aws-amplify-vue/src/components/authenticator/ForgotPassword.vue
packages/aws-amplify-vue/src/components/authenticator/SetMFA.vue
packages/aws-amplify-vue/src/components/authenticator/SignIn.vue
packages/aws-amplify-vue/src/components/authenticator/SignOut.vue
packages/aws-amplify-vue/src/components/authenticator/SignUp.vue
packages/aws-amplify-vue/src/components/interactions/Chatbot.vue
packages/aws-amplify-vue/src/components/storage/PhotoPicker.vue

Changes name of 'option' objects to 'config', and makes README more readable.

Documentation

---

packages/api/src/API.ts
packages/pubsub/__mocks__/paho-mqtt.js
packages/pubsub/__tests__/PubSub-unit-test.ts
packages/pubsub/package.json
packages/pubsub/src/Providers/MqttOverWSProvider.ts
packages/pubsub/src/vendor/paho-mqtt.js

#1448 
Adding paho client on vendor directory and sending on observable error connection issues.

fix(@aws-amplify/api): send websocket disconnect errors thru observable

---

packages/amazon-cognito-identity-js/package.json
packages/api/package.json
packages/auth/package.json
packages/aws-amplify-angular/package.json
packages/aws-amplify/package.json

Bumping package version to unstable release

fix(): bumping version for deploying on unstable tag

---

packages/aws-amplify-vue/.gitignore
packages/aws-amplify-vue/__mocks__/Amplify.mocks.js
packages/aws-amplify-vue/__tests__/AmplifyPlugin.test.js
packages/aws-amplify-vue/__tests__/Authenticator.test.js
packages/aws-amplify-vue/__tests__/Chatbot.test.js
packages/aws-amplify-vue/__tests__/ConfirmSignIn.test.js
packages/aws-amplify-vue/__tests__/ConfirmSignUp.test.js
packages/aws-amplify-vue/__tests__/ForgotPassword.test.js
packages/aws-amplify-vue/__tests__/GetUser.test.js
packages/aws-amplify-vue/__tests__/PhotoPicker.test.js
packages/aws-amplify-vue/__tests__/S3Album.test.js
packages/aws-amplify-vue/__tests__/S3Image.test.js
packages/aws-amplify-vue/__tests__/SetMFA.test.js
packages/aws-amplify-vue/__tests__/SignIn.test.js
packages/aws-amplify-vue/__tests__/SignOut.test.js
packages/aws-amplify-vue/__tests__/SignUp.test.js
packages/aws-amplify-vue/jest.config.js
packages/aws-amplify-vue/package.json
packages/aws-amplify-vue/src/components/authenticator/Authenticator.vue
packages/aws-amplify-vue/src/components/authenticator/SetMFA.vue
packages/aws-amplify-vue/src/components/authenticator/SignUp.vue
packages/aws-amplify-vue/src/components/storage/PhotoPicker.vue
packages/aws-amplify-vue/src/components/storage/S3Album.vue
packages/aws-amplify-vue/src/plugins/AmplifyPlugin.js

Unit tests
Coverage summary
Statements   : 82.16% ( 281/342 )
Branches     : 74.44% ( 99/133 )
Functions    : 79.71% ( 110/138 )
Lines        : 82.11% ( 280/341 )

more vue tests

---

packages/aws-amplify-vue/README.md
packages/aws-amplify-vue/package.json
packages/aws-amplify-vue/src/components/authenticator/SetMFA.vue

cancelHandler in setMFA

---

docs/media/api_guide.md

Update GraphQL codegen documentation

Update api_guide.mdwith GraphQL codegen changes

---

docs/media/react_guide.md

Fixing typo in "prompted"

---

packages/analytics/src/vendor/dom-utils/matches.ts

fixes #1785
try to access property only if proto exists

fixes #1785

---

packages/aws-amplify-vue/src/Amplify.vue
packages/aws-amplify-vue/src/components/interactions/Chatbot.vue
packages/aws-amplify-vue/src/components/storage/S3Album.vue
packages/aws-amplify-vue/src/components/storage/S3Image.vue

fixes(#1783 )
removes importation of angular.css

removed usage of angular style sheet

---

packages/analytics/src/trackers/EventTracker.ts
packages/analytics/src/trackers/PageViewTracker.ts
packages/analytics/src/trackers/SessionTracker.ts
packages/analytics/src/vendor/dom-utils/matches.ts
packages/analytics/src/vendor/dom-utils/parse-url.ts
packages/auth/src/Auth.ts
packages/core/src/OAuthHelper/FacebookOAuth.ts
packages/core/src/OAuthHelper/GoogleOAuth.ts
packages/core/src/ServiceWorker/ServiceWorker.ts

use JS.browserOrNode().isBrowser to check window object

---

packages/aws-amplify-react/src/Auth/FederatedSignIn.jsx

fixes(#1826 )
Adds I18n to 'or' in FederatedSignIn react file.

fixes(#1826)

---

packages/aws-amplify-react-native/src/Auth/Authenticator.js
packages/aws-amplify-react/src/Auth/Authenticator.jsx

fix(aws-amplify-react): jump to the initial state if not signed in

---

packages/aws-amplify-vue/src/components/authenticator/Authenticator.vue

fixes(#1861)
Renames props to correct name.

fixes(#1861)

---

packages/analytics/package.json
packages/interactions/package.json
packages/storage/package.json
packages/xr/package.json

To remove the dependency of aws-sdk in other packages.

remove aws-sdk dependency

---

packages/aws-amplify-react/src/Auth/Authenticator.jsx

#1777 
Hide Toast component when auth state changes

Hide Toast component when auth state changes

---

packages/aws-amplify-react/src/Auth/Authenticator.jsx

fix(aws-amplify-react): only call Auth signOut if some error happens during signed in

---

packages/aws-amplify-react/src/Auth/SignUp.jsx
packages/aws-amplify-react/src/Auth/index.jsx

fixing parameter structure in react HOC and logger error in signup jsx

fixing parameter structure in react HOC and logger error in signup jsx

---

packages/pubsub/__tests__/PubSub-unit-test.ts

Updating paho client mock on pubsub unit test

fix(@pubsub): Unit test: updating PahoClient mock 

---

packages/aws-amplify-react-native/src/Auth/SignUp.js
packages/aws-amplify-react/__tests__/Auth/SignUp-test.js
packages/aws-amplify-react/__tests__/Auth/__snapshots__/SignUp-test.js.snap
packages/aws-amplify-react/__tests__/Auth/__snapshots__/index-test.js.snap
packages/aws-amplify-react/src/Auth/SignUp.jsx
packages/aws-amplify-react/src/Auth/index.jsx
packages/aws-amplify-vue/src/components/authenticator/SignUp.vue

Resolving issues from testing.

Angular signup fields

---

packages/aws-amplify-react-native/src/Auth/SignUp.js
packages/aws-amplify-react/src/Auth/SignUp.jsx

additional fixes

---

packages/core/src/ClientDevice/browser.ts

fix(@aws-amplify/core): check if window.addListener is a function

---

packages/aws-amplify-vue/__mocks__/Amplify.mocks.js
packages/aws-amplify-vue/__tests__/ConfirmSignIn.test.js
packages/aws-amplify-vue/__tests__/RequireNewPassword.test.js
packages/aws-amplify-vue/src/Amplify.vue
packages/aws-amplify-vue/src/components/authenticator/Authenticator.vue
packages/aws-amplify-vue/src/components/authenticator/ConfirmSignIn.vue
packages/aws-amplify-vue/src/components/authenticator/ForgotPassword.vue
packages/aws-amplify-vue/src/components/authenticator/RequireNewPassword.vue
packages/aws-amplify-vue/src/components/authenticator/SignIn.vue
packages/aws-amplify-vue/src/components/authenticator/index.js

User on Gitter noted that Vue seemed to be missing require-new-password component.
This PR adds the component, and modifies other issues in auth flow.

adding require new password component for vue

---

packages/aws-amplify-react/src/Auth/TOTPSetup.jsx
packages/aws-amplify-react/src/Storage/S3Album.js
packages/aws-amplify-react/src/Storage/S3Image.js
packages/aws-amplify-react/src/Storage/S3Text.js

To optimize the way of importing modules

optimize the way of importing components

---

packages/api/src/API.ts

Fix issue on react-native with Object.assign

---

packages/aws-amplify-react-native/src/Auth/Greetings.js
packages/aws-amplify-react/src/Auth/Greetings.jsx

Fix issue 2183

---

packages/amplify-ui/CHANGELOG.md
packages/aws-amplify-vue/CHANGELOG.md

fixes changelog merge errors

---

packages/storage/src/Storage.ts

fixing storage provider bug on all APIs

---

packages/aws-amplify-vue/__tests__/Amplify.test.js
packages/aws-amplify-vue/__tests__/AmplifyPlugin.test.js
packages/aws-amplify-vue/__tests__/Authenticator.test.js
packages/aws-amplify-vue/__tests__/Chatbot.test.js
packages/aws-amplify-vue/__tests__/ConfirmSignIn.test.js
packages/aws-amplify-vue/__tests__/ConfirmSignUp.test.js
packages/aws-amplify-vue/__tests__/Connect.test.js
packages/aws-amplify-vue/__tests__/ForgotPassword.test.js
packages/aws-amplify-vue/__tests__/PhotoPicker.test.js
packages/aws-amplify-vue/__tests__/RequireNewPassword.test.js
packages/aws-amplify-vue/__tests__/S3Album.test.js
packages/aws-amplify-vue/__tests__/S3Image.test.js
packages/aws-amplify-vue/__tests__/SetMFA.test.js
packages/aws-amplify-vue/__tests__/SignIn.test.js
packages/aws-amplify-vue/__tests__/SignOut.test.js
packages/aws-amplify-vue/__tests__/SignUp.test.js
packages/aws-amplify-vue/__tests__/SumerianScene.test.js
packages/aws-amplify-vue/src/Amplify.vue
packages/aws-amplify-vue/src/plugins/AmplifyPlugin.js

Change to AmplifyPlugin export/import in aws-amplify-vue

changing export for plugin

---

packages/aws-amplify-vue/__tests__/Amplify.test.js
packages/aws-amplify-vue/__tests__/AmplifyPlugin.test.js
packages/aws-amplify-vue/__tests__/Authenticator.test.js
packages/aws-amplify-vue/__tests__/Chatbot.test.js
packages/aws-amplify-vue/__tests__/ConfirmSignIn.test.js
packages/aws-amplify-vue/__tests__/ConfirmSignUp.test.js
packages/aws-amplify-vue/__tests__/Connect.test.js
packages/aws-amplify-vue/__tests__/ForgotPassword.test.js
packages/aws-amplify-vue/__tests__/PhotoPicker.test.js
packages/aws-amplify-vue/__tests__/RequireNewPassword.test.js
packages/aws-amplify-vue/__tests__/S3Album.test.js
packages/aws-amplify-vue/__tests__/S3Image.test.js
packages/aws-amplify-vue/__tests__/SetMFA.test.js
packages/aws-amplify-vue/__tests__/SignIn.test.js
packages/aws-amplify-vue/__tests__/SignOut.test.js
packages/aws-amplify-vue/__tests__/SignUp.test.js
packages/aws-amplify-vue/__tests__/SumerianScene.test.js
packages/aws-amplify-vue/src/Amplify.vue
packages/aws-amplify-vue/src/plugins/AmplifyPlugin.js

fixes(#2254)
changes import/export of AmplifyPlugin

fixes(#2254)

---

packages/aws-amplify-react/src/Auth/Authenticator.jsx
packages/aws-amplify-react/src/Auth/SignIn.jsx

fix(aws-amplify-react): correctly hide links under production mode

---

packages/aws-amplify-vue/package.json
yarn.lock

Possible temporary fix for amplify-vue/amplify-ui issue.

changing ui dependency

---

packages/amazon-cognito-identity-js/README.md
packages/amazon-cognito-identity-js/src/CognitoUser.js
packages/auth/src/Auth.ts
packages/auth/src/types/Auth.ts

feat(amazon-cognito-identity-js): cache the user data

---

packages/aws-amplify-react-native/package.json
packages/aws-amplify-react/package.json

Version bump for react and react-native.

react and react-native version bump

---

packages/aws-amplify-react-native/src/Interactions/ChatBot.js

reverting chatbot rn

---

packages/amplify-ui/CHANGELOG.md
packages/amplify-ui/package.json
packages/aws-amplify-angular/CHANGELOG.md
packages/aws-amplify-angular/package.json
packages/aws-amplify-react-native/CHANGELOG.md
packages/aws-amplify-react-native/package.json
packages/aws-amplify-react/CHANGELOG.md
packages/aws-amplify-react/package.json
packages/aws-amplify-vue/CHANGELOG.md
packages/aws-amplify-vue/package.json
packages/aws-amplify/CHANGELOG.md
packages/aws-amplify/package.json
packages/interactions/CHANGELOG.md
packages/interactions/package.json

release into master

---

packages/aws-amplify-react/src/Interactions/ChatBot.jsx
packages/aws-amplify-vue/src/components/interactions/Chatbot.vue

React & Vue chatbot components required microphone permissions even when voiceEnabled was false. This PR moves the audio recording library to conditional import so will only ask for permissions when needed. Also includes a small fix for placeholder message for voiceEnabled and textEnabled on Vue.

fix(@aws-amplify/react @aws-amplify/vue): conditional imports for react and vue chatbot

---

packages/aws-amplify-react-native/src/Interactions/ChatBot.js
packages/aws-amplify-react-native/src/Interactions/ReactNativeModules/index.js

React Native chatbot voice interactions

feat(@aws-amplify/react-native): React Native chatbot voice interactions

---

packages/pushnotification/android/src/main/java/com/amazonaws/amplify/pushnotification/RNPushNotificationModule.java

fix(@aws-amplify/pushnotification): open app on device with Android 8.0

---

packages/auth/src/Auth.ts

fix(@aws-amplify/auth): typo

---

packages/aws-amplify-angular/src/components/authenticator/sign-up-component/sign-up.component.core.ts

#2404 
Doesn't validate phone number if it's not in the field array.

fixes(#2404)

---

packages/api/__tests__/API-test.ts
packages/api/src/API.ts

- Change "no" to "not" in error messages
- Capitalize "API" in error messages

Fix error message typos

---

packages/amplify-ui/src/Form.css

#2162 
Sets min-width to auto for form sections on mobile

Fix form section overflow in mobile

---

packages/amplify-ui/src/Input.css

#2163 
Increase input font-size for mobile to get rid of annoying mobile zoom

Increase font size to prevent zoom

---

packages/aws-amplify-react/__tests__/Auth/Provider/withGoogle-test.js
packages/aws-amplify-react/src/Auth/Provider/withGoogle.jsx

Issue #2466 
Return profile image url for Google authentication provider.

Google profile image

---

packages/analytics/__tests__/Providers/AWSAnalyticsProvider-unit-test.ts
packages/analytics/__tests__/trackers/SessionTracker-rn-test.ts
packages/analytics/__tests__/trackers/SessionTracker-test.ts
packages/analytics/src/Analytics.ts
packages/analytics/src/Providers/AWSPinpointProvider.ts
packages/analytics/src/trackers/SessionTracker-rn.ts
packages/analytics/src/trackers/SessionTracker.ts

fix(@aws-amplify/analytics): fix the event name of session start/stop

---

packages/aws-amplify-react/src/Widget/PhotoPicker.js

fixes type

---

packages/core/src/StorageHelper/reactnative.ts

fix(@aws-amplify/core): storage, avoid to sync twice

---

packages/auth/src/index.ts

N/A
Export CognitoUser from @amplify/auth

Export CognitoUser from @amplify/auth

---

packages/aws-amplify-vue/src/components/authenticator/RequireNewPassword.vue

fix(#2158)

---

packages/aws-amplify-react/CHANGELOG.md
packages/aws-amplify-react/package.json
packages/aws-amplify-vue/__mocks__/Amplify.mocks.js
packages/aws-amplify-vue/__tests__/Authenticator.test.js
packages/aws-amplify-vue/__tests__/VerifyContact.test.js
packages/aws-amplify-vue/src/Amplify.vue
packages/aws-amplify-vue/src/components/authenticator/Authenticator.vue
packages/aws-amplify-vue/src/components/authenticator/ConfirmSignIn.vue
packages/aws-amplify-vue/src/components/authenticator/RequireNewPassword.vue
packages/aws-amplify-vue/src/components/authenticator/SignIn.vue
packages/aws-amplify-vue/src/components/authenticator/VerifyContact.vue
packages/aws-amplify-vue/src/components/authenticator/index.js

N/A
Allows verification of user.

Vue User Verification

---

packages/aws-amplify-react-native/src/Interactions/ChatBot.js
packages/aws-amplify-react/src/Interactions/ChatBot.jsx

#2574 
Removes dupe property declaration in React chatbot which breaks IE in strict mode. Also fixes RN for consistency.

fix(aws-amplify-react) fix(aws-amplify-react-native)

---

packages/amazon-cognito-identity-js/README.md

#2587
Adding polyfill sample on readme

Add example polyfill for node-fetch

---

packages/aws-amplify-vue/src/components/api/graphql/Connect.vue

#2568 
Adds then/catch block to mutation section of _fetchData in Vue's Connect component.

fix(aws-amplify-vue)

---

.circleci/config.yml

Checking npm user user before publish

Check npm user before publish

---

packages/analytics/src/Providers/AWSPinpointProvider.ts

To give out the error when sending events failed.
Also update the warning message to be more informative.

fix(@aws-amplify/analytics): update warning message

---

package.json

build: Use exact version when updating dependencies

---

packages/core/src/index.ts

Testing publish

---

vscode/auto_snippet_documentation.md
vscode/snippets/auto.code-snippets

Add brackets to arrow function in docs and doc gen.

Add missing brackets to docs via snippet gen

---

packages/aws-amplify-react/src/Widget/PhotoPicker.js
packages/aws-amplify-react/src/Widget/Picker.js
packages/aws-amplify-react/src/Widget/TextPicker.js

Related to:
https://github.com/aws-amplify/amplify-js/pull/2138

Remove unused variables and imports

---

packages/aws-amplify-react/src/Storage/S3Album.js

Related to:
https://github.com/aws-amplify/amplify-js/pull/2136

Remove unused import and variable

---

packages/amazon-cognito-identity-js/src/CognitoUser.js
packages/core/src/Hub.ts

Fix issue 845

---

packages/amazon-cognito-identity-js/src/CognitoUser.js

fixes #747 
Resets the challenge name on the Cognito User after complete password finishes.

fix(amazon-cognito-identity-js) reset challengename

---

packages/amplify-ui/package.json
packages/pubsub/package.json

Changed rm to use rimraf instead to support building locally on Windows.

Pubsub windows build fix

---

packages/auth/package.json
packages/auth/src/Auth.ts
packages/auth/src/urlListener.native.ts
packages/auth/src/urlListener.ts

fix(auth): Split urlListener into web/react-native

---

packages/analytics/src/Providers/AWSPinpointProvider.ts

Fix typo in Pinpoint Provider

---

packages/auth/__tests__/auth-unit-test.ts
packages/auth/src/Auth.ts

fix(@aws-amplify/auth): check if has the right scope to send the request GetUserData

---

packages/api/__tests__/API-test.ts

test(api): Happy path for GraphQL subscription

---

packages/aws-amplify-react/src/Storage/S3Album.js
packages/core/src/ClientDevice/browser.ts

fix(core): Remove unneeded Hub.dispatch and Hub.listen

---

packages/auth/__tests__/auth-unit-test.ts
packages/auth/src/Auth.ts

fix(@aws-amplify/auth): get the user attributes after signing in

---

packages/aws-amplify-react/src/Storage/S3Album.js
packages/aws-amplify-react/src/Storage/S3Image.js
packages/aws-amplify-react/src/Storage/S3Text.js

#2736
Fix warning for setState on unmounted state component for Storage components

fix(aws-amplify-react) Fix warning for setState on unmounted state

---

packages/api/__tests__/API-test.ts
packages/api/src/API.ts

Fixes #1302 
Merge options found in root level with the ones found in the `API` object.

fix(api): allow API options to be merged with root level options

---

packages/aws-amplify-react/src/Auth/SignIn.jsx

fix(aws-amplify-react): the username should not be undefined

---

packages/aws-amplify-react/src/Widget/TOTPSetupComp.jsx

Would like to have the ability to customize the TOTP issuer. This change would allow for that as well as localization of the issuer.

Localize/Customize TOTP issuer

---

packages/analytics/src/Analytics.ts
packages/analytics/src/Providers/AWSPinpointProvider.ts
packages/auth/src/Auth.ts
packages/core/__tests__/Hub-test.ts
packages/core/__tests__/HubClass-test.ts
packages/core/src/Hub.ts
packages/storage/src/Providers/AWSS3Provider.ts

Fixes: #2983 
Adding checking for Symbol support. I didn't want to export `AMPLIFY_SYMBOL` because is an implementation detail

Adding compatibility for Symbol

---

packages/core/__tests__/Hub-test.ts
packages/core/src/Hub.ts

Fix problem found with this binding
Adding onHubCapsule callback binding and unit test

fix hub this binding issue

---

package.json
packages/aws-amplify-react/cypress/integration/auth_spec.js
yarn.lock

- Cypress tests were failing in CircleCI due to a UI change

fix: update cypress version and fix auth text check

---

packages/amazon-cognito-identity-js/README.md

Use input instead of prompt for password

---

packages/aws-amplify-angular/package.json

fix(aws-amplify-angular): major version bump

---

packages/amazon-cognito-identity-js/README.md

Make use case 23 more explicit on how to use it in an app
Fixes: 3043
#3043 
Update docs sample for newPasswordChallenge flow

Update use case 23

---

packages/aws-amplify-angular/src/components/authenticator/confirm-sign-in-component/confirm-sign-in-component.core.ts
packages/aws-amplify-angular/src/components/authenticator/confirm-sign-up-component/confirm-sign-up.component.core.ts
packages/aws-amplify-angular/src/components/authenticator/forgot-password-component/forgot-password.component.core.ts
packages/aws-amplify-angular/src/components/authenticator/require-new-password-component/require-new-password.component.core.ts
packages/aws-amplify-angular/src/components/authenticator/sign-in-component/sign-in.component.core.ts
packages/aws-amplify-angular/src/components/authenticator/sign-up-component/sign-up.component.core.ts

#2950 
Clears error message on state change.  Also minor change for linting.

fix(aws-amplify-angular): clears error message on state change

---

packages/aws-amplify-react-native/src/Auth/Authenticator.js

fix(aws-amplify-react-native): catch the error when verifying contact

---

packages/core/__tests__/JS-test.ts
packages/core/src/JS.ts

… transferKeyToUpperCase/transferKeyToLowerCase
fixes #2724 

fix(@aws-amplify/core): directly return if input is null for function transferKeyToUpperCase/transferKeyToLowerCase

---

packages/amplify-ui/src/Input.css
packages/aws-amplify-react/src/Amplify-UI/Amplify-UI-Theme.jsx

Fixes: #3131
* Added a missing label class to Amplify-UI 

fix: adds label styling to verify contact component

---

packages/aws-amplify-react-native/src/AmplifyTheme.js
packages/aws-amplify-react-native/src/Auth/Authenticator.js

fix(aws-amplify-react-native): Fix funky background

---

packages/aws-amplify-react-native/src/Auth/withOAuth.js

https://github.com/aws-amplify/amplify-js/issues/3021
* Add a `loading` prop to the `withOAuth` higher order component
that defaults to `true`.
* Once the amplify session has been created, the `loading` prop
is set to `false`.
* This allows wrapped components to make decisions and display
animations to users when the HOC is loading.
* Resolves https://github.com/aws-amplify/amplify-js/issues/3021

feat(aws-amplify-react-native): withOAuth Loading

---

packages/aws-amplify-react/src/AmplifyI18n.js

I added the german localisation and formatted the file a bit to make it more readable

Added german localisation

---

packages/analytics/package.json

Fixing Lerna failure to increment version after deploy to NPM.

fix(@aws-amplify/analytics): manual version bump

---

packages/api/package.json
packages/auth/package.json
packages/aws-amplify-angular/package.json
packages/aws-amplify/package.json
packages/cache/package.json
packages/core/package.json
packages/interactions/package.json
packages/pubsub/package.json
packages/pushnotification/package.json
packages/storage/package.json
packages/xr/package.json

fix(aws-amplify): manual version bumps for lerna issue

---

README.md

Update readme - Angular modules link takes to AngularJS docs

---

packages/api/package.json

#3354 
Bumping axios version. Tested with APIGW and AppSync with sigV4, api-key, and CUP token.

Bumping axios version

---

packages/pubsub/src/Providers/MqttOverWSProvider.ts

fix(@aws-amplify/pubsub): fix ZenObservable import

---

packages/core/package.json

for Amazon personalize support
Updating aws-sdk to latest

latest aws-sdk

---

packages/aws-amplify/package.json

Analytics version to be same as monorepo

---

.github/stale.yml

[ci skip]
add feature-request to exempt list

Update stale config

---

packages/pubsub/src/Providers/MqttOverWSProvider.ts
packages/pubsub/src/types/index.ts

fix(@aws-amplify/pubsub): fix the typescript error

---

packages/auth/src/Auth.ts
packages/auth/src/OAuth/OAuth.ts
packages/auth/src/urlListener.native.ts

Fixes #3399
Closes #3576
Fixes #3247
Fixes #3592
Fixes #3210
Closes #3356

fix(@aws-amplify/auth, aws-amplify-react-native): Fix OAuth flow in react native

---

packages/core/__tests__/Signer-test.ts
packages/core/src/Signer.ts

fix(@aws-amplify/core): Preserve port when creating signed url

---

packages/auth/src/urlListener.native.ts

Fixes #3681
Fixes #3707
Tested with
- https://github.com/manueliglesias/hosted-ui-react-native-cli
- RN cli app - no Expo
- "react-native": "0.58.4"
- both iOS and Android
- https://github.com/manueliglesias/hosted-ui-react-native
- Expo 31
- both iOS and Android

fix(@aws-amplify/auth): Improve OAuth flow in react native

---

packages/storage/__tests__/Storage-unit-test.ts
packages/storage/src/Storage.ts

Fixes: #3759 
Fixes: #3752 
Removing the check of an object for custom prefix to be added correctly to the AWSS3 provider. Added an additional test for custom prefix

Remove object check & value is undefined in order to resolve custom prefix issue

---

packages/aws-amplify-angular/package.json

*Description of changes:* Dev dependency was out of sync and caused CircleCI fails on some branches.

Sync angular dev-dependency with main package

---

.circleci/config.yml

- Predictions sample app integration tests

Predictions CircleCI integration tests on React sample

---

packages/predictions/src/Predictions.ts

#3791
Remove addPluggable error

Fix add pluggable error on Predictions

---

packages/core/src/Parser.ts
packages/pubsub/__tests__/PubSub-unit-test.ts
packages/pubsub/src/Providers/MqttOverWSProvider.ts
packages/pubsub/src/PubSub.ts
packages/storage/__tests__/Providers/AWSS3Provider-unit-test.ts
packages/storage/src/Providers/AWSS3Provider.ts

This code adds the functionality necessary to support local testing of api and storage once enabled with the cli

feat: Add support for local testing of api and storage

---

packages/auth/src/Auth.ts

Changed 'authenticted' to 'authenticated'

Fix typo in logger output

---

.github/stale.yml

From https://github.com/probot/stale#usage
```yaml
```

chore: Make stalebot ignore PRs

---

packages/storage/__tests__/Storage-unit-test.ts

fix(@aws-amplify/storage): fix typo

---

packages/core/src/index.ts

removing empty line

---

packages/amplify-ui-components/src/components/amplify-button/amplify-button.stories.tsx
packages/amplify-ui-components/src/components/amplify-hint/amplify-hint.stories.tsx
packages/amplify-ui-components/src/components/amplify-label/amplify-label.stories.tsx
packages/amplify-ui-components/src/components/amplify-text-field/amplify-text-field.stories.tsx
packages/amplify-ui-components/src/components/amplify-tooltip/amplify-tooltip.stories.tsx

- It looks much nicer now!
- This doesn't have any performance savings, but the OCD savings are dramatic
- Gonna miss you guys :)

Stories constants for consistency across files

---

.circleci/config.yml

[Pivotal Task](https://www.pivotaltracker.com/story/show/167358017)
* Added the job for angular integration testing
* Made angular integ test/ predictions react integ test required for deployment
* renamed `integration` to `integ` for all jobs
Test Branch CircleCI [run](https://circleci.com/workflow-run/141ea9bc-e916-473c-aa3b-610b0194d3dd)

chore: (add angular integration testing)

---

packages/auth/src/OAuth/OAuth.ts

#3932 
Adds try/catch block to handleAuthResponse.

fix(#3932)

---

package.json

Add Prettier pre-commit hook to enforce Prettier formatting

Add Prettier pre-commit husky hook

---

packages/amazon-cognito-identity-js/.eslintrc.yaml
packages/amazon-cognito-identity-js/package.json

Tweaks the eslintrc.yaml file in the cognito sdk 

fix(amazon-cognito-identity-js): linting config

---

packages/auth/src/Auth.ts

#3862 
Changes an error message for signUp failure to be understandable for end user.

fix(#3862) : Renders human readable error message for signin

---

.github/stale.yml
packages/aws-amplify-vue/package.json

#3937 
Upgrading vue2-filters package

fix(#3937) : upgrading vue2-filters package

---

codecov.yml

* Setting our code coverage to 82% 

chore: Updating code coverage 

---

codecov.yml
packages/auth/src/Auth.ts

* Adjusting in order to not have code coverage run on project and patch PRs

fix: Adjusting code coverage

---

packages/auth/src/Auth.ts

#4083 
Adding forgotPassword and forgotPasswordSubmit auth events

fix(#4083) : adding forgotPassword and forgotPasswordSubmit auth events

---

packages/amplify-ui-components/package.json
packages/amplify-ui-components/src/components.d.ts
packages/amplify-ui-components/src/components/amplify-auth-fields/amplify-auth-fields-interface.ts
packages/amplify-ui-components/src/components/amplify-examples/amplify/#current-cloud-backend/amplify-meta.json
packages/amplify-ui-components/src/components/amplify-examples/amplify/#current-cloud-backend/auth/cognito5e8d6bdf/cognito5e8d6bdf-cloudformation-template.yml
packages/amplify-ui-components/src/components/amplify-examples/amplify/#current-cloud-backend/auth/cognito5e8d6bdf/parameters.json
packages/amplify-ui-components/src/components/amplify-examples/amplify/#current-cloud-backend/backend-config.json
packages/amplify-ui-components/src/components/amplify-examples/amplify/#current-cloud-backend/xr/scene1/parameters.json
packages/amplify-ui-components/src/components/amplify-examples/amplify/#current-cloud-backend/xr/scene1/template.json
packages/amplify-ui-components/src/components/amplify-examples/amplify/.config/local-env-info.json
packages/amplify-ui-components/src/components/amplify-examples/amplify/backend/amplify-meta.json
packages/amplify-ui-components/src/components/amplify-password-field/amplify-password-field.tsx
packages/amplify-ui-components/src/components/amplify-scene/amplify-scene.tsx
packages/amplify-ui-components/stencil.config.ts
yarn.lock

* Update amplify cli local resources
* Add new package content
* Refactor FunctionalComponent type

chore: Example updates and small refactoring

---

packages/amazon-cognito-identity-js/src/AuthenticationHelper.js
packages/amazon-cognito-identity-js/src/CognitoJwtToken.js
packages/amazon-cognito-identity-js/src/CognitoUser.js

- Remove '/' that was breaking Rollup build in Stencil

Remove '/' in buffer import

---

packages/aws-amplify-react/src/Widget/Picker.tsx

_Issue #, if available:_ #3950 
_Description of changes:_ Just a line of styling that got lost over history.

fix(#3950): picker style issue

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/usage-question.md

Updating templates to add labels for respected templates and more amplify information

Update issue templates

---

scripts/build.js

_Issue #, if available:_#4219
_Description of changes:_Readd the variable declaration allDiagnostics

fixes #4219 Readd the variable declaration allDiagnostics

---

packages/api/package.json

_Issue #, if available:_#4217, #4194
_Description of changes:_upgrade graphql version to 14.0.0. Tested changes with sample apps.

fixes #4217,#4194 upgrade graphql version to 14.0.0

---

packages/analytics/src/Providers/AWSPinpointProvider.ts

https://github.com/aws-amplify/amplify-js/issues/4232
Quick fix for this in React Native. Will include a cleaner solution as part of the Analytics refactor I'm currently working on.

fix(analytics): Don't call sendBeacon when not supported

---

.github/ISSUE_TEMPLATE/bug_report.md
scripts/build.js

#4282 
use path.join to resolve the path.

fix(scripts/build): windows build

---

packages/pushnotification/package.json
packages/pushnotification/src/PushNotification.ts

This commit adds the change to use the react-native-community version of push notifications.

Push notification ios

---

.circleci/config.yml
package.json

* Added a new command in order to have release branch point to the "next" tag on npm.
* Updated the CircleCI config for 1.0-stable branch.

chore: (Updating package.json / CircleCI config)

---

packages/amplify-ui-components/src/components.d.ts
packages/amplify-ui-components/src/components/amplify-authenticator/__snapshots__/amplify-authenticator.spec.ts.snap
packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx
packages/amplify-ui-components/src/components/amplify-authenticator/readme.md
packages/amplify-ui-components/src/components/amplify-examples/readme.md
packages/amplify-ui-components/src/components/amplify-greetings/__snapshots__/amplify-greetings.spec.ts.snap
packages/amplify-ui-components/src/components/amplify-greetings/amplify-greetings.spec.ts
packages/amplify-ui-components/src/components/amplify-greetings/amplify-greetings.stories.tsx
packages/amplify-ui-components/src/components/amplify-greetings/amplify-greetings.style.ts
packages/amplify-ui-components/src/components/amplify-greetings/amplify-greetings.tsx
packages/amplify-ui-components/src/components/amplify-greetings/readme.md
packages/amplify-ui-components/src/components/amplify-nav/__snapshots__/amplify-nav.spec.ts.snap
packages/amplify-ui-components/src/components/amplify-nav/amplify-nav.spec.ts
packages/amplify-ui-components/src/components/amplify-nav/amplify-nav.stories.tsx
packages/amplify-ui-components/src/components/amplify-nav/amplify-nav.style.ts
packages/amplify-ui-components/src/components/amplify-nav/amplify-nav.tsx
packages/amplify-ui-components/src/components/amplify-nav/readme.md
packages/amplify-ui-components/src/components/amplify-sign-out/readme.md
packages/amplify-ui-components/src/global/variables.css

- `amplify-greetings` component
- `amplify-nav` component
- Rebase from #4412
[Delivers: #167797513]

feat(@aws-amplify/ui-components): amplify-greetings/amplify-nav

---

.circleci/config.yml

Forgot a step for linking analytics

Forgot a step for linking analytics

---

.circleci/config.yml

Fix angular integ test

---

package.json

- Updating release scripts for release and 1.0-stable. 1.0-stable.

chore: Update release command, update stable 1.0 command

---

packages/api/src/index.ts
packages/api/src/types/index.ts
packages/core/__tests__/Mutex-test.ts
packages/core/src/Util/Mutex.ts
packages/core/src/Util/Reachability.ts
packages/core/src/Util/Retry.ts
packages/core/src/Util/index.ts

Co-authored-by: manueliglesias <manuel.iglesias@gmail.com>
Co-authored-by: elorzafe <frodriguez.cs@gmail.com>
Upgrade to **core** and **api** category

upgrade core and api

---

package.json
packages/datastore/.npmignore
packages/datastore/__tests__/DataStore.ts
packages/datastore/__tests__/indexeddb.test.ts
packages/datastore/__tests__/model.ts
packages/datastore/__tests__/schema.ts
packages/datastore/build.js
packages/datastore/index.js
packages/datastore/package.json
packages/datastore/src/datastore/datastore.ts
packages/datastore/src/index.ts
packages/datastore/src/predicates/index.ts
packages/datastore/src/storage/adapter/index.ts
packages/datastore/src/storage/adapter/indexeddb.ts
packages/datastore/src/storage/storage.ts
packages/datastore/src/sync/index.ts
packages/datastore/src/sync/merger.ts
packages/datastore/src/sync/outbox.ts
packages/datastore/src/sync/processors/mutation.ts
packages/datastore/src/sync/processors/subscription.ts
packages/datastore/src/sync/processors/sync.ts
packages/datastore/src/sync/utils.ts
packages/datastore/src/types.ts
packages/datastore/src/util.ts
packages/datastore/tslint.json
packages/datastore/webpack.config.dev.js
packages/datastore/webpack.config.js

Co-authored-by: Ashika  <35131273+ashika01@users.noreply.github.com>
Co-authored-by: Francisco Javier Rodriguez Elorza <28815678+elorzafe@users.noreply.github.com>
Co-authored-by: Manuel Iglesias <6154160+manueliglesias@users.noreply.github.com>

Amplify category updates

---

packages/datastore/src/sync/processors/subscription.ts

PubSub enabling on amplify categories

PubSub enabling on amplify categories

---

packages/amplify-ui-components/stencil.config.ts
yarn.lock

- Fix build failure from stencil config

Fix stencil config

---

packages/analytics/src/Providers/AWSKinesisProvider.ts
packages/analytics/src/Providers/AWSPinpointProvider.ts
packages/analytics/src/Providers/AmazonPersonalizeProvider.ts
packages/core/src/Credentials.ts
packages/core/src/Platform/index.ts
packages/interactions/src/Providers/AWSLexProvider.ts
packages/predictions/src/Providers/AmazonAIConvertPredictionsProvider.ts
packages/predictions/src/Providers/AmazonAIIdentifyPredictionsProvider.ts
packages/predictions/src/Providers/AmazonAIInterpretPredictionsProvider.ts
packages/storage/src/providers/AWSS3Provider.ts

_Description of changes:_ append amplify user agent to all V3 SDK calls

feat: append amplify user agent to all V3 SDK calls

---

.circleci/config.yml
package.json

In order to get ui components into preview, we need these commands in master prior.

Add a preview tag command for the ui components

---

.circleci/config.yml
package.json

This reverts commit dd731b78ba1708b7a7e4e155a650e30cde41a67d.
Merged in by mistake, reverting

Revert "Add a preview tag command for the ui components (#4686)"

---

packages/amplify-ui-components/src/components.d.ts
packages/amplify-ui-components/src/components/amplify-auth0-button/readme.md
packages/amplify-ui-components/src/components/amplify-authenticator/readme.md
packages/amplify-ui-components/src/components/amplify-examples/readme.md
packages/amplify-ui-components/src/components/amplify-federated-buttons/readme.md
packages/amplify-ui-components/src/components/amplify-form-field/readme.md
packages/amplify-ui-components/src/components/amplify-form-section/readme.md
packages/amplify-ui-components/src/components/amplify-input/readme.md
packages/amplify-ui-components/src/components/amplify-link/readme.md
packages/amplify-ui-components/src/components/amplify-radio-button/readme.md
packages/amplify-ui-components/src/components/amplify-select-mfa-type/readme.md
packages/amplify-ui-components/src/components/amplify-totp-setup/readme.md
packages/amplify-ui-components/src/components/amplify-verify-contact/readme.md
yarn.lock

_Issue #, if available:_ #4685 , #4676 
WIth #4685, `yarn.lock` and the auto-generated READMEs were out-of-date, making noise in #4676.
This is just `yarn` && `yarn workspace @aws-amplify/ui-components build`.

Update @aws-amplify/ui-components build

---

packages/amplify-ui-components/src/components.d.ts
packages/amplify-ui-components/src/components/amplify-auth0-button/readme.md
packages/amplify-ui-components/src/components/amplify-authenticator/readme.md
packages/amplify-ui-components/src/components/amplify-examples/readme.md
packages/amplify-ui-components/src/components/amplify-federated-buttons/readme.md
packages/amplify-ui-components/src/components/amplify-form-field/readme.md
packages/amplify-ui-components/src/components/amplify-form-section/readme.md
packages/amplify-ui-components/src/components/amplify-input/readme.md
packages/amplify-ui-components/src/components/amplify-link/readme.md
packages/amplify-ui-components/src/components/amplify-radio-button/readme.md
packages/amplify-ui-components/src/components/amplify-select-mfa-type/readme.md
packages/amplify-ui-components/src/components/amplify-totp-setup/readme.md
packages/amplify-ui-components/src/components/amplify-verify-contact/readme.md

- Sync build for ui components
- Fix deploy

Build sync

---

packages/datastore/__tests__/model.ts
packages/datastore/__tests__/schema.ts
packages/datastore/src/datastore/datastore.ts

fixes: #4695 
Adding validation for self type referencing and unit test validation

fix(@aws-amplify/datastore): Topological sorting fix for self type referencing

---

.github/ISSUE_TEMPLATE/bug_report.md

Updating template to use proper label

chore: Update issue templates to reflect new label

---

.github/stale.yml

Second Pull Request after implementation of [Adding new label](https://github.com/aws-amplify/amplify-js/commit/3cc6ba4999686dcacff7f61964737d6590d379e6)

chore: Removing unused label from exempt labels

---

packages/auth/src/Auth.ts

fix unhandled urlListener for OAuth with `error_description`

---

packages/analytics/index-rn.js
packages/api/index-rn.js
packages/auth/index-rn.js
packages/aws-amplify/index-rn.js
packages/cache/index-rn.js
packages/cache/package.json
packages/core/index-rn.js
packages/interactions/index-rn.js
packages/predictions/index-rn.js
packages/pubsub/index-rn.js
packages/storage/index-rn.js
packages/xr/index-rn.js

Issue #, if available:
Fixes: #4711
Revert change from e61d906 to import RN-specific cache module

fix(cache): export correct module for RN

---

.circleci/config.yml
package.json

_Description of changes:_Enable preview publishes from modularization branch

Enable preview publishes from modularization branch

---

.circleci/config.yml
package.json

Enable publish from rn-datastore branch

Enable publish from rn-datastore branch

---

packages/amplify-ui-components/__tests__/__snapshots__/bundle-size.spec.js.snap
packages/amplify-ui-components/stencil.config.ts

- Clean up new commonjs named exports from aws-sdk-v3

chore(@aws-amplify/ui-components): CommonJS named exports from sdk-v3

---

packages/amplify-ui-components/stencil.config.ts

- Add XR module to externals for sumerian-scene component
- Add Storage module to externals for Storage UI components

chore(@aws-amplify/ui-components): Add Amplify XR + Storage modules to externals

---

packages/amplify-ui-components/__tests__/__snapshots__/bundle-size.spec.js.snap
packages/amplify-ui-components/stencil.config.ts

_Description of changes:_ Updates the stencil config cjs exports.

Chore update stencil config

---

packages/storage/__tests__/Providers/AWSS3Provider-unit-test.ts

- Update unit test's response object to match what aws-sdk-v3 returns 

chore(modularization): Fix AWSS3Provider unit tests

---

packages/core/package.json

fix(core): revert dep addition. Move to peerDeps

---

.circleci/config.yml

ci: Make deploy wait on integ_rn_ios_storage

---

packages/api/src/API.ts

_Issue #, if available:_ https://github.com/aws-amplify/amplify-js/issues/4981
_Description of changes:_ fix minor typo in a function

chore(@aws-amplify/api): fix non-breaking typo in function

---

packages/datastore/src/storage/adapter/AsyncStorageDatabase.ts
packages/datastore/src/sync/datastoreConnectivity.ts
packages/datastore/src/sync/index.ts
packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts
packages/pubsub/src/index.ts

Adding socket disconnection detection to improve reachability capabilities. Also fixing disconnection issue on react-native.
Tested on Android Device and Web browser

Adding socket disconnection detection

---

.circleci/config.yml

_Issue #, if available:_NA
_Description of changes:_Enable integration tests on modularization branch

Enable integration tests on modularization branch

---

.circleci/config.yml

N/A
Don't copy datastore built files since the samples repo doesn't use them

chore: remove datastore form RN integ tests

---

packages/amazon-cognito-identity-js/package.json
packages/auth/package.json

_Issue #, if available:_ Resolves #5159
Version `3.3.0` is equivalent to `3.1.9-1`:
> https://github.com/brix/crypto-js/issues/256#issuecomment-585175130
Resolves security vulnerability:
> https://app.snyk.io/vuln/SNYK-JS-CRYPTOJS-548472

Update to crypto-js@^3.3.0

---

packages/amplify-ui-components/Readme.md

**_Description of changes:_**
Update readme for usage of `usernameAlias` property.

[UI Components] Chore usernameAlias readme update

---

packages/amplify-ui-components/Readme.md
packages/amplify-ui-react/package.json
packages/amplify-ui-react/src/index.ts
packages/amplify-ui-react/src/withAuthenticator.tsx
packages/amplify-ui-storybook/README.md
packages/amplify-ui-storybook/package.json
packages/amplify-ui-storybook/src/stories/AmplifyAuthenticator.stories.tsx

_Issue #, if available:_ Delivers #171965194
> ![Screen Shot 2020-03-26 at 12 18 28 PM](https://user-images.githubusercontent.com/15182/77688519-6f68c400-6f5d-11ea-8537-bb3412d3564d.png)

feat(@aws-amplify/ui-react): withAuthenticator(Component[, props])

---

packages/amplify-ui-components/Readme.md

Modeled after @ashika01's `usernameAlias` PR #5065, this adds documentation for `federated` including usage & the shape.
---

chore(@aws-amplify/ui-components): federated documentation

---

packages/storage/package.json

_Issue #, if available:_ fixes #5278
_Description of changes:_Add axios dependency in storage package

Fix #5278 Add axios dependency in storage package

---

packages/amazon-cognito-identity-js/index.d.ts

- Update appendCognitoUserName type
- Made type more accurate
- Related: https://github.com/aws-amplify/amplify-js/pull/5288

Update cognito user name append type

---

packages/amplify-ui-angular/tsconfig.json

- Change flatModuleId in angular tsconfig

Fix Angular 9 without ivy configured

---

packages/amazon-cognito-identity-js/src/CognitoUser.js

https://github.com/aws-amplify/amplify-js/issues/4396
https://github.com/aws-amplify/amplify-js/issues/5043
https://github.com/aws-amplify/amplify-js/issues/2534
https://github.com/aws-amplify/amplify-js/issues/5229
Refresh cached user after updating attributes

fix(auth): refresh cached user after updating attributes

---

packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts

fix(@aws-amplify/pubsub) Remove cyclic dependency that causes issues with watch builds

fix(@aws-amplify/pubsub) Remove cyclic dependency that causes issues with watch builds

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

**Description**
Updating the Bug template in order to have more clarity from customers to help us help them reproduce their issues

chore: (Update bug templates)

---

packages/amplify-ui-components/src/components/amplify-confirm-sign-up/amplify-confirm-sign-up.tsx
packages/amplify-ui-components/src/components/amplify-forgot-password/amplify-forgot-password.tsx
packages/amplify-ui-components/src/components/amplify-sign-in/amplify-sign-in.tsx
packages/amplify-ui-components/src/components/amplify-sign-up/amplify-sign-up.tsx

**_Quick fix_** to `handleInputChanges` for formFields. Looking at this, we might need to think more around defaults for formField in general.

UI Components - Chore add default value to handleInput of formFields

---

packages/datastore/src/datastore/datastore.ts
packages/datastore/src/index.ts

Fixes: #5448 
Adding `Amplify.register` to DataStore class

Fix DataStore production build

---

packages/amplify-ui-components/src/common/Translations.ts
packages/amplify-ui-components/src/components/amplify-email-field/amplify-email-field.spec.ts

https://github.com/aws-amplify/amplify-js/issues/5498

Update email placeholder 

---

.vscode/settings.json

N/A
Set default formatter in VS Code to prettier

chore: Set default formatter in VS Code to prettier

---

packages/amplify-ui-components/src/components/amplify-greetings/amplify-greetings.scss
packages/amplify-ui-components/src/components/amplify-greetings/amplify-greetings.tsx

fixes: https://github.com/aws-amplify/amplify-js/issues/5551
- Remove slot from greetings that was causing improper rendering

Fix improper greetings slot

---

packages/analytics/package.json
packages/core/package.json
packages/interactions/package.json
packages/predictions/package.json
packages/storage/package.json

Reverts aws-amplify/amplify-js#5575

Revert "Upgrade aws-sdk clients to beta4"

---

packages/amplify-ui-components/stencil.config.ts

- Set `initializeNextTick` in stencil config to get rid of component hydration flicker
- https://github.com/ionic-team/stencil/issues/2148#issuecomment-620243210

fix(@aws-amplify/ui-components): Fix component flickering

---

.circleci/config.yml

Reverts aws-amplify/amplify-js#5653

Revert "Increase cypress coverage"

---

packages/amazon-cognito-identity-js/index.d.ts

_Issue #5674 
_Description of changes: Added missing AdvancedSecurityDataCollectionFlag to ICognitoUserPoolData

Added missing flag to ICognitoUserPoolData

---

.circleci/config.yml
packages/amplify-ui-react/__tests__/withAuthenticator-test.tsx
packages/amplify-ui-storybook/package.json

- Update `withAuthenticator` unit test
- Add unit tests to CI for new ui libraries

Add new ui unit tests to circleci, fix withAuthenticator unit test

---

packages/core/src/Util/Retry.ts

fixes: #5638
- Correctly log error object for retry failure

fix(@aws-amplify/core): Correctly log retry error object

---

README.md
packages/aws-amplify-react/__tests__/Auth/Provider/withFacebook-test.tsx
packages/aws-amplify-react/src/Auth/Provider/withFacebook.tsx

Based on @danielbayerlein's work in https://github.com/aws-amplify/amplify-js/pull/4220
---

chore: Update README.md with new docs links

---

packages/datastore/src/storage/adapter/asyncstorage.ts
packages/datastore/src/storage/adapter/indexeddb.ts
packages/datastore/src/types.ts
packages/datastore/src/util.ts

resolves #5088 
Enable relational modeling using the `@key` directive

feat(@aws-amplify/datastore): enable keyName relations

---

packages/pushnotification/src/PushNotification.ts

Handle launching an app from killed state through notifications in iOS

Handle launching an app from killed state through notifications in iOS

---

.circleci/config.yml

ci: add datastore integ test to pipeline

---

packages/core/src/index.ts
packages/datastore/src/sync/index.ts
packages/datastore/src/sync/processors/subscription.ts
packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts
packages/pubsub/src/index.ts

Co-authored-by: Francisco Javier Rodriguez Elorza <28815678+elorzafe@users.noreply.github.com>
Fixes: #5648
Fixes: #4811
Log connection errors for models, keep syncing the available ones.

fix(@aws-amplify/datastore): Allow partial subscriptions.

---

packages/amplify-ui-angular/src/amplify-module.ts

- Add `AmplifyContainer` to Angular module

Angular container added to module

---

.circleci/config.yml

Add storage integ test to pipeline

Add storage integ test to pipeline

---

packages/amazon-cognito-identity-js/index.d.ts

_Description of changes: add missing optional parameter clientMetadata to CognitoUser refreshSession 

add missing optional parameter clientMetadata to CognitoUser refreshSession 

---

.circleci/config.yml
vscode/package-lock.json

chore(deps): fix some vscode/* vulnerable deps

---

packages/amazon-cognito-identity-js/README.md

removed empty javascript code block

doc: readme Use case 26

---

packages/datastore/src/datastore/datastore.ts

Fixes a bug where passing a `conflictHandler` in a separate invocation of `configure` would ignore the custom handler, even if the existing handler was set to default. 
E.g., running `Amplify.configure(awsconfig)` sets the conflictHandler to `defaultConflictHandler` so if that is followed by:
```js
DataStore.configure({
conflictHandler: async (data) => {
console.warn('Conflict: ', data);
}
});
```
DataStore ignores the custom handler.
This PR gives precedence to the custom handler set via `DataStore.configure`

fix(@aws-amplify/datastore): give precedence to config.conflictHandler

---

packages/amplify-ui-components/package.json

chore(@aws-amplify/ui-components): pin @stencil/core

---

packages/amplify-ui-components/package.json

chore(@aws-amplify/ui-components): pin @stencil/core@1.15.0

---

packages/amplify-ui-angular/package.json

chore(@aws-amplify/ui-angular): pin @types/node@12.12.47

---

packages/amplify-ui-components/src/components.d.ts
packages/amplify-ui-components/src/components/amplify-s3-album/readme.md

- adding missed files that updates readme

Update Storage Components

---

packages/amplify-ui-components/src/components.d.ts
packages/amplify-ui-components/src/components/amplify-photo-picker/amplify-photo-picker.tsx
packages/amplify-ui-components/src/components/amplify-photo-picker/readme.md
packages/amplify-ui-components/src/components/amplify-picker/amplify-picker.tsx
packages/amplify-ui-components/src/components/amplify-picker/readme.md
packages/amplify-ui-components/src/components/amplify-s3-image-picker/amplify-s3-image-picker.tsx

- Minor chore cleaning up warnings.

[Chore] UI Components storage - update click handler and docs

---

.circleci/config.yml

- Enables Storage UI Components Integration test in CircleCI
The integration tests was run successfully when tried running the tests on the branch - https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/5494/workflows/fbc6fb16-e130-40a6-8c85-ee386fe7d011
**Screenshot of storage tests:**

UI Components Storage Circle CI

---

README.md

Add link to the new JS Samples Repo. Used term "demo applications". 

Add link to JS Samples

---

CONTRIBUTING.md

- Update react reference to new UI components

Update react reference to new UI components

---

vscode/snippet_maker.py
vscode/snippets/I18n.code-snippets
vscode/snippets/analytics.code-snippets
vscode/snippets/angular.code-snippets
vscode/snippets/api.code-snippets
vscode/snippets/auth.code-snippets
vscode/snippets/auto.code-snippets
vscode/snippets/cache.code-snippets
vscode/snippets/classes.code-snippets
vscode/snippets/configure.code-snippets
vscode/snippets/functions.code-snippets
vscode/snippets/hub.code-snippets
vscode/snippets/interactions.code-snippets
vscode/snippets/interfaces.code-snippets
vscode/snippets/logger.code-snippets
vscode/snippets/object_literals.code-snippets
vscode/snippets/pubsub.code-snippets
vscode/snippets/push_notifications.code-snippets
vscode/snippets/service_workers.code-snippets
vscode/snippets/storage.code-snippets
vscode/snippets/variables.code-snippets

_Issue #, if available:_ N/A
_Description of changes:_ This PR adds the `typescriptreact` scope to all code snippets allowing them to be used in `.tsx` files.

feat(vscode-extension): Add TypeScript React support

---

packages/amplify-ui-components/src/components.d.ts
packages/amplify-ui-components/src/components/amplify-totp-setup/readme.md

- Update TOTP setup readme with new prop
- Fix CircleCI deploy failure

Update TOTP setup readme

---

packages/datastore/package.json

- bump `dexie` version for type fix

fix - datastore unit test fail

---

vscode/snippets/storage.code-snippets

I updated the Storage snippets, added new prefix and i also removed redundant prefix that does nothing but output a line of text.

Made changes to the storage snippets

---

vscode/snippets/hub.code-snippets

I removed onHubCapsule because it's now Legacy, I added hub.listen, hub.dispatch and hub.install.

Created vscode Hub snippets

---

vscode/snippets/pubsub.code-snippets

- Updated pubsub snippets
- Added unsubscribe which was not in the old snippet

Vscode pubsub

---

vscode/snippets/push_notifications.code-snippets

Updated the Push Notification config and the onNotification API, i also removed push notification code blocks that are not useful.

Vscode push notification

---

packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.scss
packages/amplify-ui-components/src/components/amplify-section/amplify-section.scss
packages/amplify-ui-components/src/global/theme.ts

Issue #6076 fix
Add a few more styling overrides to the Authenticator box - box-shadow, border-radius, padding & margin bottom
Additional context
#6047 

Authenticator style overrides

---

vscode/snippets/interactions.code-snippets

Made changes on on the interactions snippets and updated the react and react native chat bot prefix so that they are different from each other.

Vscode interactions

---

vscode/snippets/service_workers.code-snippets

Updated Register and enablePush, i also created a config for service worker, A send and receive snippets

Vscode service worker

---

vscode/package.json
vscode/snippets/datastore.code-snippets

_Description of changes:_ This PR adds DataStore code snippets to the Amplify vscode extension

feat(vscode-extension): Add DataStore code snippets

---

vscode/snippets/auth.code-snippets

_Issue #, if available:_ None
_Description of changes:_ This PR updates `auth.code-snippets` and adds snippets for Amplify's UI components

feat(vscode-extension): Update auth code-snippets

---

vscode/snippets/analytics.code-snippets

_Issue #, if available:_ N/A
_Description of changes:_ This PR fixes a small typo in `analytics.code-snippets`.

fix(vscode-extension): Fix typo in analytics.code-snippets

---

.circleci/config.yml
package.json

_Description of changes:_ Enable preview release from ui-components/main branch.

ci: enable preview release from ui-components/main

---

scripts/build.js

Add asyncgenerator library to be included at compilation

---

package.json
scripts/build.js

_Description of changes:_ This syncs ui-components/main with main branch to fix ci issues.

Sync ui-components/main with main

---

.circleci/config.yml

ci: pass correct option to retry script for android

---

.circleci/config.yml
packages/auth/src/Auth.ts
packages/datastore/__tests__/subscription.test.ts
packages/datastore/src/sync/processors/subscription.ts
packages/datastore/src/types.ts

_Description of changes:_ This PR syncs ui-component/main with main.

Sync ui-component/main with main

---

packages/aws-amplify/src/withSSRContext.ts
packages/datastore/__tests__/AsyncStorage.ts
packages/datastore/src/storage/adapter/AsyncStorageDatabase.ts
packages/datastore/src/storage/adapter/InMemoryStore.native.ts
packages/datastore/src/storage/adapter/InMemoryStore.ts

See commits for further details.
Introduced by https://github.com/aws-amplify/amplify-js/pull/6146

fix(@aws-amplify/datastore): DataStore regression with AsyncStorage

---

.circleci/config.yml

Run DataStore public/private auth tests in CircleCI.
---

chore: add private & public DS auth tests to CCI

---

.circleci/config.yml

chore: add DS custom claim test to CircleCI

---

packages/core/src/Util/Reachability.ts

Addresses [this part](https://github.com/aws-amplify/amplify-js/issues/6204#issuecomment-654488556) of the feature request for adding web worker support for DataStore. The other part was added in #6874 

feat(@aws-amplify/core): add worker support to reachability

---

NOTICE

Based on feedback shared from our Open Source team, I went ahead and removed the copyright date in favor of what is in the file with this change.

chore:Update NOTICE file to remove copyright date

---

packages/amplify-ui-components/src/components/amplify-sign-up/amplify-sign-up.tsx

update description for signInText

---

packages/amplify-ui-components/src/components/amplify-section/amplify-section.scss

_Issue #, if available:_ Fixes #7003 
_Description of changes:_ This assigns default values to amplify-section.

fix: assign default values to amplify-section

---

packages/amazon-cognito-identity-js/index.d.ts

_Issue #, if available:_ #1355

Add Type Definitions

---

packages/amplify-ui-components/src/components/amplify-phone-field/__snapshots__/amplify-phone-field.spec.ts.snap
packages/amplify-ui-components/src/components/amplify-phone-field/amplify-phone-field.tsx

Fixes: #7201 
type="tel" now on correct component

Fix phone number input type

---

packages/datastore/src/datastore/datastore.ts
packages/datastore/src/storage/adapter/IndexedDBAdapter.ts
packages/datastore/src/storage/storage.ts
packages/datastore/src/types.ts

feat(@aws-amplify/datastore): handle sessionId

---

packages/amazon-cognito-identity-js/README.md

This is the replacement for https://github.com/aws-amplify/amplify-js/pull/7400

Docs updated: define the variable before using it.

---

packages/amplify-ui-components/src/common/audio-control/helper.ts

_Description of changes:_ Changes audiio to audio 🙃 

fix(@aws-amplify/ui-components): fix typo

---

packages/amazon-cognito-identity-js/index.d.ts

https://github.com/aws-amplify/amplify-js/pull/7633#issuecomment-769693491
- `options` should be optional 
---

fix(amazon-cognito-identity-js): make options optional

---

packages/amplify-ui-components/src/common/Translations.ts
packages/amplify-ui-components/src/components/amplify-sign-up/amplify-sign-up.tsx

_Issue #, if available:_ fixes #7636
_Description of changes:_ Checks for empty string and `undefined` before doing any string operation.

fix(@aws-amplify/ui-components): handle non-username alias cases

---

.github/actions/bundle-size-action/webpack/package.json
.github/actions/bundle-size-action/webpack4/package.json
packages/analytics/package.json
packages/analytics/src/Providers/AWSPinpointProvider.ts
packages/core/package.json
packages/interactions/package.json
packages/predictions/package.json
packages/storage/package.json
packages/storage/src/providers/AWSS3ProviderManagedUpload.ts
packages/storage/src/providers/axios-http-handler.ts

Reverts aws-amplify/amplify-js#7674

Revert "chore: bump aws-sdk to 3.4.1"

---

.circleci/config.yml

- add integration test for Storage multi-part upload with progress reporting
- https://github.com/aws-amplify/amplify-js-samples-staging/pull/196
Note: this test will fail until https://github.com/aws/aws-sdk-js-v3/issues/2000 is resolved, since `unstable` is currently using the latest version of the AWS SDK. I have verified that the tests pass on `latest` however.
---

chore: add storage multi-part w/ progress to CircleCI

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/workflows/bug-report-helper.yml

chore: improve bug report template

---

.github/ISSUE_TEMPLATE/new_bug_report.yaml

- fix duplicate label on environment field

fix: Update new_bug_report.yaml

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/workflows/bug-report-helper.yml

chore: update bug template

---

packages/amazon-cognito-identity-js/src/CognitoUser.js

- Update `userDataKey` when `username` is set from challenge parameters during `InitiateAuth`.
- Formatting changes from Prettier.
---

fix(amazon-cognito-identity-js): set userDataKey with updated username

---

packages/core/src/Util/DateUtils.ts

chore: test ci

---

package.json

see https://github.com/lerna/lerna/issues/2788 for more info

ci: allow lerna publish with npm automation token

---

.circleci/config.yml

Adding e2e test for https://github.com/aws-amplify/amplify-js/pull/8000 to the CI pipeline.
Successful run: https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/7514/workflows/e707dc61-f455-4b5d-a6d5-0e43633f1522/jobs/36624

chore: add consecutive saves e2e test

---

packages/amazon-cognito-identity-js/__tests__/CognitoAccessToken.test.js
packages/amazon-cognito-identity-js/jest.config.js

test(cognito-identity-js): adding coverage for cognito access token

---

.github/ISSUE_TEMPLATE/1.bug_report.yaml

- update for deprecated fields and all textareas now being rich text editor-enabled
- add reference to discussions in confirmation sections

chore(issue forms): update for deprecated fields

---

packages/amazon-cognito-identity-js/__tests__/CognitoUserPool.test.js
packages/amazon-cognito-identity-js/__tests__/constants.js

Adding unit test coverage to CognitoUserPool
yarn test

test(cognito-identity-js): adding unit test coverage to CognitoUserPool

---

packages/amazon-cognito-identity-js/__tests__/CognitoIdToken.test.js

I ran `yarn test` to ensure that my tests provided the appropriate coverage

Adding test coverage for wrapper class CognitoIdToken

---

packages/amazon-cognito-identity-js/__tests__/Client.test.js
packages/amazon-cognito-identity-js/__tests__/CognitoUserSession.test.js
packages/amazon-cognito-identity-js/__tests__/StorageHelper.test.js
packages/amazon-cognito-identity-js/__tests__/constants.js
packages/amazon-cognito-identity-js/jest.config.js
packages/amazon-cognito-identity-js/package.json

test(cognito-identity-test): added unit test coverage to Client.js

---

packages/amazon-cognito-identity-js/__tests__/CognitoUser.test.js
packages/amazon-cognito-identity-js/__tests__/CognitoUserSession.test.js

Merging cognito-identity-test-eddy into cognito-identity-test

---

.github/ISSUE_TEMPLATE/1.bug_report.yaml

- remove optional attr that is breaking rendering

chore(repo):remove optional attr that is breaking rendering

---

packages/amazon-cognito-identity-js/__tests__/CognitoUser.test.js

tests(cognito-id-js): adding unit test coverage to getSession

---

packages/amazon-cognito-identity-js/__tests__/CognitoUser.test.js

adding a function call that was left out for some reason

---

packages/amazon-cognito-identity-js/__mocks__/mocks.js
packages/amazon-cognito-identity-js/__tests__/CognitoUser.test.js
packages/amazon-cognito-identity-js/__tests__/constants.js

refactoring mock implementations into the __mocks__ folder and calling them as needed. Also added some constants to dry up code.
running yarn test after each change to verify that the tests behave as expected

test(cognito-id-js): adding mocks and refactoring network requests

---

.circleci/config.yml
packages/datastore/src/sync/processors/subscription.ts

- Add additional required tests to CircleCI config
- Update logger warning format in `subscription.ts`

fix(@aws-amplify/datastore): Update CCI config & logger warning format

---

.circleci/config.yml

- Prepping the `native` branch so we can merge it into `main`

chore: re-enable skipped RN tests

---

.circleci/config.yml

This PR adds the CircleCI config to run integration tests for the guest authentication user scenario.
Tested against CircleCI, and tests ran successfully here: 
https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/7967/workflows/85b88d47-595c-4ba5-99e9-3af77b619811
```
[1]   Guest to Auth user scenario:
[1]     ✓ Unauthenticated (guest) Identity ID should be initially created in localstorage, then cleared after sign in (4457ms)
[1]     ✓ Authenticated user tokens should be created in localstorage on signin, removed on signout (2543ms)
[1] 
[1] 
[1]   2 passing (7s)
[1] 
[1] 
[1]   (Results)
[1] 
[1]   ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
[1]   │ Tests:        2 …
```

chore: update config for running new guest auth tests

---

CONTRIBUTING.md

Minor fixes to CONTRIBUTING doc:
* make it easier to copy/paste commands by removing unnecessary `$`'s
* replace deprecated `--skip-git` param with `--no-git-tag-version --no-push`
N/A

fix: minor contributing doc fixes

---

.circleci/config.yml

- Update Detox setup for Android tests in CircleCI
The `cask` command is no longer needed when using Homebrew.
Successful CircleCI run: https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/8099/workflows/a26279ea-3502-4294-abec-dd936a606ce3

chore: remove testing changes

---

.circleci/config.yml
packages/amazon-cognito-identity-js/index.d.ts
packages/amazon-cognito-identity-js/src/Client.js
packages/amazon-cognito-identity-js/src/CognitoUser.js
packages/auth/__tests__/auth-unit-test.ts
packages/auth/__tests__/hosted-ui.test.ts
packages/auth/src/Auth.ts

Adding token revocation feature
Added cypress test in samples repo
CircleCI workflow [here]( https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/8107/workflows/c555b390-d2f0-4a14-ab64-211bf7eddc59/jobs/44033)
- Add `token-revocation.spec.js` on integration test suite to validate this changes after merge

feat(amazon-cognito-identity-is, @aws-amplify/auth)

---

packages/amplify-ui-components/package.json

Bumps `ui-components` peer dependency to `4.x.x`
Fixes #8437
Matches current version: https://github.com/aws-amplify/amplify-js/blob/eb3b707722084f07d025344bf6bbc34927b79bf5/packages/aws-amplify/package.json#L3

Bump aws-amplify peer deps to `4.x.x`

---

.circleci/android-rn.sh
.circleci/config.yml

Update Android Emulator setup in CircleCI to use stable version instead of canary.

chore: update android setup in CircleCI

---

.circleci/config.yml

Temporarily disable Android Detox tests from running in CircleCI until we can fix the environment. These tests will be manually validated for each release.

chore: temporarily disable Android tests

---

packages/auth/src/Auth.ts

Dummy commit to force version bump

---

packages/amazon-cognito-identity-js/package.json

Resolves [this dependabot alert](https://github.com/aws-amplify/amplify-js/security/dependabot/packages/amazon-cognito-identity-js/package.json/react-native/open). This only bumps a dev dependency, so there is no effect on customers from this version bump.

chore: bump devDep react-native version

---

package.json
packages/geo/.npmignore
packages/geo/build.js
packages/geo/index.js
packages/geo/package.json
packages/geo/src/index.ts
packages/geo/tslint.json
packages/geo/webpack.config.dev.js
packages/geo/webpack.config.js

Geo category Milestone 1 - PR 1/6
Initial scaffolding for the Geo category package that exports an empty `Geo` class.
Builds succeed
Tests pass

feat(Geo): add Geo category initial scaffolding - Geo milestone 1 - PR 1/6

---

packages/datastore/src/util.ts

Per [this issue](https://github.com/aws-amplify/amplify-js/issues/8398), if an app using Datastore has a schema with optional `@connection` directives between two models - currently the `traverse` method it Datastore's `util.ts` file explicitly sets the value of the model's `@key` field to `null`.
This causes problems because DynamoDB can't reference the connection successfully. The record is saved fine in the IndexedDB locally, but the GraphQL call to the server ultimately fails because of the `null` value.
This fix simply converts the ternary assignment to a conditional which checks for a truthy value first before adding the property to the connected model's instance within the `IndexedDBAdapter`.
https://github.com/aws-amplify/amplify-js/issues/8398
Without the fix, we can see a …

fix(@aws-amplify/datastore): remove null properties from connected model instances

---

packages/core/__tests__/parseMobileHubConfig-test.ts
packages/core/src/Parser.ts
packages/geo/__tests__/Geo.test.ts
packages/geo/__tests__/Providers/AmazonLocationServicesProvider.test.ts
packages/geo/__tests__/data.ts
packages/geo/package.json
packages/geo/src/Geo.ts
packages/geo/src/Providers/AmazonLocationServicesProvider.ts
packages/geo/src/index.ts
packages/geo/src/types/Geo.ts
packages/geo/src/types/Provider.ts
packages/geo/src/types/index.ts

Geo milestone 1 - PR 3/6
Adds:
- initial `Geo` class
- initial `amazonLocationServicesProvider`
- configuration methods for both
- unit tests
Builds and unit tests all pass

feat(Geo): add Geo class and amazonLocationServicesProvider - Geo milestone 1 - PR 3/6

---

packages/core/src/Parser.ts
packages/geo/__tests__/Providers/AmazonLocationServicesProvider.test.ts
packages/geo/package.json
packages/geo/src/Geo.ts
packages/geo/src/Providers/AmazonLocationServicesProvider.ts
packages/geo/src/types/Geo.ts
packages/geo/src/types/Provider.ts

Geo milestone 1 - PR 6/6
Adds `searchByCoordinates`
- Builds and unit tests pass
- Validated using PoC application
*Documentation will be added in a follow-up PR*

feat(Geo): searchByCoordinates - Geo milestone 1 - PR 6

---

packages/core/__tests__/parseMobileHubConfig-test.ts
packages/core/src/Parser.ts
packages/geo/__tests__/Geo.test.ts
packages/geo/__tests__/Providers/AmazonLocationServicesProvider.test.ts
packages/geo/__tests__/data.ts
packages/geo/package.json
packages/geo/src/Geo.ts
packages/geo/src/Providers/AmazonLocationServicesProvider.ts
packages/geo/src/types/Geo.ts
packages/geo/src/types/Provider.ts

Update config methods to be more agnostic and scope configs to providers. The CLI's exported config to `aws-exports` was updated to nest `amazon_location_services` config under the `geo` key (before it was not scoped and just under `geo`). This updates Geo's config to handle that scoping. Also, updates to allow for more scoped provider configurations in the future, making it more agnostic to the provider.
Updated tests and ran this through my example application
_Documentation PRs are next in line_

chore(geo): update configs for newer scoped configurations and providers - Geo milestone 1 - PR 7

---

.circleci/config.yml
package.json

Add circle ci config to publish geo tag

Add circle ci config to publish geo tag

---

README.md

Adds the Geo category and docs link to the main Readme

chore(geo): add Geo to main readme

---

packages/analytics/webpack.config.js
packages/api-graphql/webpack.config.js
packages/api-rest/webpack.config.js
packages/api/webpack.config.js
packages/auth/webpack.config.js
packages/cache/webpack.config.js
packages/datastore/webpack.config.js
packages/interactions/webpack.config.js
packages/predictions/webpack.config.js
packages/pubsub/webpack.config.js
packages/storage/webpack.config.js
packages/xr/webpack.config.js

Update webpack config to correct link between bundles
`yarn build`
- [ x ] PR description included
- [ x ] `yarn test` passes

Update webpack config to correct link between bundles

---

packages/geo/src/Providers/AmazonLocationServicesProvider.ts

Add amplify user agent to location service client

Add amplify user agent to location service client

---

packages/geo/__tests__/Geo.test.ts
packages/geo/__tests__/Providers/AmazonLocationServicesProvider.test.ts
packages/geo/src/Providers/AmazonLocationServicesProvider.ts
packages/geo/src/types/AmazonLocationServiceProvider.ts
packages/geo/src/types/Geo.ts
packages/geo/src/types/index.ts

- Update types to be more provider agnostic
- Add Region to MapStyle from AmazonLocationServicesProvider
Updated tests and ran through PoC

feat(Geo): add region to MapStyle and update types

---

packages/datastore/package.json

Patching [this vuln](https://github.com/aws-amplify/amplify-js/security/dependabot/packages/datastore/package.json/immer/open) 
* automated tests + sample app

fix(@aws-amplify/datastore): patch immer vuln

---

packages/geo/CHANGELOG.md

chore(geo): add changelog with latest changes

---

packages/core/__tests__/Providers/AWSCloudWatchProvider-test.ts
packages/core/src/Providers/AWSCloudWatchProvider.ts

Yarn test was not working for me in core package. Fix in error throwing and assertions was needed
I ran tests in core scope and they passed. They are still failing for other packages but I will address them in a separate PR
BTW, these tests that I changed within this PR, did they run for all of you guys successfully ? I forked the repo a couple of days ago and was not able to run all tests.

fix(@aws-amplify/core): error throwing and tests

---

packages/aws-amplify/src/index.ts

Align with https://docs.amplify.aws/lib/analytics/getting-started/q/platform/js/#update-endpoint

fix(aws-amplify): export AnalyticsProvider

---

packages/aws-amplify/package.json
packages/geo/package.json

Conventional Commits won't bump to v1.0.0 due to https://github.com/lerna/lerna/issues/2668
So we are bumping to 1.0.0 manually and will release to 1.1.0 for GA.

chore(geo): bump version for GA release

---

.github/semantic.yml

chore: semantic-pr config

---

packages/notifications/src/inAppMessaging/InAppMessaging.ts

This PR prevents a duplicate pluggable from being added to InAppMessaging

chore: Don't allow adding an already added plugin

---

packages/notifications/src/inAppMessaging/Providers/AWSPinpointProvider/utils.ts

This PR allows the Pinpoint provider to extract custom data defined on the Pinpoint campaign as part of the message metadata
Localized testing

chore: Forward Pinpoint campaign custom data as message metadata

---

.circleci/config.yml
package.json

Add `publish:in-app-messaging/main` command and update circle ci config to publish in-app messaging tag
NA
NA

chore(in-app-messaging): add in-app messaging publish tag command

---

packages/notifications/package.json

This PR updates `package.json` in the Notifications package to updated dependency versions.

chore(in-app-messaging): Update dependency versions

---

packages/notifications/package.json

chore: Add uuid as a dependency

---

packages/core/package.json

chore:update @aws-sdk/client-cloudwatch-logs version in core

---

packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts

fix: AWSAppSyncRealTimeProvider websocket init fix

---

packages/notifications/src/inAppMessaging/Providers/AWSPinpointProvider/index.ts
packages/notifications/src/inAppMessaging/Providers/AWSPinpointProvider/types.ts
packages/notifications/src/inAppMessaging/Providers/AWSPinpointProvider/utils.ts
packages/notifications/src/inAppMessaging/types.ts

This PR updates config typing to be more accurate as to what's allowable.
Tested in test app

fix: Update config typing

---

packages/notifications/src/inAppMessaging/InAppMessaging.ts
packages/notifications/src/inAppMessaging/SessionTracker/SessionTracker.native.ts
packages/notifications/src/inAppMessaging/eventListeners.ts

This PR contains only auto-formatted changes as a result of running prettier through the package.

chore: Run prettier through package

---

packages/notifications/package.json

Upgrade internal dependency versions
NA
`yarn clean && yarn && yarn bootstrap && yarn build`

chore(in-app-messaging): upgrade internal dependency versions

---

packages/aws-amplify-react-native/package.json
packages/notifications/package.json

Use `in-app-messaging` tag for Notifications amplify deps
NA
`yarn clean && yarn && yarn bootstrap && yarn build && yarn test`

chore(in-app-messaging): use in-app-messaging tag for Notifications amplify deps

---

packages/datastore/package.json

Bump dexie to unblock the pipeline. Only used for testing datastore, so no downstream effects from this dependency update.
* Ran unit tests locally - passing now

chore(@aws-amplify/datastore): bump dexie packages
