media/storage_guide.md

This document currently does not render properly at https://aws.github.io/aws-amplify/media/storage_guide.html#amazon-s3-bucket-cors-policy I guess the superfluous space is the culprit; fixed a typo

Fixed a rendering error and a typo

---

packages/aws-amplify/src/Common/index.ts
packages/aws-amplify/src/index.ts

We would like to use the Signer method with a third-party http module like Angular's HttpClientModule.
So Signer interface will be exposed to the outside.
and use it like this
```
import { Signer } from 'aws-amplify';
```

Export Signer interface for 3rd party HttpModules.

---

packages/aws-amplify/src/Common/Platform/index.ts

Hi guys,
I'm using `awsmobile-cli` to configure a cloud-api for the project and the following command `awsmobile cloud-api invoke CloudApiTest <method> <path> [init]` is failing with an error
```
cloud-api invoke error:
ReferenceError: navigator is not defined
at Object.<anonymous> (/usr/local/lib/node_modules/awsmobile-cli/node_modules/aws-amplify/lib/Common/Platform/index.js:21:1)
```
So I've added this safe check for `navigator` variable.
Please let me know what you think on this.
Thank you!

Add safe check for navigator variable

---

README.md
packages/aws-amplify-react-native/dist/Auth/index.js
packages/aws-amplify-react-native/dist/index.js
packages/aws-amplify-react-native/src/Auth/index.js
packages/aws-amplify-react-native/src/index.js
packages/aws-amplify-react/dist/Auth/index.js
packages/aws-amplify-react/dist/index.js
packages/aws-amplify-react/src/Auth/index.jsx
packages/aws-amplify-react/src/index.jsx

This will allow for building custom SignIn, Loading, etc components but still leveraging the ease of `withAuthenticator`.

Make `withAuthenticator` HOC configurable

---

packages/aws-amplify-react-native/dist/AmplifyI18n.js
packages/aws-amplify-react-native/dist/Auth/Authenticator.js
packages/aws-amplify-react-native/dist/Auth/Loading.js
packages/aws-amplify-react-native/dist/Auth/index.js
packages/aws-amplify-react-native/src/AmplifyI18n.js
packages/aws-amplify-react-native/src/Auth/Authenticator.js
packages/aws-amplify-react-native/src/Auth/Loading.js
packages/aws-amplify-react-native/src/Auth/index.js

This is necessary because Auth.currentAuthenticatedUser() returns a Promise.
When a user is logged in and the app is reloaded, there is a brief flicker
during which the SignIn screen is shown before the authenticated app
appears. This Loading screen replaces that flicker and will toggle to
either signIn or signedIn, as appropriate.

Add Loading page for React Native authenticator

---

packages/aws-amplify-react-native/src/Auth/ConfirmSignUp.js
packages/aws-amplify/src/Auth/Auth.ts

*Issues #303 and #304*
* Add check for null user.
* Use `componentWillReceiveProps` instead of `componentWillMount` to set `username` in `confirmSignUp`.

Fixes for #303 and #304

---

README.md

#341
Updated the README.md file
For the "Add Authentication to your App" section, this PR added the instruction to enable user-signin feature first to the backend awsmobile project. 
This step is needed for the user to follow through without hitting errors.

Add instruction to enable user-signin feature

---

packages/amazon-cognito-identity-js/package.json

- Change repo url to https://github.com/aws/aws-amplify.git
- Change license info to point to`LICENSE` since `LICENSE.txt` does not exists in the `aws-amplify` repo.

Change repository URL and info on license

---

docs/media/authentication_guide.md
packages/aws-amplify/__tests__/Auth/auth-unit-test.ts
packages/aws-amplify/src/Auth/Auth.ts
packages/aws-amplify/src/Auth/types/Auth.ts

#179 
Add a new option `cookieStorage` to the manual setup for `Auth`. This parameter is the params passed to `CognitoUserPool` and `CognitoUser` as described in _Use case 26. Using cookies to store cognito tokens_ on https://github.com/aws/aws-amplify/tree/master/packages/amazon-cognito-identity-js
By setting this Cognito will store the tokens in a cookie allowing them to be used across subdomains.
If this option is not set then everything will work as is.

Cognito cookie storage

---

packages/aws-amplify/src/Auth/Auth.ts

#308 and #416
This PR add `developer` to the list of domains`setCredentialsFromFederation()` will accept credentials for. After this change you sign in using developer authenticated credentials from a Cognito Identity Pool with `federatedSignIn()` by passing `developer` as the provider.

Add support for developer authenticated strategies

---

packages/aws-amplify/src/Common/Logger/ConsoleLogger.ts

Issue #451
Using bind() to ensure that console.[log|warn|error] works in any environment.

Binding console to console functions

---

docs/media/push_notifications_setup.md

Added the missing maven repository url. The documentation mentions it above, but the code snippet appears to be the React Native default.

add updated maven repository url

---

packages/aws-amplify/__tests__/Auth/auth-unit-test.ts
packages/aws-amplify/src/Auth/Auth.ts

#592 
Fix the problem when using ```Auth.currentUserInfo()``` in the ```componentDidMount``` will return empty object

Auth current user info fix

---

docs/media/authentication_guide.md

- added a missing "-" in a domain name
- replaced "them" with "theme"

fix minor typos in authentication_guide.md

---

docs/media/api_guide.md

Changed `API.delete` to `API.del` as per previous Promise-based call

Fixed small typo

---

docs/media/federated_identity_setup.md

Adding additional detail in federated signin documentation

initial commit of documentation change

---

packages/amazon-cognito-identity-js/src/Client.js

Hi,
it related to PR : https://github.com/aws/aws-amplify/pull/605
Minor change : 
return "NetworkError" code inside the error callback in client.js on network error instead of Error code "Error".

use NetworkError code in aws-cognito-identity

---

packages/aws-amplify-react/src/AmplifyTheme.jsx

The hidden style is mandatory for AmplifyTheme because it is used in the PhotoPicker component.
The PhotoPicker component does not hide the preview with option `preview="hidden"` because there is no hidden style in AmplifyTheme as it should.
I am not sure there is a declared issue so it might be a new one. 
This pull request adds an hidden style in AmplifyTheme to make PhotoPicker work properly with `preview="hidden"` option.

Add hidden style

---

docs/media/api_guide.md
packages/aws-amplify/src/API/API.ts

Fixes #696 
[(https://github.com/aws/aws-amplify/issues/696)]
Adds the ability to sign custom graphql requests.

custom-graph-signatures

---

packages/aws-amplify/__tests__/Auth/auth-unit-test.ts
packages/aws-amplify/src/Auth/Auth.ts

Closes #796 
Changed logic of refresh to stop removing valid user if a refreshHandler is not configured for the provider.
Added a test. 
Any suggestions are welcome.

Changed refreshing federated token logic

---

packages/aws-amplify/__tests__/Common/Amplify-test.ts
packages/aws-amplify/src/API/index.ts
packages/aws-amplify/src/Analytics/Analytics.ts
packages/aws-amplify/src/Analytics/index.ts
packages/aws-amplify/src/Auth/index.ts
packages/aws-amplify/src/Common/Amplify.ts
packages/aws-amplify/src/Common/I18n/index.ts
packages/aws-amplify/src/Common/index.ts
packages/aws-amplify/src/PubSub/PubSub.ts
packages/aws-amplify/src/PubSub/index.ts
packages/aws-amplify/src/Storage/index.ts
packages/aws-amplify/src/index.ts

Move amplify config into common module

---

.gitignore
packages/aws-amplify/package.json
yarn.lock

Fixes: #761 
Set graphql dependency version to exactly 0.13.0

Set graphql dependency version to exactly 0.13.0

---

packages/amazon-cognito-identity-js/package.json

After upgrading to 3.0.0, we found it causes errors in Angular 6 and react native
Rollback to the previous version. Will try to replace crypto-browserify with sjcl

Roll back crypto-browserify to 1.0.9

---

packages/aws-amplify/src/Auth/Auth.ts

fix: setPreferredMFA method throws error when setting totp with no cellphone

---

packages/aws-amplify/src/API/API.ts

Move credential check inside AWS_IAM auth switch for GraphQL requests to prevent unnecessary warnings
Fixes #726
#726 
GraphQL requests performed a credential check no matter the auth type. This change moves the credential check inside of the auth type that needs it (AWS_IAM)

fix(API):Move credential check inside AWS_IAM auth switch

---

README.md

This is a very minor typo but I would like to correct it. `https` protocol should comes with two slashes but the original README contains only one slash.

Fix minor protocol typo

---

packages/aws-amplify/src/Interactions/Interactions.ts

Fixes #1075 
Do not raise an error in `Interactions.addPluggable` if type `pluggable.getProviderName()` does not match, just silently ignore it.

do not raise error on pluggable configuration

---

packages/amazon-cognito-identity-js/src/Client.js

Default 'UnknownError' message has typo: 'Unkown error', should be 'Unknown error'

fix typo: Unkown > Unknown

---

.circleci/config.yml

- Refactor circleci caching for workflows to save .ssh directory for deploy step use
- Minor update in cache key name and checksum

Cache ssh directory for circleci deploy step

---

packages/aws-amplify-react/.babelrc
packages/aws-amplify-react/__tests__/Auth/Provider/withAmazon-test.js
packages/aws-amplify-react/__tests__/Auth/Provider/withFacebook-test.js
packages/aws-amplify-react/__tests__/Auth/Provider/withGoogle-test.js
packages/aws-amplify-react/__tests__/Auth/__snapshots__/ConfirmSignIn-test.js.snap
packages/aws-amplify-react/__tests__/Auth/__snapshots__/ConfirmSignUp-test.js.snap
packages/aws-amplify-react/__tests__/Auth/__snapshots__/ForgotPassword-test.js.snap
packages/aws-amplify-react/__tests__/Auth/__snapshots__/VerifyContact-test.js.snap
packages/aws-amplify-react/package.json
packages/aws-amplify-react/src/Auth/Provider/withAmazon.jsx
packages/aws-amplify-react/src/Auth/Provider/withFacebook.jsx
packages/aws-amplify-react/src/Auth/Provider/withGoogle.jsx

To pass the user object in `onStateChange` so the `authData` gets defined.

React federated sign in fix

---

packages/aws-amplify/src/Auth/Auth.ts

Completing a fix to this issue:
https://github.com/aws/aws-amplify/issues/841
https://github.com/aws/aws-amplify/pull/967
Corrects a typo -- as you can see on line 107 of the updated file, the property name should be lower-cased when referenced on 'this'.

Fix typo which is breaking oauth combined with cookie storage

---

packages/api/__tests__/API-test.ts
packages/api/src/API.ts
packages/api/src/RestClient.ts

Removing credentials dependency on REST requests

---

packages/aws-amplify-react/src/Widget/SelectMFAType.jsx

fix(aws-amplify-react): show the setup totp component if totp is not verified

---

packages/api/__tests__/API-test.ts
packages/auth/__tests__/auth-unit-test.ts
packages/auth/__tests__/cred-unit-test-rn.ts
packages/core/__tests__/Credentials-test.ts
packages/core/src/Credentials.ts

fix(aws-amplify): use method get instead of getPromise for credentials

---

packages/amazon-cognito-identity-js/README.md

Updating the path of the repo in the README.md of `/amazon-cognito-identity-js` package. That session has a call to action for the developer engage on feedback in this project, it is quite annoying clicking on `https://github.com/aws/amazon-cognito-identity-js` being redirected to `https://github.com/amazon-archives/amazon-cognito-identity-js` to read the description and then be redirected to `https://github.com/aws-amplify/amplify-js/tree/master/packages/amazon-cognito-identity-js`

Fix repository path in amazon-cognito-identity-js package README.md

---

packages/core/src/Credentials.ts

*Issue #1382*
This is a one line change to fix the conditional statement while verifying the type of the object stored in `AWS.config.credentials`.

Fix not picking up existing credentials

---

packages/aws-amplify-react/src/Auth/AuthStateWrapper.jsx
packages/aws-amplify-react/src/Auth/Authenticator.jsx

Fixes #1482
After modularization of amplify library Amplify became the default export of @aws-amplify/core. The import statement in aws-amplify-react still used named import. Update code to use the default import

fix(aws-amplify-react): Fix import statement

---

packages/aws-amplify-react/__tests__/Auth/__snapshots__/Authenticator-test.js.snap
packages/aws-amplify-react/__tests__/Auth/__snapshots__/index-test.js.snap
packages/aws-amplify-react/__tests__/Widget/__snapshots__/TextPicker-test.js.snap
packages/aws-amplify-react/src/Auth/Authenticator.jsx
packages/aws-amplify-react/src/Auth/SignIn.jsx

Users can pass a list of components to withAuthenticator and it would render only the passed list. If the user does not pass SignUp or Forgot password the SignIn form will not render the links
for SignUp and Forgot password
Fixes issue #1467

fix(aws-amplify-react):Hide Forgot Password/Singup conditionally

---

packages/aws-amplify-angular/rollup.config.js

Fixes(#1469) - partially. 
Decreases angular package bundle size from..
```
-----------------------------
Rollup File Analysis
-----------------------------
bundle size:    452.454 KB
original size:  551.576 KB
code reduction: 17.97 %
module count:   146
-----------------------------
```
to...
```
-----------------------------
Rollup File Analysis
-----------------------------
bundle size:    244.845 KB
original size:  322.112 KB
code reduction: 23.99 %
module count:   145
-----------------------------
```
Also updates rollup config to conform with new supported schema and remove console errors.

changing rollup config to treat angular/common as external

---

.circleci/config.yml
packages/aws-amplify-vue/__tests__/SetMFA.test.js
packages/aws-amplify-vue/package.json
yarn.lock

Sets the babel-core value for aws-amplify-vue to enable tests to run.

setting babel-core version in vue

---

docs/media/authentication_guide.md
packages/aws-amplify-react-native/src/Auth/Authenticator.js

*Issue #1677*
update auth doc to clarify that federated option is not currently support on HOC react native component
delete useless federated mention on Authetificator.js file

clarify doc, HOC RN doesn't support federated option

---

docs/media/react_native_guide.md

Delete npm install aws-amplify-react, is not needed on react native app and is confusing.

delete useless npm install (react native project)

---

docs/media/authentication_guide.md

Fixes incorrect usage of then.

fix(spelling): Changes then to than

---

packages/core/src/Signer.ts

Fixes https://github.com/aws-amplify/amplify-js/issues/750
*Issue #, if available: 750*

Fixes "In this environment the sources for assign MUST be an object" for PubSub

---

packages/analytics/src/Providers/AWSPinpointProvider.ts
packages/core/src/RNComponents/index.ts

fixes #1790 
also fixes #1759 

fix for issue 1790

---

packages/core/package.json

fixing aws-sdk version to be the same as aws-appsync-sdk

fix(@aws-amplify/core): fix aws-sdk version to 2.329.0

---

packages/auth/src/Auth.ts
packages/core/src/Credentials.ts

fix(@aws-amplify/auth): throw error when failed to sync items from AsyncStorage into Memory

---

packages/aws-amplify-react/src/Auth/SignIn.jsx

*Issue #:* None
*Description of changes:* Fixes `SignIn` component not calling `signIn()` when Enter key is pressed.
The check for `!this.props.hide` didn't make sense, because `this.props.hide` is an array that contains components. The breaking change was introduced [here](https://github.com/aws-amplify/amplify-js/commit/bc6e54c3618ae38deee8e77f970066a8e2c851cc) .

Fix SignIn not signing in onKeyDown

---

packages/amplify-ui/package.json
packages/aws-amplify-angular/package.json
packages/aws-amplify-react-native/package.json
packages/aws-amplify-react/package.json
packages/aws-amplify-react/src/Auth/SignUp.jsx
packages/aws-amplify-vue/package.json

Proper semantic versioning plus resolving lerna issue:
```
Changes:
- @aws-amplify/ui: 1.0.9-unstable.0 => 1.0.9-beta.0
- aws-amplify-angular: 2.0.12-unstable.3 => 2.0.12-beta.0
- aws-amplify-react-native: 2.0.8 => 2.0.9-beta.0
- aws-amplify-react: 2.1.3-unstable.3 => 2.1.3-beta.0
- aws-amplify-vue: 0.1.6-unstable.0 => 0.1.6-beta.0
lerna info auto-confirmed 
lerna ERR! execute caught error
lerna ERR! Error: fatal: tag 'aws-amplify-angular@2.0.12-beta.0' already exists
lerna ERR! 
```

bumping versions

---

packages/auth/src/Auth.ts
packages/aws-amplify-react/src/Auth/Authenticator.jsx
packages/aws-amplify-react/src/Auth/Loading.jsx
packages/aws-amplify-react/src/Auth/Provider/withOAuth.jsx
packages/aws-amplify-react/src/Auth/common/constants.js
packages/aws-amplify-react/src/Auth/index.jsx

When redirecting back from the Hosted UI page, there is some latency before the user gets logged in. We need to render a loading page instead of the SignIn component for that latency so that the user knows he's in the process of getting logged in.

feat(aws-amplify-react): adding loading page

---

packages/amazon-cognito-identity-js/src/CognitoUser.js

#525 
Allow custom auth flow type as an extension of normal signin with username/password.
A user should be able to start a signin by entering username and password, and when that passes, be prompted for additional challenges (like custom MFA).  Cognito supports that workflow.  Amplify doesn't.  This solves that.  I have tested this change by making it locally, and everything works following that -> the user is launched into the custom auth flow in Cognito, invoking the correct triggers within.

feature(amazon-cognito-identity-js) allow custom auth

---

packages/core/src/I18n/index.ts

#1028
While doing the TypeScript conversion I noticed that I18n.get() is called in many places without the second parameter. Looking at the code it seems like this should be an optional parameter so I've added the `?` to make it optional.

The second parameter should be optional for I18n.get()

---

packages/pushnotification/android/src/main/java/com/amazonaws/amplify/pushnotification/modules/RNPushNotificationHelper.java

The custom sound from notification payload is not used correctly.
The actual payload is:
```
2018-09-13 17:44:11.207 5370-5370/app I/RNPushNotificationMessagingService: sendNotification: Bundle[{pinpoint.openApp=true, userInteraction=false, pinpoint.notification.sound=notification.caf, pinpoint.notification.title=Title, pinpoint.notification.body=Body, id=-727273900, pinpoint.campaign.campaign_id=_DIRECT, pinpoint.notification.silentPush=0}]
```
So we should retrieve the custom sound name by `pinpoint.notification.sound`
And for Android O or later, custom sound is not applied.

Fix couldn't play custom sound for notification on Android Oreo & later

---

packages/amplify-ui/src/Button.css
packages/aws-amplify-react/__tests__/Auth/SignIn-test.js
packages/aws-amplify-react/src/Amplify-UI/Amplify-UI-Components-React.jsx
packages/aws-amplify-react/src/Auth/SignIn.jsx

**Issue**
Sign in button was not disabled when loading.
This makes the UI look like nothing is happening after submitting user credentials, specially when using the keyboard Enter key for submission.
**Description of changes:**
1. Added `disabled` state to `Button` component on `Amplify-UI`
2. Making `disabled=true` when signing in on `aws-amplify-react -> Auth`

feat(aws-amplify-react): disable sign in button while loading

---

packages/aws-amplify-angular/package.json
packages/aws-amplify-react/package.json
packages/aws-amplify/package.json

Add @aws-amplify/ui into the dependencies of `aws-amplify` and remove it from `aws-amplify-angular` and `aws-amplify-react`.

add @aws-amplify/ui as the dependent of aws-amplify

---

packages/aws-amplify-react-native/src/Auth/ConfirmSignIn.js
packages/aws-amplify-react-native/src/Auth/ConfirmSignUp.js

#1882
Pass theme to AmplifyButton in React Native ConfirmSignIn and ConfirmSignUp components.

Add theme to button for SignUp and SignIn

---

packages/aws-amplify-react/__tests__/Auth/SignUp-test.js
packages/aws-amplify-react/src/Auth/SignUp.jsx

Fixes bug where hiding phone number input would case an error see issue #2160
https://github.com/aws-amplify/amplify-js/issues/2160 
There are multiple things going on in that issue, this addresses one of them, number 2 in the summary of mrcoles
When adding the attributes to the `signup_info`, the current code creates the `phone_number` attribute both for the `phone_line_number` and the `dial_code` inputs. The second assignment just overrides the first with the same value.
The problem occurs if the phone number default is hidden as the `dial_code` is still added as an input, causing a reference error when calling `replace` on `phone_line_number` which is undefined. 
The fix only adds the `phone_number` attribute for the …

fix(@aws-amplify-react/Auth)

---

packages/storage/src/Providers/AWSS3Provider.ts

*Issue #, if available:* Fixes #2378
Add explicit signature version when creating S3 object. This allows generating a presigned URL for AWS KMS–managed encrypted files. From docs:
"When creating a presigned URL for an object encrypted using an AWS KMS–managed encryption key, you must explicitly specify Signature Version 4."
See https://docs.aws.amazon.com/AmazonS3/latest/dev/kms-using-sdks.html

fix(@aws-amplify/storage): Explicitly declare signatureVersion 'v4'

---

packages/core/src/Credentials.ts
packages/storage/src/Providers/AWSS3Provider.ts

#2397
Core/Credentials
Return aws credentials instead of calling load credentials
Storage/AWSS3Provider
Configure credentials on S3 instead of AWS.config

fix(@aws-amplify/core) fix(@aws-amplify/storage) Fix credentials issue with storage and aws config credentials

---

packages/aws-amplify-react/src/Auth/Authenticator.jsx

Related to #2318 
> Using hideDefault={true} was throwing an error props_children does not have function find.

fix(aws-amplify-react): transfer the children object to array

---

packages/aws-amplify-react-native/src/Auth/ForgotPassword.js
packages/aws-amplify-react-native/src/Auth/Greetings.js
packages/aws-amplify-react-native/src/Auth/VerifyContact.js

#2465 
Pass theme into AmplifyButton instance that previously did not have a theme prop or used style prop.

Pass theme to AmplifyButton instances

---

packages/aws-amplify-react/src/Auth/index.jsx

#1693 
Use React.Fragment to wrap elements instead of legacy div dom element wrapper.

Use React fragment instead of container div dom element

---

packages/analytics/src/Providers/AWSPinpointProvider.ts

Fixed a bug that transformed attributes and userAttributes object keys to lowercase while processing updateEndpoint requests.
*Issue:*
`_updateEndpoint()` transforms event object keys (such as eventId, name, session) to lowercase before sending to `_endpointRequest()` for request formatting. In the process, *attributes* and *userAttributes* object keys are inadvertently transformed.
Essentially, the whitelist variable supplied to the transform function is filtering out *Attributes* and *UserAttributes* which does not exist on the event object. Instead, it should filter out *attributes* and *userAttributes*.
Changed values of the whitelist variable to `['attributes', 'userAttributes']`
By submitting this pull request, I confirm that my contribution is made under …

fix(@aws-amplify/analytics): Fix attributes and userAttributes case transform on updateEndpoint.

---

packages/auth/src/Auth.ts

To give more info when `Auth.currentAuthenticatedUser()` failed.

print a console error if no user pool

---

packages/aws-amplify-react/src/Auth/Greetings.jsx

Those client ids are not used in `SignOut` component. Related to #2436 

Remove unused props in Greetings

---

packages/aws-amplify-react/__tests__/Storage/S3Album-test.js
packages/aws-amplify-react/__tests__/Storage/S3Image-test.js
packages/aws-amplify-react/__tests__/Storage/S3Text-test.js
packages/aws-amplify-react/src/Storage/S3Album.js
packages/aws-amplify-react/src/Storage/S3Image.js
packages/aws-amplify-react/src/Storage/S3Text.js

Surfacing the identityId option from the Storage class
as a prop of the S3* React components allows viewing protected files
of other users in a social app. The identityId values for other users
must be provided out-of-band, e.g. via GraphQL.
Resolves #2424

feat(aws-amplify-react): add identityId prop to S3Album, S3Image, S3Text

---

packages/analytics/src/Providers/AWSPinpointProvider.ts

Currently, the code displays:
```
Please ensure you have updated you Pinpoint IAM Policywith the Action: "mobiletargeting:PutEvents" in order tocontinue using AWS Pinpoint Service
```
This changes displays:
```
Please ensure you have updated your Pinpoint IAM Policywith the Action: "mobiletargeting:PutEvents" in order to continue using AWS Pinpoint Service
```

Fix typo in AWSPinpointProvider

---

packages/aws-amplify-vue/src/components/authenticator/SignIn.vue

#2571 
Redirects user to confirmsignup (vue) when usernotconfirmed exception is returned.

fixes(aws-amplify-vue)

---

packages/analytics/src/trackers/SessionTracker.ts
packages/analytics/src/types/Analytics.ts

Replacing PR #735 (inactive) Thanks @gnomishperson
#734

Update EventAttributes type

---

package.json

https://github.com/lerna/lerna/tree/2.x#--exact
This will force pre-releases and betas to use an exact match of dependencies from the monorepo.

Use Lerna's --exact when publishing prereleases

---

packages/analytics/src/Providers/AWSPinpointProvider.ts

*Issue #, if available:* 
N/A
Noticed a small typo on the console logger for `updateEndpoint`. The relevant change is on line 388. As an (unfortunate?) bonus, my linter cleaned up useless whitespace.

Updates typo on logger.warn for updateEndpoint

---

packages/xr/__tests__/XR-unit-test.ts
packages/xr/src/Providers/SumerianProvider.ts

#2366 
- Use Sumerian scene configured region (from downloaded Sumerian json config)
- As a fallback use the XR configured region
- If neither is defined throw an Error

Allow dynamic region config for Sumerian scene provider

---

packages/amazon-cognito-identity-js/src/AuthenticationHelper.js

Fixes #1181 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Import_a_module_for_its_side_effects_only
> Import a module for its side effects onlySection
Import an entire module for side effects only, without importing anything. This runs the module's global code, but doesn't actually import any values.

fix(build): Prevent tree-shaking of crypto-js/lib-typedarrays

---

packages/cache/src/InMemoryCache.ts

wether->whether
Simple comment typo.
Changed "wether" to "whether" in comment in cache memory implementation.

"wether" typo

---

packages/amplify-ui/package.json

Changed package.json to use cpx instead of cp to support building locally on Windows.

Amplify ui windows build fix

---

packages/amplify-ui/src/Angular.css

The alert element was not centered like it was on larger screens. I added left/right margins that makes it centered again.

Fixes alert element not being centered on small screens

---

packages/aws-amplify-react/src/Auth/Greetings.jsx
packages/aws-amplify-react/src/Auth/index.jsx

#2701 
Uses Authenticator in HOC signedIn state instead of Greetings only, and adds validAuth state to greetings component to make this possible

fix(aws-amplify-react) #2301

---

packages/aws-amplify-react/src/Auth/index.jsx

This semicolon gets rendered as HTML text.
:heavy_check_mark: By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

fix: remove stray semicolon after app wrapper

---

packages/aws-amplify-react/src/Auth/SignIn.jsx

When clicking federated buttons, the signIn method will be false triggered. This is because the <form/> element also includes the federated buttons.
Adjust the position of <FederatedButtons/> and <form/>

fix(aws-amplify-react): Change the position of <form/> element in the <SignIn/> component

---

packages/storage/__tests__/Storage-unit-test.ts
packages/storage/src/Storage.ts
packages/storage/src/index.ts

#2693 
Update Storage.configure and Storage.vault.configure to support backwards compatibility (without using provider configuration) added unit test.

Storage configure fix

---

packages/aws-amplify-react/__tests__/Auth/Authenticator-test.js
packages/aws-amplify-react/src/Auth/Authenticator.jsx

Enable passing through a custom container, or using an empty container in the Authenticator component.
https://github.com/aws-amplify/amplify-js/issues/2877
Enabled opt-in behaviour of using the Amplify UI `Container` component for wrapping the `Authenticator`'s children:
- If `Authenticator`'s `container === undefined`, it will default to using the AWS UI `Container` component (retains existing behaviour).
- If `Authenticator`'s `container` prop is falsey (i.e. `container === ""`), it will use an `EmptyContainer` component which wraps `Authenticator`'s components with a `React.Fragment` instead of a `div`.
- Any other custom `Container` component can be passed to `Authenticator` via the `container` prop.
_By submitting this pull request, …

aws-amplify-react: specify custom Authenticator container component

---

packages/aws-amplify-react/src/API/GraphQL/Connect.js

@alebiavati
Updated version of https://github.com/aws-amplify/amplify-js/pull/1828, as original fork was deleted
Addresses https://github.com/aws-amplify/amplify-js/issues/1771
Setting a mounted flag in componentDidMount, removing the flag in componentWillUnmount. Then checking for this flag before setting state inside the subscription.

Prevent setState warning on unmounted component

---

packages/analytics/__tests__/Analytics-unit-test.ts
packages/analytics/src/Analytics.ts

fixes #2971 
- Log debug error and reject promise if Analytics is not configured

Log error in Analytics API if not configured

---

packages/auth/src/OAuth/OAuth.ts
packages/auth/src/types/Auth.ts
packages/aws-amplify-react/__tests__/Auth/Provider/withOAuth-test.js
packages/aws-amplify-react/src/Auth/Provider/withOAuth.jsx

fix(@aws-amplify/auth): Valide OAuth state only when generated by Amlify

---

packages/aws-amplify-angular/package.json

#3075 
Moves rxjs-compat to dependencies.

fix(aws-amplify-angular): moves rxjs-compat to dependencies

---

packages/pushnotification/android/src/main/java/com/amazonaws/amplify/pushnotification/RNPushNotificationModule.java

Missing lib for https://github.com/aws-amplify/amplify-js/blob/master/packages/pushnotification/android/src/main/java/com/amazonaws/amplify/pushnotification/RNPushNotificationModule.java#L66

fix(@aws-amplify/pushnotification): import necessary lib

---

packages/aws-amplify-react/src/AmplifyI18n.js

I've added a bunch of French translation for React Auth.

feat(auth i18n french)

---

packages/xr/src/Providers/SumerianProvider.ts

This makes it easier for caching libraries like Workbox to cache requests which enable offline PWA Sumerian apps.
Using Signer.sign to sign the request and passing in the results as a header to fetchOptions.

feat(@aws-amplify/xr): Changing signing logic in SumerianProvider to use Auth Headers instead of Query Params. 

---

packages/aws-amplify-react/__tests__/Auth/SignUp-test.js
packages/aws-amplify-vue/src/components/authenticator/SignUp.vue

Related to: https://github.com/aws-amplify/docs/pull/458
Fixes: #3166 
- Use hideDefaults or hideAllDefaults to hide default SignUp fields
- hideAllDefaults is what is listed in the docs for each framework

Parody for each framework to use hideAllDefaults in SignUp

---

packages/aws-amplify-vue/package.json
packages/aws-amplify-vue/src/components/authenticator/SignUp.vue
yarn.lock

fixes: #3032
- Use lodash orderBy instead of mixin

Update vue to use lodash orderBy

---

packages/auth/src/Auth.ts

Fixes #3117
By not awaiting for the url to open when signing out, a user may not be fully signed out.
This PR waits for the signout promise to be resolved.
These two snippets illustrate the issue:
```js
// the promise resolves immediately and the url is opened 3 seconds later
await new Promise(res => {setTimeout(() => {window.open('https://aws.amazon.com/')}, 3000); res('done');});
```
```js
// the promise is resolved after the url is opened
await new Promise(res => setTimeout(() => {window.open('https://aws.amazon.com/'); res('done')}, 3000));
```

fix(@aws-amplify/auth): User may not be fully signed out

---

packages/auth/src/Auth.ts

*Issue #, if available:* 
- resolves: https://github.com/aws-amplify/amplify-js/issues/3057
In a non-browser environment, the `window` global object will likely not be available. Currently, the latest versions of `aws-amplify` throw a YellowBox warning when using authentication in React Native:
```
Possible Unhandled Promise Rejection (id: 0)
TypeError: undefined is not an object (evaluating 'window.location.href')
```
- Use the `browserOrNode` JS helper function to determine the runtime environment. Guard against the case when not running in a browser by providing a `null` value.
- My text editor caught some trailing whitespace throughout the file - I've committed these changes as well.
By submitting this pull request, I confirm that my contribution is made …

fix(@aws-amplify/auth): react-native - guard for window reference

---

packages/aws-amplify-vue/src/components/authenticator/SignUp.vue

Cognito does not accept empty attribute values so corresponding attributes cannot be submitted to avoid any error from returned API.
This pull request is fixes #3174.
In Vue <amplify-sign-up> component, we now check that attributes are non-empty prior to submitting them.
No change on the validator has been made so rules for checking correct formatting and required values are not affected.

fix(Vue-SignUp): check fields are non-empty prior to submitting them

---

packages/storage/__tests__/Storage-unit-test.ts
packages/storage/src/index.ts

Fixes #3207
This fixes a problem where the global Storage instance (the one
gotten from the Amplify registry) would be private by default, and adds
a test for it.

fix(@aws-amplify/storage): private by default

---

packages/core/src/constants.ts

resolves: https://github.com/aws-amplify/amplify-js/issues/3233
* Some JS interpreters don't natively support `Symbol` yet. An example is the version of JavaScriptCore that ships with React Native 0.58 on Android.
* Add a guard clause that checks for the existence of `Symbol`. If it's not available, substitute the value for a string prefixed with `@@`.
* I used the same pattern used in https://github.com/aws-amplify/amplify-js/pull/2992.

fix(@aws-amplify/core): guard for Symbol reference

---

packages/aws-amplify-react/src/Auth/SignIn.jsx

#3211 
Made sure to call `preventDefault` in the `signIn` method, only if an `event` is present

make sure to call `preventDefault` only if `event` is defined

---

packages/analytics/package.json
packages/analytics/src/Providers/AmazonPersonalizeHelper/MediaAutoTrack.ts

fixes #3477 
The issue is that when the library running in non-browser environment, the `window` object in the `node_modules/youtube-iframe/index.js` will be `undefined`.
To fix this issue, I moved the code in the index js into `MediaAutoTrack.ts` and remove `youtube-iframe` from the `package.json`. Because `MediaAutoTrack` is not exposed to public and will only be initiated in browser env, so it will be safe to run the `youtube-iframe` code there.

remove youtube-iframe and move the impl into MediaAutoTrack

---

packages/aws-amplify-react-native/src/Auth/SignUp.js

***Issue #, if available:***
Refs #3292 (fixup)
TBA
***Description of changes:***
In #3292, the default dial code used was changed to be:
https://github.com/aws-amplify/amplify-js/blob/b07ce9613d1680533c715ac13eb339e98646e3e6/packages/aws-amplify-react-native/src/Auth/SignUp.js#L241
Which is defined as:
https://github.com/aws-amplify/amplify-js/blob/b07ce9613d1680533c715ac13eb339e98646e3e6/packages/aws-amplify-react-native/src/Auth/SignUp.js#L51
`this.getDefaultDialCode` is a function, and so the default dial code will be returned by `this.getDefaultDialCode()` (and not simply `this.getDefaultDialCode`, like which is currently used).
// cc @dabit3 @gsans
---

Fix default dial code

---

packages/aws-amplify-react/src/Storage/S3Image.js

Add the level change check in update method so that the S3Image will reload when the level is changed.

fix: image will reload when level is changed

---

packages/analytics/src/index.ts

The `signIn`, `signUp` events will be sent no matter analytics module is configured or not.
Stop sending those events when analytics or auth module is not configured. This can be done by checking the flags `authConfigured` and `analyticsConfigured`

fix(@aws-amplify/analytics): do not send events when analytics modules not configured

---

packages/api/__tests__/API-test.ts
packages/api/src/RestClient.ts

Fixes #368 
- Added support for timeout in the init parameters supplied to API.[get/post/put/patch/del/head] requests
- Set default timeout to 0 in line with Axios's default timeout.
Usage example:
```
let params = {
timeout: 2500 // OPTIONAL
};
API.get('apiName, '/path', params);
```

feat (@aws-amplify/api): Added support for timeout in the init parameters supplied to API

---

.circleci/config.yml

- Use specific cypress [spec](https://docs.cypress.io/guides/guides/command-line.html#cypress-run-spec-lt-spec-gt) for specific sample app running

Use specific Cypress spec file

---

packages/analytics/__tests__/Providers/AWSPinpointProvider-unit-test.ts
packages/analytics/src/Providers/AWSPinpointProvider.ts

fix(@aws-amplify/analytics): use startsWith to filter the updateEndpoint error message

---

packages/aws-amplify-angular/src/components/authenticator/sign-in-component/sign-in.component.core.ts
packages/aws-amplify-react/src/Auth/AuthPiece.jsx

#3654 
Prevents authStateChange from firing twice.  It does this be removing the setAuthState call from the signIn component, which isn't needed because of the decorateSignIn decorator.  Also fixes checks on URLSearchParams in react.

fixes #3654 and bug in react url search params check

---

packages/core/src/Credentials.ts

fix(@aws-amplify/core): Await for cache.setItem when setting federatedInfo

---

packages/core/src/ClientDevice/browser.ts

Fixes #3192 
Move the Trident|Edge check above the Chrome one

fix(@aws-amplify/core): Edge browser misidentified as Chrome

---

lgtm.yml

Introduce LGTM config file to optimize extraction times. The vanilla setup for LGTM.com analyzes the folder 'docs' which includes the files located in docs/api, where there is ~177KB of minified JS in each html file. If we can avoid this folder during extraction, then there is a huge speedup in analysis time. It does not appear like the code in this folder is of interest for scanning.
[ci skip]
Internal email communications with Michael.
Exclude /docs folder from extraction by LGTM using LGTM.yml config file. For further documentation on yml file configuration for LGTM, please see here: https://help.semmle.com/lgtm-enterprise/user/help/lgtm.yml-configuration-file.html
By submitting this pull request, I confirm that my contribution is made …

LGTM configuration file

---

packages/aws-amplify-react/src/Auth/ForgotPassword.jsx

The Inputs in the ForgotPassword doesn't have input label!
The other component has Input labels, Adding it here also to make it consistent with other places.

Add input labels

---

packages/auth/src/Auth.ts

https://github.com/aws-amplify/amplify-js/issues/3983
Return empty `Promise.reject()` to prevent error from showing up in the console

Prevent console error when using guest creds with Storage

---

packages/analytics/__tests__/Providers/AWSPinpointProvider-unit-test.ts
packages/analytics/__tests__/trackers/SessionTracker-test.ts
packages/analytics/package.json
packages/analytics/src/Providers/AWSPinpointProvider.ts
packages/analytics/src/setupTests.ts
packages/analytics/src/trackers/SessionTracker.ts
packages/analytics/tsconfig.json
packages/aws-amplify-react/__tests__/Auth/__snapshots__/ForgotPassword-test.js.snap
packages/core/package.json
packages/core/src/Signer.ts

utilize `navigator.sendBeacon()` to reliably send _session.stop events on `beforunload`
closes issues #3786 and #3042

fix: Pinpoint analytics stopSession event

---

package.json

This is a workaround for the following issue when using lerna with the `--canary` option:
https://github.com/lerna/lerna/issues/2060

fix: lerna linking for unstable and beta

---

.prettierignore

Mostly opening this to test the changes Sam made to codecov but this can get merged afterward (since currently, Prettier tries to format those those files in subdirs and it shouldn't)

fix: update .prettierignore ignore files in subdirs

---

packages/xr/src/Providers/SumerianProvider.ts

* `Signer.sign` is an async function now, use `await` in the SumerianProvider.

chore: Use await for async function Signer.sign in SumerianProvider

---

packages/interactions/__tests__/Interactions-unit-test.ts
packages/interactions/package.json
packages/interactions/src/Providers/AWSLexProvider.ts

Related to #3365
This PR upgrades the aws-sdk v2 clients used in the Interactions category to aws-sdk V3 client. This helps achieve modularization at the AWS clients level in Interactions.
[Delivers #168789986]

[Delivers #168789986] Migrate Interactions category to use aws-sdk v3 clients

---

packages/api/__tests__/API-test.ts
packages/api/src/API.ts

`x-amz-user-agent` header was not set for AppSync calls
Adding `x-amz-user-agent` header

Adding x-amz-user-agent for AppSync calls

---

packages/auth/src/Auth.ts

#4001 
Removes call to `currentAuthenticatedUser` in `federatedSignIn` function, and instead checks local storage directly in order to avoid logging of error from `currentAuthenticatedUser`.

fix(#4001)

---

packages/auth/src/Auth.ts

fixes: #4175
Reverting back custom messages before refactor is in place

Reverting custom message for InvalidParameterException on signUp

---

packages/aws-amplify-react/src/Auth/AuthPiece.tsx
packages/aws-amplify-react/src/Auth/AuthStateWrapper.tsx
packages/aws-amplify-react/src/Auth/Authenticator.tsx
packages/aws-amplify-react/src/Auth/ConfirmSignIn.tsx
packages/aws-amplify-react/src/Auth/FederatedSignIn.tsx
packages/aws-amplify-react/src/Auth/ForgotPassword.tsx
packages/aws-amplify-react/src/Auth/Greetings.tsx
packages/aws-amplify-react/src/Auth/Loading.tsx
packages/aws-amplify-react/src/Auth/Provider/index.tsx
packages/aws-amplify-react/src/Auth/Provider/withAmazon.tsx
packages/aws-amplify-react/src/Auth/Provider/withAuth0.tsx
packages/aws-amplify-react/src/Auth/Provider/withFacebook.tsx
packages/aws-amplify-react/src/Auth/Provider/withGoogle.tsx
packages/aws-amplify-react/src/Auth/Provider/withOAuth.tsx
packages/aws-amplify-react/src/Auth/RequireNewPassword.tsx
packages/aws-amplify-react/src/Auth/SignUp.tsx
packages/aws-amplify-react/src/Auth/index.tsx

_Issue #, if available:_ #4226 
_Description of changes:_ In Auth category of aws-amplify-react package
* Remove ts-ignores
* Add typings to AuthPiece and components
* Cleanup imports
* Remove unused variables

fixes #4226 Remove ts-ignore and add typings to AuthPiece components

---

packages/predictions/package.json

_Issue #, if available:_ NA
_Description of changes:_ We are using few aws-sdk packages that are part of their V3 release. Since V3 is not in GA yet and aws-sdk team is expecting changes in their packages, locking the package versions of such packages so we don't break by their new changes inadvertently.

fix: Use exact version of the @aws-sdk V3 packages

---

packages/analytics/package.json
packages/api/package.json
packages/auth/package.json
packages/aws-amplify/package.json
packages/interactions/package.json
packages/predictions/package.json
packages/pubsub/package.json
packages/storage/package.json
packages/xr/package.json

_Issue #, if available:_#4259 
fixes #4261 
React native has issues with the ES modules where we are using wildcard imports from aws-sdk instead of using the default import (which is a class and has constructors we use). 

fixes #4259 revert back to use commonJs modules for react native

---

.github/ISSUE_TEMPLATE/bug_report.md

Projects like [styled-components](https://github.com/styled-components/styled-components/issues/new) leverage [envinfo](https://github.com/tabrindle/envinfo) to simplify getting environment/dependency data for reproducing bugs.
Ideally, I would like to see this handled via `amplify --info` or part of `amplify status`, similar to [`npx create-react-app --info`](https://github.com/facebook/create-react-app/blob/master/packages/create-react-app/createReactApp.js#L157-L174), which allows for greater control for us & a simpler command for users:
<details>
<summary><code>npx create-react-app --info</code></summary>
```
Environment Info:
System:
OS: macOS 10.14.6
CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
Binaries:
Node: 12.12.0 - /usr/local/bin/node
Yarn: 1.19.1 - /usr/local/bin/yarn …
```

chore: use npxinfo to simplify bug reports

---

packages/aws-amplify-vue/src/components/authenticator/PhoneField.vue
packages/aws-amplify-vue/src/components/authenticator/UsernameField.vue

Addresses issue #3598 
On Android-Web, `v-model` is not updated with keyboards using IME, unless a space is typed as described in https://github.com/vuejs/vue/issues/8231 and https://github.com/vuejs/vue/issues/8723
Which leads to `this.signInUsername` to stay empty in `components/authenticator/SignIn.vue` 
Adding `v-on:input` as suggested by https://github.com/vuejs/vue/issues/8231#issuecomment-416585972 fixes the issue for Android-Web without any impact on Desktop.
Tested on Chrome-Android and Chrome Desktop.

[Fix] Handle form input on Android-Web

---

packages/auth/src/Auth.ts

reject if NotAuthorizedException was thrown caused by session revoking by another SSO app.
#3594 
Add NotAuthorizedException catcher caused by SSO logout.

fix(@aws-amplify/auth): NotAuthorizedException

---

packages/analytics/src/Providers/AWSPinpointProvider.ts

fixes #4305 check type of `navigator` to be `undefined` instead of only checking the value `undefined` since the variable `navigator` is not in scope.
_Issue #, if available:_ #4305

 fixes #4305 check type of navigator to be undefined

---

packages/cache/package.json
packages/core/package.json

_Issue #, if available:_ #4309
_Description of changes:_add react native overrides for cache and core package as index.js now points to a bundle in dist folder and not to modules.

fixes #4309 add react native overrides for cache and core package

---

packages/storage/__tests__/Providers/AWSS3Provider-unit-test.ts
packages/storage/package.json
packages/storage/src/providers/AWSS3Provider.ts

_Issue #, if available:_ https://github.com/aws-amplify/amplify-js/issues/3365
_Description of changes:_ This PR upgrades the S3 client from aws sdk V2 to V3 client to achieve modularization at the AWS clients level.
[Delivers #168673124]

[Delivers #168673124] Migrate S3 client to aws sdk V3

---

package.json
packages/api/package.json
packages/api/src/API.ts
packages/core/package.json

N/A
Upgrade to prettier 1.19.0 so we can start using TypeScript 3.7 features without prettier complaining.
Tested with a small usage of `??` and verifying that the pre-commit hook handled it fine

chore:Prettier 1.19.0

---

packages/analytics/package.json
packages/api/package.json
packages/auth/package.json
packages/aws-amplify-angular/package.json
packages/aws-amplify-react-native/package.json
packages/aws-amplify-react/package.json
packages/aws-amplify-vue/package.json
packages/aws-amplify/package.json
packages/cache/package.json
packages/core/package.json
packages/interactions/package.json
packages/predictions/package.json
packages/pubsub/package.json
packages/pushnotification/package.json
packages/storage/package.json
packages/xr/package.json

Moving packages to 2.0.0 as follows:
- @aws-amplify/analytics@2.0.0
- @aws-amplify/api@2.0.0
- @aws-amplify/auth@2.0.0
- aws-amplify-angular@4.0.0
- aws-amplify-react-native@3.0.0
- aws-amplify-react@3.0.0
- aws-amplify-vue@1.0.0
- aws-amplify@2.0.0
- @aws-amplify/cache@2.0.0
- @aws-amplify/core@2.0.0
- @aws-amplify/interactions@2.0.0
- @aws-amplify/predictions@2.0.0
- @aws-amplify/pubsub@2.0.0
- @aws-amplify/pushnotification@2.0.0
- @aws-amplify/storage@2.0.0
- @aws-amplify/xr@1.0.0

chore: (aws-amplify@2.0.0) Moving AWS Amplify JS to 2.0.0

---

.circleci/config.yml
packages/analytics/webpack.config.js

After adding a module to Analytics, the Angular Auth integ test is failing due to a linking issue with the analytics package (related to adding a new exported module, AWSKinesisFirehoseProvider)
See: https://circleci.com/gh/aws-amplify/amplify-js/9432
Manually linking @aws-amplify/analytics should allow this test to run successfully. A better long-term solution will need to be implemented to prevent this from happening with future module additions.
Also: adding aws-sdk/clients/firehose to `externals` in the webpack config to exclude it from the output bundle.

Fix angular integration test

---

package.json
packages/api/src/API.ts

Fixes: https://github.com/aws-amplify/amplify-js/issues/4389
TypeScript 3.7 introduced a feature change to declaration files which broke support with Angular versions supported by AmplifyJS. 
Downgrading the version to `~3.6.4` thereby floating the patch version but pinning the major and minor version to 3.6.
Reverting change to `packages/api/src/API.ts` that utilized nullish coalescing operator `??`

fix: Downgrade TS to ~3.6

---

packages/pushnotification/package.json
packages/pushnotification/src/PushNotification.ts
packages/pushnotification/tsconfig.json

_Issue #:_
#3995
#4089
Adding support for push notifications in iOS for React Native 0.60+
Tested these changes on an iPhone running iOS 12.x and a React Native 0.61.x app. Was able to receive push notifications through a pinpoint campaign and log the notification data in the onNotification handler.

Adding support for push notifications in iOS for React Native 0.60+

---

packages/aws-amplify-vue/package.json

Pinning version of vue-test-utils version to beta.29 in order to resolve unit test failure. New vue-test-utils [version](https://www.npmjs.com/package/@vue/test-utils) was released four days ago.

chore: (aws-amplify-vue) Pin vue test utils version

---

packages/amplify-ui-components/src/common/constants.ts
packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx

- Check user before Authenticator loads to determine if they are signed in or not

chore(@aws-amplify/ui-components): Check for user before authenticator loads

---

packages/analytics/__tests__/Providers/AWSPinpointProvider-unit-test.ts
packages/analytics/src/Providers/AWSPinpointProvider.ts

_Issue #, if available:_ #4485
@mariotsi discovered in #4485:
> From our remote logs we saw errors coming from this line `TypeError: Cannot read property 'startsWith' of undefined`. We are unable to check more deeply what was the response because we do not not log payloads. I'm making this change in order to make the code more failsafe
This PR fixes a unit test that was incorrectly asserting that a rejection happened, _not what got rejected_, and adds a test case for the behavior @mariotsi is seeing.
The primary difference between aa8e3de and this PR is that `message` is cast as a `String` to defensively catch `undefined`, `null`, booleans, numbers, or any other valid, non-String JSON responses.  It also avoids defaulting `message` to `"", so that the original value of `undefined` is …

Handle Pinpoint error without "message"

---

packages/auth/src/Auth.ts

Amplify oAuth knows if there’s a customeOAuth state parameter only if theres a ‘-‘ in the URL, but what if my state parameter itself contains a ‘-‘?
For instance:
My:custome:state-this-information-is-lost
This causes the “customeOAuthState’ to publish everything up to the first ‘-‘, so in this example it would give:
My:custome:state
In this PR, we're updating the parsing to include everything after the first '-', including dashes themselves.

Fix customState parsing to include all text past the first hyphen

---

packages/api/package.json
packages/pubsub/package.json

_Issue #, if available:_ #4342
Moves `@types/zen-observable` to `devDependencies` and updates to `^0.8.0`.
This is a regression of #3529 when #4007 was merged.

Fix #4342: move @types/zen-observable to devDependencies

---

.github/labeler.yml
.github/workflows/label.yml

From https://github.com/actions/labeler, this GitHub action automates away manual label (e.g. <kbd>Analytics</kbd>, <kbd>Auth</kbd>, <kbd>API</kbd>, etc.) attribution for PRs to help streamline on-call duties and issue organization.
---

Auto-label PRs based on files changed

---

packages/auth/package.json
packages/core/package.json

_Issue #, if available:_ #4506
`core` uses `zen-observable`:
https://github.com/aws-amplify/amplify-js/blob/8d2ba6e85031a7880d2b573e1f68108d22a7de54/packages/core/src/Util/Reachability.ts#L1
But it isn't declared as a dependency:
https://github.com/aws-amplify/amplify-js/blob/8d2ba6e85031a7880d2b573e1f68108d22a7de54/packages/core/package.json#L39-L46
Users who had multiple packages installed (such as API/PubSub) would get this as a  transitive dependency, which hid the error.
See this demo repo: https://github.com/ericclemmons/amplify-js-issues-4506

fix(@aws-amplify/core): add zen-observable dependency

---

packages/amplify-ui-components/src/common/types/auth-types.ts
packages/amplify-ui-components/src/components.d.ts
packages/amplify-ui-components/src/components/amplify-auth0-button/__snapshots__/amplify-auth0-button.spec.tsx.snap
packages/amplify-ui-components/src/components/amplify-auth0-button/amplify-auth0-button.spec.tsx
packages/amplify-ui-components/src/components/amplify-auth0-button/amplify-auth0-button.stories.tsx
packages/amplify-ui-components/src/components/amplify-auth0-button/amplify-auth0-button.tsx
packages/amplify-ui-components/src/components/amplify-auth0-button/readme.md
packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.stories.tsx
packages/amplify-ui-components/src/components/amplify-federated-buttons/amplify-federated-buttons.tsx
packages/amplify-ui-components/src/components/amplify-sign-in/amplify-sign-in.stories.tsx

[Delivers #169928296]
A placeholder was implemented in #4249, but wasn't functional.  This PR adds that functionality:
> ![auth0](https://user-images.githubusercontent.com/15182/70668939-d7530300-1c29-11ea-95a2-8ad143c6e196.gif)
(View commits for overview)
1. Followed instructions at:
> https://aws-amplify.github.io/docs/js/authentication#federated-with-auth0
and
> https://auth0.com/docs/integrations/integrating-auth0-amazon-cognito-mobile-apps
1. Setup Identity Provider + Identity Pool to match existing `aws-exports.js` file
1. Updated `amplify-examples/authenticator-example.tsx` to look like:
```diff
diff --git a/packages/amplify-ui-components/src/components/amplify-examples/authenticator-example.tsx b/packages/amplify-ui-components/src/components/amplify-examples/authenticator-example.t …
```

feat(@aws-amplify/ui-components): amplify-auth0-button

---

packages/aws-amplify/src/index.ts

`AmazonAIPredictionsProvider` is unused in `packages/aws-amplify/src/index.ts`. It is likely to have been meant to be exported.

fix(aws-amplify): delete unused AmazonAIPredictionsProvider import

---

packages/amplify-ui-components/src/components/amplify-icon/amplify-icon.spec.ts
packages/amplify-ui-components/src/components/amplify-icon/amplify-icon.stories.tsx

- Left the `snapshotOverrideTestIcon` if you want to take the time to fix the [shared nodes problem](https://stenciljs.com/docs/templating-jsx#avoid-shared-jsx-nodes) and add it into the inner `describe()` block
- Another Storybook playground to show that the shared nodes thing isn't an issue in the real world

Added icon unit tests and additional storybook

---

packages/pushnotification/package.json

pinning latest known working version - 1.0.3 to resolve the build error

fix(dependencies): pin version for push-notification-ios

---

packages/aws-amplify-angular/src/assets/countries.ts
packages/aws-amplify-vue/src/assets/countries.js

https://github.com/aws-amplify/amplify-js/issues/4693
Corrected phone country code for Czech Republic to `+420`

fix: correct Czech Republic phone country code

---

packages/auth/src/OAuth/OAuth.ts

_Issue #, if available: Potentially fixes #4375, but should provide further visibility into further errors._
**tldr;** If a duplicate or invalid `?code=...` is in the URL, Cognito returns an error that is caught, logged but not thrown. `undefined` is returned, causing run-time errors when trying to destructuring `accessToken` from it.
> https://github.com/aws-amplify/amplify-js/issues/4375#issuecomment-569963165
This fix was recommended here: https://github.com/aws-amplify/amplify-js/issues/4375#issuecomment-570270373
We could potentially unwrap the entire `try/catch` block, but doing so would make it more difficult to catch any other run-time errors within this code (that's primarily happy-path).
---
By submitting this pull request, I confirm that my contribution is made under the terms …

Throw an error to prevent returning undefined as auth response

---

packages/amplify-ui-angular/package.json

Troubleshooting issues with `@aws-amplify/ui-angular` and found this dependency should've been in `devDependencies`.
Related to https://github.com/aws-amplify/amplify-js-samples-staging/pull/42
---

Move tslib to devDependencies

---

packages/amplify-ui-components/package.json

When consuming `@aws-amplify/ui-react`, `@aws-amplify/ui-components/loader` cannot be resolved because it's not included in the package:
See: https://unpkg.com/browse/@aws-amplify/ui-components@0.1.1-ui-preview.3/
> <img width="1025" alt="Screen Shot 2020-01-16 at 10 25 54 AM" src="https://user-images.githubusercontent.com/15182/72551999-d75aaa00-384a-11ea-8752-e7e4ac7c22fa.png">
This adds it for publishing so this resolves correctly.
Related to https://github.com/aws-amplify/amplify-js-samples-staging/pull/42.
---

Include @aws-amplify/ui-components/loader in package

---

packages/aws-amplify/webpack.config.js

_Issue #, if available:_ #4666
_Description of changes:_ fixes: #4666 Remove externals from amplify's root webpack build

fixes: #4666 Remove externals from amplify's root webpack build

---

.github/stale.yml

As part of OE, we need to adjust the current label `to-be-triaged` to `to-be-reproduced`. This is the first Pull Request of two to add the new label and the second PR will be to remove `to-be-triaged`

chore:(stale bot updates) Add label for to-be-reproduced

---

packages/amplify-ui/src/SelectInput.css

_Issue #, if available:_ Fixes #3944
Before, the caret encroaches upon the country code:
> <img width="572" alt="Screen Shot 2020-01-22 at 12 57 50 PM" src="https://user-images.githubusercontent.com/15182/72934187-09bb4a00-3d18-11ea-9825-873f5f7767a0.png">
With this change (thanks to @gsans), it can breath:
> ![72844426-57b94a80-3c51-11ea-8ef1-57e87194e933](https://user-images.githubusercontent.com/15182/72844426-57b94a80-3c51-11ea-8ef1-57e87194e933.png)
See #3944 for more research.
---

fix(@aws-amplify/ui): Add padding to caret for SignUp component

---

package.json
packages/api-graphql/src/GraphQLAPI.ts
yarn.lock

https://github.com/aws-amplify/amplify-js-samples-staging/pull/42#issuecomment-579427196 was blocked by TypeScript issues.
Investigation found that `^3.5.3` matches `3.7`, which is what has been installed for this branch for sometime.
This is effectively cherry-picking Ivan's 6597db2b0704d7aff5b612557536142b82e1731 that hasn't made it in since 788d7df7b2f1a3c02a6e6909e934de5fdc0b5954.
> https://github.com/aws-amplify/amplify-js/commits/ui-components/master/package.json
---

fix(@ui-components/master): force TypeScript@~3.6.4

---

packages/aws-amplify-angular/package.json
packages/aws-amplify-react-native/package.json
packages/aws-amplify-react/package.json

Also fix peer dependencies for `aws-amplify-react-native` and `aws-amplify-angular`.
Matched packages used in `aws-amplify-react` to peerDependencies in order to more precisely express dependencies.
Also, looks like some peer dependencies were not updated when migrating versions to 2.x.

fix(aws-amplify-react): Fix peer dependencies

---

packages/core/__tests__/JS-node-runtime-test.ts
packages/core/src/JS.ts

This fix reverts our environment checks to a previous version that worked fine, but failed under certain curcustances now fixed (see #4678)
The solution using `new Function('return this')()` caused problems when using CSP
Fixes: #4723 

fix(@aws-amplify/core): Revert environment checks

---

packages/auth/src/Auth.ts

#4388
Added a solution provided by @mithunkalan that prevents the auth flow from being executed twice by the same url. This was an issue impacting both react-native and react-native with expo that caused an "invalid_grant" error.

fix(auth) - prevent urlListener from firing auth flow twice with the same URL 

---

packages/amazon-cognito-identity-js/package.json
packages/auth/package.json
packages/core/package.json
packages/core/src/Util/Reachability.native.ts
packages/datastore/src/storage/adapter/AsyncStorageDatabase.ts
packages/datastore/src/storage/adapter/asyncstorage.ts
packages/datastore/src/storage/adapter/getDefaultAdapter/index.native.ts
packages/datastore/src/storage/adapter/getDefaultAdapter/index.ts
packages/datastore/src/storage/storage.ts
packages/datastore/src/sync/index.ts

Addresses feature request #4527  
- Wrote a React Native specific storage adapter that uses AsyncStorage under the hood
- Created a database-like abstraction for AsyncStorage to make it easier to plug into the adapter
- To implement the notion of separate stores in AsyncStorage, we keep track of a collection of keys prefixed by storeName
- Logic to get default adapter now lives in platform specific files
- Wrote a React Native specific implementation for Reachability using @react-native-community/netinfo 

React native datastore feature

---

packages/aws-amplify-vue/src/plugins/AmplifyPlugin.js

When troubleshooting why `aws-amplify-vue@unstable` works but `aws-amplify-vue@preview` **does not**, I discovered that `AuthClass` is not exported available as `AmplifyModules`.
`AuthClass` is currently required for the plugin to work, despite not having any explicit dependencies on it:
https://github.com/aws-amplify/amplify-js/blob/0c336ef5895401be365b2b22db4aecdbf7f81b8a/packages/aws-amplify-vue/src/plugins/AmplifyPlugin.js#L18-L33
Vue captures the underlying `AmplifyPlugin installation method...` error and only outputs the following error:
```console
* [Vue warn]: Error in mounted hook (Promise/async): "TypeError: this.$Amplify is undefined"
found in
---> <Authenticator>
<App> at src/App.vue
<Root>
```
---
By submitting this pull request, I confirm that my contribution is made under …

Remove AuthClass from requiredModules

---

packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts

Fixes: #4910 
Adding Buffer import to fix issue with React-Native
Tested on a react-native App using react-native cli and a regular web App

Fix issue for AppSyncRealTimeProvider with Buffer on react-native

---

packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts

Fixes #4852
Fix race condition during unsubscribe and subscribe

Fix for unsubscription new subscription race condition

---

packages/amplify-ui-components/src/components/amplify-sign-in-button/amplify-sign-in-button.tsx
packages/amplify-ui-components/src/components/amplify-strike/__snapshots__/amplify-strike.spec.ts.snap
packages/amplify-ui-components/src/components/amplify-strike/amplify-strike.tsx

When testing #4944, I noticed that the federated styles were likely broken by #4872:
> ![Screen Shot 2020-02-18 at 14 26 37](https://user-images.githubusercontent.com/15182/74786298-33a55500-5261-11ea-98a8-10eb3e8b4309.png)
Switching to `scoped: true` fixes it:
> ![Screen Shot 2020-02-18 at 14 19 34](https://user-images.githubusercontent.com/15182/74786320-40c24400-5261-11ea-8b2d-acb33035d9c9.png)
---

fix(@aws-amplify/ui-components): federated button styling

---

packages/core/src/Util/Reachability.native.ts
packages/datastore/__tests__/DataStore.ts
packages/datastore/src/datastore/datastore.ts
packages/datastore/src/sync/index.ts
packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts

N/A
Make sure initialization happens only once

initialize only once

---

packages/amplify-ui-components/src/components/amplify-country-dial-code/amplify-country-dial-code.stories.tsx
packages/amplify-ui-components/src/components/amplify-label/amplify-label.spec.ts
packages/amplify-ui-components/src/components/amplify-link/amplify-link.spec.ts
packages/amplify-ui-components/src/components/amplify-verify-contact/amplify-verify-contact.stories.tsx

When running Storybook (#4973), there were unused variables.
This PR removes them.
---

chore(@aws-amplify/ui-components): Remove unused variables

---

packages/core/package.json

@react-native-community/netinfo is required to build core. Needs to be in main dependencies, not dev.

fix(core): move react-native dependency from dev

---

.circleci/config.yml

Here's what it looks like when it's running: https://app.circleci.com/jobs/github/aws-amplify/amplify-js/11280
If someone wants to take it for a spin, lmk and we can copy this branch and then temporarily disable the other jobs in the pipeline to have it it only run the detox tests

ci: Add React Native integration testing with Detox

---

packages/api/__tests__/API-test.ts
packages/api/src/API.ts

Additional headers are merged **after** merging in headers set at config time.
Additional headers will overwrite any existing values and merge the rest.
_Issue #, if available:_ https://github.com/aws-amplify/amplify-js/issues/4981
_Description of changes:_ Existing private `_graphql` function allowed passing a param called `additionalHeaders` but was never used. The public `graphql` function now accepts an optional `additionalHeaders` param and is passed to private `_graphql` method. `_graphql` method was modified to merge in `additionalHeaders` **after** merging in previously set headers. This is how I would expect the parameter to function.

feat(@aws-amplify/api): pass additionalHeaders to graphql function

---

packages/datastore/src/datastore/datastore.ts
packages/datastore/src/predicates/index.ts

Fixes #4827
This change is a backwards compatible way to keep using `Predicates.ALL` without changing the behavior at all, only the types of the public API
- Introduce a new symbol (not exported from entry-point)
- Changed `query` and `delete` signatures to accept the symbol
- Change `Predicates.ALL` return type to the symbol
Tested with
```typescript
console.log('No criteria', await DataStore.query(Note));
console.log('Predicates.ALL', await DataStore.query(Note, Predicates.ALL));
console.log('c => c', await DataStore.query(Note, c => c));
console.log(`c => c.content('beginsWith', 'XXX')`, await DataStore.query(Note, c => c.content('beginsWith', 'XXX')));
```
By submitting this pull request, I confirm that my contribution is made under …

fix(@aws-amplify/datastore): Fix query and delete types

---

packages/amplify-ui-vue/package.json

`vue build` was ignoring `import "@aws-amplify/ui-vue"` from production due to `sideEffects: false`.
**Note that removing this line entirely has the same result as `sideEffects: true`, but explicitness is beneficial when things are "magical" like tree-shaking**.
~~**tldr; Drop `@aws-amplify/ui-vue` in favor of manual setup from https://stenciljs.com/docs/vue.**~~
~~`@aws-amplify/ui-vue` was largely a wrapper around https://stenciljs.com/docs/vue, but it turns out that Vue's `build` command **marks the package for dead code removal**.~~
~~Instead, I've updated the README to match.  This mean the `ui-vue` package has been removed.~~
~~_I'm currently looking into adding `sideEffects: true`..._~~
---
By submitting this pull request, I confirm that my contribution is made under the terms of …

fix(@aws-amplify/ui-components): Fix Vue production

---

packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts

Allow in PubSub the same capabilities as API for custom headers:
* Async header
* Override headers (Authorization)
Check issue #4928 for explanations.
_Issue #4928:_

Allow in PubSub to add async custom headers

---

packages/predictions/src/index.ts
packages/pubsub/src/index.ts

Export necessary providers and types from the package root to avoid importing from generated paths

Export necessary providers and types from the package root

---

packages/amplify-ui/src/Button.css

_Issue #, if available:_ #5064
**Demo**: https://codesandbox.io/s/amplify-jsissues5064-zj1z1
@michaelcuneo discovered that, when using React Bootstrap, federated buttons looked like this:
> ![with-bootstrap](https://user-images.githubusercontent.com/15182/76378808-a8712980-630b-11ea-8527-c327c7218c80.png)
This is due to CSS resets present when including:
```js
import 'bootstrap/dist/css/bootstrap.min.css';
```
Without `bootstrap`, styles appear correctly:
> <img width="488" alt="without-bootstrap" src="https://user-images.githubusercontent.com/15182/76378864-d0f92380-630b-11ea-82e3-1ff3956bb58e.png">
This bug required addressing 2 things:
> <img width="333" alt="Screen Shot 2020-03-10 at 7 55 21 PM" src="https://user-images.githubusercontent.com/15182/76378960-0dc51a80-630c-11ea-95d7-b8803 …

fix(aws-amplify-react): Fix Federated icons when using React Bootstrap

---

packages/aws-amplify-react/src/Amplify-UI/Amplify-UI-Components-React.tsx

**This will require a MAJOR version bump, ideally with `modularization`**.
_Issue #, if available:_ Fixes #3348, fixes #3854, fixes #2230, fixes #3053. Related to #1613, but there's more work to be done to support categories in Next.js.
Importing non-JS files is invalid JavaScript, as it relies on a bundler (e.g. webpack) & breaks SSR for Next.js.
It works with CRA because CRA *builds all dependencies*, just-in-case.
Docs PR: https://github.com/aws-amplify/docs/pull/1258
---

fix(aws-amplify-react): BREAKING - Remove "import '@aws-amplify/ui/dist/style.css'"

---

.circleci/config.yml
packages/datastore/__tests__/DataStore.ts
packages/datastore/__tests__/graphql.ts
packages/datastore/__tests__/indexeddb.test.ts
packages/datastore/__tests__/model.ts
packages/datastore/__tests__/schema.ts
packages/datastore/package.json
packages/datastore/src/datastore/datastore.ts
packages/datastore/src/storage/adapter/indexeddb.ts
packages/datastore/src/storage/storage.ts
packages/datastore/src/sync/index.ts
packages/datastore/src/sync/processors/mutation.ts
packages/datastore/src/sync/processors/subscription.ts
packages/datastore/src/sync/processors/sync.ts
packages/datastore/src/sync/utils.ts
packages/datastore/src/types.ts
packages/datastore/src/util.ts

See aws-amplify/amplify-cli#2988
This change allows the usage of types with no `@model` directive.
Field values of a non-\@model type will be stored alongside the @model instance
e.g. with the following schema, the JSON shown is stored
```graphql
type Note @model {
id: ID!
content: String!
metadata: Metadata
}
type Metadata {
author: String!
tags: [String]
nested: Nested
}
type Nested {
x: Int
}
```
```json
{
"__typename": "Note",
"_lastChangedAt": 1584144474971,
"_version": 1,
"content": "Content 1584144474557",
"createdAt": "2020-03-14T00:07:54.911Z",
"id": "b41f57cc-4375-4bc5-83e2-1da694381f7f",
"metadata": {
"author": "Manolo",
"tags": [
"amazon",
"aws",
"mobile"
],
"nested": {
"x": 12345
}
},
"updatedAt": "2020-03-14T00:07:54.911Z"
} …
```

feat(@aws-amplify/datastore): Support non-@model types in DataStore

---

packages/api-graphql/package.json
packages/api-graphql/src/GraphQLAPI.ts
packages/api/src/API.ts
packages/core/package.json
packages/core/src/Util/Reachability.native.ts
packages/core/src/Util/Reachability.ts
packages/datastore/__tests__/DataStore.ts
packages/datastore/package.json
packages/datastore/src/datastore/datastore.ts
packages/datastore/src/storage/storage.ts
packages/datastore/src/sync/datastoreConnectivity.ts
packages/datastore/src/sync/index.ts
packages/datastore/src/sync/processors/mutation.ts
packages/datastore/src/sync/processors/subscription.ts
packages/pubsub/package.json
packages/pubsub/src/Providers/AWSAppSyncProvider.ts
packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts
packages/pubsub/src/Providers/MqttOverWSProvider.ts
packages/pubsub/src/Providers/PubSubProvider.ts
packages/pubsub/src/PubSub.ts
packages/pubsub/src/types/Provider.ts

* Migrate zen-observable to zen-observable-ts. zen-observable was causing issues with RN and ES modules. zen-observable-ts seems better suited for this. It was already used in Datastore package, this change makes it consistent everywhere else.
* zen-push was being imported as wild card which is not compatible with RN and ES modules
* Force ES modules to be used in datastore category for RN
Tested Datastore subscriptions in Web and react native.

[RN] Migrate zen-observable to zen-observable-ts and fix zen-push import

---

packages/amplify-ui-storybook/package.json

- Cleanups `testing-library` dependency. It was an unnecessary dependency carried around from CRA. This PR removes it.
**Major learning / Reasons tests were failing:** was because the external dependency has all updated their packages with the new typescript features and which is causing the failure. Upgrading to newest version solves. 

[UI Components] Build issue fix

---

.circleci/config.yml
packages/datastore/src/datastore/datastore.ts
packages/datastore/src/sync/index.ts
packages/datastore/src/sync/processors/sync.ts
packages/datastore/src/types.ts

Allow user to configure sync pagination limit due to limit reach of 1MB if dynamodb documents are bigger. By reducing pagination limit it's possible to overcome following issue:
```
{
"data": {
"syncDocuments": null
},
"errors": [
{
"path": [
"syncDocuments"
],
"data": null,
"errorType": "MappingTemplate",
"errorInfo": null,
"locations": [
{
"line": 2,
"column": 5,
"sourceName": null
}
],
"message": "Transformation too large"
}
]
}
```
This pull request allow users to add such configuration as following: 
```
DataStore.configure({
syncPageSize: number
})
```

feat(@aws-amplify/datastore): configurable sync pagination limit

---

packages/aws-amplify-react/src/Auth/index.tsx

This change makes it possible to specify the usernameAttribute prop in TypeScript without using `any`.
Fixes #5196 
Here I've exposed the UsernameAttributes enum as a named export by exposing everything in the `common/types.ts` file.

Export UsernameAttributes enum

---

packages/amazon-cognito-identity-js/index.d.ts

_Issue #5144
_Description of changes: Added clientMetadata to sendMFACode typescript definition

Added clientMetadata to sendMFACode

---

packages/amplify-ui-angular/package.json
packages/amplify-ui-react/package.json
packages/amplify-ui-vue/package.json

chore(@aws-amplify/ui-components): Pin @aws-amplify/ui-components to ^0.1.0

---

packages/amplify-ui-components/src/components/amplify-federated-buttons/amplify-federated-buttons.tsx

`federated` gets merged with `oauth`, but when `undefined` it throws run-time errors unless a user manually adds `<amplify-authenticator federated={...} />`.
https://github.com/aws-amplify/amplify-js/blob/778a39a11b623ed28585fb222b618ec0e4189f95/packages/amplify-ui-components/src/components/amplify-federated-buttons/amplify-federated-buttons.tsx#L27-L35
---

fix(@aws-amplify/ui-components): Default federated, since aws-exports#oauth gets merged with it

---

package.json

_Issue #, if available:_https://github.com/terser/terser/issues/624

fix builds that were broken by new terser 4.6.8 version

---

packages/amplify-ui-components/src/common/types/auth-types.ts
packages/amplify-ui-components/src/components/amplify-confirm-sign-up/amplify-confirm-sign-up.tsx
packages/amplify-ui-components/src/components/amplify-sign-up/amplify-sign-up.tsx

_Issue #, if available:_ Fixes #5201 
- This PR ensures the user to be `signedIn` after performing `confirmSignUp`

stay signedin after confirm signup

---

packages/amazon-cognito-identity-js/__tests__/UserAgent-test.js
packages/amazon-cognito-identity-js/src/UserAgent.js
packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx
packages/auth/src/Auth.ts

- Revert default user agent in Cognito SDK
- Change user agent in `amplify-authenticator` to be component name

(@aws-amplify/ui-components) Revert User Agent change to Cognito SDK

---

packages/amplify-ui-components/src/common/constants.ts
packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx

_Issue #, if available:_ #5232
I've been able to reproduce Ivan's hosted UI bug.  Found several ancillary issues to be resolved: https://github.com/aws-amplify/amplify-js/issues/5232#issuecomment-606345994
This PR brings over logic from `aws-amplify-react` that was missing in `amplify-authenticator`:
https://github.com/aws-amplify/amplify-js/blob/38e55b090e10b71251439344365f6aa9344d049a/packages/aws-amplify-react/src/Auth/Authenticator.tsx#L70-L79
> ![hosted-ui](https://user-images.githubusercontent.com/15182/78073372-a3752800-7355-11ea-8938-575122f9308a.gif)
It's worth noting that the `Auth` category still returns lots of errors (which isn't specific to the components, but is in `master`):
> ![Screen Shot 2020-03-31 at 1 27 18 …

fix(@aws-amplify/ui-components): Listen to auth channel for managing Hosted UI auth state

---

package.json

This is necessary so `unstable` doesn't start creating versions ahead of future releases to `latest`.
Reverts 9f2800d20b3a89a01903935fda472d2b7e84067b & 6b1ef79f0766cdc8ece49fd5bfa2485742620d78.
---

chore: publish:master does --canary release

---

packages/storage/src/providers/axios-http-handler.ts

`publish:master` was blocked by a failing integration test:
> https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/4324/workflows/69414fdd-8207-4249-a112-2c782191e1ba/jobs/12230
The regression was intermittent, but ultimately was due to iOS not getting a correct `blob` when created via `new Blob([response.data])`.
By using Axios' built-in `responseType: "blob"`, this bypasses the `Blob` bug specific to iOS, returning `null` for `result`:
> ![Screen Shot 2020-03-31 at 6 44 06 PM](https://user-images.githubusercontent.com/15182/78179317-db43a480-7415-11ea-8526-1f6e801e9ca9.png)
---

Explicitly set `responseType` to `blob` rather than using `new Blob`

---

.circleci/config.yml
package.json

Merging this will trigger a release in CircleCI which will create a new NPM tag 2.0-stable

Enable publish to npm tag stable-2.0 from branch 2.0-stable

---

packages/amplify-ui-components/src/components/amplify-button/amplify-button.tsx
packages/amplify-ui-components/src/components/amplify-input/__snapshots__/amplify-input.spec.ts.snap
packages/amplify-ui-components/src/components/amplify-input/amplify-input.scss
packages/amplify-ui-components/src/components/amplify-input/amplify-input.tsx
packages/amplify-ui-components/src/components/amplify-phone-field/amplify-phone-field.scss
packages/amplify-ui-components/src/global/theme.ts

- Check for `document` existence

Check if document is undefined before using it, Fix phone field width

---

packages/api/src/types/index.ts

_Issue #, if available:_https://github.com/aws-amplify/amplify-cli/issues/3863
_Description of changes:_Re-Export graphql types from @aws-amplify/api/types folder to maintain backwards compatibility with consumers still using @aws-amplify/api/lib/types style imports.

fix(@aws-amplify/api) Export graphql types from @aws-amplify/api/types folder as well

---

packages/amplify-ui-components/src/components/amplify-button/amplify-button.tsx

https://github.com/aws-amplify/amplify-js/issues/5325
- Revert back to simulate form submit with button
- Add browser check for server side rendering

Revert formSubmit, add isBrowser check

---

packages/amplify-ui-components/package.json

- Jest types was out of date for stencil's jest tests.. bumping version

Bump jest types version in UI components

---

packages/amplify-ui-react/package.json

`@aws-amplify/ui-react` whitelisted `files` instead of ignoring:
`aws-amplify-react` uses `.npmignore`:
---

fix(@aws-amplify/ui-react): Exclude files via .npmignore rather than files

---

packages/amplify-ui-react/jest.config.js

@jordanranz raised an issue with `yarn test` in the project root returning errors:
```console
@aws-amplify/ui-react: FAIL __tests__/withAuthenticator-test.tsx
@aws-amplify/ui-react:   ● Test suite failed to run
@aws-amplify/ui-react:     TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
@aws-amplify/ui-react:     __tests__/withAuthenticator-test.tsx:1:8 - error TS1259: Module '"/Users/jranz/amplify/amplify-js/node_modules/@types/react/index"' can only be default-imported using the 'esModuleInterop' flag
@aws-amplify/ui-react:     1 import React from 'react';
@aws-amplify/ui-react:              ~~~~~
@aws-amplify/ui-react:       ../../node_modules/@types/react/index.d.ts:63:1
@aws-amplify/ui-react:         63 export = React;
@aws-amplify/ui-react: …
```

Specific ts-jest tsconfig.json, since ts-jest defaults to <root>/tsconfig.json

---

packages/aws-amplify-react/src/AmplifyUI.tsx

_Issue_ https://github.com/aws-amplify/amplify-js/issues/5355
Add theme property on `SectionFooterContent`

SectionFooterContent should inherit theme prop

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/usage-question.md

Currently, https://github.com/aws-amplify/amplify-js/issues/new/choose looks like:
> ![Screen Shot 2020-04-10 at 11 17 53 AM](https://user-images.githubusercontent.com/15182/79013818-627fcf00-7b1e-11ea-84be-a43116498f5e.png)
With this PR, users will instead get links to https://github.com/aws-amplify/amplify-js/discussions like:
> ![Screen Shot 2020-04-10 at 11 20 28 AM](https://user-images.githubusercontent.com/15182/79013847-73304500-7b1e-11ea-829b-34100f13b5b0.png)
> – https://github.com/zeit/next.js/issues/new/choose
Already issues can be converted to Discussions:
> ![Screen Shot 2020-04-10 at 11 55 07 AM](https://user-images.githubusercontent.com/15182/79015709-31090280-7b22-11ea-95a5-b7f64969b2d0.png)
**However**, I'm interested to see how customers leverage it as they go through …

Link questions to Discussions

---

packages/aws-amplify-react-native/src/AmplifyTestIDs.js
packages/aws-amplify-react-native/src/AmplifyUI.js
packages/aws-amplify-react-native/src/Auth/AuthPiece.js
packages/aws-amplify-react-native/src/Auth/ConfirmSignIn.js
packages/aws-amplify-react-native/src/Auth/ConfirmSignUp.js
packages/aws-amplify-react-native/src/Auth/ForgotPassword.js
packages/aws-amplify-react-native/src/Auth/Greetings.js
packages/aws-amplify-react-native/src/Auth/Loading.js
packages/aws-amplify-react-native/src/Auth/RequireNewPassword.js
packages/aws-amplify-react-native/src/Auth/SignIn.js
packages/aws-amplify-react-native/src/Auth/SignUp.js
packages/aws-amplify-react-native/src/Auth/VerifyContact.js
packages/aws-amplify-react-native/src/Auth/common/default-sign-up-fields.js

There are currently no `testID` props on the components from `withAuthenticator` in React Native, which makes end-to-end testing difficult.
This adds the `testID` prop to various components in order to allow the auth workflows to be tested.
---

add React Native testIDs to auth

---

packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts

Updated the AWSAppSyncRealTime provider to connect to Amplify CLI mock websocket server when local mocking
https://github.com/aws-amplify/amplify-cli/issues/3008

feat(@aws-amplify/pubsub) add mokcing support for websocket subscription

---

packages/amplify-ui-angular/package.json

Builds are failing because the latest major version (13.13.0) of `@types/node` released earlier today is being added.
(See error message below)
Even though we are including `"@types/node": "^12.6.3"` in `amplify-ui-components`, it looks like our dependency of `rollup` in `amplify-ui-angular` has a [dependency](https://github.com/rollup/rollup/blob/v1.32.1/package.json#L68) of `"@types/node": "*"`, so the latest version is being used.
It seems that we would want to lock the major version at 12, so this PR is just explicitly setting `@types/node` as a dependency for `amplify-ui-angular`.
```
@aws-amplify/ui-angular: node_modules/@types/node/globals.d.ts(1075,15): error TS2430: Interface 'Require' incorrectly extends interface 'RequireFunction'. …
```

set node types version for amplify-ui-angular

---

packages/analytics/src/Providers/AWSKinesisFirehoseProvider.ts

https://github.com/aws-amplify/amplify-js/issues/5337
Fixes encoding issue when recording to Kinesis Firehose. 
Remove references to `PartitionKey` in `AWSKinesisFirehoseProvider.ts:_sendEvents` as that param is only used by Kinesis, not Firehose.

fix(analytics): fix Firehose data encoding

---

packages/datastore/__tests__/DataStore.ts
packages/datastore/__tests__/subscription.test.ts
packages/datastore/package.json
packages/datastore/src/datastore/datastore.ts
packages/datastore/src/storage/adapter/indexeddb.ts
packages/datastore/src/types.ts

Fixes #5422 
- Improve `query` and `observe` typings. (Types verified with an angular 9 app)
- Validate tests with tslint (`npm run test` will fail when there are compilation errors in test files)
This also includes a small fix to handle an indexeddb cursor when store is empty

fix(@aws-amplify/datastore): Improve query and observe typings

---

packages/api-rest/package.json
packages/storage/__tests__/providers/AWSS3ProviderManagedUpload-unit-test.ts
packages/storage/package.json
packages/storage/src/providers/AWSS3ProviderManagedUpload.ts
packages/storage/src/providers/axios-http-handler.ts
packages/storage/src/providers/httpHandlerOptions.ts

_Issue #, if available:_ fixes #5432 
* For multipart uploads, any file properties/metadata are supposed to be added in the CreateMultipartRequest as per the S3 documentation
> If you want to provide any metadata describing the object being uploaded, you must provide it in the request to initiate multipart upload. 
* If the POST request body is empty but content-type header is set, axios is forcibly removing it. See https://github.com/axios/axios/issues/1535 and axios refusing to fix it https://github.com/axios/axios/issues/755. This change is a workaround to set the data as null (instead of undefined) to prevent axios from removing the content-type header. Link for the [source code](https://github.com/axios/axios/blob/dc4bc49673943e35280e5df831f5c3d0347a9393/lib/ …

fix(@aws-amplify/storage) Add contentType and Metadata to multipart upload

---

packages/storage/__tests__/providers/axios-http-handler.test.ts
packages/storage/src/providers/AWSS3Provider.ts
packages/storage/src/providers/AWSS3ProviderManagedUpload.ts
packages/storage/src/providers/axios-http-handler.ts

_Issue #, if available:_ fixes #5376 
There are two headers that are creating warnings in customer apps `host` and `Content-Length` Both of these headers are forbidden for http clients to set for security reasons, see https://fetch.spec.whatwg.org/#forbidden-header-name and https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name
Both of these headers are set by the browsers automatically based on the request. Host is determined from the url and content length from the body. aws-sdk-js-v3 adds both of these headers in the request (which fetch doesn't seem to create warnings even though it doesn't set it) while axios creates the noise mentioned in the issue #5376 
There are two ways we can remove these headers from being set in axios request, one …

Remove headers from the request that axios deems unsafe to set

---

packages/amplify-ui-components/src/components/amplify-email-field/__snapshots__/amplify-email-field.spec.ts.snap
packages/amplify-ui-components/src/components/amplify-input/amplify-input.tsx

fix https://github.com/aws-amplify/amplify-js/issues/5512
Refactoring back to `onInput` because of the following.
> change events fire when the user commits a value change to a form control. This may be done, for example, by clicking outside of the control or by using the Tab key to switch to a different control.
https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onchange

UI Component - Fix keydown press.

---

packages/amplify-ui-components/package.json

fixes: https://github.com/aws-amplify/amplify-js/issues/5552
- Fix deprecated method warning in React components

Bump react output target version

---

packages/analytics/package.json
packages/aws-amplify-react/__tests__/__snapshots__/AmplifyUI-test.tsx.snap
packages/core/package.json
packages/interactions/package.json
packages/predictions/package.json
packages/storage/package.json

Beta.5 version of aws-sdk is released which uses exact dependencies instead of loose versioning for dependent aws-sdk dependencies to ensure that new aws-sdk version releases will not impact amplify customers.

Upgrade aws-sdk clients to beta.5 which uses exact dependencies

---

packages/amplify-ui-components/src/components/amplify-forgot-password/amplify-forgot-password.tsx
packages/amplify-ui-components/src/components/amplify-sign-in/amplify-sign-in.tsx
packages/amplify-ui-components/src/components/amplify-sign-up/amplify-sign-up.tsx

Fixes https://github.com/aws-amplify/amplify-js/issues/5298
The phone number formField's value was assigned directly to the user attribute without `composePhoneNumberInput` method being invoked causing the bug. This PR enforces the follow and handle the phone_field follow as intended.

fix(@aws-amplify/ui-component) - formField phone_number compose

---

packages/analytics/package.json
packages/analytics/src/Providers/AWSKinesisFirehoseProvider.ts
packages/analytics/src/Providers/AWSKinesisProvider.ts

3_Issue #, if available:_ fixes #5544
aws-sdk requires the record format to be a UInt8Array instead of string. This PR converts the string(or a JSON object) to an UInt8Array that is then base64encoded by the aws-sdk before sending to Kinesis or Firehose.
Tested in React and ReactNative

fix(@aws-amplify/analytics) send the analytics data to kinesis and firehose correctly encoded

---

packages/aws-amplify-react-native/src/Auth/Authenticator.js

_Issue #, if available:_ fixes #4824 
Checking if the analytics module is configured before making the call for record similar to [this implementation](https://github.com/aws-amplify/amplify-js/blob/b4b40aa62644ea3688068e4e64f4573c568677a0/packages/analytics/src/Analytics.ts#L311)
This will be revisited with rewrite of auth modules in react native. 

fix (aws-amplify-react-native) : analytics warning/error when using auth module

---

CONTRIBUTING.md

Tweaking wording and punctuation for readability.

---

packages/analytics/__tests__/Analytics-unit-test.ts
packages/analytics/src/Analytics.ts
packages/api-rest/__tests__/RestAPI-test.ts
packages/api-rest/src/RestAPI.ts
packages/api-rest/src/RestClient.ts
packages/api/__tests__/API-test.ts
packages/auth/__tests__/auth-unit-test.ts
packages/core/__tests__/Amplify-test.ts
packages/core/__tests__/Credentials-test.ts
packages/core/src/Amplify.ts

_Issue #, if available:_ #5671, 
This change is to call configure() and apply current _"Amplify"_ configuration to all the new categories imported or initialized (especially when imported in a UI component). For instance the following App code will work with the change which right now throws exception "Auth module is not configured"
```
...
import { withAuthenticator } from "@aws-amplify/ui-react";
import awsconfig from './aws-exports';
import Amplify from '@aws-amplify/core';
Amplify.configure(awsconfig);
function App() {
return (
<div className="App">
<header className="App-header">
...
</header>
</div>
);
}
export default withAuthenticator(App);
```
After the modularization updates, when an `Amplify.configure()` is called, not all the modules/categories are …

Configure all new components or categories when imported

---

packages/api/src/API.ts

https://github.com/aws-amplify/amplify-js/pull/5001
- Backport `additionalHeaders` from `API.graphql`
- https://github.com/aws-amplify/amplify-js/pull/5001#issuecomment-623147532

Backport graphql api parameter to API.graphql

---

.vscode/settings.json

- Typescript formatter was being used as the default in Typescript files
- Use prettier as the default formatter for Typescript files

Set default Typescript formatter

---

packages/storage/__tests__/providers/AWSS3Provider-unit-test.ts
packages/storage/src/providers/AWSS3Provider.ts

_Issue #, if available:_ fixes #5677 
_Description of changes:_ Since beta versions of aws-sdk, the expire option is a number and not a Date object. Updating S3 provider to reflect that.

fix(@aws-amplify/storage) Update expires param to be a number

---

packages/api-graphql/__tests__/GraphQLAPI-test.ts
packages/api-graphql/src/GraphQLAPI.ts
packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts

_Issue #5576_
An `additionalHeaders` object can be supplied to `GraphQLAPI.graphql({query, variables}, additionalHeaders)`, but prior to this PR the option is only respected for query and mutation requests.
In the case of AppSync, these headers are passed to the resolver as input in `context.request.headers`, allowing for queries, mutations, and now subscriptions to be authorized (or execute any custom logic) based on these headers.

fix(@aws-amplify/api-graphql) Respect additionalHeaders in GraphQLAPI subscription requests

---

packages/analytics/src/Providers/AWSPinpointProvider.ts
packages/analytics/src/Providers/EventBuffer.ts

fix regression https://github.com/aws-amplify/amplify-js/pull/5618#discussion_r422039389

fix(@aws-amplify/analytics): change logger.error back to debug

---

.circleci/config.yml
packages/amplify-ui-components/src/common/helpers.ts
packages/amplify-ui-components/src/components/amplify-confirm-sign-up/amplify-confirm-sign-up.tsx
packages/amplify-ui-components/src/components/amplify-sign-in/amplify-sign-in.tsx

_Issue #, if available:_ #5298
Handle provide hint with default value under certain conditions.
This PR handles hint for password and code and  in the following ways,
- `hint: null` is passed to `formFields`
- string is to `hint` in `formFields`
- if nothing is passed in or a function component, it would resolve to fallback

fix(@aws-amplify/ui-components): formFields hint handle

---

packages/amplify-ui-components/src/components/amplify-auth-fields/__snapshots__/amplify-auth-fields.spec.ts.snap
packages/amplify-ui-components/src/components/amplify-auth-fields/amplify-auth-fields.scss
packages/amplify-ui-components/src/components/amplify-auth-fields/amplify-auth-fields.tsx
packages/amplify-ui-components/src/components/amplify-button/amplify-button.scss
packages/amplify-ui-components/src/components/amplify-input/amplify-input.scss
packages/amplify-ui-components/src/components/amplify-select/amplify-select.scss

- Fix grey background on hints in Safari:
- Fix janky phone field in Safari
- Add margin to auth fields and remove from individual input

fix(@aws-amplify/ui-components): Styling fixes

---

packages/aws-amplify-angular/src/__mocks__/mock_module.ts
packages/aws-amplify-angular/src/__tests__/providers/auth.decorator.spec.ts
packages/aws-amplify-angular/src/providers/auth.decorator.ts

Reverts aws-amplify/amplify-js#5443
This introduced a regression found in integration tests where `email` was not being correctly passed to `Auth.signUp`:
> https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/4976/workflows/7c22204f-aecb-4a40-a548-7c139a25facb/jobs/15189
Choosing to revert to unblock our release pipeline before re-applying work.

Revert "fix(aws-amplify-angular): decorateSignUp matches Auth.signUp"

---

packages/api-graphql/__tests__/GraphQLAPI-test.ts
packages/api-graphql/src/GraphQLAPI.ts
packages/api-rest/__tests__/RestAPI-test.ts
packages/api-rest/__tests__/RestClient-unit-test.ts
packages/api-rest/src/RestAPI.ts
packages/api-rest/src/RestClient.ts
packages/api/src/API.ts

Co-authored-by: kbuechl <karlrbuechler@gmail.com>
_Issue #, if available:_ fixes #989, closes #3769
_Description of changes:_ This is a replacement PR for #3769 since that PR has a lot of merge conflicts which requires a pretty much rewrite since API category has been refactored into api-rest and api-graphql categories.
This PR builds on the same concept as https://github.com/aws-amplify/amplify-js/pull/3769#issuecomment-552660025 but instead of keeping keeping the promises from axios in the weakmap, we are utilizing the promises that library return to the clients. This is because using async/await wraps any promises being returned and renders the whole idea of using promises as key useless.
We keep a weakmap<promise, canceltoken> for every request made in the RestClient. If the client …

Add feature to cancel axios requests used by API rest and graphql category

---

packages/amplify-ui-components/src/components.d.ts
packages/amplify-ui-components/src/components/amplify-totp-setup/amplify-totp-setup.tsx
packages/amplify-ui-components/src/components/amplify-totp-setup/readme.md

- Add `headerText` to `AmplifyTOTPSetup` component to match customization docs

Add headerText to TOTPSetup component

---

packages/amplify-ui-components/src/components/amplify-forgot-password/__snapshots__/amplify-forgot-password.spec.ts.snap
packages/amplify-ui-components/src/components/amplify-forgot-password/amplify-forgot-password.tsx

Our project uses Finnish translations with the app and noticed that in the amplify-forgot-password some of the texts were not utilizing the Translations enum. I simply updated the code to utilize these instead of static strings. 

Make all the strings in amplify-forgot-password translatable

---

.circleci/config.yml
.circleci/retry-publish.sh
package.json

Add bash retry logic for `lerna publish` - when publishing to verdaccio as well as to npm

ci: add retry logic for lerna publish

---

packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.scss
packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx
packages/amplify-ui-components/src/components/amplify-section/amplify-section.scss
packages/amplify-ui-components/src/global/theme.ts
packages/amplify-ui-vue/package.json

https://github.com/aws-amplify/amplify-js/issues/5799
- Expose `--background-color` on `amplify-authenticator` which will cascade down to children in it's shadow dom
- Expose `--amplify-background-color` global theme background variable and use it for the default Authenticator background color

Expose background color css api for global theme and authenticator

---

packages/datastore/src/util.ts

Error in console when running DataStore 2.2.0.
Fixes unhandled promise rejection because of undefined variable ('performance') in React native.

Fix performance undefined variable in RN

---

packages/datastore/src/util.ts

Consumers could define a global variable "performance" with a null value. This PR addresses that (unlikely but possible) case

fix(@aws-amplify/datastore): Fix potential NPE

---

CONTRIBUTING.md

The table of contents in the `CONTRIBUTING.md` had drifted away from the current document. The Table of Contents did not provide links to the sections. Both issues have been remedied.

chore(contributing): update table of contents

---

.circleci/android-rn.sh
.circleci/config.yml

Build is failing in CircleCI, potentially due to a new Detox version released recently. Based on other [examples](https://github.com/wix/Detox/blob/master/docs/Introduction.AndroidDevEnv.md), I am downgrading the SDK, emulator, & build tools to use Android 28 instead of 29.
Successful Test: https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/5326/workflows/3916116a-fe24-4f20-b6b6-442af86fac5f/jobs/17271
---

Update android detox setup

---

.circleci/config.yml

Adds Push Notification Detox tests to CircleCI.
Depends on [this sample PR](https://github.com/aws-amplify/amplify-js-samples-staging/pull/108) getting merged.
---

Push Notification iOS Detox tests

---

.circleci/config.yml
CONTRIBUTING.md
README.md
docs/.gitlab-ci.yml
docs/_config.yml
docs/_layouts/default.html
docs/_layouts/home.md
docs/amplify-theme/_includes/docs-header.html
docs/api/globals.html
docs/api/index.html
package.json
packages/amazon-cognito-identity-js/RNAWSCognito.podspec
packages/aws-amplify-react-native/README.md
packages/aws-amplify-react/README.md

- Update CircleCI to use `main` branch instead of `master`
- Update links throughout repo
- Various Prettier `.md` updates
_TODO after this gets merged:_
- Set `main` as default branch in GitHub and update branch protection rules
- Update destination branch for all PRs
- Update links in [docs](https://github.com/aws-amplify/docs) repo
---

master -> main

---

packages/aws-amplify-angular/package.json

Unit tests failing on `ERROR: invalid option --screw-ie8` in `aws-amplify-angular` because of their latest version update to `3.10.0`
- Pin version to `3.9.4`

Pin UglifyJS version

---

.circleci/config.yml

Test run with all integ tests here: https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/5398/workflows/d4d634ae-ebf8-49ac-b9a0-6ef62e56f726
Utilizing the `ci:test` script for more reliable integ testing in CCI.

ci: use ci:test script for all integ tests

---

packages/auth/__tests__/auth-attribute-test.ts
packages/auth/src/Auth.ts

Fixes: https://github.com/aws-amplify/docs/issues/1877
Only coerce `email_verified` and `phone_number_verified` to boolean 

fix(@aws-amplify/auth): User Attributes coerced to boolean

---

packages/amplify-ui-components/src/common/country-dial-codes.ts

Picking the country dial code for Poland during sign-up (`+48`) results in the wrong phone number being registered (with `+47` prefix instead of `+48`).
_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

Use the correct dial code for Poland

---

.circleci/config.yml
.circleci/retry-yarn-script.sh

Retry failed integration test suites 3 times before failing the job in circleci
Tested the pipeline on this branch with integ tests enabled here: https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/5419/workflows/63060753-8fa6-435a-b6d8-3c7642fe555a
++ previous 3 runs on the same branch

ci: add retry for integ tests

---

packages/auth/__tests__/auth-unit-test.ts
packages/auth/src/Auth.ts

#4321
#6106
Add missing `totpRequired` to `callback` for `completeNewPassword`.
---

fix(@aws-amplify/auth): add totpRequired callback to completeNewPassword

---

packages/amplify-ui-react/src/withAuthenticator.tsx

This fixes an issue with an async call in `useEffect`.
In this update, the code ensures that the `setUser` function is complete before returning.

fix(@aws-amplify/ui-react): Fix user not being set on initial render

---

packages/amplify-ui-react/src/withAuthenticator.tsx

Introduced by #6306, this adds back in the `return` needed in `useEffect` to ensure listeners are removed on unmount.
---

fix(@aws-amplify/ui-react): Remove side-effects on unmount

---

packages/amplify-ui-components/src/common/Translations.ts
packages/amplify-ui-components/src/components.d.ts
packages/amplify-ui-components/src/components/amplify-forgot-password/amplify-forgot-password.spec.ts
packages/amplify-ui-components/src/components/amplify-forgot-password/amplify-forgot-password.tsx
packages/amplify-ui-components/src/components/amplify-forgot-password/readme.md

https://github.com/aws-amplify/amplify-js/issues/6253
- Split up send and submit button text for different forms

(@aws-amplify/ui-components): refactor reset password send/submit button text

---

packages/datastore/src/sync/index.ts
packages/datastore/src/sync/processors/subscription.ts

#6162
This PR will ensure disconnectionHandler is called when a subscription fails.

fix(@aws-amplify/datastore): Fix disconnection handler

---

packages/analytics/src/Providers/AWSPinpointProvider.ts

Pinpoint events not being sent because CORS failure.
Related : 
- https://github.com/aws-amplify/amplify-js/issues/6339
Based on `aws-sdk-js` team's recommendation. A short term fix is implemented. 

Fix @aws-amplify/analytics. - Pinpoint header correction

---

packages/storage/__tests__/providers/AWSS3Provider-unit-test.ts
packages/storage/src/providers/AWSS3Provider.ts

The storage category provides a way to track events in pinpoint provided the track event is set to `true`. This was not working.
Initially, the tracking wasn't working since there was a [pinpoint issue around CORS](https://github.com/aws-amplify/amplify-js/pull/6392). 
Once that was resolved the storage track `putEvents` where failing with an error
This was happening due to `null` value was being sent in place of metrics by default. This was blocking storage UI component's `track` functionality too
This PR address the issue and append metrics to `Analytics.record` call only if present.
After the PR events are being sent (screenshot of network tab):
By submitting this pull request, I confirm that my contribution is made under the terms of …

fix (@aws-amplify/storage) - track property

---

.circleci/config.yml

Another attempt at resolving the infamous zlib error in the deploy job.
Since the `lerna publish` command in the deploy job has many side effects, e.g. incrementing versions in package.json, creating a commit and pushing up tags to GitHub, it's difficult to retry the command (like we do in the publish to Verdaccio steps), as before we can re-run the command, we would need to undo these side effects, which in turn can have cascading repercussions. 
Since we have never encountered these zlib errors when running the publish command locally in macOS, I think it's a decent bet that it might be exclusive to Linux environments.
Therefore, I'm changing the executor for the deploy job to use a macos environment. 
Also, removing some unneeded caching steps.
By submitting this pull request, I …

ci: use macos executor for deploy job

---

packages/auth/src/Auth.ts
packages/auth/src/types/Auth.ts

_Issue #, if available:_ #5860 
- use provider/customProvider keys to determine the type of Provider instead of also relying on customState
- add check for customState key if no provider is passed

bugfix #5860: using custom state forces congnito UI for custom provider

---

.circleci/config.yml

This fixes the issue we encountered yesterday during the release. Namely, when doing a `git pull` in the post_release, we see an interactive prompt:
```
The authenticity of host 'github.com (140.82.112.4)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? 
```
Caching the .ssh directory in the build job and restoring in post_release prevents this interactive prompt from appearing since the host gets saved in known_hosts.

ci: restore ssh cache step

---

.circleci/config.yml

Add initial `amazon-cognito-identity-js` integration tests to CircleCI.
Successful test run: https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/5785/workflows/af8895dc-9891-4434-be4e-af7d2099321d/jobs/19521
---

Add amazon-cognito-identity-js tests to CircleCI

---

packages/auth/__tests__/auth-creds-test.ts
packages/auth/src/Auth.ts

Fixes: #3938
Clearing credentials when `bypassCache: true` for `Auth.currentAuthenticatedUser`, that will lazy allow to lazy load AWS Credentials with using the refreshed token.

Force clear credentials when bypassCache: true

---

.circleci/retry-yarn-script.sh

`exit 1` after retrying test instead of allowing job to succeed.

ci: return correct exit code after retrying

---

package.json

I've been noticing that sometimes even with the retry logic, CCI jobs will error out with the zlib error (after 5 retries).
Going to try this suggested fix: https://github.com/lerna/lerna/issues/2278#issuecomment-652538695

ci: zlib fix using npm-packlist

---

packages/amplify-ui-components/src/components/amplify-chatbot/amplify-chatbot.scss
packages/amplify-ui-components/src/components/amplify-chatbot/amplify-chatbot.tsx

_Description of changes:_ This moves width/height control to container level, add min-width to chatbot footer, and resets chat state upon session finish. 

fix(@aws-amplify/ui-components): Update scss and reset chat state upon finish 

---

packages/auth/src/Auth.ts

Fixes: #6634
Adding default argument for `requiredAttributes` for `Auth.completeNewPassword` API

fix(@aws-amplify/auth): Fix types for completeNewPassword

---

.circleci/config.yml

- Sample name now is *-legacy for legacy UI samples

Use *-legacy naming for legacy samples

---

packages/amplify-ui-components/Readme.md
packages/amplify-ui-components/src/common/Translations.ts
packages/amplify-ui-components/src/common/audio-control/recorder.ts
packages/amplify-ui-components/src/components/amplify-chatbot/__snapshots__/amplify-chatbot.spec.tsx.snap
packages/amplify-ui-components/src/components/amplify-chatbot/amplify-chatbot.scss
packages/amplify-ui-components/src/components/amplify-chatbot/amplify-chatbot.tsx
packages/amplify-ui-components/src/components/amplify-chatbot/animation.scss
packages/amplify-ui-components/src/global/theme.ts

_Description of changes:_  This PR makes improvements to chatbot that is on `ui-preview` right now.
Improvements:
- Errors are now divided into recoverable and unrecoverable errors and are handled accordingly. 
- Users no longer need to wait for bot to finish speaking. They can interrupt the audio by pressing mic or send button.
- Loading dots are now customizable. 
- Use different input placeholder when only voice is enabled.
Fix:
- Disable text sending through `enter` keystroke when only voice is enabled.

@feat(@aws-amplify/ui-components): Error/audio handling and css improvements

---

.circleci/config.yml

_Description of changes:_ This adds interactions integration test with vue, angular, and react.

ci: add interactions integ test 

---

packages/datastore/package.json
packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts

_Issue #, if available:_ #6718 
#6146 added `isomorphic-ws` for `WebSocket` support in Node.js, but for those installing `@aws-amplify/*` packages separately (vs. `aws-amplify` in our integration tests & samples), this dependency wasn't added.
Removing instead, since this was more of a polyfill and subscriptions won't be used for SSR.

Remove isomorphic-ws & ws from SSR DataStore usage

---

package.json

Upstream dependency @types/babel__traverse was updated to require TypeScript@3.4.0. Since ui-angular is still on 3.2, the build script for that package is failing.
This change forces packages to resolve @types/babel__traverse: 7.0.8, which supports TS@3.2
More of a band-aid fix to unblock us. We should look into upgrading ui-angular to more recent versions of TS, Angular, and Angular Compiler

chore: pin @types/babel__traverse to allow ui-angular to build

---

packages/amplify-ui-components/src/components/amplify-auth0-button/amplify-auth0-button.tsx
packages/amplify-ui-components/src/components/amplify-federated-buttons/amplify-federated-buttons.tsx
packages/amplify-ui-components/src/components/amplify-federated-sign-in/amplify-federated-sign-in.tsx
packages/auth/src/Auth.ts

_Issue #, if available:_ #6786 
- `Auth.configure({})` was being used for retrieving the config, **but this resets `Auth` back to defaults. (Breaking `Amplify.configure({ ssr: true })`)**.
- Updates signature to `Amplify.configure(config?)`.
- Reproduced via https://github.com/aws-amplify/amplify-js-samples-staging/pull/160
(Notice `Auth._storage` changes on render)
(Notice `Auth._storage` is the same shape)
Closes #6786
---

Update to Auth.configure(config?) for retrieving the config

---

packages/aws-amplify/webpack-utils.js
packages/datastore/__tests__/AsyncStorage.ts
packages/datastore/__tests__/indexeddb.test.ts
packages/datastore/__tests__/model.ts
packages/datastore/__tests__/schema.ts
packages/datastore/package.json
packages/datastore/src/datastore/datastore.ts
packages/datastore/src/predicates/index.ts
packages/datastore/src/predicates/sort.ts
packages/datastore/src/storage/adapter/AsyncStorageAdapter.ts
packages/datastore/src/storage/adapter/AsyncStorageDatabase.ts
packages/datastore/src/storage/adapter/IndexedDBAdapter.ts
packages/datastore/src/storage/adapter/asyncstorage.ts
packages/datastore/src/storage/adapter/index.ts
packages/datastore/src/storage/adapter/indexeddb.ts
packages/datastore/src/storage/storage.ts
packages/datastore/src/types.ts
packages/datastore/src/util.ts

* Enables passing a sort predicate to `DataStore.query`
E.g.,
```typescript
import { DataStore, Predicates, SortDirection } from '@aws-amplify/datastore';
await DataStore.query(User, Predicates.ALL, {
page: 0,
limit: 50,
sort: (s) => s.lastName(SortDirection.ASCENDING),
});
```
* The sort predicate is chainable, allowing for multi-field sort: `s.lastName('ASCENDING').age('DESCENDING')`
* Full TypeScript Intellisense support, like with the query predicate

feat(@aws-amplify/datastore): add query sorting

---

packages/aws-amplify-react-native/src/AmplifyTestIDs.js
packages/aws-amplify-react-native/src/Auth/RequireNewPassword.tsx

I noticed while writing Detox tests on a project that there are missing testIDs in the RequireNewPassword component. This pull request adds the missing attributes so the UI can be controlled in tests.

fix(@aws-amplify-react-native):  Add missing testID attributes in RequireNewPassword component.

---

packages/auth/__tests__/auth-unit-test.ts
packages/auth/src/Auth.ts

_Issue #, if available:_ Fixes #6806 
- `Auth.currentCredentials` wasn't bound to `this` like `Auth.currentUserCredentials` are. This caused the error "`this is undefined`".
- Customers should use `Auth.currentUserCredentials` instead, and in the meantime. (`Auth.currentCredentials` is likely to be deprecated)
- I recommend customers configure with `Amplify.configure` instead of `Auth.configure` as well.
---

fix(@aws-amplify/auth): Fix binding for Auth.currentCredentials

---

packages/core/__tests__/Credentials-test.ts
packages/core/src/Credentials.ts

_Issue #, if available:_ Fixes #6750
- Introduced by #6146, `Credentials` referenced `Amplify.Auth` for deferring to `Auth.currentUserCredentials()`, but only when `Auth` was imported/registered.
- The bug was that `Auth = Amplify.Auth` only worked when `Auth` was already imported & registered _first_, which wasn't always the case.
- Instead, `this.Auth` is preferred over `Amplify.Auth` within the `_keepAlive` function at run-time, rather than when constructed.  This ensures that `this.Auth` wins for SSR, but `Amplify.Auth` is always the latest reference.
---

fix(@aws-amplify/auth): No Auth module registered in Amplify

---

packages/core/package.json

_Issue #, if available:_ #6826.
_Description of changes:_ `universal-cookie: 4.0.4` resolves `require is not undefined` error that appeared when using Amplify with Rollup. I confirmed that this fixes the rollup errors in our docs as well.
Customers should already have `4.0.4` because we have `universal-cookie: ^4.0.3`, but I wanted to get the resolved version specified in `package.json`.

deps(@aws-amplify/core): bump universal cookie to ^4.0.4

---

packages/analytics/package.json
packages/api-graphql/package.json
packages/api-rest/package.json
packages/api/package.json
packages/auth/package.json
packages/cache/package.json
packages/core/package.json
packages/datastore/package.json
packages/interactions/package.json
packages/predictions/package.json
packages/pubsub/package.json
packages/storage/package.json
packages/xr/package.json

Related to #6844
This PR adds files that call `Amplify.configure()` to the `"sideEffects"` key in `package.json`.
The purpose of this is to *hint* bundlers to not remove the categories registration when creating the bundle.
Tests were done with an angular 9 application in production mode using `@aws-amplify/auth`

fix: Add files with Amplify.register to sideEffects array

---

packages/core/src/JS.ts
packages/datastore/src/storage/adapter/getDefaultAdapter/index.ts

https://github.com/aws-amplify/amplify-js/issues/6870
* Add `isWebWorker` function to @aws-amplify/core to check if running on web worker or not
* Add isWebWorker condition in DataStore getDefaultAdapter

feat(datastore): support IndexedDB Adapter on web worker

---

packages/datastore/src/datastore/datastore.ts
packages/datastore/src/util.ts

I missed [this](https://github.com/aws-amplify/amplify-js/pull/6784/files#diff-0b1030adae876f32132a5bffa1541233R53) while reviewing https://github.com/aws-amplify/amplify-js/pull/6784. It's attempting to import `isNullOrUndefined` from a dependency we don't explicitly install, **utils**.
It got caught in our integ tests, so it wasn't deployed with the bug.

fix(@aws-amplify/datastore): fix import isNullOrUndefined

---

.circleci/config.yml
.gitignore

Just some minor improvements:
* Generate and store yarn.lock as an artifact (then delete it from source)
* This will allow us to more easily debug dependency-related build issues by diff'ing against the lockfile from the last known working build. We've spent entire days simply trying to pinpoint which upstream dependency got updated with breaking changes. This should expedite that process if it happens again.
* Remove save_cache/restore_cache steps for CocoaPods in RN integ test jobs. More trouble than it's worth, causes issues when RN itself and RN-deps are upgraded in the sample apps. 
* Upgrade the macOS executor to XCode 11.5.0 (this is the latest we can use until we upgrade our Android emulator)
* Test run for pipeline changes: …

ci: minor improvements

---

.circleci/config.yml
packages/aws-amplify-react/package.json

_Description of changes:_ This PR updates integration tests to run on both dev builds and prod builds. This also resolves sideEffects regression in `aws-amplify-react` that was found along the way.
I considered creating a separate job for prod testing, but this was inefficient because we would have to run `persist_to_workspace` for each of our sample to transition from dev to prod. 
I've tested that all our browser integration tests pass on both prod and dev with the accompanying PR on samples repo. See [link](https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/6281/workflows/197a14ea-5ea6-466b-ad02-e4045e05d9b9) to see what this looks like on circleCI!
By submitting this pull request, I confirm that my contribution is made under the terms of the …

ci: enable production integration testing

---

packages/datastore/src/sync/processors/subscription.ts

`logger.warn` causes a yellow warning to show up in React Native, but this error show only show when debugging is enabled.

fix(@aws-amplify/datastore): switch log to debug so RN doesn't show warning

---

.circleci/config.yml

Adding Docker Hub authentication to our CircleCI pipeline to accommodate [this change](https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress) in Docker's ToS.

ci: add docker hub auth to config

---

packages/datastore/src/sync/processors/subscription.ts

OIDC group authorization for subscriptions was failing because we weren't returning the value from `userGroups.find()`, so `validOidcGroup` was always `undefined`. Due to this, OIDC group authorization was never being returned from `getAuthorizationInfo`. Also see line 136 for proper usage (with user pools).

fix(@aws-amplify/datastore): fix OIDC group auth rules

---

packages/datastore/__tests__/DataStore.ts
packages/datastore/src/datastore/datastore.ts

Fix #5206 
Fix #6453
Fix #6744 
https://github.com/aws-amplify/amplify-js/issues/5206#issuecomment-714200927
`validateModelFields` currently throws an error when setting `undefined` to an optional field. This PR fixes this wrong behavior.
cc/ @iartemiev 

fix(datastore): validate model fields to allow undefined

---

packages/datastore/src/datastore/datastore.ts

Initialize syncPredicates to an empty `WeakMap` to prevent `undefined` error caught by integ tests

fix(@aws-amplify/datastore): initialize syncPredicates to empty WeakMap

---

packages/datastore/src/datastore/datastore.ts

fix(@aws-amplify/datastore): return empty WeakMap

---

packages/datastore/src/datastore/datastore.ts
packages/datastore/src/sync/index.ts

* support returning `Predicates.ALL` from `syncExpression` - allows clearing the syncExpression at runtime
* persist `lastSyncPredicate` to `ModelMetadata` in order to better detect when the predicates have changed, e.g., if developer stops application, changes the `syncExpression` and then restart their application.

feat(@aws-amplify/datastore): selective sync enhancements

---

packages/amazon-cognito-identity-js/src/utils/cryptoSecureRandomInt.js

#4886 
- Use `randomBytes` in Node environment. 
This fix, along with setting `global.crypto = require('crypto')`, should enable this package to work in Node.
`crypto-js` reference: https://github.com/brix/crypto-js/blob/4.0.0/core.js#L52-L70
---

fix(amazon-cognito-identity-js): use Node randomBytes

---

packages/datastore/src/datastore/datastore.ts
packages/datastore/src/types.ts

Fixes #7088 
Tested the following sync expressions in **TS** and **JS**. No errors and Intellisense works as expected in each case:
```js
syncExpression(User, () => {
return (c) => c.jobTitle('eq', 'someVal');
}),
syncExpression(User, async () => {
return (c) => c.jobTitle('eq', 'someVal');
}),
syncExpression(User, (c) => c.jobTitle('eq', 'someVal')),
```
cc @harrysolovay - let me know if you have any suggestions on how to improve the types further (: 
I would prefer to get rid of the `| undefined` [here](https://github.com/aws-amplify/amplify-js/compare/main...iartemiev:syncExpression-type-fix?expand=1#diff-11db1320cd9ef8ce406ca63de04c6f9104cb7674410c8d33fed7731155d13230R481) and [here](https://github.com/aws-amplify/amplify-js/compare/main...iartemiev:syncExpression-type-fix?expand=1#dif …

fix(@aws-amplify/datastore): fix syncExpression types

---

packages/aws-amplify/__tests__/exports-test.ts
packages/aws-amplify/src/index.ts

Fixes https://github.com/aws-amplify/amplify-js/issues/7101
export `SortDirection` and `syncExpression` from `aws-amplify`

fix(@aws-amplify/datastore): export SortDirection and syncExpression

---

packages/amazon-cognito-identity-js/__tests__/cryptoSecureRandomInt-test.js
packages/amazon-cognito-identity-js/src/utils/cryptoSecureRandomInt.js
packages/amazon-cognito-identity-js/webpack.config.js

https://github.com/aws-amplify/amplify-js/issues/7098
This allows `amazon-cognito-identity-js` to run in the Node environment without having to explicitly add `global.crypto = require('crypto')` in your code.
I tested this in React Native, Expo, React, & Node. Normally, using a dynamic `require` like this causes problems with React Native, but since this only exists in `cryptoSecureRandomInt.js` and not `cryptoSecureRandomInt.native.js`, Metro bundler doesn't evaluate this particular file.
---

fix(amazon-cognito-identity-js): set crypto for Node

---

packages/amazon-cognito-identity-js/index.d.ts
packages/amazon-cognito-identity-js/src/CognitoUser.js
packages/amazon-cognito-identity-js/src/CognitoUserPool.js
packages/auth/__tests__/auth-unit-test.ts
packages/auth/src/Auth.ts

_Issue #, if available:_ #6352 
A cleaner implementation to that of #6983 
```ts
Hub.listen('auth', (data) => {
switch (data.payload.event) {
case 'tokenRefresh': {
logger.log("New token has been process");
break;
}
case 'tokenRefresh_failure': {
logger.log("Failed to retrieve new token");
break;
}
}
});
```

feat: enable hub listening of token refresh & refresh failure events

---

packages/amazon-cognito-identity-js/package.json
packages/amazon-cognito-identity-js/src/StorageHelper-rn.js
packages/cache/__mocks__/AsyncStorage.js
packages/cache/src/AsyncStorageCache.ts
packages/core/package.json
packages/core/src/RNComponents/reactnative.ts
packages/core/src/StorageHelper/reactnative.ts
packages/datastore/src/storage/adapter/InMemoryStore.native.ts
packages/pushnotification/__tests__/PushNotification-test.ts
packages/pushnotification/src/PushNotification.ts

This PR migrates our libraries to use the community version of AsyncStorage `(@react-native-async-storage/async-storage)` as  AsyncStorage provided by `react-native` will be deprecated in the future.
This change impacts all **React Native** customers, who now need to install `@react-native-async-storage/async-storage` in their apps due to how RN currently handles linking of transitive dependencies.
**Note: This PR is not yet ready for review**
_TODO: Next step is to move netinfo into core_

Migrate to AsyncStorage from community

---

packages/datastore/__tests__/graphql.ts
packages/datastore/__tests__/schema.ts
packages/datastore/src/sync/utils.ts

Current Behavior: When using a type with implicit owner, the `owner` field does not get added to the selection set, which means that subscriptions won't come through for the owner.
- Changes: Add `owner` to selection set when using implicit owner auth so subscriptions will work correctly. 
```gql
type Post @model @auth(rules: [{ allow: owner }]) {
id: ID!
title: String!
}
```
```gql
mutation operation($input: CreatePostInput!) {
createPost(input: $input) {
id
title
_version
_lastChangedAt
_deleted
}
}
mutation operation($input: CreatePostInput!) {
createPost(input: $input) {
id
title
owner
_version
_lastChangedAt
_deleted
}
}
```
---

fix(@aws-amplify/datastore): add implicit owner to selection set

---

packages/amplify-ui-components/stencil.config.ts

_Description of changes:_ `stencil-sass` [recently updated](https://github.com/ionic-team/stencil-sass/pull/36) the `injectGlobalPath` config option to use `@use` instead of `@import`. You can see [link](https://github.com/ionic-team/stencil-sass/commit/46133575019cf30154618d02fac14207e46a4756) to read about the changes. This PR updates `stencil.config.ts` in `ui-components` to reflect this. 

fix(@aws-amplify/ui-components) update injectGlobalPaths

---

packages/auth/src/Auth.ts

Relates to #7102 
`${user} has signed in` is being rendered as `[object Object] has signed in` because user is of type `CognitoUser`
It should say `A user ${user.getUsername()} has been signed in`, as seen in:
https://github.com/aws-amplify/amplify-js/blob/5173a9911096627ce1b45067808af249668b260b/packages/auth/src/Auth.ts#L496-L500
Screenshot:

fix(@aws-amplify/auth): fix signIn event message

---

.circleci/config.yml
package.json

This adds a new `native` tag in NPM that will be used primarily for the community to test React Native changes before going to `main`, with the first changes to be tested being the AsyncStorage upgrade: https://github.com/aws-amplify/amplify-js/pull/7118
---

chore: deploy native tag for React Native

---

packages/datastore/src/sync/index.ts

`modelMetadata.lastSyncPredicate` is already a stringified object here. 

fix(@aws-amplify/datastore): fix sel. sync delta

---

packages/datastore/src/types.ts

Explicitly allow `Predicates.ALL` as a return type.
Fixes https://github.com/aws-amplify/amplify-js/issues/7217

fix(@aws-amplify/datastore): extend Lookup type to allow Predicates.ALL

---

packages/datastore/package.json

_Description of changes:_ This bumps `dexie` to `3.0.3` to resolve datastore unit tests.

deps: bump dexie to 3.0.3

---

packages/datastore/__tests__/DataStore.ts
packages/datastore/__tests__/util.test.ts
packages/datastore/src/datastore/datastore.ts
packages/datastore/src/types.ts
packages/datastore/src/util.ts

Relates to #5963
Perform some basic local validations for all [AppSync Defined Scalars](https://docs.aws.amazon.com/appsync/latest/devguide/scalars.html). Currently there are no validations on these fields so one can store anything in e.g. `AWSDateTime` field locally. During datastore sync, AppSync does validations and graphql requests will fail. 
This PR uses basic regex to validate all the fields listed. However, some of the fields could use better validations. e.g. `2020-99-99T00:00:00Z` will pass validation with the current regex, We cannot use the built-in date function because AppSync supports non-standard ISO 8601 standard:
> The seconds field in the timezone offset will be considered valid even though it is not part of the ISO …

feat(@aws-amplify/datastore): add local validations to AppSync scalars

---

packages/datastore/__tests__/DataStore.ts
packages/datastore/src/datastore/datastore.ts

N/A
1. Update error message to show `[null]` instead of `[object]` for `[null]`s.
2. The current test suite does not handle scenarios for something like
```
misc: [String]
``` 
`amplify codegen models` generates the following type:
```
readonly misc?: (string | null)[];
```
and schema:
```
"misc": {
"name": "misc",
"isArray": true,
"type": "String",
"isRequired": false,
"attributes": [],
"isArrayNullable": true
},
```
With the current validation function, setting `misc: [null]` throws an exception stating 
```
All elements in the rewards array should be of type string | null | undefined , [null] received. 
```
This is clearly a mistake because `[null]` should pass validation. 
**To summarize**, this PR (1) fixes the datastore validation …

fix(@aws-amplify/datastore): fix validation for array with optional element

---

packages/analytics/__tests__/Providers/AWSPinpointProvider-unit-test.ts
packages/analytics/src/Providers/AWSPinpointProvider.ts

fix(@aws-amplify/analytics)!: do not attempt to delete unused endpoints

---

package.json

_Issue #, if available:_ closes #7247 
_Description of changes:_ With the latest `@types/react` major release (`17.x.x`), `yarn build` is failing due to conflicting `@types/react` versions among sub-dependencies. This pr adds `@types/react` to `resolutions` to use `16.x.x` version. Once sub-dependencies are updated to use `17.x.x`, this change should be reverted.

deps(@aws-amplify/ui-components): add `@types/react` to the resolution list

---

packages/datastore/__tests__/subscription.test.ts
packages/datastore/src/sync/utils.ts

https://github.com/aws-amplify/amplify-js/issues/7206#issuecomment-732061640
Continuing from https://github.com/aws-amplify/amplify-js/pull/7208, this will add additional handling for a `groupClaim` as a plain string, which is currently throwing a `JSON.parse` error.
---

fix(@aws-amplify/datastore): handle groupClaim as plain string

---

packages/analytics/src/Analytics.ts
packages/analytics/src/Providers/AWSPinpointProvider.ts

When `autoSessionRecord` is disabled, custom events are never being sent because `_endpointGenerating` is defaulted to true which causes the buffer to pause indefinitely due to this block of code in `_initBuffer`:
```js
if (this._endpointGenerating) {
this._buffer.pause();
}
```
My assumption is that this was originally added to make sure the endpoint was updated with `immediate: true` before sending the initial session events. See `sendEvents` in `Analytics.ts` for more context.
This PR will set `_endpointGenerating` dynamically based on if `autoSessionRecord` is enabled or not.
---

fix(@aws-amplify/analytics): send events when autoSessionRecord is disabled

---

packages/amplify-ui-components/stencil.config.ts

_Issue #, if available:_ Reverts #7168
_Description of changes:_ This reflects the `injectGlobalPaths` behavior change from the latest `stencil-sass` release.

fix(@aws-amplify/ui-components): flatten `injectGlobalPaths` array

---

packages/datastore/src/sync/processors/subscription.ts

This fixes an Auth error that shows in the console when using DataStore with API Key and the Auth category isn't configured. The error is showing because we are calling `Auth.currentAuthenticatedUser()`. As the code comment says, we're checking if Auth is configured first with `Auth.configure()` before attempting to get the OIDC token below. If it's not configured, we're just throwing an error as a string to the `catch` to be logged with `logger.debug`, as opposed to the `logger.error` currently being used in `Auth.currentAuthenticatedUser()`.
For reference, this is where `region` is set for Auth:
https://github.com/aws-amplify/amplify-js/blob/main/packages/core/src/Parser.ts#L19-L29
---
By submitting this pull request, I confirm that my …

fix(@aws-amplify/datastore): check auth config before getting token

---

packages/datastore/package.json

_Issue #, if available:_ https://github.com/aws-amplify/amplify-js/issues/7348
NPM 7 attempts to automatically install peer dependencies and errors out when there are conflicts. 
This means it'll always attempt to install `@react-native-community/netinfo`, even though it's only required for react-native apps. 
The docs [already specify](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/js#option-1-platform-integration) netinfo as a required package for RN. 
This PR removes netinfo as a peer dependency.

fix(@aws-amplify/datastore): remove netinfo from peer deps to prevent npm7 error

---

packages/datastore/src/datastore/datastore.ts
packages/datastore/src/sync/datastoreConnectivity.ts
packages/datastore/src/sync/index.ts

https://github.com/aws-amplify/amplify-js/issues/7312
Currently when calling `DataStore.stop()` or `DataStore.clear()`, the `DataStoreConnectivity` observer is not unsubscribed, leading to the subscriptions getting [initialized](https://github.com/aws-amplify/amplify-js/blob/main/packages/datastore/src/sync/index.ts#L164-L166) again if the network connection goes from offline to online. This is problematic because `stop/clear` implies that all DataStore functionality should be halted.
In the case of the related issue, it is leading to duplicate sync queries and subscriptions being made.
This PR will properly unsubscribe the sync engine after calling `DataStore.stop()` or `DataStore.clear()`.
---
By submitting this pull request, I confirm …

fix(@aws-amplify/datastore): unsubscribe connectivity on stop/clear

---

packages/auth/__tests__/totp-unit-test.ts
packages/auth/src/Auth.ts

Issue #6774 
Added a `dispatchAuthEvent` call inside the `onSuccess` callback of `verifyTotpToken`.
Mocked `CognitoUser.getUsername()` and adapted the current 'totp-unit-test' to work with the addition.

fix(6774): fixed 'signIn' not being called on successful totp verification.

---

CONTRIBUTING.md

N/A
The current verdaccio publish instructions do not work. This is because lerna is using yarn not npm. This PR updates docs so contributors can get verdaccio set up without surprises.

docs(CONTRIBUTING.md): update verdaccio instructions

---

packages/aws-amplify-react-native/package.json

#7381 
Due to a recent [update](https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/) with NPM CLI 7.0.0, peer dependencies will get automatically installed. This is causing issues in the `aws-amplify-react-native` library because we have a few outdated peer dependencies that are only used for the [Interaction components](https://docs.amplify.aws/ui/interactions/chatbot/q/framework/react-native). 
Since we already have a callout in the docs for installing the peer dependencies, they are no longer needed in the `package.json`.
---

fix(aws-amplify-react-native): remove peerDependencies

---

packages/auth/src/Auth.ts

_Issue #, if available:_ Fixes #7161 
See my reproduction here: https://github.com/aws-amplify/amplify-js/issues/7161#issuecomment-740081033
Track the `Auth.signIn` attempt and prevent **subsequent** sign-ins from happening until that resolves.
(I originally wanted to _cancel_ the previous ones, favoring the latest sign-in attempt. However, because the mutation of `user` happens _somewhere_ in that promise chain, it's not safe to cancel unless we practically track the state through that entire flow)
Because we **don't** have an understanding _why_ two different accounts would be signed in on the same computer, within milliseconds of each other, in the same browser, this seemed reasonable to prevent mutating `Auth.user`'s `attributes` with those of another.
> ![Kapture 2020-12-10 at 12 53 …

fix(@aws-amplify/auth): Disallow simultaneous Auth.signIn attempts

---

packages/amplify-ui-components/src/common/auth-helpers.ts

_Issue #, if available:_ Fixes #5623 
_Description of changes:_ Displays "password cannot be empty" message on sign in attempts without a password, if custom lambda triggers are not configured.
**Problem**
If `password` is empty on `Auth.signIn()`, `Auth` assumes that the client is on a custom auth flow with lambda triggers set up. This is not the case for UI users who just forgot to put a password (or mistakenly pressed enter early). They would get "Custom auth lambda trigger is not configured for the user pool." error instead, which is unreadable to end users. 
**Solution**
This PR detects if the error is due to empty password on custom auth flow, and changes the message to "Password cannot be empty" for readability. 
By submitting this pull request, I confirm that my contribution is …

fix(@aws-amplify/ui-components): display friendly error for empty password

---

packages/amplify-ui-components/src/common/auth-helpers.ts

_Issue #, if available:_ #5623, follows up #7401 
_Description of changes:_ Use translatable constants for empty password error message.
Usage:
```jsx
import { I18n } from 'aws-amplify';
import { Translations } from '@aws-amplify/ui-components';
I18n.putVocabulariesForLanguage('en-US', {
[Translations.EMPTY_PASSWORD]: 'Custom Empty Password Translation',
});
```

fix(@aws-amplify/ui-componets): Use constant for empty password error

---

package.json

Fixes build error in `@aws-amplify/ui-angular` introduced by the latest version of `@babel/types`.
---

chore: pin @babel/types causing ui-angular build error

---

packages/api-rest/package.json
packages/storage/package.json

_Description of changes:_ This bump is in response to a medium secuirty vulnerability with axios described in https://github.com/axios/axios/pull/3410. This PR bumps axios to 0.21.1 in which the security patch is released. 
Looking at the [changelog](https://github.com/axios/axios/blob/hotfix/0.21.1/CHANGELOG.md) from 0.19.0 to 0.21.1, I don't see any commits that would cause regression, but it would be great if anyone else can confirm this.

deps: bump axios to 0.21.1

---

packages/amplify-ui-components/src/common/auth-helpers.ts

#7554 
When using the Amplify UI Components, `Auth.verifiedContact(...)` is being called after signing in to check whether the user should be routed to the app or the "Verify Contact" screen. However, this causes a problem when using Identity Pool federation because the `user` is [not actually a `CognitoUser`](https://docs.amplify.aws/lib/auth/advanced/q/platform/js#identity-pool-federation) and `verifiedContact` calls `user.getSession` (via [`userSession`](https://github.com/aws-amplify/amplify-js/blob/843183b094281b42ec829b010dd41d214899c23d/packages/auth/src/Auth.ts#L1389)) which doesn't exist.
This PR checks to make sure `user` is an instance of `CognitoUser` before calling `Auth.verifiedContact` and changes the auth state to "signed …

fix(@aws-amplify/ui-components): handle federated user in checkContact

---

packages/amazon-cognito-identity-js/index.d.ts
packages/amazon-cognito-identity-js/src/CognitoUser.js
packages/auth/__tests__/auth-refresh-token-test.ts
packages/auth/src/Auth.ts

Include client metadata from `Auth.configure` to be send also for token refresh
```jsx
Auth.configure(awsconfig);
Auth.configure({
clientMetadata: {
test: 'this should be on refresh token as well'
}
})
function App() {
async function signIn() {
const user = await Auth.signIn({
username: 'xxxxx',
password: 'yyyy',
})
}
async function currentUser() {
const user = await Auth.currentAuthenticatedUser({ bypassCache: true });
}
return (
<div className="App">
<header className="App-header">
<button onClick={signIn}>sign in</button>
<button onClick={currentUser}>refresh token</button>
</header>
</div>
);
}
```
When refreshing the token when doing `Auth.currentAuthenticatedUser` Amplify is not sending `ClientMetadata` param to Cognito service.
#6731 
_Description of …

fix(@aws-amplify/auth, amazon-cognito-identity-js): Include clientMetadata for token refresh

---

.circleci/config.yml

- add integration test for React Native Storage multi-part upload with progress reporting
- https://github.com/aws-amplify/amplify-js-samples-staging/pull/197
Note: this test will fail until https://github.com/aws/aws-sdk-js-v3/issues/2000 is resolved, since unstable is currently using the latest version of the AWS SDK. I have verified that the tests pass on latest however.
---

chore: add RN storage multi-part w/ progress to CircleCI

---

.circleci/config.yml
packages/datastore/__tests__/util.test.ts
packages/datastore/src/util.ts

Currently, we're only allowing a 3-digit millisecond (the `SSS` in `HH:mm:ss.SSSZ`) in our AWSTime and AWSDateTime validators. We throw an error when the number of millisecond digits is anything other than 3.
AppSync doesn't care how many digits are in the millisecond. Any number `>= 1` is valid. This PR aligns the clientside validation logic with that.
Reviewers: the actual changes are [here](https://github.com/aws-amplify/amplify-js/pull/7717/files#diff-89f8afda2fb41bbdaea63170a71ab23374df7b81bef86a6f7cf1eb9af0baea78R442) and [here](https://github.com/aws-amplify/amplify-js/pull/7717/files#diff-89f8afda2fb41bbdaea63170a71ab23374df7b81bef86a6f7cf1eb9af0baea78R448). I've added tests around this too. 
Ignore the formatting changes, my guess is that this was due to the way the original …

fix(@aws-amplify/datastore): align AWSTime validation with AppSync

---

.circleci/config.yml
.github/actions/bundle-size-action/webpack/package.json
.github/actions/bundle-size-action/webpack4/package.json
package.json
packages/analytics/package.json
packages/analytics/src/Providers/AWSPinpointProvider.ts
packages/core/package.json
packages/interactions/package.json
packages/predictions/package.json
packages/storage/package.json
packages/storage/src/providers/AWSS3ProviderManagedUpload.ts
packages/storage/src/providers/axios-http-handler.ts

- Upgrade to latest version of aws-sdk modular packages
Reference: https://github.com/aws/aws-sdk-js-v3/releases
Successful CircleCI build with integration tests: https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/7181/workflows/171bfbee-0e77-43ff-9478-3d20ae5176bd
---

chore: update to aws-sdk 3.4.1

---

packages/datastore/__tests__/AsyncStorageAdapter.test.ts
packages/datastore/__tests__/DataStore.ts
packages/datastore/__tests__/IndexedDBAdapter.test.ts
packages/datastore/src/datastore/datastore.ts
packages/datastore/src/storage/adapter/AsyncStorageAdapter.ts
packages/datastore/src/storage/adapter/IndexedDBAdapter.ts

This PR fixes a bug where calling `DataStore.query(Post)` _without_ a pagination object would use the cursor-based fetch from IndexedDB, as opposed to `getAll()`, which is optimized specifically for getting all the records. This was having a negative effect on the performance of `DataStore.query` when retrieving all the items for a given model.
The pagination object was getting initialized to `{limit: undefined, page: undefined, sort: undefined}` in the `DataStore.processPagination` private method, therefore `pagination` always had a truthy value in the conditional checks that determine which retrieval method to utilize. This gets fixed [here](https://github.com/aws-amplify/amplify-js/pull/7746/files#diff-10866b5ac7d469b38dd9928d9d7056a3a402904fef591ea8cfe773b4d75d63efR1131-R1134).
Also: …

fix(@aws-amplify/datastore): improve IDB query performance

---

.github/ISSUE_TEMPLATE/new_bug_report.yaml

- Clean up spacing
- Rearrange sections
- Use `placeholder` vs `value` for optional configuration code inputs
- Remove note on CLI repo - can add in future, if needed

update: New issue form structure cleanup

---

packages/amplify-ui-components/Readme.md

_Issue #, if available:_ Closes #7856
- Remove `@ui-preview` tag
- Use `@aws-amplify/ui-components` instead of `@aws-amplify/ui-vue` for general web installation
- Some typo fixes
I suggest you turn on "hide whitespace changes" to ignore prettier changes.

docs(@aws-amplify/ui-components): Update Readme.md with latest

---

.circleci/config.yml

ci: unblock unstable deployments

---

packages/aws-amplify-react-native/src/Auth/index.tsx

_Description of changes:_  This PR addresses an issue with the `aws-amplify-react-native` `withAuthenticator` HOC where, following the implementation outlined in our documentation, a user provided theme would be ignored. 

fix(aws-amplify-react-native): respect user provided theme in react-native withAuthenticator HOC

---

packages/datastore/src/sync/processors/sync.ts

Fixes a bug where the sync engine breaks when a sync query returns an `unauthorized` error. 
The expected behavior for DataStore is that an unauthorized error on a model should not break syncing for other models.
Currently, when a sync query request returns unauthorized, we get the following unhandled error
```
error on  TypeError: Cannot read property 'items' of null
```
on [this line](https://github.com/aws-amplify/amplify-js/blob/main/packages/datastore/src/sync/processors/sync.ts#L181). 
An unauthorized query response typically won't return any `items`, so this PR adds a check to see if `items` are defined before attempting to iterate over them. If not defined, we return an empty list (`items: []`) and `nextToken: null` to signal to the `retrievePage` method that it shouldn't attempt …

fix(@aws-amplify/datastore): handle sync query unauthorized

---

packages/auth/src/Auth.ts

chore(@aws-amplify/auth): fix typo in comment

---

packages/datastore/src/sync/processors/subscription.ts

e2e test: https://github.com/aws-amplify/amplify-js-samples-staging/pull/207

fix(@aws-amplify/datastore): keep syncing when subs disabled

---

.circleci/config.yml

Adding e2e test for DataStore working with disabled subscriptions to the pipeline
Successful run here: https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/7443/workflows/b62d22a8-1a77-428f-ae1a-b9b7c5415846

ci: add subs-disabled test

---

packages/datastore/__tests__/DataStore.ts
packages/datastore/__tests__/helpers.ts
packages/datastore/__tests__/storage.test.ts
packages/datastore/src/datastore/datastore.ts
packages/datastore/src/storage/adapter/AsyncStorageAdapter.ts
packages/datastore/src/storage/adapter/IndexedDBAdapter.ts
packages/datastore/src/storage/adapter/index.ts
packages/datastore/src/storage/storage.ts
packages/datastore/src/util.ts

https://github.com/aws-amplify/amplify-js/issues/7840
This PR changes the way we derive the correct update mutation input when using DataStore. Relying on Immer patches makes it difficult to resolve field data for connections and to include the correct fields when updating relational data. E.g., in the linked issue. Using a diff between the updated record and the previous record is a simpler and more reliable approach.

fix(@aws-amplify/datastore): update mutation input - diff with DB instead of patches

---

.github/actions/bundle-size-action/webpack/package.json
packages/api-graphql/src/GraphQLAPI.ts
packages/datastore/__tests__/mutation.test.ts
packages/datastore/src/sync/processors/mutation.ts

I didn't open a new issue, but you can reproduce the problem as follow:
1. Open a react native app on iOS.
2. Go to device's Settings > Developer > Network Link Conditioner > Enable and select 100% Loss.
3. Immediately switch back to the app, update a record.
4. Approximately 15 seconds later, you'll see a warning appearing on your app. (you can refer to the attachment below)
The consequences of not handling this error is that DataStore will dequeue this mutation and the record will never be updated to the server which is a big nono.
This PR will make sure mutation processor to perform retry if the mutation GraphQL returns `timeout of 0ms exceeded`.
By submitting this pull request, I confirm that my contribution is made under the terms of …

fix(@aws-amplify/datastore): Retry mutation if GraphQL timeout due to bad network condition.

---

.github/actions/bundle-size-action/webpack/package.json
packages/datastore/__tests__/outbox.test.ts
packages/datastore/__tests__/util.test.ts
packages/datastore/src/datastore/datastore.ts
packages/datastore/src/sync/index.ts
packages/datastore/src/sync/outbox.ts
packages/datastore/src/sync/processors/mutation.ts
packages/datastore/src/types.ts
packages/datastore/src/util.ts

Issue #, if available:
#7888, #7950, #8012
* Allow consecutive updates to work correctly with the changes in the [update mutation input PR](https://github.com/aws-amplify/amplify-js/pull/7935)
* Enable consecutive saves (other than updates). E.g.,
1. Create new record, then immediately update
2. Create new record, wait for sync to complete, then update 3 times consecutively
3. Create new record, then immediately delete
* Updated unit tests
* Added e2e tests for all these scenarios: https://github.com/aws-amplify/amplify-js-samples-staging/pull/211

fix(@aws-amplify/datastore): consecutive saves

---

packages/datastore/__tests__/util.test.ts
packages/datastore/src/util.ts

Add a type check to `util.objectsEqual` to ensure we're only attempting to compare 2 objects

fix(@aws-amplify/datastore): add additional type check to util.objectsEqual

---

packages/auth/__tests__/auth-attribute-test.ts
packages/auth/__tests__/auth-creds-test.ts
packages/auth/__tests__/auth-unit-test.ts
packages/auth/__tests__/hosted-ui.test.ts
packages/auth/__tests__/totp-unit-test.ts
packages/auth/package.json

* Enabled type-checking our auth unit tests
* Fixed most of the existing test file type errors by setting using `<any>`. We can gradually convert these to actual types if/when we decide to do so, but in many of the cases here where we're testing `private` methods and mocking method implementations, so `any` is the only viable solution.
* This will enable us to write new Auth unit tests that perform type-checking

chore(@aws-amplify/auth): enable type-checking in unit tests

---

packages/amazon-cognito-identity-js/__tests__/DateHelper.test.js

test(cognito-identity-test): add unit test coverage for DateHelper.js

---

packages/amazon-cognito-identity-js/__tests__/StorageHelper.test.js
packages/amazon-cognito-identity-js/src/StorageHelper.js

StorageHelper.js is a utility function that allows the other files within cognito-identity-js to interact with the local storage of a browser and these unit tests provide 100% coverage that the functions perform as expected. The removeItem(key) function within StorageHelper.js has some unexpected behavior in that it returns true regardless of if the key exists within the storage object.
After running yarn test, I was able to see full coverage for the changes

test(cognito-identity-test): adding unit test coverage to StorageHelper

---

packages/datastore/__tests__/DataStore.ts
packages/datastore/__tests__/outbox.test.ts
packages/datastore/__tests__/storage.test.ts
packages/datastore/__tests__/util.test.ts
packages/datastore/src/datastore/datastore.ts
packages/datastore/src/storage/adapter/AsyncStorageAdapter.ts
packages/datastore/src/storage/adapter/IndexedDBAdapter.ts
packages/datastore/src/storage/adapter/index.ts
packages/datastore/src/storage/storage.ts
packages/datastore/src/sync/index.ts
packages/datastore/src/sync/outbox.ts
packages/datastore/src/util.ts

Re-work of https://github.com/aws-amplify/amplify-js/pull/8000
Addresses issues in comments
Issue #, if available:
#7888, #7950, #8012
* Allow consecutive updates to work correctly with the changes in the [update mutation input PR](https://github.com/aws-amplify/amplify-js/pull/7935)
* Enable the follow workflows:
1. Create new Post, then immediately update
2. Create new Post, then immediately update with a different field
3. Create new Post, wait for sync to complete, then update 10 times consecutively
4. Create new Post, then immediately delete
5. Create new Post with Comment, reassign Comment to a different Post
6. Consecutive updates with conditions
* Updated unit tests
* Added e2e tests for all these scenarios: https://github.com/aws-amplify/amplify-js-samples-staging/pull/212
By …

fix(@aws-amplify/datastore): consecutive saves 2

---

packages/datastore/src/sync/outbox.ts

Adds support for one more use case to the work in https://github.com/aws-amplify/amplify-js/pull/8038
Create Post, then create another Post and immediately update another field
e2e test PR updated to include this scenario.

fix(@aws-amplify/datastore): handle merging queued create with incoming update

---

packages/amazon-cognito-identity-js/__tests__/CognitoUser.test.js
packages/amazon-cognito-identity-js/__tests__/CognitoUserPool.test.js
packages/amazon-cognito-identity-js/__tests__/CognitoUserSession.test.js
packages/amazon-cognito-identity-js/__tests__/constants.js
packages/amazon-cognito-identity-js/src/CognitoUser.js

Adding unit test coverage and changing constants to include an invalidUserSession such that CognitoUser().verifySoftwareToken() can go through all cases. Ensured that all other dependencies continued to change despite the change in constants.
yarn test and all other tests went back to the expected result.

test(cognito-identity-js): adding unit coverage to associate software and updating constants

---

scripts/build.js

Force generating TypeScript source maps when building the library in **watch mode**. 
Currently, when linking the library into a sample app, we can only see the transpiled JS code if we inspect the code in the Sources tab in Dev Tools. This makes it very difficult to debug library issues.
This change allows us to see the original TypeScript code, as well as set breakpoints and step through, inspect values, etc.
The change only applies when we build the lib in **watch mode** e.g., `yarn build:watch`, `yarn build:esm:watch`, `yarn build:watch --scope @aws-amplify/core`, etc. 
The standard build script `yarn build`, i.e., the one we use in CI is unaffected by this.
n/a
1. Link aws-amplify in sample app
2. Run `yarn build:watch` from the library dir
3. Go to dev tools > sources; open a …

chore: generate TS source maps with build:watch

---

packages/amplify-ui-components/src/components/amplify-input/amplify-input.tsx

On Vue 3 specifically, autofill with `amplify-auth-conatainer` was failing because it was trying to get the reference to the `input` before it has materialized. This PR moves this logic to `componentDidLoad` so that `autofill` is attempted after the component is fully loaded. Also adds a basic null check.
follows up #8181 
Did a `yarn link` with a vue 3 authenticator sample and validated that the inputs get autofilled.

fix(@aws-amplify/ui-components): Get autofill data on `componentDidLoad`

---

packages/amazon-cognito-identity-js/README.md
packages/amazon-cognito-identity-js/src/CognitoUser.js
packages/auth/src/Auth.ts

PR #2707 from Feb. 2019 (two years ago) indicated that `getMFAOptions()` was not returning meaningful values. Currently, [`MFAOptions`](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_GetUser.html#CognitoUserPools-GetUser-response-MFAOptions) is no longer supported *at all*. Hence, the method needs to be deprecated.
The [corresponding method in `auth`](https://github.com/aws-amplify/amplify-js/blob/main/packages/auth/src/Auth.ts#L652-L658) is *already* deprecated.
Two incidents where customers were expecting this method to behave meaningfully: #2707, #3330
No functional changes.
Notably, [tests do still exist for these methods](https://github.com/aws-amplify/amplify-js/search?q=getMFAOptions&type=code). Since these methods are simply marked as deprecated …

chore(amazon-cognito-identity-js): deprecate getMFAOptions

---

packages/amplify-ui-react/__tests__/withAuthenticator-test.tsx
packages/amplify-ui-react/src/withAuthenticator.tsx

support passing props to the wrapped component of withAuthenticator HOC.
Fixes #8173
- add a tiny unit test, run yarn run test --scope @aws-amplify/ui-components
- test the customer [repro](https://github.com/ctjlewis/aws-amplify-test/commit/00cbf31cb5dc900b50004e11909fa7166e5a4cb6)

#8173 UI react with authenticator props

---

packages/datastore/__tests__/AsyncStorageAdapter.test.ts
packages/datastore/__tests__/IndexedDBAdapter.test.ts
packages/datastore/__tests__/helpers.ts
packages/datastore/src/storage/adapter/AsyncStorageAdapter.ts
packages/datastore/src/storage/adapter/IndexedDBAdapter.ts
packages/datastore/src/types.ts

Allow deleting records that have a **Has One** relation. Perform a cascading delete.
**Note:** This library bugfix relies on a recent Codegen change, and in order to work correctly, [this feature flag](https://docs.amplify.aws/cli/reference/feature-flags#useAppsyncModelgenPlugin) needs to be set to `true`. Starting 5/1 this will be the default CLI/Codegen behavior for new projects.
https://github.com/aws-amplify/amplify-js/issues/6560
* Created unit tests for both of the JS Storage Adapters
* Manually validated in a sample
* Created an e2e test: https://github.com/aws-amplify/amplify-js-samples-staging/pull/216
~Relevant documentation is changed or added (and PR referenced)~ N/A
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …

fix(@aws-amplify/datastore): fix hasOne delete

---

packages/auth/__tests__/auth-unit-test.ts
packages/auth/src/Auth.ts

- Ignores case when converting a string representing a boolean in user attributes to a boolean value. This allows the user attributes `email_verified` and `phone_number_verified` to have the value `True` written in Cognito without breaking the sign in flow.
[8205](https://github.com/aws-amplify/amplify-js/issues/8205)
I validated the changes by adding unit tests.

#8205 Makes conversion of 'true' string to boolean for user attributes case insensitive

---

.circleci/config.yml

Configures CircleCI to run new integration tests used to capture various errors caused by duplicate packages. Please see [docs PR 3215](https://github.com/aws-amplify/docs/pull/3135) and [js PR 8083](https://github.com/aws-amplify/amplify-js/pull/8083) for documentation regarding this error.
[docs PR 3215](https://github.com/aws-amplify/docs/pull/3135)
[js PR 8083](https://github.com/aws-amplify/amplify-js/pull/8083)
Ran an integration test workflow in our CircleCI pipeline to ensure config changes properly run the `duplicate-packages` Cypress tests:
https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/7763/workflows/8240bb12-7cca-49eb-9c9f-9890116371cc
- ~Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contribution …

Add configuration for duplicate-packages integ tests

---

packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx

Fix the memory leak issue by using the correct lifecycle method to remove event listener when component is unmounted from DOM.
It seems there is no such lifecycle hook called `componentWillUnload`. Based on the stencil doc https://stenciljs.com/docs/component-lifecycle#disconnectedcallback, it should be `disconnectedCallback`.
Fixes #6840
- run it locally to see the lifecycle is called and `handleExternalAuthEvent` is being removed from Hub, and thus fix the memory leak issue.

correct the unmount lifecyle for amplify-authenticator

---

packages/datastore/src/sync/processors/subscription.ts

When a subscription fails to connect due to an authorization error, we don't need to throw an error since the subscription cleanup is already taking place and there is no place for a customer to catch this error directly. Instead, we can just log a warning with the message to let the developer know that the authorization failed.

fix(@aws-amplify/datastore): log subscription error instead of throwing

---

packages/datastore/__tests__/helpers.ts
packages/datastore/__tests__/storage.test.ts
packages/datastore/src/storage/storage.ts
packages/datastore/src/types.ts
packages/datastore/src/util.ts

Include all fields that comprise a composite key in the update mutation request input if any of those fields was changed
For example:
```gql
type Post
@model
@key(name: "titleSort", fields: ["title", "created", "sort"]) {
id: ID!
title: String!
description: String
created: String
sort: Int
}
```
Performing the following update:
```js
await DataStore.save(Post.copyOf(post, updated => {
updated.title = 'Updated';
}));
```
Should include `title`, `created`, and `sort` in the GraphQL mutation input even though the latter 2 fields are unchanged.
#7714 
~- [ ] Relevant documentation is changed or added (and PR referenced)~

fix(@aws-amplify/datastore): updates with composite keys

---

packages/amplify-ui-vue/tsconfig.json

We're getting a [build error](https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/7921/workflows/020a3b7c-d11e-4075-b47f-71f764afa117/jobs/41430) in this package due to a change in the types of an upstream dependency. Since we're not actually utilizing any of these dependencies in the source of this package, I'm adding `types: []` to ignore the external types when building ui-vue.
* built all the packages in the repo locally without errors

fix(@aws-amplify/ui-vue): exclude external types in tsconfig

---

packages/datastore/__tests__/storage.test.ts
packages/datastore/src/storage/storage.ts

A customer pointed out that if we define the value of a model's field as `undefined`, the mutation doesn't persist. However, if passed as `null`, it would work fine. So this one-liner just checks to see if a pre-existing field's passed value is `undefined` and coerces that value to `null`.
https://github.com/aws-amplify/amplify-js/issues/7565
I tested the changes linked to a local sample app. Screenshots attached.
*Example* (with requested change) of explicitly setting the value of an existing field to `undefined`:
*Example* (with requested change) of explicitly setting the value of a NEW field - (doesn't coerce to `null` because the key doesn't exist on the model yet):

fix(@aws-amplify/datastore): coerce undefined field values to null

---

packages/amplify-ui-storybook/package.json

`yarn test` on local dev was hanging because `ui-storybook` tests were running on watch mode. Passing `CI=true` resolves this. There are other workarounds (https://github.com/facebook/create-react-app/issues/6899#issuecomment-510115970), but passing `CI=true` seems the cleanest way.
Ran `yarn test` locally.

chore(@aws-amplify/ui-storybook) Add `CI=true` to storybook test script

---

.github/actions/bundle-size-action/cra/package.json
.github/actions/bundle-size-action/next/package.json
.github/actions/bundle-size-action/webpack4/package.json

Some bundle size checks are failing after upgrading to `crypto-js@4`. This PR bumps those limits to prevent us from becoming blind to other bundle size spikes. A GH issues will be created for us to re-examine our usage of `crypto-js@4` and try to tamp bundle size back down.
No changes to library codebase. Tested new bundle limits with `rm -rf node_modules && yarn && yarn calculate` for each `bundle-size-action`.

chore: bump bundle limits for crypto-js@4 bump

---

packages/datastore/src/datastore/datastore.ts
packages/datastore/src/sync/processors/mutation.ts

The default error and conflict handler in DataStore were getting overwritten and set to `undefined`. This was causing console errors when mutation errors and unhandled mutation conflicts occurred (unless the handlers were explicitly set via `DataStore.configure`): 
> `this.errorHandler` is not a function
This PR fixes the default behavior, preventing the default handlers from being overwritten
Also: allow the `errorHandler` to be async (like `conflictHandler`) so that customers can perform custom async handling logic if needed before the MutationProcessor attempts to process the next record in the queue.
N/A
Tested in a sample app. No longer getting the `this.errorHandler` is not a function error when a custom error handler is not explicitly set via `DataStore.configure`. Same goes for …

fix(@aws-amplify/datastore): fix default error/conflict handler

---

packages/datastore/src/sync/datastoreConnectivity.ts

Currently, unsubscribing the Reachability observer in the DataStoreConnectivity class does not stop it from continuing to send messages that are consumed by the SyncEngine. This is due to a `setTimeout` that does not get canceled upon calling `DataStoreConnectivity.unsubcribe()`. (See https://github.com/aws-amplify/amplify-js/blob/main/packages/datastore/src/sync/datastoreConnectivity.ts#L46-L61 for context). 
This results in the `setTimeout` callback continuing to send messages to the SyncEngine, causing it to attempt to restart at inappropriate times. Additional context is in the linked issue, but here's a summary:
1. Network connectivity is lost
2. `DataStore.stop` is called as a result of some user action shortly thereafter (within 5 seconds of network connectivity loss)
3. SyncEngine …

fix(@aws-amplify/datastore):  correct reachability unsubscribe behavior

---

packages/datastore/__tests__/helpers.ts
packages/datastore/__tests__/mutation.test.ts
packages/datastore/__tests__/storage.test.ts
packages/datastore/__tests__/util.test.ts
packages/datastore/src/datastore/datastore.ts
packages/datastore/src/storage/storage.ts
packages/datastore/src/sync/processors/mutation.ts
packages/datastore/src/types.ts
packages/datastore/src/util.ts

Expands on this PR: https://github.com/aws-amplify/amplify-js/pull/8253
If the model has a custom primary key defined, always include it in the update and delete mutation input.
N/A
* Added and ran unit tests 
* Validated against sample apps

feat(@aws-amplify/datastore): include custom pk in update/delete mutations

---

packages/amazon-cognito-identity-js/package.json
packages/core/package.json

Including an RN peer dependency in the package.json of @aws-amplify/core prevents npm@7 from hoisting @aws-amplify/core into e.g., my-app/node_modules/@aws-amplify/core. The RN peer deps cause /core to conflict with newer versions of React, since npm@7 will attempt to auto-install peer deps. 
This PR removes RN-specific peer deps from core and amazon-cognito-identity-js.
https://github.com/aws-amplify/amplify-js/issues/8333
* Published to local verdaccio registry; installed into CRA app with --use-npm & npm@7; confirmed /core is getting hoisted correctly

fix: remove RN-specific peerDeps to correctly hoist core in npm@7

---

packages/aws-amplify-angular/src/components/interactions/chatbot/chatbot.component.core.ts

Remove unneeded `util` import that's causing a build error in Angular 12
https://github.com/aws-amplify/amplify-js/issues/8347

fix(aws-amplify-angular): remove util import to fix ng-12 build error

---

packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx

Removes hostedui redirection check from `amplify-authenticator`. This is based on @ericclemmons's observation here: https://github.com/aws-amplify/amplify-js/issues/7081#issuecomment-845277842. 
Fixes #7081
I don't think this needs to be manually validated. `checkUser` is **required** to initiate the correct auth state for the `authenticator`. We should run `checkUser` unconditionally, which is what this PR does. 

fix(@aws-amplify/ui-components): remove hosted ui check

---

packages/amplify-ui-components/src/components.d.ts
packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx
packages/amplify-ui-components/src/components/amplify-authenticator/readme.md

This PR updates the TypeScript definition for our `initialAuthState` to include `AuthState.ForgotPassword` as an accepted initial state. Interestingly, we already have a test covering this use.
https://github.com/aws-amplify/amplify-js/issues/7668
Tested locally in a sample app. We already have a unit test for this specific case of setting `ForgotPassword` as the initial state.

chore: updating typescript definition for initialAuthState

---

.circleci/config.yml

- Splitting up DataStore multi-auth tests so CircleCI workflows will be faster.
NOTE: https://github.com/aws-amplify/amplify-js-samples-staging/pull/235 will need to be merged before this.

chore: split up DataStore multi-auth e2e tests

---

packages/amplify-ui-components/src/components/amplify-sign-in/__snapshots__/amplify-sign-in.spec.ts.snap
packages/amplify-ui-components/src/components/amplify-sign-in/amplify-sign-in.scss
packages/amplify-ui-components/src/components/amplify-sign-in/amplify-sign-in.tsx

This change detects if the `hideSignUp` property is enabled on the `AmplifySignIn` component and, if so, will render the "Sign In" button with the full width of the component container.
Sreenshot - 
https://github.com/aws-amplify/amplify-js/issues/7564
Testing locally in a sample app.

feat: make sign in button full width if not sign up button present

---

packages/amplify-ui-components/src/components/amplify-button/amplify-button.scss
packages/amplify-ui-components/src/components/amplify-button/readme.md

Adds a border radius prop to the `amplify-button` scss.
Original pull request here - https://github.com/aws-amplify/amplify-js/pull/7904
^^ comes from another contributor. However, the PR hasn't been updated with the requested changes and it's been a few months. I'm resubmitting it now so we can get it merged and knock off an issue in our milestone.

feat: adding border radius to amplify-button

---

packages/amplify-ui-components/src/components/amplify-require-new-password/amplify-require-new-password.spec.ts
packages/amplify-ui-components/src/components/amplify-require-new-password/amplify-require-new-password.tsx

This PR basically takes over an older PR that was submitted, but not updated, a few months ago - https://github.com/aws-amplify/amplify-js/pull/7802
It fixes the phone number formatting on the "require new password" form. Description from the other PR - 
""
This issue occurs when creating a new cognito user with temporary password and without a phoneNumber. If phoneNumber is an required field, the amplify-require-new-password component will contain a dialCode dropdown and a phoneNumber input. Both the dropdown and input field overrides the required phone_numberfield, and only way to proceed is to enter the entire dialCode + phoneNumber in the input field.
This issue was fixed using same helper functions handlePhoneNumberChange and composePhoneNumberInput as used in components (sign-up, …

Amplify UI components/fix phone number input new pw

---

packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.spec.ts
packages/amplify-ui-components/src/components/amplify-confirm-sign-in/amplify-confirm-sign-in.tsx

Ref. https://github.com/aws-amplify/amplify-js/pull/8255#issuecomment-866642875
Cc: @hannesj
Including handleInputChange in amplify-confirm-sign-in fields only when not specified
https://github.com/aws-amplify/amplify-js/pull/8255#issuecomment-866642875

fix(@aws-amplify/ui-components): including handleInputChange in amplify-confirm-sign-in fields only when not specified

---

packages/datastore/__tests__/DataStore.ts
packages/datastore/__tests__/helpers.ts
packages/datastore/src/datastore/datastore.ts
packages/datastore/src/types.ts

(updated PR due to messy git/branch issues)
--------
[start of original PR]
Currently, if the `"addtimestampfields": true` flag is defined in an Amplify project via `cli.json`, when a user runs `amplify codegen models`, the outputted code in `schema.js` will have these timestamp fields added (with values managed by AppSync):
```js
"createdAt": {
"name": "createdAt",
"isArray": false,
"type": "AWSDateTime",
"isRequired": false,
"attributes": [],
"isReadOnly": true
},
"updatedAt": {
"name": "updatedAt",
"isArray": false,
"type": "AWSDateTime",
"isRequired": false,
"attributes": [],
"isReadOnly": true
}
```
Codegen has been updated to add these fields ([aws-amplify/amplify-codegen#114](https://github.com/aws-amplify/amplify-codegen/pull/114)) but the current implementation of Amplify JS …

feat(@aws-amplify/datastore): expose timestamp fields and prevent writing to read-only fields

---

packages/amazon-cognito-identity-js/src/Client.js

Rewrite the `retry` method in `amazon-cognito-identity-js` as promised based, to avoid the implicit dependency on the `regeneratorRuntime` polyfill.
This is to fix #8514, a breaking change reported by the customer. The issue is caused by a recent change in `amazon-cognito-identity-js`, where `aysnc` and `await` syntax is [used](https://github.com/aws-amplify/amplify-js/blob/main/packages/amazon-cognito-identity-js/src/Client.js#L177-L201) for the first time in that package.
It creates an implicit dependency on `regeneratorRuntime` in all its built code (umd/es/commonjs), and affect downstream packages like auth.
- `amazon-cognito-identity-js` was written long ago with traditional nodejs callback style + promise.
- It was written in ES6 and transpiled to ES5 by babel using …

rewrite retry as promise based

---

.circleci/config.yml

Re-enabling the React Native Android tests.
The original issue was from a combination of the Macos version of the CircleCI executor, and a bug in Android emulator 30.7.4 (see: https://issuetracker.google.com/issues/191805460)
The issue has been fixed on July 1st, I manually triggered a CircleCI deploy and the tests ran successfully. https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/8329/workflows/c4eecd81-d0c3-4beb-8317-306edfb736b8
Manually triggered a CircleCI deploy on another branch.

re-enable rn android tests

---

packages/amplify-ui-vue/tsconfig.json
packages/aws-amplify/__tests__/exports-test.ts
packages/aws-amplify/src/index.ts
packages/core/__tests__/ConsoleLogger-test.ts
packages/core/__tests__/Providers/AWSCloudWatchProvider-test.ts
packages/core/__tests__/parseMobileHubConfig-test.ts
packages/core/package.json
packages/core/src/Logger/ConsoleLogger.ts
packages/core/src/Logger/logger-interface.ts
packages/core/src/Parser.ts
packages/core/src/Providers/AWSCloudWatchProvider.ts
packages/core/src/Providers/index.ts
packages/core/src/Util/Constants.ts
packages/core/src/Util/index.ts
packages/core/src/index.ts
packages/core/src/types/types.ts
packages/pushnotification/tsconfig.json

Reverting the "revert" of the `core/cloudwatch-logging` release. https://github.com/aws-amplify/amplify-js/pull/8412
Feature has been approved by AppSec
Also adding in `"es2018.asynciterable", "es2018.asyncgenerator"` to fix build failure
n/a
`yarn test`

feat: core/cloudwatch-logging

---

packages/amazon-cognito-identity-js/__tests__/CognitoUser.test.js
packages/amazon-cognito-identity-js/src/CognitoUser.js

This is to follow the previous fix(https://github.com/aws-amplify/amplify-js/pull/5394) for the sibling call `updateAttributes`, to update the cached data if delete action succeed.
It calls the [`getUserData`](https://github.com/aws-amplify/amplify-js/blob/main/packages/amazon-cognito-identity-js/src/CognitoUser.js#L1251), which encapsulate the logic of refreshing local cache. Notice it will fire another network request to fetch most updated data from server side, because
1. delete api does not return anything if succeed
2. it is not easy to capture all side effects without talking to the server side. For example, deleting `email` will toggle `email_verified` to `false`.
2. local cached data can be in different places (localStorage or  in memory)
This is a required fix before we can merge …

 refresh cached user after deleting attributes

---

packages/amplify-ui-components/src/components/amplify-forgot-password/amplify-forgot-password.tsx

Empties `newFormFields` whenever we call `buildFormFields` so that we don't add duplicate fields.
Closes #8629.
Validated with local linking.
Not sure why this isn't very reproducible on 1.2.7 (likely some nuance of when these components get re-rendered based on the `newFormFields`), but I confirmed internally that this patch prevents the array from getting duplicate entries.

Empty `newFormfFields` array on rebuild

---

packages/api-graphql/__tests__/GraphQLAPI-test.ts
packages/api-graphql/src/GraphQLAPI.ts
packages/api-graphql/src/types/index.ts
packages/datastore/__tests__/authStrategies.test.ts
packages/datastore/__tests__/helpers.ts
packages/datastore/__tests__/subscription.test.ts
packages/datastore/src/authModeStrategies/multiAuthStrategy.ts
packages/datastore/src/datastore/datastore.ts
packages/datastore/src/sync/processors/mutation.ts
packages/datastore/src/sync/processors/subscription.ts
packages/datastore/src/sync/processors/sync.ts
packages/datastore/src/sync/utils.ts
packages/datastore/src/types.ts
packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider.ts

note: opening this as a branch in upstream in order to run e2e tests. 
Adds support for Lambda Authorizers for AppSync APIs to the API category and DataStore.
* refactored/DRY'd some of our existing unit tests
```js
let authToken = 'some-auth-token-string'; // developer-managed token
// if AWS_LAMBDA is the default auth type, i.e., aws_appsync_authenticationType: 'AWS_LAMBDA':
const blogs = await API.graphql({query: queries.listBlogs, authToken: authToken});
// if you have a different default auth type configured:
const blogs = await API.graphql({query: queries.listBlogs, authMode: 'AWS_LAMBDA', authToken: authToken});
```
```js
let authToken = 'some-auth-token-string'; // developer-managed token
DataStore.configure({
authProviders: {
functionAuthProvider: () => (
{
token: authToken,
}
), …
```

Lambda authorizers support (API, DataStore, PubSub)

---

.circleci/config.yml

Disabling the android multipart e2e test again for now to [unblock the pipeline](https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/8449/workflows/7ed93c8b-c593-4bf9-a012-ce4b9ab65fe6/jobs/48774/steps), will re-enable once we've solved the issue with Android Emulator in CCI.

chore: disable rn android multipart e2e test

---

packages/core/src/Parser.ts
packages/geo/__tests__/Geo.test.ts
packages/geo/__tests__/Providers/AmazonLocationServicesProvider.test.ts
packages/geo/src/Geo.ts
packages/geo/src/Providers/AmazonLocationServicesProvider.ts
packages/geo/src/types/Geo.ts
packages/geo/src/types/Provider.ts

Geo milestone 1 - PR 4/6
Adds:
- getAvailableMaps
- getDefaultMap
Pulls this data from `aws-exports` so only to get maps that were created with the Amplify CLI.
- Builds and unit tests pass
- Validated using PoC application
*Documentation will be added in a follow-up PR*

feat(Geo): getAvailableMaps and getDefaultMap - Geo milestone 1 - PR 4

---

packages/auth/src/Auth.ts

- Fixed typo on `disableSMS` method name header
Just checking the comment

Auth.ts - Fixed typo

---

packages/core/__tests__/parseMobileHubConfig-test.ts
packages/geo/__tests__/Geo.test.ts
packages/geo/__tests__/Providers/AmazonLocationServicesProvider.test.ts
packages/geo/__tests__/data.ts
packages/geo/src/Providers/AmazonLocationServicesProvider.ts
packages/geo/src/types/Geo.ts

Matches the update on Amplify CLI to use `search_indices` instead of `place_indexes`.
Updated unit tests and ran it through my sample application

chore(geo): update to use search_indices

---

packages/geo/src/types/Geo.ts

Reverse Longitude and Latitude as they were in the wrong order. This still passed everything successfully through to the AWS-SDK, but the types were improperly labeled.
https://github.com/aws-amplify/amplify-js/issues/8690
https://github.com/aws-amplify/amplify-js/issues/8691
All tests pass.

feat(Geo): add Geo category initial scaffolding - Geo milestone 1 - PR 1/6 (#8615)

---

packages/auth/src/OAuth/OAuth.ts

It passes in the redirectUri after sign out which is in parity with the urlOpener signature when sign in. 
The difference in parameters are evident between these two lines: 
Sign in, https://github.com/aws-amplify/amplify-js/blob/1e0887bdc45e178f04229c888051ecf10d2bfabc/packages/auth/src/OAuth/OAuth.ts#L117
Sign out, https://github.com/aws-amplify/amplify-js/blob/1e0887bdc45e178f04229c888051ecf10d2bfabc/packages/auth/src/OAuth/OAuth.ts#L294 
https://github.com/aws-amplify/amplify-js/issues/8673
Tested it on ios simulator 

fix(@aws-amplify/auth): passing redirectUri to the urlOpener after signOut 

---

packages/amplify-ui-components/src/components/amplify-authenticator/amplify-authenticator.tsx

This looks another copy and paste from legacy authenticator that is no longer needed. I checked the repo but I couldn't find any place where `AUTHENTICATOR_AUTHSTATE` is set, so this is safe to remove.

fix(@aws-amplify/ui-components): Remove local storage check

---

packages/geo/__tests__/Geo.test.ts
packages/geo/__tests__/Providers/AmazonLocationServicesProvider.test.ts
packages/geo/src/Providers/AmazonLocationServicesProvider.ts
packages/geo/src/types/AmazonLocationServicesProvider.ts
packages/geo/src/types/index.ts

- Add new `AmazonLocationServiceMapStyle` type
- Add `region` to this type and return in the `MapStyle` objects from the `AmazonLocationServicesProvider`
Published to Verdaccio locally and used it through `maplibre-gl-js-amplify` with a Demo application:

feat(geo): add region to Amazon Location Service MapStyle

---

packages/amazon-cognito-identity-js/__tests__/CognitoUser.test.js
packages/amazon-cognito-identity-js/index.d.ts
packages/amazon-cognito-identity-js/src/CognitoUser.js
packages/auth/src/Auth.ts

The function `forgotPasswordSubmit` does not return anything on successful password reset. This PR adds a 'SUCCESS' response when the password reset is successful. 
The `forgotPasswordSubmit` function is a part of the forgot password flow where users get a verification code (email or SMS ..) and provide that code along with the new password to the forgotPasswordSubmit function to reset the password.   
#8453 
- linked a test app with my local AmplifyJS project with yarn linking and verified that we get 'SUCCESS' response when successfully submitting the verification code and the new password.
- `yarn test` passes

feat(@aws-amplify/auth): Add a 'SUCCESS' response on successful call to forgotPasswordSubmit

---

packages/datastore/src/storage/adapter/getDefaultAdapter/index.ts
packages/datastore/src/types.ts

1. Remove conditional require from `getDefaultAdapter` for compatibility with Vite, etc.
2. Align type for `functionAuthProvider` with expected value (unrelated to 1.)
https://github.com/aws-amplify/amplify-js/issues/7901
* Tested against web and RN sample apps locally
* Checked bundle size pre/post change to ensure this change doesn't add bloat

fix(@aws-amplify/datastore): remove conditional require

---

.circleci/config.yml
packages/datastore/src/sync/utils.ts

We added automatic JSON parsing for AWSJSON fields in the latest version of DataStore (3.4.0). This change inadvertently affected non-model Types. 
This PR corrects that behavior, only stringifying fields of type AWSJSON.
* unit tests
* local sample app with non-model types and AWSJSON fields
* running e2e tests in CircleCI. Successful run: https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/8632/workflows/8c7e7f80-a713-4cc7-9707-ccd247c717fe

fix(@aws-amplify/datastore): only stringify nested AWSJSON in mutation event

---

packages/api-rest/package.json
packages/storage/package.json

Axios had a security vulnerability on version 0.21.1 and they release a patch that would handle a denial of service attacked based on weak regular expression rules. This patch has been released by Axios yesterday.
[Axios pull request ](https://github.com/axios/axios/pull/3980), [issues from customers](https://github.com/aws-amplify/amplify-js/issues/8852)
I deleted all the node modules in the packages that were using the old version of axios and ran the unit tests with axios 0.21.4 and all the tests pass as before.
- [n/a] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [n/a] Relevant documentation is changed or added (and PR referenced)
By submitting this pull request, I confirm that my contribution is made …

chore(fix axios version): patch security vuln for api-rest and storage

---

packages/geo/webpack.config.js

Update webpack config to mark amplify core as external such that core doesn't get duplicated.
Built the bundles and tested in a barebone html website.

fix(@aws-amplify/geo): Update webpack config to mark core as external

---

packages/geo/__tests__/Geo.test.ts
packages/geo/__tests__/Providers/AmazonLocationServiceProvider.test.ts
packages/geo/src/Providers/AmazonLocationServiceProvider.ts
packages/geo/src/types/Geo.ts

Adds better error handling to tell developers what's happening and what to do to solve the issue
Unit tests

chroe(geo): better error handling when missing location service resources

---

packages/amazon-cognito-identity-js/src/CognitoUserPool.js

- Check the User Pool ID for a max length of 55 (as per https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UserPoolType.html#CognitoUserPools-Type-UserPoolType-Id)
- Fix the regex used to validate the User Pool ID to remove the backtracking (see: https://owasp.org/www-community/attacks/Regular_expression_Denial_of_Service_-_ReDoS)
N/A
Ran tests

fix(amazon-cognito-identity-js): Fix UserPoolId validation ReDoS

---

packages/analytics/src/Providers/AWSPinpointProvider.ts

We have customer complaining about the number of endpoints reaching maximum limits (https://github.com/aws-amplify/amplify-js/issues/6896, https://github.com/aws-amplify/amplify-js/issues/7251). After investigation, we notice this issue is due to the local cached endpoint id being deleted, thus amplify recreates a new one and assign it to the same user.
The cached endpoint id might be deleted manually by devTool during development, or might due to using a different browser (e.g. incognito mode), which we cannot prevent.
However, we notice customers report that the issue also happens in production. A deep dive reveals that the current endpoint id is cached with the default [3 days TTL](https://github.com/aws-amplify/amplify-js/blob/main/packages/cache/src/Utils/CacheUtils.ts#L23), meaning …

fix: update TTL of the cached endpoint id

---

packages/analytics/__tests__/Providers/AWSPinpointProvider-unit-test.ts
packages/analytics/src/Providers/AWSPinpointProvider.ts

Customers are still reporting the default endpoints Amplify created reaching the maximum limit, especially, during browser update.
The default endpoint we create does not have any channelType, and is used for collecting web analytics data. Currently, Pinpoint does not support a specific channel type for web analytics.
After discussion with service team, this change is to set the default channel type to "PUSH". This legacy channel type is not used for push notification, and will auto evict if reach maximum limits.
#7251
#6896
- localbrowser
- verify with service team
- [x ] PR description included
- [x ] `yarn test` passes
- [ x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
By submitting this pull request, I …

fix: default to PUSH channel type for web analytics

---

packages/aws-amplify-react-native/src/InAppMessaging/components/BannerMessage/types.ts
packages/aws-amplify-react-native/src/InAppMessaging/components/FullScreenMessage/FullScreenMessage.tsx
packages/aws-amplify-react-native/src/InAppMessaging/components/FullScreenMessage/index.ts
packages/aws-amplify-react-native/src/InAppMessaging/components/FullScreenMessage/styles.ts
packages/aws-amplify-react-native/src/InAppMessaging/components/FullScreenMessage/types.ts
packages/aws-amplify-react-native/src/InAppMessaging/components/index.ts
packages/aws-amplify-react-native/src/InAppMessaging/components/types.ts
packages/aws-amplify-react-native/src/InAppMessaging/hooks/useInAppMessageImage/types.ts
packages/aws-amplify-react-native/src/InAppMessaging/hooks/useInAppMessageImage/useInAppMessageImage.ts
packages/aws-amplify-react-native/src/InAppMessaging/index.ts

Add In-App Messaging `FullScreenMessage` React Native UI component for rendering InAppMessage payloads created in the Amazon Pinpoint console:
**Examples**

feat(in-app-messaging): add FullScreenMessage component

---

packages/storage/src/providers/AWSS3Provider.ts

Add `useAccelerateEndpoint` to the other `createNewS3Client` function (it was only enabled in `AWSS3ManagedUpload`).
fixes #9143
`yarn test`

fix(@aws-amplify/storage): add useAccelerateEndpoint to create s3client

---

packages/datastore-storage-adapter/__tests__/SQLiteUtils.test.ts
packages/datastore-storage-adapter/src/SQLiteAdapter/SQLiteUtils.ts

Don't attempt to enforce non-nullability of model fields in SQL, since relational data for those do not get saved in the fields themselves locally. 
For example:
```gql
type Post @model {
comments: [Comment]! @connection
}
type Post @model {
comments: [Comment!] @connection
}
```
Should **not** result in a `NOT NULL` constraint to be added to the `comments` column, as it will always be empty in the local store.
https://github.com/aws-amplify/amplify-js/issues/9128

fix(datastore-storage-adapter): don't enforce required model fields in sql

---

packages/aws-amplify-react-native/src/InAppMessaging/components/hooks/useMessageImage/useMessageImage.ts
packages/aws-amplify-react-native/src/InAppMessaging/components/hooks/useMessageImage/utils.ts

- only call `setImageDimensions` on success or error of size retrieval/prefetching of image
- rename `getImageDimensions` to `getLayoutImageDimensions`

fix(in-app-messaging): prevent extraneous setImageDimensions call

---

packages/core/package.json

Reverts aws-amplify/amplify-js#9189 since there are existing issues and breaking changes in the sdk version ^3.40.0

revert(aws-sdk):chore:update @aws-sdk/client-cloudwatch-logs version in core"

---

packages/analytics/src/Analytics.ts

This PR adds Hub dispatch events to Analytics startSession and stopSession which do not invoke Analytics.record and instead send their events through private functions directly. The autoTrack function of Analytics does use Analytics.record so does not require any changes.
N/A
Tested locally with test app

fix: Update Analytics to report session start/stop over Hub

---

packages/datastore/__tests__/indexeddb.test.ts
packages/datastore/__tests__/model.ts
packages/datastore/__tests__/schema.ts
packages/datastore/src/datastore/datastore.ts

Many to Many LazyLoading implementation
Unit tests

feat(@aws-amplify/datastore): lazy loading Many to Many implementation

---

packages/aws-amplify-react-native/src/InAppMessaging/components/constants.ts
packages/aws-amplify-react-native/src/InAppMessaging/components/hooks/useMessageProps/utils.ts
packages/aws-amplify-react-native/src/InAppMessaging/components/types.ts

- apply a default `opacity` on press events for in-app UI buttons
- add support for custom press event style
NA
Manually tested in sample app

feat(in-app-messaging): add default and support for custom feedback on button press events

---

packages/datastore/src/util.ts

- revert `pretty-quick` formatting changes in _datastore/src/util.ts_ that were caused by merging from `main` , changes are causing `yarn test` to fail as the prettier rules applied by `pretty-quick` are conflicting with the `tslint` rules
NA
`yarn test`

chore(in-app-messaging): revert pretty-quick formatting changes in datastore/src/util.ts

---

.prettierrc.js
packages/datastore-storage-adapter/src/SQLiteAdapter/SQLiteAdapter.ts
packages/datastore-storage-adapter/src/SQLiteAdapter/SQLiteUtils.ts
packages/datastore-storage-adapter/src/SQLiteAdapter/types.ts
packages/datastore/__tests__/AsyncStorageAdapter.test.ts
packages/datastore/__tests__/IndexedDBAdapter.test.ts
packages/datastore/__tests__/helpers.ts
packages/datastore/src/storage/adapter/AsyncStorageAdapter.ts
packages/datastore/src/storage/adapter/IndexedDBAdapter.ts
packages/datastore/src/util.ts

Some minor improvements for HasOne relationships. Non-breaking. 
1. Allow saving hasOne by model field. 
```gql
type User @model @auth(rules: [{ allow: public }]) {
id: ID!
profileID: ID
profile: Profile @connection(fields: ["profileID"])
}
type Profile @model @auth(rules: [{ allow: public }]) {
id: ID!
name: String
}
```
```ts
const profileBob = await DataStore.save(new Profile({
name: 'Bob'
}));
await DataStore.save(new User({
profile: profileBob
}));
// can still save by FK if desired:
await DataStore.save(new User({
profileID: profileBob.id
}));
```
2. Resolve hasOne connected model, just like belongsTo
```ts
const user = await DataStore.query(User, 'id');
// user.profile will correctly resolve to the linked profile
```
3. Fix bug where deletes were erroring out for optional hasOne …

feat(@aws-amplify/datastore): hasOne CRUD improvements

---

packages/aws-amplify-react-native/src/InAppMessaging/components/BannerMessage/index.ts
packages/aws-amplify-react-native/src/InAppMessaging/components/CarouselMessage/index.ts
packages/aws-amplify-react-native/src/InAppMessaging/components/FullScreenMessage/index.ts
packages/aws-amplify-react-native/src/InAppMessaging/components/InAppMessageDisplay/index.ts
packages/aws-amplify-react-native/src/InAppMessaging/components/MessageWrapper/index.ts
packages/aws-amplify-react-native/src/InAppMessaging/components/ModalMessage/index.ts
packages/aws-amplify-react-native/src/InAppMessaging/components/hooks/useMessage/index.ts
packages/aws-amplify-react-native/src/InAppMessaging/components/index.ts
packages/aws-amplify-react-native/src/InAppMessaging/context/index.ts
packages/aws-amplify-react-native/src/InAppMessaging/hooks/index.ts
packages/aws-amplify-react-native/src/InAppMessaging/index.ts
packages/aws-amplify-react-native/src/InAppMessaging/ui/Button/index.ts
packages/aws-amplify-react-native/src/InAppMessaging/ui/IconButton/index.ts
packages/aws-amplify-react-native/src/InAppMessaging/ui/index.ts
packages/aws-amplify-react-native/src/index.ts
packages/notifications/src/InAppMessaging/Providers/AWSPinpointProvider/types.ts
packages/notifications/src/InAppMessaging/Providers/AWSPinpointProvider/utils.ts
packages/notifications/src/InAppMessaging/Providers/index.ts
packages/notifications/src/InAppMessaging/SessionTracker/SessionTracker.native.ts
packages/notifications/src/InAppMessaging/SessionTracker/SessionTracker.ts
packages/notifications/src/InAppMessaging/SessionTracker/index.ts
packages/notifications/src/InAppMessaging/SessionTracker/types.ts
packages/notifications/src/InAppMessaging/eventListeners.ts
packages/notifications/src/InAppMessaging/index.ts
packages/notifications/src/index.ts

- add missing licenses in in-app messaging feature files
NA
NA

chore(in-app-messaging): audit in-app messaging feature files for licenses

---

packages/notifications/package.json
packages/notifications/src/InAppMessaging/InAppMessaging.ts
packages/notifications/src/InAppMessaging/Providers/AWSPinpointProvider/index.ts

This PR fixes a bug in the cap enforcement logic. Previously, an incremented count was being compared against a 0 cap which is meant to be unlimited. The logic now treats a 0 cap as always true when determining if below cap.
Local unit testing and local test app

fix: Bug fix for cap enforcement

---

packages/amplify-ui-angular/package.json
packages/amplify-ui-components/package.json
packages/amplify-ui-react/package.json
packages/amplify-ui-vue/package.json
packages/amplify-ui/package.json
packages/aws-amplify-angular/package.json
packages/aws-amplify-react/package.json
packages/aws-amplify-vue/package.json

With [aws-amplify/amplify-ui](https://github.com/aws-amplify/amplify-ui) going GA and publishing to `latest`, we need to ensure that publish to `latest` only happens on the UI repo and not on the JS repo. 
For more context, Amplify UI publishes to `@aws-amplify/ui-react@2.x.x` and sets it as `latest`. But after a JS stable release, the `latest` dist-tag will be overwritten back to `@1.x.x`. To prevent this, we're putting `private` tags on the JS repo so that they are ignored from Lerna's versioning and publishing.
Migration will be the top priority as UI repo has reached GA. This PR is just to ensure `latest` dist-tags don't get overwritten by one another until we migrate completely.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …

chore: mark ui packages as private

---

packages/datastore/__tests__/outbox.test.ts
packages/datastore/src/sync/outbox.ts

As of [this](https://docs.amplify.aws/cli/reference/feature-flags/#addTimestampFields) CLI feature flag timestamp fields get automatically added to the schema with a readOnly property and are added to the GraphQL selection set for queries and mutations. 
This PR adds logic to ignore the default (or custom - if configured) timestamp fields when comparing records as part of the [Consecutive Saves protocol](https://github.com/aws-amplify/amplify-js/pull/7354).
* unit tests updated
* sample app with default timestamps
* sample app with custom timestamp fields

fix(@aws-amplify/datastore): consecutive updates with timestamps

---

packages/notifications/src/InAppMessaging/SessionTracker/SessionTracker.ts

Previously, session tracking for the purposes of Pinpoint in-app messaging campaign session caps only worked with React Native. This PR implements the session tracker for web to extend that feature to the web.
N/A
Created a web app and tested session cap mechanism to see that:
1. Session caps were enforced
2. Session caps were reset when browser visibility went from inactive to active
Tested with Chrome, Firefox, Safari and Edge

feat(in-app-messaging): Add web support for session cap

---

packages/geo/__tests__/Geo.test.ts
packages/geo/__tests__/Providers/AmazonLocationServiceProvider.test.ts
packages/geo/__tests__/data.ts
packages/geo/src/Geo.ts
packages/geo/src/Providers/AmazonLocationServiceProvider.ts
packages/geo/src/types/AmazonLocationServiceProvider.ts
packages/geo/src/types/Geo.ts
packages/geo/src/types/Provider.ts

NOTE: MUST BE MERGED AFTER https://github.com/aws-amplify/amplify-js/pull/9309
- adds `listGeofences` api
- Unit tests
- Testing through Verdaccio in a sample app

feat(geo): add listGeofences api

---

packages/geo/__tests__/Geo.test.ts
packages/geo/__tests__/Providers/AmazonLocationServiceProvider.test.ts
packages/geo/__tests__/data.ts
packages/geo/src/Geo.ts
packages/geo/src/Providers/AmazonLocationServiceProvider.ts
packages/geo/src/types/AmazonLocationServiceProvider.ts
packages/geo/src/types/Geo.ts
packages/geo/src/types/Provider.ts

NOTE: MUST MERGE AFTER https://github.com/aws-amplify/amplify-js/pull/9310
- Extract batch API call code from `createGeofences` to reusable `_batchPutGeofence` method
- Add `updateGeofence` method
- right now this is an exact copy of `createGeofence`
- next steps will be to add the validation if geofences either already exist or not
- These are marked with the TODO comments
- Unit tests
- Through Verdaccio into demo app

feat(geo): add updateGeofences api

---

packages/core/src/I18n/I18n.ts

This PR fixes the I18n `get` function return an empty string, if provided vocabulary contains an empty string entry.
Only fallback to the default value if the vocabulary doesn't contain such a key at all.
https://github.com/aws-amplify/amplify-js/issues/8754
* Local unit testing
* Verified that get function return an empty string in my local app
test code
```
I18n.setLanguage('fr');
const dict = {
'fr': {
'empty string': "",
'Sign Up': "S'inscrire"
}
};
I18n.putVocabularies(dict);
console.log(I18n.get('empty string'));// returnig empty string
console.log(I18n.get('Sign Up'));// returnig provided vocabulary ( "S'inscrire" )
console.log(I18n.get('Sign in'));//returnig key value('Sign in')
console.log(I18n.get('Sign in','Se connecter'));//returnig default value ('Se connecter')
```
By …

fix(@aws-amplify/core): use empty string as translation

---

packages/amazon-cognito-identity-js/package.json
packages/core/package.json
packages/pushnotification/package.json

Reverts aws-amplify/amplify-js#9451
Potentially causes failures in the `integ_rn_ios_push_notifications` and `integ_rn_android` integration tests, will re-open once the tests are passing with the changes

chore(amplify-js): revert 9451 - consolidate react-native dependencies

---

.circleci/config.yml

This will unblock our code pipeline. The `integ_rn_ios_push_notifications` and `integ_rn_android_storage` integration tests were failing.
- Re-enabled the Android multipart upload progress tests
- Removed the `Install node@10` step as it's no longer needed and is breaking some of the RN tests
- Upgraded the executor of the `integ_rn_ios_push_notifications` test (along with a bump in RN and detox version on the corresponding sample on a separate PR)
N/A
I created a separate branch on the samples repo and ran CircleCI tests against it (tweaking the `git clone` command to clone the specific branch with the new sample). Here's an example of a successful run:
https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/9968/workflows/c9dd0b9a-625e-440a-b4b1-f8d157367aab
By submitting this …

fix: Fix CircleCI integration tests

---

packages/amazon-cognito-identity-js/package.json

The latest jsdoc requires node >= 14. Pinning it to an older version to avoid upgrading our docker images' node version.
CircleCI 

fix: pin jsdoc version

---

.circleci/config.yml
packages/amazon-cognito-identity-js/package.json
packages/core/package.json
packages/pushnotification/package.json

Consolidate `react-native` dependencies to a single dependency in `@aws-amplify/core`
> This is a duplicate of an earlier merged PR ([9451](https://github.com/aws-amplify/amplify-js/pull/9451)) that was preemptively reverted due to potential but ultimately unrelated integ test failures
**Why?**
Currently, Amplify JS has multiple versions of `react-native` listed as either `devDependencies` or `peerDependencies` in category level _package.json_ files, which leads to multiple `react-native` versions installed in the top-level `node_modules` during development. Usage of multiple versions is unnecessary as Amplify JS relies on very few React Native APIs, which are all available in version `63.4` and up.
NA
- manually tested in sample app
- `yarn clean && yarn && yarn bootstrap && yarn build` …

chore(amplify-js): consolidate react-native dependencies

---

packages/datastore/src/datastore/datastore.ts
packages/datastore/src/sync/index.ts

Some recent changes we made to DataStore introduced a regression causing certain config values (e.g. `syncPageSize` and `maxRecordsToSync`) to not be utilized correctly in the Sync Engine.
This PR restores the expected behavior.
https://github.com/aws-amplify/amplify-js/issues/9534
Sample app

fix(datastore): correctly apply config values

---

packages/geo/__tests__/Geo.test.ts
packages/geo/__tests__/Providers/AmazonLocationServiceProvider.test.ts
packages/geo/package.json
packages/geo/src/Geo.ts
packages/geo/src/Providers/AmazonLocationServiceProvider.ts
packages/geo/src/types/Geo.ts
packages/geo/src/types/Provider.ts

- Adds a new api `searchForSuggestions` that takes in a search text, with optional parameters, and returns an array of strings matching the results from calls to Amazon Location Service `SearchPlaceIndexForSuggestions` API.
search for `starbucks`
search for `star`
search for `amazon`
- unit tests
- sample app

feat(@aws-amplify/geo): searchForSuggestions API

---

packages/storage/__tests__/providers/AWSS3ProviderManagedUpload-unit-test.ts
packages/storage/package.json

Remove `sinon` as a dependency of `@aws-amplify/storage` by converting `sinon` spies to `jest` mock functions.
> There are some additional updates due to `prettier`, relevant changes are noted.
https://github.com/aws-amplify/amplify-js/issues/9565
`yarn clean && yarn && yarn bootstrap && yarn build && yarn test`

chore(storage): remove sinon as a dependency; convert sinon spies to mock functions

---

packages/amazon-cognito-identity-js/package.json
packages/core/package.json

Pinning `@react-native-async-storage/async-storage` in cognito and core package to `1.15.17`, `1.16` that was just published is causing build issues.
`yarn build`

fix: pin async storage to 1.15.17

---

package.json
packages/amazon-cognito-identity-js/package.json

`yarn build` was failing due to an issue in bable. Pinning the `@babel/core` and `@babel/cli` version.
See: https://github.com/babel/babel/issues/14273
N/A
ran `yarn setup-dev` from a fresh clone.

fix(ops): pin babel-core and babel-cli version

---

packages/analytics/src/Analytics.ts
packages/analytics/src/types/Analytics.ts

- Add back the `_tracker={}` line in constructor
- Add some missing types back to autotrack

fix(@aws-amplify/analytics): Analytics/types hotfix

---

packages/aws-amplify-react-native/src/AmplifyTheme.ts
packages/aws-amplify-react-native/src/AmplifyUI.tsx

Add linkUnderlay to theme object can be overridden
This PR adds a `linkUnderlay` property to the `AmplifyTheme` object and updates references to the original constant to use the theme instead. This allows the underlay color to be configurable.
Previously:
```js
const AuthTheme = Object.assign({}, AmplifyTheme, {
container: {
backgroundColor: '#000',
},
// no way to override link underlay color - underlay would always show up white on dark background
});
```
After this PR:
```js
const AuthTheme = Object.assign({}, AmplifyTheme, {
container: {
backgroundColor: '#000',
},
linkUnderlay: {
color: '#000',
},
});
```
#9446 
Manually tested the ability to override this property with a test app using the authenticator HOC.
Manually tested the authenticator HOC works as before (white underlay) if …

fix(aws-amplify-react-native): Add linkUnderlay to theme object

---

.circleci/config.yml

The current version of the Cypress Docker image (cypress/included:8.7.0) uses Firefox v89, which has a WebGL issue when running on Linux containers and prevents us from being able to test `@aws-amplify/geo` with Firefox in CI.
The latest version (cypress/included:9.5.1) uses Firefox v96, which fails our `amazon-cognito-identity-js-cookie-storage` tests due to an issue with cookies using the `lax` property for `cookie.sameSite`. This also happens when I run Cypress locally with Firefox v96 installed on my dev machine.
Using Firefox v97 fixes this issue locally, but there isn't a Cypress Docker image with that version out yet (well, technically, there _is_, but it's a `slim` version and doesn't even have `git` installed and thus breaks nearly all of our tests 😅).
Thus, this PR moves us to …

ci: update cypress docker image version

---

packages/core/src/Util/Retry.ts
packages/datastore/__tests__/mutation.test.ts
packages/datastore/src/sync/processors/mutation.ts

Fixes a bug wherein mutation retries due to service reachability issues eventually end, resulting in data loss. Data can become isolated to a single client. This change causes failures due to network errors to retry indefinitely until connectivity is restored.
Provides an alternative to reachability testing from #9700.
#9699
Tested in app by overriding DataStore reachability test to always show online and disabling network in browser. Observed retries continue "indefinitely", whereas they did not previously.
Added unit test to show that retry delay scales on large attempt values for network errors.

fix(@aws-amplify/datastore): fix mutations to retry indefinitely on network error

---

.circleci/config.yml

Testing potential Cypress version upgrades
None - all builds are currently blocked on Circle CI

fix: upgrade CircleCI Cypress image to 12.22.8

---

packages/aws-amplify-react-native/src/InAppMessaging/components/BannerMessage/__tests__/BannerMessage.spec.tsx
packages/aws-amplify-react-native/src/InAppMessaging/components/FullScreenMessage/__tests__/FullScreenMessage.spec.tsx
packages/aws-amplify-react-native/src/InAppMessaging/components/hooks/useMessageImage/__tests__/useMessageImage.spec.ts
packages/aws-amplify-react-native/src/InAppMessaging/components/hooks/useMessageImage/constants.ts
packages/aws-amplify-react-native/src/InAppMessaging/components/hooks/useMessageImage/useMessageImage.ts
packages/aws-amplify-react-native/src/InAppMessaging/ui/Carousel/Carousel.tsx

Remove `INITIAL_IMAGE_DIMENSIONS` constant as it was being reused between `Carousel` messages leading to  incorrect image dimensions being used for rendering
NA
Manually tested

fix(in-app-messaging): prevent reuse of image dimension object between multiple messages
