packages/datastore/src/storage/storage.ts

Add `undefined` check: https://github.com/aws-amplify/amplify-js/pull/9268/files#diff-543f05c6407653f099050505c460af9780d945838cd2f69a44d0ac6113f63efbR328
We recently upgraded Prettier, so there are a couple of unintentional formatting changes as well.

fix(@aws-amplify/datastore): belongsTo bug

---

packages/notifications/package.json

This PR updates the notifications package.json to use semver versions of Amplify dependencies matching aws-amplify instead of pointing at tags.

chore(in-app-messaging): Update dependencies back to semvers

---

packages/analytics/__tests__/Analytics-unit-test.ts
packages/notifications/__mocks__/data.ts
packages/notifications/__mocks__/mocks.ts
packages/notifications/__tests__/InAppMessaging/InAppMessaging.test.ts
packages/notifications/__tests__/InAppMessaging/Providers/AWSPinpointProvider/index.test.ts
packages/notifications/__tests__/InAppMessaging/Providers/AWSPinpointProvider/utils.test.ts
packages/notifications/__tests__/InAppMessaging/eventListeners.test.ts
packages/notifications/__tests__/Notifications.test.ts
packages/notifications/package.json

This PR adds unit tests to the In-App Messaging feature.
Relevant docs are in PR:
https://github.com/aws-amplify/docs/pull/3783

chore(in-app-message): In app messaging/add unit tests

---

packages/amplify-ui/package.json

Unblocks the ability to publish the Amplify UI package due to the `private` property being set to `true` in the `package.json` of Amplify UI.
https://github.com/aws-amplify/amplify-js/issues/9302

fix(@aws-amplify/amplify-ui): change private property to false in package.json

---

packages/amplify-ui/package.json

fix(@aws-amplify/amplify-ui): remove private prop from package.json

---

packages/geo/__tests__/Geo.test.ts
packages/geo/__tests__/Providers/AmazonLocationServiceProvider.test.ts
packages/geo/__tests__/data.ts
packages/geo/src/Geo.ts
packages/geo/src/Providers/AmazonLocationServiceProvider.ts
packages/geo/src/types/Geo.ts
packages/geo/src/types/Provider.ts
packages/geo/src/util.ts

NOTE: `createGeofences` PR MUST BE MERGED FIRST – https://github.com/aws-amplify/amplify-js/pull/9278
- Update some types
- Add `geoGeofence` api with tests
- Unit tests
- Tested in local app through publishing to verdaccio

feat(geo): add getGeofence api

---

packages/geo/__tests__/Providers/AmazonLocationServiceProvider.test.ts
packages/geo/__tests__/data.ts
packages/geo/src/Geo.ts
packages/geo/src/Providers/AmazonLocationServiceProvider.ts
packages/geo/src/types/AmazonLocationServiceProvider.ts
packages/geo/src/types/Geo.ts
packages/geo/src/types/Provider.ts

NOTE: MUST MERGE AFTER https://github.com/aws-amplify/amplify-js/pull/9312
-  Add `deleteGeofences` api
- Update types
- Unit tests
- Ran in sample app through verdaccio

feat(geo): add deleteGeofences api

---

packages/geo/__tests__/Geo.test.ts
packages/geo/__tests__/Providers/AmazonLocationServiceProvider.test.ts
packages/geo/__tests__/util.test.ts
packages/geo/src/Geo.ts
packages/geo/src/Providers/AmazonLocationServiceProvider.ts
packages/geo/src/types/Geo.ts
packages/geo/src/types/Provider.ts
packages/geo/src/util.ts

Due to the way that Location Service handles checking if a geofence exists (404 error if it does not exist, which would be logged to the console), we have decided to not separate these methods and combine them into one without checks if the geofences already exist.
- remove `updateGeofences`
- change `createGeofences` to `saveGeofences`
- use `logger.debug` instead of `logger.warn`
- Util tests were wrapped in a larged `describe` block - No actual test changes in that file
There were not much logic changes here, more of rearranging and renaming code
- Unit tests updated
- Testing in demo app through Verdaccio

chore(geo): refactor create/update to saveGeofences

---

packages/aws-amplify-react-native/.eslintrc.js

Update to `packages/aws-amplify-react-native/.eslintrc.js ` to fix broken dev build on Windows machines
#9328 
- Ran successful build on Windows
- Ran successful build on Mac

fix(@aws-amplify/aws-amplify-react-native): fix dev build for Windows

---

packages/geo/__tests__/Geo.test.ts
packages/geo/__tests__/Providers/AmazonLocationServiceProvider.test.ts
packages/geo/__tests__/testData.ts
packages/geo/__tests__/testUtils.ts
packages/geo/__tests__/util.test.ts
packages/geo/package.json

No logic changes, just splitting out the functions from the `data` file into their own.
- This only effects unit tests, and they all pass.

chore(geo): split out `__tests__/data` to `testData` and `testUtils`

---

packages/api-graphql/package.json
packages/pubsub/package.json

Updating `graphql` dependencies to `15.8.0`
Dev build and production build with latest `create-react-app` (5.0.0) by linking the library, did `Auth.signIn` successfully on the App.

fix(@aws-amplify/api-graphql): Fix webpack build

---

packages/aws-amplify-react-native/package.json
packages/aws-amplify/package.json
packages/notifications/package.json

- bump `notifications` category minor version
- upgrade `notifications` internal deps
NA
NA

chore(in-app-messaging): upgrade internal dependency versions and notifications version

---

packages/core/src/Hub.ts

Trivial typo in code comment.
NA
NA

fix: typo in comment (psuedo)

---

.vscode/launch.json
packages/datastore/__tests__/IndexedDBAdapter.test.ts
packages/datastore/__tests__/__snapshots__/indexeddb.test.ts.snap
packages/datastore/__tests__/indexeddb.test.ts
packages/datastore/src/datastore/datastore.ts
packages/datastore/src/predicates/index.ts
packages/datastore/src/storage/adapter/IndexedDBAdapter.ts
packages/datastore/src/types.ts

feat(@aws-amplify/datastore): custom PK storage engine & IDB adapter

---

packages/datastore/src/storage/adapter/IndexedDBAdapter.ts

fix query one

---

.circleci/config.yml

Use latest macOS executor with RN e2e test jobs where possible
Older RN tests that need to be migrated will remain on 11.5 for now
Also: Bumped resource classes to `large`, since those are included with our plan and provide a 10-20% improvement in job running time
https://app.circleci.com/pipelines/github/aws-amplify/amplify-js?branch=ci-upgrade-node-mac&filter=all

ci: upgrade macOS executors

---

packages/core/src/I18n/I18n.ts

Reverts aws-amplify/amplify-js#9403

Revert "fix(@aws-amplify/core): use empty string as translation"

---

packages/aws-amplify-angular/package.json

Removed old zone package
Built locally and on CI

fix(aws-amplify-angular): removed old zone package

---

packages/datastore/__tests__/outbox.test.ts
packages/datastore/src/sync/index.ts
packages/datastore/src/sync/merger.ts
packages/datastore/src/sync/outbox.ts

fix(@aws-amplify/datastore): custom pk bug fix + pr reqd change

---

packages/datastore-storage-adapter/src/SQLiteAdapter/SQLiteDatabase.ts
packages/datastore/__tests__/AsyncStorageAdapter.test.ts
packages/datastore/__tests__/IndexedDBAdapter.test.ts
packages/datastore/__tests__/model.ts
packages/datastore/src/storage/adapter/AsyncStorageAdapter.ts
packages/datastore/src/storage/adapter/IndexedDBAdapter.ts

fix: test updates

---

packages/geo/__tests__/Geo.test.ts
packages/geo/__tests__/Providers/AmazonLocationServiceProvider.test.ts
packages/geo/src/Providers/AmazonLocationServiceProvider.ts
packages/geo/src/types/AmazonLocationServicesProvider.ts
packages/geo/src/types/Geo.ts

These are some bug fixes that I found on an old branch that have not made it to `main` yet:
- Remove `ensure to` from error messages - This is from DA feedback
- Remove unused `AmazonLocationServiceProvider.ts` file (this was replaced by `AmazonLocationServicesProvider.ts`)
- Fix bad type comment
- Fix implementation for failing when both `biasPosition` and `searchAreaConstraints` are given in search options
Updated tests and ran through sample application

fix(@aws-amplify/geo): bug fixes

---

.github/actions/bundle-size-action/next/package.json

fix security issue related to next bundle analysis
https://github.com/aws-amplify/amplify-js/security/dependabot/.github/actions/bundle-size-action/next/package.json/next/open
- [Y] PR description included
- [] `yarn test` passes

chore: upgrade next version to ^11.1.3 for security patch

---

packages/core/__tests__/Hub-test.ts
packages/core/src/Hub.ts

This PR adds a new `ui` protected Hub channel.

feat(@aws-amplify/core): add ui protected channel

---

.envrc
packages/datastore/__tests__/custom-pk-typings.test.ts
packages/datastore/src/datastore/datastore.ts
packages/datastore/src/predicates/index.ts
packages/datastore/src/types.ts

- Fix `IdentifierFieldValue `
- Minor TS changes to reduce errors in strict mode

Custom PK - Fix IdentifierFieldValue 

---

.github/actions/bundle-size-action/next/package.json

Fixes [this](https://github.com/aws-amplify/amplify-js/security/dependabot/6) dependabot alert

chore: update bundle-size-action/next deps

---

packages/amazon-cognito-identity-js/LICENSE.txt
packages/amazon-cognito-identity-js/NOTICE.txt
packages/amazon-cognito-identity-js/RNAWSCognito.podspec
packages/amazon-cognito-identity-js/ios/JKBigInteger/LICENSE.txt
packages/amazon-cognito-identity-js/package.json
packages/amazon-cognito-identity-js/src/AuthenticationDetails.js
packages/amazon-cognito-identity-js/src/AuthenticationHelper.js
packages/amazon-cognito-identity-js/src/CognitoAccessToken.js
packages/amazon-cognito-identity-js/src/CognitoIdToken.js
packages/amazon-cognito-identity-js/src/CognitoJwtToken.js
packages/amazon-cognito-identity-js/src/CognitoRefreshToken.js
packages/amazon-cognito-identity-js/src/CognitoUser.js
packages/amazon-cognito-identity-js/src/CognitoUserAttribute.js
packages/amazon-cognito-identity-js/src/CognitoUserPool.js
packages/amazon-cognito-identity-js/src/CognitoUserSession.js
packages/amazon-cognito-identity-js/src/DateHelper.js
packages/amazon-cognito-identity-js/src/Platform/index.js
packages/amazon-cognito-identity-js/src/StorageHelper-rn.js
packages/amazon-cognito-identity-js/src/StorageHelper.js
packages/amazon-cognito-identity-js/src/index.js
packages/amazon-cognito-identity-js/webpack.config.js

Relicensed this library from Amazon Software License to Apache-2.0 with assent from Amazon and contributors.
I don't have expertise in the codebase, so I've merely been careful to get syntax correct. It's mostly documentation only changes, so focus on the parts that aren't just documentation, like the `.podspec` especially.

chore(amazon-cognito-identity-js): Relicense to Apache-2.0

---

packages/amazon-cognito-identity-js/package.json
packages/aws-amplify-react-native/package.json
packages/aws-amplify/package.json
packages/core/package.json
packages/notifications/package.json

Bumps notifications and dependency versions. The previous merge missed bumping dependency versions and the tag got out of sync.

chore(in-app-messaging): bump versions

---

packages/geo/__tests__/Geo.test.ts
packages/geo/__tests__/Providers/AmazonLocationServiceProvider.test.ts
packages/geo/__tests__/testData.ts
packages/geo/__tests__/util.test.ts
packages/geo/package.json
packages/geo/src/Geo.ts
packages/geo/src/Providers/AmazonLocationServiceProvider.ts
packages/geo/src/util.ts

- Add validation to ensure `LinearRing` is wound clockwise
- Update all validation error messages to include more information, such as the `geofenceId` that has the issue
- Move Amazon Location Service specific validations to `AmazonLocationProvider` instead of `Geo` class
- Updated tests

fix(geo): update validations and error messages

---

packages/core/__tests__/Providers/APILoggingProvider-test.ts
packages/core/src/Logger/ConsoleLogger.ts
packages/core/src/Providers/APIProvider/APILoggingProvider.ts
packages/core/src/Providers/APIProvider/CloudWatchEventFormatter.ts
packages/core/src/Providers/APIProvider/Fetch.ts
packages/core/src/Providers/AWSCloudWatchProvider.ts
packages/core/src/types/types.ts

Updating event format sent thru `APILoggingProvider`
WIP

fix: refactoring logger event

---

packages/aws-amplify-react-native/jest.config.js
packages/aws-amplify-react-native/src/InAppMessaging/components/CarouselMessage/CarouselMessage.tsx
packages/aws-amplify-react-native/src/InAppMessaging/components/CarouselMessage/CarouselMessageItem.tsx
packages/aws-amplify-react-native/src/InAppMessaging/components/CarouselMessage/__tests__/CarouselMessage.spec.tsx
packages/aws-amplify-react-native/src/InAppMessaging/components/CarouselMessage/__tests__/CarouselMessageItem.spec.tsx
packages/aws-amplify-react-native/src/InAppMessaging/components/CarouselMessage/__tests__/__snapshots__/CarouselMessage.spec.tsx.snap
packages/aws-amplify-react-native/src/InAppMessaging/components/CarouselMessage/__tests__/__snapshots__/CarouselMessageItem.spec.tsx.snap
packages/aws-amplify-react-native/src/InAppMessaging/components/hooks/useMessageProps/__tests__/__snapshots__/utils.spec.ts.snap
packages/aws-amplify-react-native/src/InAppMessaging/components/hooks/useMessageProps/__tests__/utils.spec.ts
packages/aws-amplify-react-native/src/InAppMessaging/ui/Carousel/Carousel.tsx
packages/aws-amplify-react-native/src/InAppMessaging/ui/Carousel/CarouselPageIndicator.tsx
packages/aws-amplify-react-native/src/InAppMessaging/ui/Carousel/__tests__/Carousel.spec.tsx
packages/aws-amplify-react-native/src/InAppMessaging/ui/Carousel/__tests__/CarouselPageIndicator.spec.tsx
packages/aws-amplify-react-native/src/InAppMessaging/ui/Carousel/__tests__/__snapshots__/Carousel.spec.tsx.snap
packages/aws-amplify-react-native/src/InAppMessaging/ui/Carousel/__tests__/__snapshots__/CarouselPageIndicator.spec.tsx.snap

This PR adds unit tests to the In-App Messaging Carousel Message component along with some minor edge case fixes discovered as a result of adding unit tests.
Tested code change in local sample app to make sure behavior was unchanged. 

chore(in-app-messaging): Add unit tests for carousel

---

.github/ISSUE_TEMPLATE/2.feature_request.yaml

Adds `Geo` to our Github Issues template

chore: add geo to `.github/ISSUE_TEMPLATE`

---

.circleci/config.yml

- Related pr - https://github.com/aws-amplify/amplify-js-samples-staging/pull/325
- Reducing the number of geo test applications and integration specs to fewer files

chore(geo): reduce number of integ spec cases

---

packages/notifications/package.json

Bump `Notifications` category Amplify deps

chore(in-app-messaging): update Notification category amplify depedencies

---

packages/storage/src/providers/axios-http-handler.ts

Revert side effect lintstaged updates

fix(in-app-messaging): revert side effect lintstaged updates

---

packages/amazon-cognito-identity-js/README.md

Update the README.md docs to fix the variable name in the use case 12 example, to match the variable passed to the confirmPassword method

fix: docs for amazon-cognito-identity-js

---

.circleci/config.yml

Adds a canary workflow to our CircleCI pipeline that will run every hour.
The workflow:
1. Scaffolds new applications with each of our supported frameworks
2. Installs `aws-amplify@latest` from npm
3. Calls the library from the app
4. Builds for dev and starts the app
5. Builds for prod and starts the app
The workflow will fail and notify team members if it encounters errors or times out during any of these steps.
**After merge to main**
* Create a Scheduled Trigger in CircleCI that executes hourly and targets the `canaries` workflow (https://circleci.com/docs/2.0/scheduled-pipelines/#project-settings)
**Note: I'm adding the new orb inline in the config for now in case we need to make changes to any of the job definitions. I will extract it into an actual orb after we've confirmed that …

ci: add canaries workflow

---

.circleci/config.yml

Minor update to the canaries retry script to fix error handling

ci: update canaries retry script

---

.circleci/config.yml

Fix `run-with-retry` command to correctly handle errors, particularly with chained scripts (e.g. `cmd1 && cmd2`)
Test run: https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/11294/workflows/38dc4c73-684e-426a-878a-9c88faf10e01

ci: canaries - fix retry command

---

packages/aws-amplify-react-native/package.json
packages/aws-amplify/package.json
packages/notifications/package.json

This PR bumps the In-App Messaging version.
N/A
`yarn test`

chore(in-app-messaging): version bump

---

packages/datastore/__tests__/helpers.ts
packages/datastore/__tests__/subscription.test.ts
packages/datastore/src/sync/processors/subscription.ts

Restore change in https://github.com/aws-amplify/amplify-js/pull/9987 after revert and fix integration tests. The integration test was dependent on a warning message that had been removed.
N/A
Successful integration test run: https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/11632/workflows/9e73f35d-cce1-432f-afde-87595556b699

fix: decrease error handler verbosity on self recovering errors

---

packages/aws-amplify-vue/package.json

fix: pin vue version to unblock build

---

.circleci/config.yml

Add DataStore's integration test schema drift to CircleCI pipeline
TBD: Just made the changes to circleCI's config.yml, need to do a dryrun or some sort of config.yml validation here.

chore(datastore): Add schema-drift integration test

---

.github/CODEOWNERS

chore(data): update CODEOWNERS file

chore(data): update CODEOWNERS file

---

CONTRIBUTING.md

Change misspelling of word "continuous"
N/A
N/A

Fix typo in contributing guide

---

packages/auth/src/Auth.ts

Changing set auto sign in storage value to string from boolean

fix(@aws-amplify/auth): fix storage bug for auto sign in value

---

packages/datastore-storage-adapter/package.json
packages/datastore/__tests__/AsyncStorage.ts
packages/datastore/__tests__/AsyncStorageAdapter.test.ts
packages/datastore/src/datastore/datastore.ts
packages/datastore/src/storage/adapter/AsyncStorageAdapter.ts
packages/datastore/src/storage/adapter/AsyncStorageDatabase.ts
packages/datastore/src/storage/adapter/IndexedDBAdapter.ts
packages/datastore/src/util.ts

async adapter bug fixes; observe and observeQuery bug fixes; empty key value bug fix

---

packages/datastore-storage-adapter/__tests__/SQLiteAdapter.test.ts
packages/datastore-storage-adapter/package.json
packages/datastore-storage-adapter/src/common/SQLiteUtils.ts
packages/datastore/src/util.ts

Ds custom pk sqlite test fixes

---

packages/datastore/__tests__/__snapshots__/indexeddb.test.ts.snap
packages/datastore/src/storage/adapter/IndexedDBAdapter.ts

fix(datastore): update schema migration script

---

packages/datastore/src/datastore/datastore.ts

fix(datastore): query - return single result for composite key OL

---

packages/datastore/src/datastore/datastore.ts

A miss from [this PR](https://github.com/aws-amplify/amplify-js/pull/10088).

fix(datastore): make di context fields private

---

.circleci/config.yml
package.json

Adding `fix/no-crypto-js` branch to be released on npm for bundle size improvements testing

Adding branch to be released on npm under size-improvement tag

---

packages/datastore/src/util.ts

fix(datastore): fix delete for explicit hasMany

---

packages/datastore/src/datastore/datastore.ts
packages/datastore/src/util.ts

Ds custom pk query update

---

packages/aws-amplify-react/package.json
packages/aws-amplify-react/src/Amplify-UI/data-test-attributes.tsx
packages/aws-amplify-react/src/Interactions/Lex2ChatBot.tsx
packages/aws-amplify-react/src/Interactions/helpers/convert.ts
packages/interactions/package.json
packages/interactions/src/Providers/AWSLex2Provider.ts
packages/interactions/src/Providers/AWSLexProviderHelper/convert.native.ts

Add LexV2Provider to support LexV2 in Interactions package and React example
#9504
#7662
This is an initial PR so @ashwinkumar6 can use it as base

Add Interactions LexV2Provider and React example

---

packages/pubsub/src/utils/ConnectionStateMonitor.ts
packages/pubsub/src/utils/ReachabilityMonitor/index.native.ts
packages/pubsub/src/utils/ReachabilityMonitor/index.ts

The connection state Reachability implementation didn't include the RN variation inclusion of NetInfo, the the correct Reachability object is being used, but missing the required input.
This change
#10148
I have validated with testing. I will do further validation by bringing this into an RN test to verify it solves the issue.

fix(pubsub): Add distinct RN Reachibility implementation

---

packages/datastore/src/datastore/datastore.ts
packages/datastore/src/util.ts

feat(data): emit warning if observe is used with object literal

---

packages/auth/src/AuthPluggable.ts
packages/auth/src/Providers/CognitoProvider/CognitoProvider.ts
packages/auth/src/Providers/CognitoProvider/Util.ts
packages/auth/src/Providers/CognitoProvider/index.ts
packages/auth/src/Providers/CognitoProvider/machines/authenticationMachine.ts
packages/auth/src/Providers/CognitoProvider/machines/authorizationMachine.ts
packages/auth/src/Providers/CognitoProvider/machines/fetchAuthSessionStateMachine.ts
packages/auth/src/Providers/CognitoProvider/machines/oAuthSignInMachine.ts
packages/auth/src/Providers/CognitoProvider/machines/refreshSessionMachine.ts
packages/auth/src/Providers/CognitoProvider/machines/signInMachine.ts
packages/auth/src/Providers/CognitoProvider/machines/signUpMachine.ts
packages/auth/src/Providers/CognitoProvider/machines/srpSignInMachine.ts
packages/auth/src/Providers/CognitoProvider/service.ts
packages/auth/src/Providers/CognitoProvider/serviceClass.ts
packages/auth/src/Providers/CognitoProvider/types/machines/authenticationMachine.ts
packages/auth/src/Providers/CognitoProvider/types/machines/authorizationMachine.ts
packages/auth/src/Providers/CognitoProvider/types/machines/fetchAuthSessionStateMachine.ts
packages/auth/src/Providers/CognitoProvider/types/machines/index.ts
packages/auth/src/Providers/CognitoProvider/types/machines/oAuthSignInMachine.ts
packages/auth/src/Providers/CognitoProvider/types/machines/refreshSessionMachine.ts
packages/auth/src/Providers/CognitoProvider/types/machines/signInMachine.ts
packages/auth/src/types/Provider.ts

Adds license headers to cognito provider files.

chore(auth): adds license headers to cognito provider files

---

packages/datastore/src/storage/adapter/IndexedDBAdapter.ts

fix(datastore): has one cascading delete

---

package.json

This fixes the build, which started failing in `amplify-ui-angular` due to a new `@types/minimatch` version being released.
```
88665a246fd5:amplify-ui-angular wirej$ yarn build
yarn run v1.22.17
$ npm run build.ng
> @aws-amplify/ui-angular@1.0.55 build.ng
> npm run build.es2015 && npm run build.es5
> @aws-amplify/ui-angular@1.0.55 build.es2015
> ngc -p tsconfig.json && rollup --config ./scripts/rollup.config.js
../../node_modules/@types/glob/node_modules/@types/minimatch/index.d.ts(29,35): error TS1005: ',' expected.
../../node_modules/@types/glob/node_modules/@types/minimatch/index.d.ts(29,41): error TS1005: ',' expected.
../../node_modules/@types/glob/node_modules/@types/minimatch/index.d.ts(42,59): error TS1005: ',' expected. …
```

chore: fixed build, minimatch dep

---

.circleci/config.yml

Add OIDC connection to connect to cloudwatch for monitoring
Tested in temp branch: https://app.circleci.com/pipelines/github/yeung-wah/amplify-js?branch=circleci-editor%2F812%2Fcircleci-cloudwatch-monitoring

Circleci cloudwatch monitoring

---

.circleci/config.yml

Adding integ test for Lex V2 provider

chore(@aws-amplify/interactions): adding lex v2 integ test

---

.github/CODEOWNERS

chore: Create CODEOWNERS on releases branch

---

.github/CODEOWNERS

Working through the permissions migration process, we are assigning `CODEOWNERS` to groups instead of individuals.
Change made with Tim's guidance pairing with Francisco

Update CODEOWNERS from permissions migration

---

packages/interactions/package.json

Upgrading lex v2 runtime client
Fixes: #10284 

fix(@aws-amplify/interactions): Upgrade client lex runtime v2

---

.github/CODEOWNERS
packages/aws-amplify/src/index.ts
packages/interactions/package.json

Amplify JS Release 2022-09-19
- #10284 

Amplify JS Release 2022-09-19

---

packages/geo/__tests__/Geo.test.ts
packages/geo/__tests__/Providers/AmazonLocationServiceProvider.test.ts
packages/geo/package.json
packages/geo/src/Geo.ts
packages/geo/src/Providers/AmazonLocationServiceProvider.ts
packages/geo/src/types/Geo.ts
packages/geo/src/types/Provider.ts

- Update existing SearchForSuggestions API to return PlaceId (if available) along with text (title, address) of the places.
- Implement a new API called SearchForLocationById which will be a wrapper around AmazonLocationService’s GetPlace API

Add PlaceId support for Geo Autocomplete feature

---

packages/geo/__tests__/testData.ts
packages/geo/__tests__/util.test.ts
packages/geo/src/Geo.ts
packages/geo/src/Providers/AmazonLocationServiceProvider.ts
packages/geo/src/util.ts

Refactor code to move search options mapping to a utility function

chore: refactor code to move search options mapping to a utility function

---

.circleci/config.yml

Integ test is broken. Fix is in progress. Temporarily disabling to unblock release, will re-enable ASAP.

ci: temp disable observeQuery e2e

---

.circleci/config.yml
docs/api/classes/asyncstoragecache.html

chore: Merging changes to release

---

.circleci/config.yml

feat(data): add custom primary key integ tests to Circle CI config

feat(data): add custom primary key integ tests to Circle CI config

---

.circleci/config.yml

Removed the `integ_react_storage_ui` tests because they are blocked by the removal of the components-ui package and do not leave any storage features untested. 
This PR is coupled with fixes to the integ tests to reflect list pagination changes: https://github.com/aws-amplify/amplify-js-samples-staging/pull/425
--> fixed integ tests tested here: https://app.circleci.com/pipelines/github/aws-amplify/amplify-js?branch=katie%2Fnext-major-version%2F5

fix: config.yml - removed integ_react_storage_ui tests

---

packages/datastore/__tests__/connectivityHandling.test.ts
packages/datastore/__tests__/helpers.ts
packages/datastore/src/datastore/datastore.ts
packages/datastore/src/sync/index.ts
packages/datastore/src/sync/processors/mutation.ts
packages/datastore/src/sync/processors/subscription.ts
packages/datastore/src/sync/processors/sync.ts

Just a draft to help me sort through diffs. :) 

Remove ds sync restart error

---

.circleci/config.yml

ci: only run cpk integ on ff

---

packages/datastore/src/datastore/datastore.ts
packages/datastore/src/sync/index.ts

fix(datastore): unblock vite build after CPK changes

---

.circleci/config.yml

feat(data): background process manager integ tests

feat(data): background process manager integ tests

---

packages/amplify-ui-components/tsconfig.json
packages/amplify-ui-vue/tsconfig.json
packages/amplify-ui/tsconfig.json
packages/core/src/Util/BackgroundProcessManager.ts
packages/pushnotification/tsconfig.json

chore: preparing release

---

packages/aws-amplify-react-native/package.json

This change bumps the patch version of `aws-amplify-react-native` to (hopefully) address a deployment issue we're seeing in CircleCI.

Bump `aws-amplify-react-native` patch version to resolve deployment issue

---

.circleci/config.yml

Testing for #10580. This will allow the integ tests to run against a branch without a release step.
This is the validation

@stocaaro ci(pubsub): add integ tests for reconnection

---

packages/pubsub/src/types/Provider.ts

Removing deprecated PubSub provider type

---

packages/auth/package.json

Remove crypto-js dependency from @aws-amplify/auth

---

.circleci/config.yml

chore: use --ignore-engines option in CI

---

.circleci/config.yml
packages/amplify-ui-components/package.json
packages/aws-amplify-angular/package.json
packages/aws-amplify-react/package.json
packages/aws-amplify-vue/package.json
packages/aws-amplify/__tests__/exports-test.ts
packages/aws-amplify/src/index.ts
packages/cache/src/index.ts

chore: Release from main

---

.circleci/config.yml

Associated with: https://github.com/aws-amplify/amplify-js-samples-staging/pull/462
* Use the new test spec to run React auth integ test
* Break the React auth test suite to 2 parallel sections to reduce the execution time.
TODO: update staging app branch once the other PR is merged.
Integ test

test(integ): migrate react auth sample app to new UI

---

.circleci/config.yml

Disabling geo tests until fix

---

.circleci/config.yml

Reenabling geo tests

---

.circleci/config.yml

fix(geo): Disabling the failing tests pending a fix

fix(geo): Disabling the failing tests pending a fix

---

.circleci/config.yml

This reverts commit d714fc7f8d79858313a685a6a0f9b1b32bad7760.
Re enabling geo integ tests

Re-enable geo tests

---

package.json

chore: Resume the conventional commit release process

chore: Resume the conventional commit release process

---

packages/datastore/__tests__/__snapshots__/indexeddb.upgrade.test.ts.snap
packages/datastore/__tests__/indexeddb.upgrade.test.ts
packages/datastore/src/storage/adapter/IndexedDBAdapter.ts

fix(datastore): upgrade after destructive schema change

---

package.json

chore: Add next tag to publish:release
Tested locally using verdaccio.

chore: Add next tag to publish:release

---

README.md

Missed nit from [prior review](https://github.com/aws-amplify/amplify-js/pull/10667)

fix: README nit missed in last review

---

.circleci/config.yml

This change updates the CircleCI config to use the default branch instead of `master` and also cleans up the `next-major-version/5` branch.

chore: Update CircleCI config to use default branch

---

README.md

fix minor typo for v5 breaking change guidance

---

lgtm.yml

Remove unnecessary LGTM config as the service is deprecated. More context in #10725 
Blocked by #10725
N/A

chore: remove gltm.yml

---

.circleci/config.yml

added nextjs integ tests; expecting failure in '-basic'

---

package.json

Change preid for `unstable` to `unstable-main`

chore: Change preid for unstable

---

packages/amazon-cognito-identity-js/src/Client.js
packages/core/__tests__/Util-test.ts
packages/core/src/Credentials.ts
packages/core/src/Util/CognitoIdentityClient.ts

Adds cache control headers.
Manual testing and unit tests.

fix(core): add cache-control header to cognito identity client (#10753)

---

.circleci/config.yml
package.json
packages/amazon-cognito-identity-js/__tests__/CognitoUser.test.js
packages/amazon-cognito-identity-js/index.d.ts
packages/amazon-cognito-identity-js/src/Client.js
packages/amazon-cognito-identity-js/src/CognitoUser.js
packages/auth/__tests__/auth-unit-test.ts
packages/auth/src/Auth.ts
packages/core/__tests__/Credentials-test.ts
packages/core/__tests__/Util-test.ts
packages/core/src/Credentials.ts
packages/core/src/Util/CognitoIdentityClient.ts
packages/datastore/__tests__/DataStore.ts
packages/datastore/src/datastore/datastore.ts
packages/pubsub/__tests__/AWSAppSyncRealTimeProvider.test.ts
packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider/index.ts

Amplify JS release from main.
N/A
Manual testing and circle ci -> unstable.

Amplify JS release

---

package.json

chore: update main branch preid to unblock release

---

.github/CODEOWNERS

Add amplify-js-admins for v4 release protection

chore: Add amplify-js-admins for v4 release protection

---

packages/auth/__tests__/auth-cognito-provider-unit-test.ts

Unit tests for sign up function rewrite

adds unit test for sign up funtion rewrite

---

packages/amazon-cognito-identity-js/src/Client.js

fix(amazon-cognito-identity-js): sets no-store header for cognito user pools
Manual testing 

fix(amazon-cognito-identity-js): sets no-store header for cognito user pools (#10804)

---

packages/auth/__tests__/state-machine-manager-test.ts
packages/auth/__tests__/state-machine-manager.ts
packages/auth/src/stateMachine/stateMachineManager.ts

feat(auth): event machine manager

---

packages/auth/__tests__/state-machine-single-test.ts
packages/auth/src/stateMachine/machine.ts
packages/auth/src/stateMachine/machineState.ts
packages/auth/src/stateMachine/types.ts

styling fixes for lint to pass

---

package.json

Update preId for unstable release

Update preId for unstable release

---

package.json

Preid fix for unstable v5

---

packages/auth/__tests__/auth-cognito-provider-unit-test.ts
packages/auth/src/Auth.ts
packages/auth/src/Providers/AmazonCognitoProvider.ts
packages/auth/src/types/aws-plugins/cognito-plugin/commands/command.ts
packages/auth/src/types/aws-plugins/cognito-plugin/commands/commandOutput.ts
packages/auth/src/types/aws-plugins/cognito-plugin/types/options/cognitoConfirmResetPasswordOptions.ts
packages/auth/src/types/aws-plugins/cognito-plugin/types/options/index.ts
packages/auth/src/types/index.ts
packages/auth/src/types/models/AuthPluginProvider.ts
packages/auth/src/types/request/confirmResetPasswordRequest.ts
packages/auth/src/types/request/index.ts
packages/auth/src/utils/CognitoIdentityProviderClientUtils.ts

Confirm reset password API rewrite. Adds new types for this API. Unit-tests

feat(auth): confirm reset password rewrite

---

packages/api-graphql/package.json
packages/api/package.json
packages/datastore/package.json

Updates bundle size limits for the `api-graphql`, `api`, and `datastore` categories to reflect latest improvements.

chore: Update bundle size limits to reflect latest improvements

---

.circleci/config.yml

feat(data): add vanilla JS + Webpack 4 DataStore E2E test
[Test run](https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/17614/workflows/dc156c2f-e956-4f1c-9676-773abcab3a78)

feat(data): add vanilla JS + Webpack 4 DataStore E2E test

---

.circleci/config.yml

feat(data): add Rollup + DataStore E2E tests

feat(data): add Rollup + DataStore E2E tests

---

packages/datastore/__tests__/commonAdapterTests.ts
packages/datastore/__tests__/helpers.ts
packages/datastore/src/storage/adapter/IndexedDBAdapter.ts

backport of https://github.com/aws-amplify/amplify-js/pull/10688
https://github.com/aws-amplify/amplify-js/issues/10685
* Unit tests
* Test in app

fix(datastore): optional hasOne (v4)

---

package.json

fix: preid change

---

package.json

fix: change preid to -v5

---

package.json
packages/analytics/src/Providers/AmazonPersonalizeHelper/MediaAutoTrack.ts
packages/datastore/src/sync/index.ts
packages/xr/package.json
packages/xr/src/Providers/SumerianProvider.ts
packages/xr/src/XR.ts

Amplify JS release 

---

.gitignore
packages/notifications/src/common/AWSPinpointProviderCommon/index.ts
packages/notifications/src/common/AWSPinpointProviderCommon/types.ts
packages/notifications/src/common/eventListeners/index.ts
packages/notifications/src/common/eventListeners/types.ts
packages/notifications/src/common/index.ts

This PR extracts common functionalities that will be used by both the existing In-App and upcoming Push Notification channels.
All changes in this PR are *additive* and thus introduces code duplication. Future PRs will update existing implementation to reference the extracted functionalities while removing the duplication.
Tested changes locally. Ran `yarn test`.

chore(notifications): Extract common functionalities

---

packages/rtn-push-notification/android/src/main/AndroidManifest.xml
packages/rtn-push-notification/android/src/main/kotlin/com/amazonaws/amplify/rtnpushnotification/PushNotificationAWSPinpointUtils.kt
packages/rtn-push-notification/android/src/main/kotlin/com/amazonaws/amplify/rtnpushnotification/PushNotificationEventManager.kt
packages/rtn-push-notification/android/src/main/kotlin/com/amazonaws/amplify/rtnpushnotification/PushNotificationFirebaseMessagingService.kt
packages/rtn-push-notification/android/src/main/kotlin/com/amazonaws/amplify/rtnpushnotification/PushNotificationHeadlessTaskService.kt
packages/rtn-push-notification/android/src/main/kotlin/com/amazonaws/amplify/rtnpushnotification/PushNotificationModule.kt
packages/rtn-push-notification/android/src/main/kotlin/com/amazonaws/amplify/rtnpushnotification/PushNotificationPackage.kt
packages/rtn-push-notification/android/src/main/kotlin/com/amazonaws/amplify/rtnpushnotification/PushNotificationUtils.kt
packages/rtn-push-notification/src/index.ts
packages/rtn-push-notification/src/types.ts

This PR adds the Android React Native module implementation for Push Notification. This native module enables the JS APIs on the Android platform which will be added in a future PR.
Tested functionality of the module locally with React Native apps versions < 0.71 and 0.71.

feat(notifications): Android native module implementation

---

packages/notifications/__tests__/InAppMessaging/Providers/AWSPinpointProvider/index.test.ts
packages/notifications/package.json
packages/notifications/src/InAppMessaging/Providers/AWSPinpointProvider/utils.ts
packages/notifications/src/Notifications.ts
packages/notifications/src/PushNotification/Platform/index.native.ts
packages/notifications/src/PushNotification/Platform/index.ts
packages/notifications/src/PushNotification/Platform/types.ts
packages/notifications/src/PushNotification/PlatformNotSupportedError.ts
packages/notifications/src/PushNotification/Providers/AWSPinpointProvider/index.ts
packages/notifications/src/PushNotification/Providers/AWSPinpointProvider/types.ts
packages/notifications/src/PushNotification/Providers/AWSPinpointProvider/utils.ts
packages/notifications/src/PushNotification/Providers/index.ts
packages/notifications/src/PushNotification/PushNotification.native.ts
packages/notifications/src/PushNotification/PushNotification.ts
packages/notifications/src/PushNotification/index.ts
packages/notifications/src/PushNotification/types.ts
packages/notifications/src/PushNotification/utils.ts
packages/notifications/src/common/AWSPinpointProviderCommon/index.ts
packages/notifications/src/common/constants.ts
packages/notifications/src/common/index.ts
packages/rtn-push-notification/android/src/main/kotlin/com/amazonaws/amplify/rtnpushnotification/PushNotificationEventManager.kt
packages/rtn-push-notification/android/src/main/kotlin/com/amazonaws/amplify/rtnpushnotification/PushNotificationFirebaseMessagingService.kt
packages/rtn-push-notification/android/src/main/kotlin/com/amazonaws/amplify/rtnpushnotification/PushNotificationModule.kt
packages/rtn-push-notification/src/types.ts

This PR adds the JavaScript functionality for the Push Notification channel of the Notifications category.
Tested locally against sample React Native apps

feat(notifications): Add Push Notification

---

.circleci/config.yml
package.json

Add `next` as a releasable branch & clean up old ones.

chore: Add `next` as releasable branch & cleanup old ones.

---

.circleci/config.yml
lerna.json
package.json
packages/aws-amplify/package.json
packages/xr/package.json

Updates `next` from `main` to pickup configuration changes to enable deployment.

chore: Update `next` from `main`

---

packages/rtn-push-notification/AmplifyRTNPushNotification.podspec
packages/rtn-push-notification/ios/AmplifyPushNotification.h
packages/rtn-push-notification/ios/AmplifyPushNotification.m
packages/rtn-push-notification/ios/AmplifyPushNotificationAppDelegateHelper.swift
packages/rtn-push-notification/ios/AmplifyRTNEventManager.swift
packages/rtn-push-notification/ios/AmplifyRTNPushNotification-Bridging-Header.h
packages/rtn-push-notification/ios/AmplifyRTNPushNotification.m
packages/rtn-push-notification/ios/AmplifyRTNPushNotification.swift
packages/rtn-push-notification/ios/AmplifyRTNPushNotificationManager.swift
packages/rtn-push-notification/ios/RtnPushNotification.xcodeproj/project.pbxproj
packages/rtn-push-notification/ios/RtnPushNotification.xcodeproj/project.xcworkspace/contents.xcworkspacedata
packages/rtn-push-notification/ios/RtnPushNotification.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist

Merge implementation of the react-native push notification iOS module/
Tested implementation with an example iOS App built with react-native.
Including:
* Receiving foreground notification
* Receiving background notification
* Request notification permissions
* Register device to Apple Push Notification
* Set and get App badge count
* App functionality running in background

feat(pn): add push notification ios native module

---

packages/notifications/src/PushNotification/types.ts
packages/notifications/src/PushNotification/utils.ts

This PR updates the PushNotificationMessage type to what should be its final shape. It also updates the normalizer to work with it and the latest round of changes from the Android utils.
Tested locally with sample RN app

chore(notifications): Update message normalizer

---

packages/rtn-push-notification/ios/AmplifyRTNEventManager.swift
packages/rtn-push-notification/ios/AmplifyRTNPushNotification.m
packages/rtn-push-notification/ios/AmplifyRTNPushNotification.swift
packages/rtn-push-notification/ios/AmplifyRTNPushNotificationManager.swift

Fix wrong constant being exported from the RN iOS module

fix(pn): wrong launchNotificationOpened constant exporting

---

packages/rtn-push-notification/android/src/main/kotlin/com/amazonaws/amplify/rtnpushnotification/PushNotificationAWSPinpointUtils.kt
packages/rtn-push-notification/android/src/main/kotlin/com/amazonaws/amplify/rtnpushnotification/PushNotificationFirebaseMessagingService.kt

This PR updates the push notification native module to share one more util function from the shared package to be published by Amplify Android
Tested changes locally with sample app to verify behavior is as intended

chore(notifications): Use shared remote message processing

---

packages/rtn-push-notification/ios/AmplifyRTNPushNotificationManager.swift

Refactored the logic of determining the launch notification. Details see comments in code.
* Xcode build
* Local App testing

fix(notifications): update iOS launch notification determining logic

---

package.json

chore: Tweaked `main` pre-id.

---

packages/notifications/__mocks__/data.ts
packages/notifications/__tests__/PushNotification/utils.test.ts
packages/notifications/babel.config.js
packages/notifications/src/PushNotification/utils.ts
packages/rtn-push-notification/android/build.gradle
packages/rtn-push-notification/android/gradle.properties
packages/rtn-push-notification/android/src/main/kotlin/com/amazonaws/amplify/rtnpushnotification/PushNotificationAWSPinpointUtils.kt
packages/rtn-push-notification/android/src/main/kotlin/com/amazonaws/amplify/rtnpushnotification/PushNotificationFirebaseMessagingService.kt
packages/rtn-push-notification/android/src/main/kotlin/com/amazonaws/amplify/rtnpushnotification/PushNotificationHeadlessTaskService.kt
packages/rtn-push-notification/android/src/main/kotlin/com/amazonaws/amplify/rtnpushnotification/PushNotificationLaunchActivity.kt
packages/rtn-push-notification/android/src/main/kotlin/com/amazonaws/amplify/rtnpushnotification/PushNotificationModule.kt

This PR updates React Native Push Notification to integrate with the latest refactoring of the Amplify Android common utilities.
* Tested locally with sample app.
* `$ yarn test`

chore(notifications): Integrate refactored Android common utils

---

packages/core/__tests__/clients/fetch-test.ts
packages/core/package.json
packages/core/src/clients/fetch.ts
packages/core/src/clients/types/core.ts
packages/core/src/clients/types/http.ts
packages/core/src/clients/types/index.ts

Basic interfaces for SDK clients and a fetch-based core handler implementation.
Unit tests

feat(clients): basic types and fetch handler

---

packages/notifications/src/PushNotification/types.ts

This PR fixes the typing for `onTokenReceived`
`yarn test`
Tested in local sample app

fix(notifications): Fix typing for onTokenReceived

---

packages/pubsub/src/Providers/MqttOverWSProvider.ts

Fix for topic symbol issue
#11114 

fix(pubsub): Topic symbol access regress

---

packages/notifications/package.json
packages/rtn-push-notification/package.json

This PR bumps the `@aws-amplify/rtn-push-notification` module to v1.0.0 for release
N/A

chore(notifications): Bump native module version to release version

---

.circleci/config.yml
package.json

update ci config for dry run

---

lerna.json
packages/notifications/src/PushNotification/types.ts

chore: Release process

---

packages/auth/src/Auth.ts

Fixed typo in Auth.verifyTotpToken log

chore: fixed typo in Auth.verifyTotpToken log

---

.circleci/config.yml

Enable tagged release of custom clients under `v5-custom-clients` dist-tag.

chore(clients): enable tagged release of custom clients

---

packages/core/__tests__/AwsClients/CognitoIdentity-test.ts
packages/core/src/AwsClients/CognitoIdentity/getCredentialsForIdentity.ts
packages/core/src/AwsClients/CognitoIdentity/getId.ts
packages/core/src/AwsClients/CognitoIdentity/index.ts
packages/core/src/clients/handlers/fetch.ts
packages/core/src/clients/internal/composeApiHandler.ts
packages/core/src/clients/middleware/retry/middleware.ts

1. Add functional test to Cognito Identity client based on API reference.
2. Prefer destructuring of parameters at the top of function.
3. Rename the API handlers I/O interface name.
Unit test; 

test(clients): add functional test to cognito identity client

---

packages/auth/package.json
packages/core/__tests__/AwsClients/CognitoIdentity-test.ts
packages/core/package.json
packages/core/src/AwsClients/CognitoIdentity/base.ts
packages/core/src/clients/middleware/userAgent/middleware.ts

Add userAgent to custom Cognito Identity client.
Unit test

feat(clients): add useragent to cognito identity

---

packages/core/src/AwsClients/CognitoIdentity/base.ts
packages/core/src/AwsClients/CognitoIdentity/getCredentialsForIdentity.ts
packages/core/src/AwsClients/CognitoIdentity/getId.ts
packages/core/src/AwsClients/CognitoIdentity/index.ts
packages/core/src/clients/handlers/fetch.ts
packages/core/src/clients/handlers/unauthenticated.ts
packages/core/src/clients/internal/composeApiHandler.ts
packages/core/src/clients/internal/composeTransferHandler.ts
packages/core/src/clients/middleware/retry/defaultRetryDecider.ts
packages/core/src/clients/middleware/retry/index.ts
packages/core/src/clients/middleware/retry/jitteredBackoff.ts
packages/core/src/clients/middleware/retry/middleware.ts
packages/core/src/clients/middleware/userAgent/index.ts
packages/core/src/clients/middleware/userAgent/middleware.ts
packages/core/src/clients/serde/index.ts
packages/core/src/clients/serde/json.ts
packages/core/src/clients/serde/responseInfo.ts
packages/core/src/clients/types/aws.ts
packages/core/src/clients/types/core.ts
packages/core/src/clients/types/http.ts
packages/core/src/clients/types/index.ts

Add missing license header to the custom clients utils.

chore(clients): add license header to files

---

packages/analytics/__tests__/Providers/AWSPinpointProvider.test.ts
packages/api-graphql/package.json
packages/api-rest/__tests__/RestAPI-test.ts
packages/api-rest/package.json
packages/api/package.json
packages/core/__tests__/Signer-test.ts
packages/core/__tests__/clients/middleware/signing/signer/signatureV4/presignUrl-test.ts
packages/core/__tests__/clients/middleware/signing/signer/signatureV4/signRequest-test.ts
packages/core/__tests__/clients/middleware/signing/signer/signatureV4/testUtils/signingTestTable.ts
packages/core/package.json
packages/core/src/Signer.ts
packages/datastore/package.json
packages/pubsub/package.json

This PR replaces the underlying implementation of the existing Signer with new SigV4 signing functions without changing
1. The Signer's overall class structure
2. The Signer's static function signatures
3. The Signer's static function output
1. Adapted Signer unit tests to more comprehensively test various input/output expectations
2. Swapped out Signer implementation
3. Made sure the same unit test suites passed
4. Tested the some call sites to validate signing was happening and services were not rejecting the requests

chore(clients): Replace existing Signer implementation

---

packages/aws-amplify/README.md

Making a minor document update recommended by Francisco. Including `feat(aws-amplify)` in the commit to increase the version so that the current `aws-amplify` versions don't conflict with previous `core` versions to disambiguate metrics.

feat(aws-amplify): Bump the aws-amplify minor version

---

packages/core/src/clients/middleware/signing/signer/signatureV4/utils/getFormattedDates.ts
packages/core/src/clients/middleware/signing/utils/extendedEncodeURIComponent.ts

This PR extracts a couple regex patterns to provide a bit of context to what they're matching.
`yarn test` to make sure containing functions are still working as intended

chore(clients): Add context to some regex

---

packages/core/src/AwsClients/CognitoIdentity/getCredentialsForIdentity.ts
packages/core/src/AwsClients/CognitoIdentity/getId.ts
packages/core/src/AwsClients/Pinpoint/updateEndpoint.ts

This PR cleans up custom client APIs a bit - Marking them as @internal.
No functional changes

chore(clients): Annotate custom client APIs with @internal

---

packages/core/__tests__/AwsClients/Pinpoint/putEvents-test.ts
packages/core/__tests__/AwsClients/Pinpoint/updateEndpoint-test.ts
packages/core/__tests__/AwsClients/testUtils/data.ts
packages/core/src/AwsClients/Pinpoint/index.ts
packages/core/src/AwsClients/Pinpoint/putEvents.ts

This PR adds the Pinpoint client `putEvents` API
Locally replaced API calls from Analytics and verified network request performed as expected

feat(clients) Add putEvents API

---

.circleci/config.yml

This reverts commit fca5451201365c915d5bb113a303f7f6d62e330d.
This change reverts the App Router canary change to hopefully resolve an issue with CircleCI.

Revert "chore: Added Next.js App Router canaries (#11360)"

---

.circleci/config.yml
packages/predictions/package.json
packages/predictions/src/Providers/AmazonAIConvertPredictionsProvider.ts

Previous release https://github.com/aws-amplify/amplify-js/pull/11366
Routine release of Amplify JS.
Integration tests & smoke testing.

release: Amplify JS release

---

.circleci/config.yml
package.json

Add pre-id build to enable custom user agent enhancement testing.

chore: Add pre-id build/release

---

packages/predictions/package.json

chore: Increase predicition size to match size creep

---

.circleci/config.yml

This change fixes an issue with our web canary executor due to an unexecutable script.
Test branch on CircleCI.

chore: Fix web canary execution

---

packages/storage/package.json

Update the size limit missed from https://github.com/aws-amplify/amplify-js/pull/11405

chore(storage): update size limit

---

.circleci/config.yml
packages/analytics/__tests__/Providers/CustomUserAgent.test.ts
packages/analytics/src/Providers/AWSKinesisFirehoseProvider.ts
packages/analytics/src/Providers/AWSKinesisProvider.ts
packages/analytics/src/Providers/AWSPinpointProvider.ts
packages/analytics/src/Providers/AmazonPersonalizeProvider.ts
packages/analytics/src/utils/UserAgent.ts
packages/core/src/Platform/types.ts
packages/core/src/index.ts

Update Analyitics providers to use the custom user agent, with basic tests.
Unit tests and basic app testing. This will need comprehensive Analytics provider testing before we release it.

feat(analytics): Use custom user agent in all Analytics providers

---

package.json

Seeing `@types/babel__traverse` type errors during core build.
Rerunning build/unit tests

fix: Core build issue

---

.github/workflows/aws-amplify-dependency-check.yml
package.json
packages/datastore/__tests__/mutation.test.ts
packages/datastore/__tests__/sync.test.ts
packages/datastore/src/sync/processors/mutation.ts
packages/datastore/src/sync/processors/sync.ts

Merge `main` into `feat/user-agent-enhancements/main`

chore: Merge from main

---

.circleci/config.yml

fix: Turn static geo test off

---

packages/analytics/__tests__/Providers/AWSPinpointProvider.test.ts
packages/analytics/src/Providers/AWSKinesisFirehoseProvider.ts
packages/analytics/src/Providers/AWSKinesisProvider.ts
packages/analytics/src/Providers/AWSPinpointProvider.ts
packages/analytics/src/Providers/AmazonPersonalizeProvider.ts
packages/analytics/src/utils/UserAgent.ts
packages/core/src/Platform/types.ts

When pinpoint records an updateEndpoint event, note this with its own customUserAgent action.

feat(analytics): Add reporting for updateEndpoint

---

.circleci/config.yml

Update playwright image version.

fix: Update playwrite image version

---

.circleci/config.yml
package.json
packages/api-rest/package.json
packages/auth/package.json
packages/geo/package.json
packages/interactions/package.json
packages/predictions/src/Providers/AmazonAIConvertPredictionsProvider.ts
packages/pubsub/package.json
packages/storage/package.json
scripts/dts-bundler/package.json

Release of build process, sdk dependency and Angular build fixes.
Integ tests are passing. The team will be manually testing prior to the release.

release(required): Amplify JS release

---

packages/analytics/package.json
packages/api-rest/package.json
packages/core/package.json
packages/core/src/Platform/types.ts
packages/notifications/package.json
packages/storage/__tests__/providers/CustomUserAgent.test.ts
packages/storage/src/providers/AWSS3Provider.ts

fix(storage): Add getProperties user agent action
Tests changed and succeeding

fix(storage): Add getProperties user agent action

---

packages/amazon-cognito-identity-js/src/Platform/constants.js
packages/amazon-cognito-identity-js/src/Platform/detectFramework.js
packages/amazon-cognito-identity-js/src/UserAgent.js
packages/analytics/__tests__/Providers/AWSPinpointProvider.test.ts
packages/api-graphql/package.json

fix: PR comments

---

packages/amazon-cognito-identity-js/__tests__/UserAgent.test.js

fix: Broken test

---

packages/predictions/src/Providers/AmazonAIIdentifyPredictionsProvider.ts

fix(predictions): Refactor shared identify user agent

---

.circleci/config.yml
package.json

Disable feature branch integ testing / preid builds
When this merges, the build will be very quick.

chore: Remove feat integ build configuration

---

packages/core/package.json

fix: Remove unused dependency

---

packages/storage/__tests__/AwsClients/S3/getPresignedGetObjectUrl-test.ts
packages/storage/src/AwsClients/S3/getObject.ts

* Ensure `defaultConfig.uriEscapePath` is applied to fix the PR title described failure
* Unit testing
* Local testing

fix(storage): fail to avoid double signing for presigned URL

---

packages/storage/__tests__/Storage-unit-test.ts
packages/storage/src/providers/AWSS3Provider.ts

Make sure correct access level param gets picked up initiating a multipart upload.
* unit test
* local manual test

fix(storage): vault uploads with public level with multipart upload

---

.circleci/config.yml
package.json

To make commits against `api-v6` branch create a tagged release as `api-v6`.

chore: add tagged releases to package.json and ci config

---

packages/api/package.json
packages/api/src/API.ts

Unblock tagged release publish to npm

---

packages/api/package.json

adjust coverage to unblock tagged release

---

packages/auth/__tests__/providers/cognito/confirmSignInHappyCases.test.ts
packages/auth/src/providers/cognito/apis/confirmSignIn.ts
packages/auth/src/providers/cognito/utils/clients/types/models.ts
packages/auth/src/providers/cognito/utils/signInHelpers.ts

chore: address feedback

---

packages/auth/__tests__/providers/cognito/auth-storage-manager.test.ts
packages/auth/__tests__/providers/cognito/testUtils/helpers.ts
packages/auth/__tests__/providers/cognito/testUtils/mocks.ts
packages/auth/src/common/AuthErrorStrings.ts
packages/auth/src/storage/DeviceKeyTokenManager.ts
packages/auth/src/storage/LegacyDeviceKeyTokenManager.ts
packages/auth/src/storage/LegacyUserPoolManager.ts
packages/auth/src/storage/UserPoolTokenManager.ts
packages/auth/src/storage/constants.ts
packages/auth/src/storage/helpers.ts
packages/auth/src/storage/keys.ts
packages/auth/src/storage/types/index.ts
packages/auth/src/storage/types/models.ts
packages/core/__tests__/JS-node-runtime-test.ts
packages/core/__tests__/storage/cookieStorage-test.ts
packages/core/__tests__/storage/inMemoryStorage-test.ts
packages/core/__tests__/storage/localStorage-test.ts
packages/core/__tests__/storage/sessionStorage-test.ts
packages/core/__tests__/storage/storage-mechanisms-node-runtime-test.ts
packages/core/src/Errors.ts
packages/core/src/StorageHelper/CookieStorage.ts
packages/core/src/StorageHelper/InMemoryStorage.ts
packages/core/src/StorageHelper/LocalStorage.ts
packages/core/src/StorageHelper/SessionStorage.ts
packages/core/src/StorageHelper/index.ts
packages/core/src/index.ts
packages/core/src/types/types.ts

feat: add userpool token manager

---

packages/api-rest/package.json
packages/core/package.json
packages/core/src/Platform/types.ts
packages/geo/package.json
packages/notifications/__tests__/InAppMessaging/InAppMessaging.test.ts
packages/notifications/internals/inAppMessaging/package.json
packages/notifications/package.json
packages/notifications/src/InAppMessaging/InAppMessaging.ts
packages/notifications/src/InAppMessaging/Providers/AWSPinpointProvider/index.ts
packages/notifications/src/InAppMessaging/internals/InternalInAppMessaging.ts
packages/notifications/src/InAppMessaging/internals/index.ts
packages/notifications/src/InAppMessaging/internals/utils.ts
packages/notifications/src/InAppMessaging/types.ts
packages/notifications/src/Notifications.ts
packages/notifications/src/common/AWSPinpointProviderCommon/index.ts
packages/notifications/src/types.ts
packages/pubsub/package.json
packages/storage/package.json

Feat/custom user agent UI/inappmessaging

---

CONTRIBUTING.md
packages/analytics/README.md
packages/api-graphql/README.md
packages/api-rest/README.md
packages/api/README.md
packages/auth/README.md
packages/aws-amplify/README.md
packages/core/README.md
packages/datastore/README.md
packages/geo/README.md
packages/interactions/README.md
packages/notifications/README.md
packages/predictions/README.md
packages/pubsub/README.md
packages/storage/README.md

This change adds "internal package" notices to the README files of our scoped packages for display in NPM to push people towards the umbrella package. Included a few other minor cleanup changes.

chore: Add internal package notices to scoped packages

---

package.json
packages/api/package.json
packages/api/src/API.ts

Simplified version of https://github.com/aws-amplify/amplify-js/pull/11671 without template literal types.
* Adds new V6 client types.

feat(api): add basic model types

---

packages/core/package.json
packages/core/src/singleton/Auth/utils/index.ts

- Fix `decodeJWT` function
- Increase bundle size for v5 (get rid of the error, but we need to add V6 size-limits test)

Fix decodeJWT issue and bundle size limits

---

packages/storage/src/errors/StorageError.ts
packages/storage/src/errors/assertValidationErrors.ts
packages/storage/src/errors/types/validation.ts

Implement the StorageError class and error messages map and ensure it aligns with the Auth category.

feat(storage): add StorageError and credentials validation

---

packages/core/src/index.ts
packages/core/src/singleton/Storage/types.ts
packages/core/src/singleton/types.ts
packages/storage/src/types/common.ts
packages/storage/src/types/index.ts

Add Storage-specific configuration interfaces and library options interfaces

feat(storage): functional storage library options

---

packages/storage/__tests__/utils/prefixResolver.test.ts
packages/storage/src/utils/prefixResolver.ts

Default prefix resolver for functional storage
Unit test

feat(storage): implement default prefix resolver

---

.github/workflows/on-schedule-canary-test.yml

Run canaries only on schedule, remove canary runs on pull request.

fix: update on-schedule-canary-test.yml

---

packages/amazon-cognito-identity-js/package.json
packages/cache/src/AsyncStorageCache.ts
packages/core/package.json
yarn.lock

Update version of `shell-quote` to resolve depandabot issues.
ran `yarn build` and `yarn test`

chore: update react-native version

---

packages/auth/src/index.ts
packages/auth/src/providers/cognito/tokenProvider/TokenOrchestrator.ts
packages/auth/src/providers/cognito/tokenProvider/TokenStore.ts
packages/auth/src/providers/cognito/tokenProvider/index.ts
packages/auth/src/providers/cognito/tokenProvider/types.ts
packages/aws-amplify/src/index.ts
packages/aws-amplify/src/initSingleton.ts
packages/core/__tests__/singleton/Singleton-test.ts
packages/core/src/index.ts
packages/core/src/singleton/Auth/index.ts
packages/core/src/singleton/Auth/types.ts
packages/core/src/singleton/index.ts

- Add default provider token provider to umbrella package
- Add fetchAuthSession API to `aws-amplify/auth`

Add default token provider to aws-amplify

---

scripts/utility.js

Exclude the macOS generated `.DS_Store` file from the build process.

chore: exclude .DS_Store file from the build process

---

.github/workflows/codeql.yml

Updates CodeQL to run for PRs against `next`.

chore: Fix CodeQL configuration on next

---

packages/pubsub/__tests__/AWSAppSyncRealTimeProvider.test.ts
packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider/index.ts

Send PubSub user agent to Auth.currentAuthenticatedUser and Auth.currentSession calls.
Added checks in unit test and tests passing

feat: capture PubSub metrics on cross-category auth calls

---

packages/notifications/__tests__/InAppMessaging/Providers/AWSPinpointProvider/utils.test.ts
packages/notifications/__tests__/PushNotification/Providers/AWSPinpointProvider/utils.test.ts
packages/notifications/src/InAppMessaging/Providers/AWSPinpointProvider/index.ts
packages/notifications/src/InAppMessaging/Providers/AWSPinpointProvider/utils.ts
packages/notifications/src/PushNotification/Providers/AWSPinpointProvider/index.ts
packages/notifications/src/PushNotification/Providers/AWSPinpointProvider/utils.ts
packages/notifications/src/common/constants.ts
packages/notifications/src/common/index.ts

This PR standardizes notification hub events to non-existence
`yarn test`

chore(notifications): Remove hub usage from notifications

---

packages/auth/src/providers/cognito/credentialsProvider/credentialsProvider.ts
packages/auth/src/providers/cognito/tokenProvider/TokenStore.ts
packages/core/__tests__/singleton/Singleton-test.ts
packages/core/src/singleton/index.ts

Fix token provider not available or not configured issue. Return `null` if there is not provider or is not configured

Fix fetch auth session without token provider

---

packages/storage/__tests__/providers/AWSS3Provider-unit-test.ts
packages/storage/src/common/StorageUtils.ts
packages/storage/src/providers/AWSS3Provider.ts

This PR standardizes storage hub events to non-existence

chore: remove storage Hub events

---

packages/auth/__tests__/providers/cognito/fetchUserAttributes.test.ts
packages/auth/src/providers/cognito/apis/fetchUserAttributes.ts
packages/auth/src/providers/cognito/apis/updatePassword.ts
packages/auth/src/providers/cognito/index.ts
packages/auth/src/providers/cognito/utils/apiHelpers.ts
packages/auth/src/types/requests.ts

The `fetchUserAttributes` API returns the current user attributes 
**API changes**
- calls the `GetUser` client to get the user attributes.
**Other changes**
- fix a typo on `updatePassword` API
**Test  cases**
- tests that `fetchUserAttributes` returns the right format of user attributes.
- tests services error
I tested this API with a sample App

feat(auth): add `fetchUserAttributes` API

---

packages/core/src/Hub/index.ts

Fixed `unknown` type assertions for Hub apis.
Changed `listener` type in Hub class.
Tested with a sample app

fix(core): remove type assertion for listeners

---

packages/aws-amplify/src/utils/index.ts
packages/core/src/index.ts
packages/core/src/libraryUtils.ts

Removes Signer from the `aws-amplify/utils` export surface.

chore: Remove Signer from customer surface

---

packages/auth/build.js
packages/auth/internals/package.json
packages/auth/package.json
packages/auth/src/index.ts
packages/auth/src/internals/index.ts
packages/auth/tsconfig.build.json

Cleans up auth export surface including the unused `internals` path and removes unused build scripts & config files.

chore: Clean up Auth exports & scripts

---

packages/core/package.json

Fix for core `npm run test:size` failure.

fix: Bunde size checks for core

---

packages/adapter-nextjs/package.json
packages/aws-amplify/package.json
packages/storage/package.json

This change updates our Storage bundle size tests to use the new functional APIs. Also added a few "combined" test cases exercising common permutations of APIs.

chore: Update Storage bundle size tests

---

packages/adapter-nextjs/package.json

chore(adapter-next): make the package publishable

---

package.json
packages/adapter-nextjs/package.json
packages/analytics/webpack.config.js
packages/api-graphql/webpack.config.js
packages/api-rest/webpack.config.js
packages/api/webpack.config.js
packages/auth/webpack.config.js
packages/aws-amplify/webpack.config.js
packages/core/webpack.config.js
packages/datastore-storage-adapter/webpack.config.js
packages/datastore/webpack.config.js
packages/geo/webpack.config.js
packages/interactions/webpack.config.js
packages/notifications/webpack.config.js
packages/predictions/webpack.config.js
packages/pubsub/webpack.config.js
packages/rtn-push-notification/webpack.config.js
packages/storage/webpack.config.js
yarn.lock

Updates `console-preview` from `next` with a change to make the new SSR package publishable.

chore: Update `console-preview` from `next`

---

packages/core/__tests__/singleton/Singleton-test.ts
packages/core/src/singleton/Auth/index.ts
packages/core/src/singleton/Auth/types.ts

Adds `userSub` to `fetchAuthSession`

Fix: fetchAuthSession with userSub

---

packages/adapter-nextjs/__tests__/runWithAmplifyServerContext.test.ts
packages/adapter-nextjs/__tests__/withAmplify.test.ts
packages/core/src/singleton/Storage/types.ts
packages/storage/__tests__/providers/s3/copy.test.ts
packages/storage/__tests__/providers/s3/downloadData.test.ts
packages/storage/__tests__/providers/s3/getProperties.test.ts
packages/storage/__tests__/providers/s3/getUrl.test.ts
packages/storage/__tests__/providers/s3/list.test.ts
packages/storage/__tests__/providers/s3/remove.test.ts
packages/storage/src/providers/AWSS3Provider.ts
packages/storage/src/providers/s3/utils/getKeyWithPrefix.ts
packages/storage/src/providers/s3/utils/resolveS3ConfigAndInput.ts
packages/storage/src/providers/s3/utils/resolveStorageConfig.ts

This change updates the Storage config shape to move everything under the new `S3` key. Also renamed `AWSS3` to `S3` in `LibraryStorageOptions`.

chore: Update Storage config shape

---

packages/aws-amplify/src/initSingleton.ts
packages/aws-amplify/tsconfig.json

This change enabled strict mode in `aws-amplify`.
Local testing.

chore: Enable strict mode in `aws-amplify`

---

packages/adapter-nextjs/__tests__/withAmplify.test.ts
packages/adapter-nextjs/src/runWithAmplifyServerContext.ts
packages/adapter-nextjs/src/utils/getAmplifyConfig.ts
packages/adapter-nextjs/src/withAmplify.ts

* Updated the import path of `parseAmplifyConfig` in `adapter-nextjs`
* Updated the documentation of `withAmplify` re: the need of using `parseAmplifyConfig` and provided example
* Added description of usage of the `parse`

chore(adapter-nextjs): update withAmplify documentation and import path of parseAmplifyConfig

---

packages/storage/src/providers/s3/apis/getUrl.ts
packages/storage/src/providers/s3/apis/list.ts
packages/storage/src/providers/s3/apis/remove.ts

Add clear documentation to storage apis

chore(storage): add clear documentation to storage apis

---

packages/storage/__tests__/providers/s3/apis/remove.test.ts
packages/storage/src/providers/s3/types/options.ts
packages/storage/src/types/options.ts

This change involves removing the targetIdentityId from `upload`, `copy` api

fix(storage): remove targetIdentityId from upload  and copy api

---

packages/adapter-nextjs/__tests__/withAmplify.test.ts
packages/adapter-nextjs/src/runWithAmplifyServerContext.ts
packages/adapter-nextjs/src/utils/getAmplifyConfig.ts
packages/adapter-nextjs/src/withAmplify.ts
packages/storage/__tests__/providers/s3/apis/copy.test.ts
packages/storage/__tests__/providers/s3/apis/getProperties.test.ts
packages/storage/__tests__/providers/s3/apis/getUrl.test.ts
packages/storage/__tests__/providers/s3/apis/list.test.ts
packages/storage/__tests__/providers/s3/apis/remove.test.ts
packages/storage/src/providers/s3/apis/getUrl.ts
packages/storage/src/providers/s3/apis/internal/getUrl.ts
packages/storage/src/providers/s3/apis/list.ts
packages/storage/src/providers/s3/apis/remove.ts
packages/storage/src/providers/s3/types/options.ts
packages/storage/src/types/options.ts

Routine sync of `console-preview` from the new `next/main` branch.

chore: Sync `console-preview` from `next/main`

---

.github/workflows/codeql.yml

- `CodeQL` is a mandatory check to merge PRs to `next/release` `next/main`. 
- Update `next` to `next/release` `next/main`
(tested workflows linked below)
- codeql [does not run](https://github.com/aws-amplify/amplify-js/pull/11999/checks) without this change
- codeql runs on [next/release](https://github.com/ashwinkumar6/amplify-js/pull/3/checks) and [next/main](https://github.com/ashwinkumar6/amplify-js/pull/4/checks) with this change

chore(actions): run codeql workflow on next/release next/main

---

packages/aws-amplify/__tests__/adapterCore/authProvidersFactories/cognito/createUserPoolsTokenProvider.test.ts
packages/aws-amplify/__tests__/exports.test.ts
packages/aws-amplify/__tests__/initSingleton.test.ts
packages/aws-amplify/src/initSingleton.ts
packages/core/src/singleton/Amplify.ts
packages/core/src/singleton/types.ts

- Add unit tests for initSingleton
* Moved `ssr` flag into the second param of `Amplify.configure()`, the `libraryOptions`
* Updated the logic in `initSingleton` using the `ssr` flag
* Added unit tests for `initSingleton`

chore(core,aws-amplify): move ssr flag into the libraryOptions param

---

packages/aws-amplify/src/utils/index.ts

This change removes extra `aws-amplify/utils` exports that shouldn't be included in preview.

chore: Remove extra util exports

---

packages/auth/src/providers/cognito/apis/verifyTOTPSetup.ts
packages/auth/src/providers/cognito/types/index.ts
packages/auth/src/providers/cognito/types/options.ts

chore(auth): fix typo

---

packages/auth/src/providers/cognito/apis/signInWithRedirect.ts

Allows `sideEffect` to parseURL after is loaded
RC when `sideEffect` is executed after `config` event is trigger

fix urlListener when is imported after configure

---

packages/auth/src/providers/cognito/apis/signInWithRedirect.ts

This change syncs `next/release` from `next/main` to pick up a missing bug fix. Confirmed that no GA changes have been merged to `next/main` yet and this change is safe to make.
**This change will be merged as a merge commit.**

chore: Sync `next/release` from `next/main`

---

.github/workflows/codeql.yml
packages/adapter-nextjs/__tests__/utils/getAmplifyConfig.test.ts
packages/adapter-nextjs/__tests__/withAmplify.test.ts
packages/adapter-nextjs/src/utils/getAmplifyConfig.ts
packages/adapter-nextjs/src/withAmplify.ts
packages/auth/cognito/server/package.json
packages/auth/package.json
packages/auth/src/providers/cognito/apis/verifyTOTPSetup.ts
packages/auth/src/providers/cognito/types/index.ts
packages/auth/src/providers/cognito/types/options.ts
packages/aws-amplify/__tests__/adapterCore/authProvidersFactories/cognito/createUserPoolsTokenProvider.test.ts
packages/aws-amplify/__tests__/exports.test.ts
packages/aws-amplify/__tests__/initSingleton.test.ts
packages/aws-amplify/auth/cognito/server/package.json
packages/aws-amplify/package.json
packages/aws-amplify/src/auth/cognito/server/index.ts
packages/aws-amplify/src/initSingleton.ts
packages/aws-amplify/src/utils/index.ts
packages/core/src/parseAWSExports.ts
packages/core/src/singleton/Amplify.ts
packages/core/src/singleton/types.ts
packages/storage/__tests__/providers/s3/apis/list.test.ts
packages/storage/package.json
packages/storage/src/providers/s3/apis/internal/list.ts
packages/storage/src/types/requests.ts

Sync console preview from `next/release` to pick up the latest changes.

chore: Sync `console-preview` from `next/release`

---

packages/auth/src/providers/cognito/apis/signInWithRedirect.ts
packages/core/__tests__/singleton/Singleton.test.ts
packages/core/src/singleton/Auth/index.ts
packages/core/src/singleton/Auth/types.ts

chore:sync next/release with console-preview

---

packages/core/__tests__/clients/fetch.test.ts
packages/core/package.json
packages/core/src/clients/handlers/fetch.ts
yarn.lock

Remove the unneeded `isomorphic-unfetch` and `@types/node-fetch` dependencies.
* `yarn test` && `yarn build`
* Tested locally with the next.js sample app

chore(core): remove the isomorphic-unfetch dependency

---

packages/api-graphql/src/GraphQLAPI.ts
packages/api-graphql/src/internals/InternalGraphQLAPI.ts
packages/api-rest/src/RestClient.ts
packages/api/src/API.ts
packages/api/src/internals/InternalAPI.ts
packages/core/src/clients/middleware/signing/signer/signatureV4/utils/getSigningValues.ts

fix issues with API Key and IAM

---

packages/storage/src/providers/s3/types/index.ts
packages/storage/src/providers/s3/types/outputs.ts

- `ListAllOutput`, `ListPaginateOutput` currently expose 3 extra types `versionId`, `contentType` and `metadata`. Remove these
- remove unused `DownloadFileOutput` type
A complete list of all storage APIs input and output types exposed to the customer  
- getPropertiesInput
- GetPropertiesInput
- GetPropertiesOutput
- getUrl
- GetUrlInput
- GetUrlOutput
- copy
- CopyInput
- CopyOutput
- remove
- RemoveInput
- RemoveOutput
- list
- default
- ListPaginateInput
- ListAllInput
- ListPaginateOutput
- ListAllOutput
- uploadData
- UploadDataInput
- UploadDataOutput
- downloadData
- downloadDataInput
- downloadDataOutput

fix(storage): fix listOutput types

---

packages/storage/src/index.ts
packages/storage/src/types/index.ts

Export required interfaces to build utility functions on top of Storage APIs.

feat(storage): export additional types

---

packages/api-graphql/src/Providers/AWSAppSyncRealTimeProvider/index.ts
packages/api-graphql/src/types/index.ts
packages/api-rest/src/index.ts
packages/api-rest/src/types/index.ts

fix types for post options

---

packages/adapter-nextjs/src/runWithAmplifyServerContext.ts
packages/adapter-nextjs/src/types/NextServer.ts
packages/adapter-nextjs/tslint.json

Add detailed inline doc for `runWithAmplifyServerContext` of the `adapter-nextjs` package.

chore(adapter-nextjs): improve the inline doc

---

packages/adapter-nextjs/__tests__/runWithAmplifyServerContext.test.ts
packages/auth/__tests__/providers/cognito/credentialsProvider.test.ts

This PR fixes a couple test references to an export member no longer being exported
`yarn test`

fix: Update test references to removed export

---

.github/workflows/push-next-release.yml

Disable next tag pushing until we're ready.

chore: Disable next tag push.

---

packages/analytics/src/providers/pinpoint/types/inputs.ts
packages/storage/src/providers/s3/types/inputs.ts
packages/storage/src/providers/s3/types/outputs.ts

Add doc to provider input output types 

chore(doc): add doc to provider input output types

---

.github/integ-config/integ-all.yml

Uncomment the e2e storage integration tests and enable them with correct spec files.

chore(storage): enable storage e2e tests

---

.github/integ-config/integ-all.yml
packages/adapter-nextjs/__tests__/utils/getAmplifyConfig.test.ts
packages/adapter-nextjs/__tests__/withAmplify.test.ts
packages/adapter-nextjs/src/utils/getAmplifyConfig.ts
packages/adapter-nextjs/src/withAmplify.ts
packages/aws-amplify/__tests__/exports.test.ts
packages/aws-amplify/__tests__/initSingleton.test.ts
packages/aws-amplify/package.json
packages/aws-amplify/src/adapterCore/index.ts
packages/aws-amplify/src/index.ts
packages/aws-amplify/src/initSingleton.ts
packages/core/__tests__/singleton/Singleton.test.ts
packages/core/src/index.ts
packages/core/src/libraryUtils.ts
packages/core/src/singleton/Amplify.ts
packages/core/src/singleton/types.ts
yarn.lock

chore: merge next/release into preview-testing

---

.github/workflows/push-next-release.yml

This change enables automatic publication to the `next` tag with changes are merged to `next/release` (assuming they pass tests).

chore: Enable publishing of the `next` tag

---

.github/integ-config/integ-all.yml

Add Analytics sample app test to v6 integ tests.
I ran it against my fork and confirmed that the new tests work - https://github.com/stocaaro/amplify-js/actions/runs/6228076731

chore: Reintroduce analytics integ test

---

scripts/set-preid-versions.sh

Update preid for the `aws-amplify` that is listed as peer deps in `package.json` of packages.

chore(repo): update preid for peer-dep aws-amplify

---

packages/adapter-nextjs/package.json

fix(adapter-nextjs): correct the wrong directory included in distribution

---

packages/aws-amplify/__tests__/exports.test.ts

Sets up export surface tests on the `aws-amplify` umbrella package to make sure we're not polluting the surface over time.

chore: Setup export surface tests

---

package.json
packages/storage/src/providers/s3/utils/client/runtime/xmlParser/pureJs.ts
yarn.lock

- fix script `yarn test`
- generate new yarn.lock
- fix type issue generated due to new yarn.lock

chore: generate new yarn.lock

---

packages/aws-amplify/package.json

adds datastore dir to be published on aws-amplify

---

packages/aws-amplify/package.json

Sync `console-preview` tag with `next/main` to fix DS publication.

chore: Sync `console-preview` tag with `next/main`

---

packages/api-graphql/package.json
packages/api-graphql/src/Providers/AWSAppSyncRealTimeProvider/index.ts
packages/api-graphql/src/types/PubSub.ts
packages/api-graphql/src/utils/ConnectionStateMonitor.ts
packages/api-graphql/src/utils/ReconnectionMonitor.ts
packages/core/__tests__/BackgroundProcessManager.test.ts
packages/core/package.json
packages/core/src/Reachability/Reachability.native.ts
packages/core/src/Reachability/Reachability.ts
packages/datastore-storage-adapter/__tests__/SQLiteAdapter.test.ts
packages/datastore-storage-adapter/__tests__/SQLiteCPKDisabled.test.ts
packages/datastore-storage-adapter/__tests__/SQLiteCPKEnabled.test.ts
packages/datastore/__tests__/DataStore.ts
packages/datastore/__tests__/connectivityHandling.test.ts
packages/datastore/__tests__/helpers/datastoreFactory.ts
packages/datastore/__tests__/helpers/fakes/connectivityMonitor.ts
packages/datastore/__tests__/helpers/fakes/graphqlService.ts
packages/datastore/__tests__/helpers/schemas/typeOnlyModels.ts
packages/datastore/__tests__/storage.test.ts
packages/datastore/__tests__/subscription.test.ts
packages/datastore/package.json
packages/datastore/src/datastore/datastore.ts
packages/datastore/src/storage/storage.ts
packages/datastore/src/sync/datastoreConnectivity.ts
packages/datastore/src/sync/index.ts
packages/datastore/src/sync/processors/mutation.ts
packages/datastore/src/sync/processors/subscription.ts
packages/datastore/src/sync/processors/sync.ts
yarn.lock

Replacing zen-obvservables with rxjs

---

packages/rtn-web-browser/android/src/main/kotlin/com/amazonaws/amplify/rtnwebbrowser/WebBrowserModule.kt
packages/rtn-web-browser/src/apis/openAuthSessionAsync.ts
packages/rtn-web-browser/src/index.ts
packages/rtn-web-browser/src/nativeModule.ts

This PR makes some small cleanup work to the web-browser module - the module getter is no longer a part of the api but just a root file instead.
`yarn test`

chore: Minor cleanup of web browser module

---

packages/auth/__tests__/providers/cognito/confirmSignInHappyCases.test.ts
packages/auth/__tests__/providers/cognito/signInErrorCases.test.ts
packages/auth/__tests__/providers/cognito/signInStateManagement.test.ts
packages/auth/src/providers/cognito/apis/confirmSignIn.ts
packages/auth/src/providers/cognito/apis/signInWithCustomAuth.ts
packages/auth/src/providers/cognito/apis/signInWithCustomSRPAuth.ts
packages/auth/src/providers/cognito/apis/signInWithRedirect.ts
packages/auth/src/providers/cognito/apis/signInWithSRP.ts
packages/auth/src/providers/cognito/apis/signInWithUserPassword.ts
packages/auth/src/providers/cognito/apis/signOut.ts
packages/core/src/Hub/types/AuthTypes.ts
yarn.lock

**Main changes:**
- changes the v5 `signIn` event to `signedIn` to align with native.
- changes the v5 `signOut` event to `signedOut` to align with native.
Tested new hub events in a sample app.

feat(auth): add signedIn and signedOut hub events

---

packages/auth/__tests__/utils/openAuthSession.native.test.ts
packages/auth/src/providers/cognito/apis/signInWithRedirect.ts
packages/auth/src/utils/openAuthSession.native.ts
packages/auth/src/utils/types.ts
packages/rtn-web-browser/ios/AmplifyRTNWebBrowser.swift
yarn.lock

This PR adds similar error handling to web if an auth session fails to open for some reason.
* `yarn test`
* Tested against a React Native application on both Android and iOS

chore(auth): improve error handling

---

packages/auth/src/providers/cognito/apis/signInWithRedirect.ts

* Await for the code exchange to complete to resolve the promise returned by `signInWithRedirect` in react-native.

fix(auth): signInWithRedirect to complete with code exchange in RN

---

packages/analytics/__tests__/providers/kinesis/apis/flushEvents.test.ts
packages/analytics/src/providers/kinesis/apis/flushEvents.ts
packages/analytics/src/providers/kinesis/apis/index.ts
packages/analytics/src/providers/kinesis/index.ts
packages/aws-amplify/__tests__/exports.test.ts

- add `flushEvents` API for service provider Kinesis Data Stream

feat(analytics): add flushEvents API for service provider KDS

---

packages/analytics/__tests__/providers/kinesis-firehose/apis/flushEvents.test.ts
packages/analytics/src/providers/kinesis-firehose/apis/flushEvents.ts
packages/analytics/src/providers/kinesis-firehose/apis/index.ts
packages/analytics/src/providers/kinesis-firehose/index.ts
packages/aws-amplify/__tests__/exports.test.ts

- add `flushEvents` API for service provider Kinesis Data Firehose

feat(analytics): add flushEvents API for service provider KDF

---

packages/analytics/__tests__/providers/personalize/apis/flushEvents.test.ts
packages/analytics/src/providers/personalize/apis/flushEvents.ts
packages/analytics/src/providers/personalize/apis/index.ts
packages/analytics/src/providers/personalize/index.ts
packages/aws-amplify/__tests__/exports.test.ts

- add `flushEvents` API for service provider Personalize

feat(analytics): add flushEvents API for service provider Personalize

---

packages/core/src/Hub/index.ts
packages/core/src/libraryUtils.ts

**PR changes:**
-exports the `HubClass` as `internal/utils`.

chore(core): export hub class 

---

packages/analytics/__tests__/providers/pinpoint/apis/flushEvents.test.ts
packages/analytics/src/index.ts
packages/analytics/src/providers/pinpoint/apis/flushEvents.ts
packages/analytics/src/providers/pinpoint/apis/index.ts
packages/analytics/src/providers/pinpoint/index.ts
packages/aws-amplify/__tests__/exports.test.ts
packages/core/__tests__/providers/pinpoint/apis/flushEvents.test.ts
packages/core/src/providers/pinpoint/apis/flushEvents.ts
packages/core/src/providers/pinpoint/apis/index.ts
packages/core/src/providers/pinpoint/utils/PinpointEventBuffer.ts

- add `flushEvents` API for service provider Pinpoint

feat(analtics): add flushEvents for service provider Pinpoint

---

packages/analytics/__tests__/providers/pinpoint/apis/flushEvents.test.ts
packages/analytics/src/providers/kinesis-firehose/apis/flushEvents.ts
packages/analytics/src/providers/kinesis-firehose/apis/record.ts
packages/analytics/src/providers/kinesis-firehose/utils/getEventBuffer.ts
packages/analytics/src/providers/kinesis/apis/flushEvents.ts
packages/analytics/src/providers/kinesis/apis/record.ts
packages/analytics/src/providers/kinesis/utils/getEventBuffer.ts
packages/analytics/src/providers/personalize/apis/flushEvents.ts
packages/analytics/src/providers/personalize/apis/record.ts
packages/analytics/src/providers/personalize/types/buffer.ts
packages/analytics/src/providers/personalize/utils/getEventBuffer.ts
packages/analytics/src/providers/pinpoint/apis/flushEvents.ts
packages/core/src/providers/pinpoint/apis/flushEvents.ts

- customize `User-Agent` header for aws clients

fix(analytics): customize user-agent header for aws client

---

lerna.json
package.json
packages/api-graphql/__tests__/v6-test.ts
packages/api-graphql/package.json
packages/api-graphql/src/Providers/AWSAppSyncRealTimeProvider/index.ts
packages/api-graphql/src/internals/InternalGraphQLAPI.ts
packages/api-graphql/src/types/PubSub.ts
packages/api-graphql/src/types/index.ts
packages/api-graphql/tsconfig.json
packages/api/src/index.ts
packages/aws-amplify/package.json
packages/notifications/package.json
packages/rtn-push-notification/package.json
packages/storage/package.json
packages/storage/src/providers/s3/utils/client/runtime/package.json
yarn.lock

chore: Sync console-preview with next/main

---

packages/auth/src/providers/cognito/utils/srp/getSignatureString.ts

Use the `textEncoder` proxy to ensure the encoding works in RN.

fix(auth): use the amplify self-vended TextEncoder proxy

---

packages/api-rest/package.json
packages/api/package.json

Missed from REST API PR, include `server` and `internal` subpaths for REST API category.
Local publish.

chore(api): include internals and server paths when publish

---

packages/auth/__tests__/providers/cognito/tokenProvider.test.ts
packages/auth/src/providers/cognito/apis/confirmSignIn.ts
packages/auth/src/providers/cognito/apis/signInWithCustomAuth.ts
packages/auth/src/providers/cognito/apis/signInWithCustomSRPAuth.ts
packages/auth/src/providers/cognito/apis/signInWithRedirect.ts
packages/auth/src/providers/cognito/apis/signInWithSRP.ts
packages/auth/src/providers/cognito/apis/signInWithUserPassword.ts
packages/auth/src/providers/cognito/tokenProvider/TokenOrchestrator.ts
packages/auth/src/providers/cognito/tokenProvider/TokenStore.ts
packages/auth/src/providers/cognito/tokenProvider/cacheTokens.ts
packages/auth/src/providers/cognito/tokenProvider/types.ts
packages/auth/src/providers/cognito/utils/refreshAuthTokens.ts
packages/auth/src/providers/cognito/utils/signInWithRedirectStore.ts

Refactor token store to use V5 keys (avoid migration)

Update Token Storage to use V5 keys

---

packages/core/__tests__/parseAWSExports.test.ts
packages/core/src/parseAWSExports.ts

Adds logic to parse AWS exports file and extract Notifications portions into the internally used config format. 
yarn link 
parses the aws-exports file containing Notifications and InAppMessaging

chore(config): add notifications exports file parsing

---

packages/aws-amplify/package.json

Missed from revious REST API PR. Make sure the `aws-amplify/api/server` subpath working properly with Next.js

fix(aws-amplify): server export path

---

packages/aws-amplify/package.json
packages/core/__tests__/parseAWSExports.test.ts
packages/core/src/parseAWSExports.ts

chore: Sync console-preview with `next/main`

---

packages/analytics/package.json
yarn.lock

Moves some Analytics dependencies to Dev Dependencies.

fix: Analytics dependencies

---

packages/api/package.json
packages/aws-amplify/package.json
packages/datastore/package.json
packages/geo/package.json
packages/notifications/package.json

chore: Added Analytics & tweaked other bundle size limits.

---

packages/core/__tests__/utils/globalHelpers/globalHelpers.native.test.ts
packages/core/src/utils/globalHelpers/index.native.ts
packages/react-native/src/index.ts
packages/react-native/src/moduleLoaders/index.ts
packages/react-native/src/moduleLoaders/loadBase64.ts

* Added `loadBase64` in `packages/react-native`
* Refactored `packages/core` to use the loader function instead of import from transitive dependent package
Published update packages locally and tested with a react-native by sign-in a user and decode JWT tokens.

feat(react-native): add loadBase64 module loader

---

.github/integ-config/integ-all.yml

- add integration test config for Analytics with Kinesis Data Firehose service provider.
https://github.com/aws-amplify/amplify-js/actions/runs/6472761491

test(analytics): add integration test config for KDF

---

packages/api/package.json
yarn.lock

bump @aws-amplify/amplify-api-next-types-alpha

---

packages/core/src/Reachability/Reachability.ts

Re-adding private function for E2E testing

feat(data): add observer override to core Reachability util

---

packages/api-graphql/__tests__/fixtures/modeled/amplifyconfiguration.js
packages/api-graphql/__tests__/fixtures/modeled/schema.ts
packages/api-graphql/__tests__/generateClient.test.ts

Adds tests for basic lazy-loading cases.

test: add basic api-graphql lazy loading tests

---

.github/workflows/callable-release-verification.yml

chore: Api v6 rebase 2023 10 11 disable tests

---

packages/auth/src/providers/cognito/utils/refreshAuthTokens.ts

fix(auth): return username from lastAuthUser in refresh tokens action

---

packages/adapter-nextjs/src/utils/createCookieStorageAdapterFromNextServerContext.ts

* Aligned encoding strategy with `js-cookie`
* Renamed the util function making its purpose clearer
- Local Next.js sample app testing.

fix(adapter-nextjs): update the cookie name encoding function

---

.github/integ-config/integ-all.yml

Re-introducing test for sample app `v2/public-auth-iam-v2`
Depends upon: https://github.com/aws-amplify/amplify-js-samples-staging/pull/635
https://github.com/stocaaro/amplify-js/actions/runs/6509132153
https://github.com/stocaaro/amplify-js/actions/runs/6509132153/job/17681013875

chore: Reintroduce v2/public-auth-iam-v2 integ test

---

.github/workflows/callable-release-verification.yml
packages/api/__tests__/models/APIClient.test.ts
packages/api/package.json
packages/api/src/API.ts
packages/api/src/APIClient.ts
packages/api/src/types/index.ts
yarn.lock

* bumps types version with latest custom sel set changes
* adds recursive flatten fn to flatten entire reponse
* tests

bump types package and add recursive flatten

---

packages/core/src/Platform/types.ts
packages/geo/src/providers/location-service/AmazonLocationServiceProvider.ts
packages/geo/src/util.ts

chore(geo): update geo api calls to use custom user agent

---

packages/api-graphql/__tests__/APIClient.test.ts
packages/api-graphql/package.json
packages/api-graphql/src/internals/APIClient.ts
packages/api-graphql/src/internals/generateModelsProperty.ts
packages/api-graphql/src/types/index.ts
packages/api/src/index.ts
packages/api/src/types/index.ts
yarn.lock

backport recent changes from v5; bump types

---

.github/workflows/push-preid-release.yml

This is the new `api-v6-models` branched off of `api-v6-rebase-2023-10-11`
Flipping the tagged release pre-id

tagged release api-v6-models

---

packages/core/src/Platform/types.ts
packages/core/src/libraryUtils.ts

Refactors custom user agent types to support integration.

chore: Refactor custom user agent types for UI integration

---

packages/notifications/__tests__/inAppMessaging/providers/pinpoint/apis/identifyUser.test.ts
packages/notifications/src/inAppMessaging/providers/pinpoint/apis/identifyUser.ts
packages/notifications/src/inAppMessaging/types/inputs.ts

Removes the nested serviceOptions
yarn test

chore(inapp): remove serviceOptions

---

packages/core/package.json
yarn.lock

upgrade @aws-crypto/sha256-js package to latest 5.2.0 with ESM artifacts.
Manual test on Angular shows no warnings.

feat(deps): upgrade sha256-js to 5.2.0 with esm artifacts

---

packages/api-graphql/src/internals/generateModelsProperty.ts

custom sel set result matches shape

---

packages/interactions/package.json
packages/interactions/src/lex-v1/apis/onComplete.ts
packages/interactions/src/lex-v1/index.ts
packages/interactions/src/lex-v2/apis/onComplete.ts
yarn.lock

- add deprecation announcement for LexV1 module.

fix(interactions): add deprecation announcement for LexV1 module

---

lerna.json
package.json
packages/datastore-storage-adapter/package.json
yarn.lock

* Re-enabled `packages/datastore-storage-adapter` in the workspace.
* Made it build-able

chore(datastore-storage-adapter): enable workspace and publish

---

.github/integ-config/detox-integ-all.yml

chore: enable integ_rn_ios_datastore_sqlite_adapter

---

.github/integ-config/detox-integ-all.yml

chore: fix integ_rn_ios_datastore_sqlite_adapter path

---

.vscode/launch.json
packages/datastore/__tests__/subscription.test.ts
packages/datastore/src/sync/processors/errorMaps.ts
packages/datastore/src/sync/processors/subscription.ts

Integration test subs disable was broken

fix(datastore): subs disable issue

---

.vscode/launch.json
packages/api-graphql/__tests__/APIClient.test.ts
packages/api-graphql/src/internals/APIClient.ts

fix deep sel set

---

packages/amazon-cognito-identity-js/android/build.gradle
packages/amazon-cognito-identity-js/android/src/hasNamespace/AndroidManifest.xml
packages/amazon-cognito-identity-js/android/src/main/AndroidManifest.xml
packages/rtn-push-notification/android/build.gradle
packages/rtn-push-notification/android/src/hasNamespace/AndroidManifest.xml

Details see https://github.com/aws-amplify/amplify-js/pull/12368
Fixes https://github.com/aws-amplify/amplify-js/issues/12306

fix: make the android modules compatible with AGP 8

---

packages/auth/__tests__/providers/cognito/identityIdProvider.test.ts
packages/auth/src/providers/cognito/credentialsProvider/IdentityIdStore.ts
packages/aws-amplify/__tests__/exports.test.ts
packages/notifications/__tests__/inAppMessaging/providers/pinpoint/apis/clearMessages.test.ts
packages/notifications/src/inAppMessaging/index.ts
packages/notifications/src/inAppMessaging/providers/pinpoint/apis/clearMessages.ts
packages/notifications/src/inAppMessaging/providers/pinpoint/apis/index.ts
packages/notifications/src/inAppMessaging/providers/pinpoint/index.ts

Removes stale TODOs that already have implementations and add the missing clearMessages APIs
yarn test and test cases

fix(inapp): remove implemented todos and add clearMessages API

---

.github/integ-config/integ-all.yml

Activate predictions integ test
Sample app runs locally and test passes in cypress

test: activate predictions integ tests

---

packages/datastore/__tests__/DataStore.ts
packages/datastore/__tests__/IndexedDBAdapter.test.ts

```
Test Suites: 25 passed, 25 total
Tests:       14 skipped, 1116 passed, 1130 total
Snapshots:   8 passed, 8 total
Time:        131.832s, estimated 136s
```
Same coverage as V5

Reenabling last 2 DS unit tests

---

packages/pubsub/package.json

Makes PubSub private again to prevent publication to NPM.
Tested in Verdaccio.

chore: Make PubSub private again

---

packages/api-graphql/__tests__/GraphQLAPI.test.ts
packages/api-graphql/src/internals/InternalGraphQLAPI.ts

Re-add subscription tests
Running the tests

fix(api-graphql): Reintroduce subscription tests

---

.github/integ-config/integ-all.yml
packages/interactions/package.json

- make Interactions private
- disable Interactions integ test
- disable pubSub integ test

chore(interactions): make package private

---

package.json

Update release command to deploy to a dist-tag to simplify the release process. Packages will be installable with version number alone, e.g. `"aws-amplify": "^6.0.0",`
Verdaccio

chore: Update release deployment target

---

packages/notifications/src/pushNotifications/types/index.ts
packages/notifications/src/pushNotifications/types/inputs.ts
packages/notifications/src/pushNotifications/types/module.ts
packages/notifications/src/pushNotifications/types/pushNotifications.ts
packages/react-native/src/index.ts
packages/rtn-push-notification/src/types/module.ts

Cherry-picking this onto `next/main`. Original PR: https://github.com/aws-amplify/amplify-js/pull/12446

fix(notifications): Duplicate types from optional packages (#12446)

---

packages/adapter-nextjs/package.json

Makes `adapter-nextjs` private to prepare for initial release.

chore: Make `adapter-nextjs` private

---

.github/integ-config/integ-all.yml

Disable SSR tests until `adapter-nextjs` package is ready.

chore: Disable SSR tests

---

packages/adapter-nextjs/package.json

chore(adapter-nextjs): make package public

---

.github/integ-config/integ-all.yml

Re-enables SSR tests now that the `adapter-nextjs` package is being published again.

chore: Re-enables SSR tests

---

.vscode/launch.json
packages/adapter-nextjs/__tests__/api/generateServerClient.test.ts
packages/adapter-nextjs/src/api/generateServerClient.ts
packages/api-graphql/__tests__/generateClient.test.ts
packages/api-graphql/__tests__/server/generateClient.test.ts
packages/api-graphql/internals/server/package.json
packages/api-graphql/package.json
packages/api-graphql/src/internals/APIClient.ts
packages/api-graphql/src/internals/generateClient.ts
packages/api-graphql/src/internals/operations/get.ts
packages/api-graphql/src/internals/operations/list.ts
packages/api-graphql/src/internals/operations/observeQuery.ts
packages/api-graphql/src/internals/operations/subscription.ts
packages/api-graphql/src/internals/server/generateClient.ts
packages/api-graphql/src/internals/server/generateModelsProperty.ts
packages/api-graphql/src/internals/server/index.ts
packages/api-graphql/src/types/index.ts
packages/api/package.json
packages/api/src/server.ts
packages/api/tsconfig.json
yarn.lock

Note: build failure expected until [this PR](https://github.com/aws-amplify/amplify-api-next/pull/29) is merged.

generateServerClient with models

---

packages/aws-amplify/data/package.json
packages/aws-amplify/data/server/package.json

add aws-amplify/data subpath aliased to /api

---

packages/adapter-nextjs/__tests__/api/generateServerClient.test.ts
packages/adapter-nextjs/package.json
packages/aws-amplify/data/package.json
packages/aws-amplify/data/server/package.json

publish adapter-nextjs to tag api-v6-models

---

packages/adapter-nextjs/data/package.json
packages/adapter-nextjs/package.json
packages/aws-amplify/package.json

add /data subpath to adapter-nextjs

---

packages/aws-amplify/package.json

chore: Tweak bundle size limits(increase)

---

package.json
packages/adapter-nextjs/package.json
yarn.lock

chore(adapter-nextjs): bump Next.js version range

---

packages/aws-amplify/__tests__/exports.test.ts
packages/aws-amplify/src/utils/index.ts

Expose the following storage helpers:
- CookieStorage
- defaultStorage
- sessionStorage
- sharedInMemoryStorage
- KeyValueStorageInterface

chore(amplify-js/utils): expose storage helpers

---

packages/api-graphql/package.json
packages/api/src/API.ts
yarn.lock

chore(api-graphql): bump types dep to 0.2.8

---

packages/core/__tests__/clients/middleware/signing/utils/getUpdatedSystemClockOffset.test.ts

test(core): fix clock skew unit test

---

packages/api/src/index.ts
packages/aws-amplify/__tests__/exports.test.ts

export connection state type and enum from /api

---

packages/react-native/android/build.gradle
packages/rtn-push-notification/android/build.gradle
packages/rtn-web-browser/android/build.gradle

This PR updates React Native native module packages to have unique namespaces defined in their `build.gradle` files to avoid build time collisions.
Using Verdaccio, locally verified changes fixed issue with Android app building

fix(react-native): Update namespaces to be unique

---

packages/adapter-nextjs/package.json
yarn.lock

chore(adapter-nextjs): bump the min support version of Next.js

---

packages/adapter-nextjs/package.json
yarn.lock

chore(adapter-nextjs): remove unused server-only dep

---

.github/actions/setup-samples-staging/action.yml
.github/workflows/push-preid-release.yml
packages/api-graphql/package.json
packages/api-graphql/tsconfig.json
packages/api-rest/package.json
packages/api-rest/tsconfig.json
packages/api/package.json
packages/api/tsconfig.json
packages/aws-amplify/package.json
packages/datastore-storage-adapter/package.json
packages/datastore/package.json
packages/pushnotification/package.json
yarn.lock

- upgrade axios version on `api-rest`
- upgrade typescript version to `5.0.2` and build scripts on `api-rest`, `api-graphql` and `api` packages similar to `core`
Axios version needs to be upgrade
- unit tests
- smoke test

chore(deps): upgrade axios to 1.6.0

---

packages/rtn-push-notification/android/build.gradle

This PR updates React Native native module packages to have unique namespaces defined in their `build.gradle` files to avoid build time collisions. This is being backported to v5 since the module is ultimately a standalone package even though it is, as of v5, the only native module in this project.

fix(react-native): Update namespace to be unique

---

.github/workflows/codeql.yml

Enables CodeQL for PRs against the `v5-stable` branch.
This PR's checks.

chore: Enable CodeQL on `v5-stable` branch

---

packages/api-graphql/package.json
yarn.lock

chore(api-graphql): bumped amplify-api-next-types-alpha version

---

packages/api-graphql/package.json
packages/api-graphql/src/internals/generateModelsProperty.ts
packages/api-graphql/src/types/index.ts
yarn.lock

point to approved dep

---

packages/api-graphql/package.json
yarn.lock

Models bump types package & merge main again

---

packages/api-graphql/__tests__/APIClient.test.ts

Merge main commits

---

packages/api-graphql/package.json
yarn.lock

fix: bump data-schema-types to unblock RN

---

packages/core/src/singleton/Auth/types.ts
packages/core/src/singleton/Auth/utils/index.ts

chore(auth): add AtLeastOne type

---

packages/adapter-nextjs/__tests__/createServerRunner.test.ts
packages/adapter-nextjs/package.json
packages/adapter-nextjs/tsconfig.json

Flips on `noImplicitAny` in `adapter-nextjs`.

chore: Flip on `noImplicitAny` on `adapter-nextjs`

---

README.md

- Update library version
- Point to v6 migration guide

Update README.md to v6

---

packages/api-graphql/src/utils/resolveConfig.ts

fix(data): fix ConsoleLogger argument typo

---

packages/auth/src/index.ts
packages/auth/src/providers/cognito/apis/confirmSignInWithOTP.ts
packages/auth/src/providers/cognito/apis/signInWithOTP.ts
packages/auth/src/providers/cognito/index.ts
packages/auth/src/providers/cognito/types/inputs.ts
packages/auth/src/providers/cognito/types/models.ts
packages/auth/src/providers/cognito/types/options.ts
packages/auth/src/providers/cognito/types/outputs.ts

Passwordless APIs TODOs:
1. Add user context 
2. Clean up code
3. Add sign-up case
4. Add magic link case

feat(auth): add otp passwordless 

---

packages/core/__tests__/adapterCore/serverContext.test.ts
packages/core/src/adapterCore/serverContext/serverContext.ts

Add a validation of the `contextSpec` object to cover the case that TS type check won't take place so it throws more meaningful error for debugging.

chore(core): add contextSpec object shape validation for better debugging

---

.github/canary-config/canary-all.yml
.github/workflows/callable-canary-sampleapp-tests.yml

Comment known flakey tests while data-team on-call fixes and can reduce on-call alerts.
🏃‍♀️ into https://github.com/aws-amplify/amplify-js/actions/runs/7035198896/job/19145236233 please please see
I think comments can not be validated

chore: comment Integ_next datastore_owner_auth

---

README.md

* Removed lgtm badage (the service has shut down in 2022)
* Can use Github analysis flow but requires a separate set up
* Replaced Circle CI build badge with the main branch GH action workflow status
* Replace HTML wit the markdown syntax

chore(repo): update badges in README

---

packages/adapter-nextjs/package.json

This change updates the `aws-amplify` peer dependency in `adapter-nextjs` to account for a function that was renamed in 6.0.7. See also: https://github.com/aws-amplify/amplify-js/pull/12691

chore: Update adapter-nextjs `aws-amplify` peer dep

---

.github/ISSUE_TEMPLATE/1.bug_report.yaml

Update the issue template
N/A
N/A

chore: Update bug report template

---

packages/api-rest/package.json
yarn.lock

Upgrades Axios in v5 to ^1.6.5 to address several new SNYK findings.
Smoke testing API rest.

chore: Upgrade Axios to 1.6.5

---

packages/react-native/package.json
yarn.lock

Bump the react-native dev dependencies to `0.71.0` for the `@aws-amplify/react-native` package.
Removed the has been deprecated package `@types/react-native`

chore(react-native): use react-native 0.71.0 as the dev dep

---

.github/workflows/callable-unit-tests.yml

chore: temporarily disable codecov GH action integration

---

packages/logging/__tests__/providers/cloudwatch/utils/loggingConstraints.test.ts
packages/logging/__tests__/providers/cloudwatch/utils/setUpRemoteConfigurationRefresh.test.ts
packages/logging/jest.config.js
packages/logging/src/errors/LoggingError.ts
packages/logging/src/errors/index.ts
packages/logging/src/providers/cloudwatch/apis/configure.ts
packages/logging/src/providers/cloudwatch/types/configuration.ts
packages/logging/src/providers/cloudwatch/utils/index.ts
packages/logging/src/providers/cloudwatch/utils/loggingConstraints.ts
packages/logging/src/providers/cloudwatch/utils/setUpRemoteConfigurationRefresh.ts

This PR adds the initial util for an interval refresher to fetch remote logging constraints
Tested locally against a NextJS app

feat(logging): Add remote configuration refresh mechanism

---

package.json
packages/adapter-nextjs/package.json
packages/analytics/package.json
packages/api-graphql/package.json
packages/api-rest/package.json
packages/api/package.json
packages/auth/package.json
packages/aws-amplify/package.json
packages/core/package.json
packages/datastore-storage-adapter/package.json
packages/datastore/package.json
packages/geo/package.json
packages/interactions/package.json
packages/notifications/package.json
packages/predictions/package.json
packages/pubsub/package.json
packages/react-native/package.json
packages/rtn-push-notification/package.json
packages/rtn-web-browser/package.json
packages/storage/package.json
yarn.lock

Revert "chore(repo): use typescript 5.0.2 across workspace"

---

packages/notifications/src/inAppMessaging/errors/validation.ts

Tiny typo fix for the InApp error message
- [] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)

fix(inApp): typo in error message

---

package.json
scripts/setup-dev-rn.js

The main change on [Line 195](https://github.com/aws-amplify/amplify-js/compare/main...Samaritan1011001:amplify-js:chore/rn-script?expand=1#diff-fa1ac283b88d32d0143192f441a8a76826946eb69bd8378bab92c9f861866491R195) uses a common `build:watch` command

fix(rn-script): build script usage

---

yarn.lock

Updates our `yarn.lock` to include Winston, which was added in: https://github.com/aws-amplify/amplify-js/pull/12990
Resolves pipeline blockage: https://github.com/aws-amplify/amplify-js/actions/runs/7839305519/job/21393124929

chore: Update yarn.lock file

---

packages/api-graphql/src/internals/APIClient.ts

fix(api-graphql): remove unnecessary console.log

---

.github/workflows/push-integ-test.yml
packages/storage/src/errors/types/validation.ts
packages/storage/src/providers/s3/apis/downloadData.ts
packages/storage/src/providers/s3/types/options.ts
packages/storage/src/types/inputs.ts
packages/storage/src/types/options.ts

- Update the deprecation message to reflect product
- Add Integ test on feature branch

Chore: Update Storage deprecation warning

---

packages/api-graphql/__tests__/fixtures/modeled/schema.ts
packages/api-graphql/package.json
yarn.lock

* Bump the version of `@aws-amplify/data-schema`
* Removed `.returns()` on custom subscriptions from the test fixture

chore(api-graphql): bump data-schema package version

---

packages/api-graphql/package.json
yarn.lock

chore(api-graphql): bump data-schema

---

yarn.lock

Updates our transitive follow-redirects dependency in response to a CVE.

chore: Upgrade transitive follow-redirects dependency

---

packages/api-graphql/package.json
yarn.lock

Bump `data-schema` and `data-schema-types` minor version to gain the latest feature changes.

chore(api-graphql): bump data-schema packages versions

---

packages/api-graphql/package.json
yarn.lock

* bumps `data-schema` dep to latest
* build/test

chore: bump data-schema dep to latest

---

.github/integ-config/integ-all.yml

chore: enable oauth test

---

.github/integ-config/integ-all.yml

feat(auth): enable gen2 e2e tests

---

.husky/pre-commit
.lintstagedrc.mjs
license_config.json
package.json
yarn.lock

Enabling run `eslint --fix` in the pre-commit hook to fixing linter and styling issues that may exist in the staged files.

chore(repo): run linter fix against staged files in pre-commit hook

---

.github/integ-config/integ-all.yml
.github/workflows/callable-canary-e2e.yml
.github/workflows/callable-e2e-test-detox.yml
.github/workflows/callable-release-verification.yml

chore: cherry-pick update macos version to latest (#13350)

---

.github/CODEOWNERS
package.json
packages/api/__tests__/API-test.ts
packages/api/package.json
packages/api/src/API.ts
packages/api/src/types/index.ts
packages/auth/__tests__/auth-unit-test.ts
packages/auth/src/Auth.ts
packages/predictions/__tests__/Predictions-unit-test.ts

- Node 16.14.0
- Webpack <=4 
- If Webpack 5 is used customers need to install the `util^0.12.4` dependency 
- ignores deprecated UI packages from lerna
- fixes `auth`, `predictions` and `graph-ql` unit tests
- update code owners
- Smoke test auth and graphql using a sample app

fix(v1): update deps and unit tests

---

packages/core/src/singleton/Amplify.ts

Updates a doc-string comment for the Amplify singleton.

chore: Update Amplify doc-string comment

---

.github/integ-config/integ-all.yml

feat: enable sign-in-with-oauth on vue

---

packages/notifications/src/types.ts

- Changed the type `PushNotification` to `Push` so that the expected `config` shape matches the the generated config object.
- Our public v5 doc will be updated according to this change, `aws-amplify/rtn-push-notification`  is only compatible with version  `@~1.1.x`. Will include callouts on the doc(https://github.com/aws-amplify/docs/pull/7689).
https://github.com/aws-amplify/amplify-js/issues/11855
- I've run locally and test with IOS sample app. Receiving expected results. 

fix(notifications): Fixed type error for Push Notification config

---

README.md
packages/aws-amplify/README.md

Fixes some incorrect/broken links in our README files.

chore: Fix broken README links

---

.github/CODEOWNERS

chore: add additional codeowners

---

.github/CODEOWNERS

chore: add additional paths and codeowners

---

.github/PULL_REQUEST_TEMPLATE.md

Update PR checklist to include adding/updating E2E tests. These tests can only be modified/run internally by the team hence we're not adding a section on `CONTRIBUTIONS`. It's crucial to make sure E2E tests are added/updated along with a new feature. 
============= Preview  =============
============= Preview  =============

chore: update PRs checklist to also add/update E2E tests

---

.github/integ-config/integ-all.yml

This change enables the [guest access](https://github.com/aws-amplify/amplify-js-samples-staging/tree/main/samples/next/storage/guest-access) Next JS App on CI

feat(storage): enable storage Next JS app

---

packages/aws-amplify/package.json
packages/core/__tests__/parseAmplifyOutputs.test.ts
packages/core/src/parseAmplifyOutputs.ts
packages/core/src/singleton/AmplifyOutputs/types.ts
packages/core/src/singleton/Storage/types.ts
packages/core/src/singleton/types.ts
packages/interactions/package.json

This PR holds parsing of the multi-bucket config from amplify outputs into ResourceConfig

[Multibucket]Parse AmplifyOutputs update

---

.github/workflows/push-integ-test.yml
packages/auth/src/providers/cognito/apis/signUp.ts

chore: test e2e tests on ci

---

.github/integ-config/integ-all.yml

The purpose of this pull request is to update the integration test list to correctly reference the updated Next.js storage application name.
[Test Run](https://github.com/jjarvisp/amplify-js/actions/runs/10220881365)

[Multi-bucket] update next.js storage integ test info

---

.github/actions/load-verdaccio-with-amplify-js/action.yml
.github/actions/node-and-build/action.yml
.github/integ-config/integ-all.yml
.github/workflows/callable-e2e-test.yml
.github/workflows/callable-e2e-tests.yml
package.json
packages/aws-amplify/package.json
packages/core/__tests__/utils/globalHelpers/globalHelpers.test.ts
packages/core/src/utils/globalHelpers/index.ts

This reverts commit 37d26277e4cbacdc8e34e8a6810b08ef7c4a8f49.

Revert "feat(core): resolve webcrypto from node:crypto for Node18 (#13599)"

---

packages/storage/__tests__/providers/s3/apis/copy.test.ts
packages/storage/__tests__/providers/s3/apis/uploadData/multipartHandlers.test.ts
packages/storage/src/providers/s3/types/inputs.ts
packages/storage/src/types/inputs.ts

Update multi-bucket test & type

[Chore] Update multi-bucket test & type

---

yarn.lock

chore(deps): bump axios from 1.7.3 to 1.7.4 on v5

---

.github/integ-config/integ-all.yml
packages/auth/__tests__/providers/cognito/signOut.test.ts
packages/auth/__tests__/providers/cognito/tokenOrchestrator.test.ts
packages/auth/__tests__/providers/cognito/tokenProvider/tokenOrchestrator.test.ts
packages/auth/__tests__/providers/cognito/utils/oauth/completeOAuthFlow.test.ts
packages/auth/__tests__/providers/cognito/utils/oauth/handleOAuthSignOut.test.ts
packages/auth/src/providers/cognito/apis/signOut.ts
packages/auth/src/providers/cognito/tokenProvider/TokenOrchestrator.ts
packages/auth/src/providers/cognito/tokenProvider/TokenStore.ts
packages/auth/src/providers/cognito/tokenProvider/types.ts
packages/auth/src/providers/cognito/utils/oauth/completeOAuthFlow.ts
packages/auth/src/providers/cognito/utils/oauth/handleOAuthSignOut.ts

This change cherry picks PR [#73712](https://github.com/aws-amplify/amplify-js/pull/13712) and enables subdomain e2e test

chore(auth): cherry-picks PR #73712 and enables subdomain test

---

packages/storage/package.json
yarn.lock

chore(storage-browser): pin crc-32 dep at 1.2.2

---

.github/workflows/callable-e2e-test-detox.yml

chore: use macos-latest-large to run detox driven tests

---

package.json
scripts/process-typedoc.mjs
typedoc.json

As part of the api docs migration typedoc will be exported as a json file and then flattened to be used by the docs repo to generate the api docs pages.

add process script and update typedoc config

---

.github/actions/load-verdaccio-with-amplify-js/action.yml
.github/actions/node-and-build/action.yml
.github/integ-config/integ-all.yml
.github/workflows/callable-e2e-test.yml
.github/workflows/callable-e2e-tests.yml
package.json
packages/core/__tests__/utils/globalHelpers/globalHelpers.test.ts
packages/core/src/utils/globalHelpers/index.ts

https://github.com/aws-amplify/amplify-js/issues/13817
https://github.com/aws-amplify/amplify-js/issues/13819
Couldn't reproduce the build issue with a minimal React and a minimal Angular app. 
Reverting this change and release as a patch to unblock the build failures.

release(required): Revert "Reapply "feat(core): resolve webcrypto from node:crypto for Node18 (#13599)" (#13775)"

---

.github/workflows/push-preid-release.yml

Enable e2e and tagged release on GH actions

chore: enable e2e and tagged release

---

packages/storage/internals/package.json
packages/storage/package.json
packages/storage/src/internals/apis/index.ts
packages/storage/src/internals/index.ts
packages/storage/src/internals/types/index.ts

Sets up a placeholder subpath for internal Storage functionality.

feat: Setup storage internals route

---

.github/CODEOWNERS

chore: update codeowner ids

---

packages/storage/src/providers/s3/apis/uploadData/multipart/uploadHandlers.ts

When trying to perform multiPart upload in RN we get a `Unhandled promise [Unknown: An unknown error has occurred.]` caught via a [failing E2E test](https://github.com/aws-amplify/amplify-js/actions/runs/11130071435/job/30932658251).
When further drilling down we notice that in `validateMultipartUploadXML.ts` [IntegrityError is hit](https://github.com/ashwinkumar6/amplify-js/blob/storage-browser/integrity/packages/storage/src/providers/s3/utils/validateMultipartUploadXML.ts#L34C13-L34C27).
input
```
{"Parts": [{"ChecksumCRC32": undefined, "ETag": "\"848b2c7322636ccc636d55baf1210ff7\"", "PartNumber": 1}, {"ChecksumCRC32": undefined, "ETag": "\"7ab0dbfb705203814ea1f941748a565b\"", "PartNumber": 2}, {"ChecksumCRC32": undefined, "ETag": "\"5f2c0e194104481a542a2ebb4cd4cc10\"", "PartNumber": …
```

fix: multipart upload storage crc32 integrity

---

scripts/dts-bundler/dts-bundler.config.js

* The `tsconfig.json` path has changed while migrating eslint, and the ds bundler didn't get a corresponding update.
* Also fixes the `sdk.ts` file name in the Auth package

chore: fix dts bundler config

---

packages/core/src/libraryUtils.ts

chore(core): export AiUserAgentInput

---

packages/core/src/Platform/types.ts

chore(ai): add UpdateConversation enum

---

.github/integ-config/integ-all.yml

PR to enable e2e test for internal storage APIs. SampleStaging [PR that adds](https://github.com/aws-amplify/amplify-js-samples-staging/pull/991) this test.
[CI run](https://github.com/aws-amplify/amplify-js/actions/runs/11301363797)

chore(ci): add new storage-gen2-internal e2e test

---

packages/storage/src/providers/s3/utils/client/utils/createRetryDecider.ts

Fix Retry decider which cause retry on network error fail

Fix: retry failure in storage retryDecider

---

packages/core/src/singleton/Auth/types.ts

remove duplicate "email" entry in OAuthScope type definition
fixes #14016 

chore(core): remove redundant "email" from OAuthScope type definition

---

packages/storage/__tests__/providers/s3/utils/client/S3/cases/copyObject.ts
packages/storage/__tests__/providers/s3/utils/client/s3Data/copyObject.test.ts
packages/storage/src/providers/s3/utils/client/s3data/copyObject.ts

fix(storage): bug in copy unmodified since to use UTC

---

packages/core/__tests__/parseAmplifyOutputs.test.ts
packages/core/src/singleton/AmplifyOutputs/types.ts

release(required): fix amplify configure with auth userGroups

---

packages/core/README.md

bump the version of out of sync packages that [didn't get published](https://github.com/aws-amplify/amplify-js/actions/runs/12146780119/job/33874606081#step:4:5889) in the previous release attempt
running `yarn publish:release` locally without `--yes` :
```
Changes:
- @aws-amplify/adapter-nextjs: 1.2.31 => 1.2.32
- @aws-amplify/analytics: 7.0.61 => 7.0.62
- @aws-amplify/api: 6.1.6 => 6.1.7
- @aws-amplify/api-graphql: 4.6.4 => 4.6.5
- @aws-amplify/api-rest: 4.0.61 => 4.0.62
- @aws-amplify/auth: 6.8.1 => 6.8.2
- aws-amplify: 6.10.1 => 6.10.2
- @aws-amplify/core: 6.7.1 => 6.7.2
- @aws-amplify/datastore: 5.0.63 => 5.0.64
- @aws-amplify/datastore-storage-adapter: 2.1.63 => 2.1.64
- @aws-amplify/geo: 3.0.61 => 3.0.62
- @aws-amplify/interactions: 6.1.2 => 6.1.3
- @aws-amplify/notifications: …
```

 fix: bump package version

---

.github/CODEOWNERS

chore: update CODEOWNER

---

.github/workflows/callable-canary-e2e.yml
.github/workflows/callable-e2e-test-detox.yml
.github/workflows/callable-release-verification.yml

chore: use macos-latest in workflows

---

.github/workflows/callable-canary-sampleapp-tests.yml

Similar to: https://github.com/aws-amplify/amplify-js/pull/14083 
Missed updating a script

fix(ci): update javascript canary build step

---

.github/integ-config/integ-all.yml

- Provide `NEXT_PUBLIC_BACKEND_CONFIG` as env variable for `sign-in-resumable-mfa`

fix(auth): provide NEXT_PUBLIC_BACKEND_CONFIG for resumable mfa E2E

---

.github/workflows/push-preid-release.yml

Enabling preid publishing for the feature branch. 

chore: enable tag publishing for server-auth

---

.github/actions/node-and-build/action.yml
.github/actions/setup-samples-staging/action.yml
.github/workflows/callable-get-package-list.yml

https://github.com/actions/cache/discussions/1510
https://github.com/aws-amplify/amplify-js/actions/runs/12718141103/job/35456135357?pr=14133#step:3:4

chore: upgrade action/cache to 4.2.0

---

.github/actions/node-and-build/action.yml
.github/workflows/callable-canary-e2e-tests.yml
packages/analytics/package.json
packages/api-graphql/package.json
packages/api-rest/package.json
packages/api/package.json
packages/auth/package.json
packages/datastore/package.json
packages/interactions/package.json
packages/predictions/package.json

fix(v5): using node 18 in GH actions

---

.github/actions/node-and-build/action.yml
.github/actions/setup-samples-staging/action.yml
.github/workflows/callable-canary-e2e-tests.yml
.github/workflows/callable-e2e-test-headless.yml
.github/workflows/callable-e2e-test.yml
.github/workflows/callable-get-package-list.yml

chore: sync GH action updates to v5-stable

---

packages/adapter-nextjs/package.json

chore(adapter-nextjs): bump the lower bond of peer aws-amplify

---

.github/workflows/callable-e2e-test.yml

Define the NODE_ENV options in the Github action level to ensure all node processes have consistent behavior throughout.

chore: for v5 E2E node env to use consistent settings

---

packages/auth/__tests__/providers/cognito/credentialsProvider/credentialsProvider.test.ts
packages/auth/__tests__/providers/cognito/testUtils/authApiTestParams.ts
packages/auth/src/providers/cognito/credentialsProvider/credentialsProvider.ts

* Ensure service returned `identityId` gets updated into the in-memory storage.
* Updated unit test to verify service returned `identityId` actually gets consumed and returned. 

fix(auth): update service returned identity id to the in-memory store

---

.github/CODEOWNERS

chore: update critical paths codeowners

---

.github/dependency-review/dependency-review-config.yml
.github/workflows/callable-dependency-review.yml

- Fix the path typo from`dependecy` to `dependency`
- Add 'ISC AND MIT' to list of accepted licenses

chore: Path typo fix and add ISC AND MIT

---

packages/core/__tests__/clients/handlers/aws/authenticated.test.ts
packages/core/__tests__/clients/handlers/aws/unauthenticated.test.ts

Create unit test coverage for internal transfer handlers.
Unit test

test(core): add internal transfer handler unit test

---

.github/workflows/push-integ-test.yml
packages/auth/src/foundation/parsers/regionParsers.ts
packages/auth/src/providers/cognito/credentialsProvider/IdentityIdStore.ts

Remove unintentional console log.

fix: remove extra console log

---

.github/workflows/callable-docs-update.yml

This step name is incorrect. Bit of copy-pasta 😅 .
NA

fix: Correct step name in docs update workflow

---

.github/CODEOWNERS

- [remove](https://github.com/aws-amplify/amplify-js/commit/915f3faf6fb1fa193998356eebecf3001600b1bc) @aws-amplify/amplify-data [from codeowners](https://github.com/aws-amplify/amplify-js/commit/915f3faf6fb1fa193998356eebecf3001600b1bc)

[Chore] Update codeowners

---

.github/workflows/callable-docs-update.yml

- This PR syncs docs branch `pre-prod/main` with `main`
- Creates a branch out of `pre-prod/main`
- Applies the changes 
- creates PR against `pre-prod/main`

[Chore] Update API docs workflow

---

.github/PULL_REQUEST_TEMPLATE.md

chore: Require contributors to open an issue first for opening a feature request

---

.github/workflows/callable-get-package-list.yml
.github/workflows/callable-native-unit-tests.yml
.github/workflows/callable-release-verification.yml
.github/workflows/pr.yml
packages/rtn-push-notification/package.json
packages/rtn-web-browser/package.json

The purpose of this PR is to enable native unit tests in CI.
- Adds additional output to get package list action to return native packages with unit tests
- Adds additional scripts to native packages to support preparation and test running steps
- Adds new callable workflow to execute preparation and test running steps for native packages
- Modifies existing workflows for PR and release to also execute native unit tests
- unit testing: https://github.com/aws-amplify/amplify-js/actions/runs/15143765044/job/42574552126

feat(rtn-passkeys): add native unit tests in ci - 4

---

package.json

This PR fixes the Dependabot alert: https://github.com/aws-amplify/amplify-js/security/dependabot/125
https://github.com/aws-amplify/amplify-js/security/dependabot/125

chore(deps): bump form-data version to 4.0.4

---

.github/workflows/close-stale-issues.yml

Fixes the stale issues action configuration to correctly detect and process stale issues by:
- Adding explicit `stale-issue-label: pending-community-response` 
- Setting `days-before-issue-stale: -1` to skip stale auto labeling step
- Changing `remove-issue-stale-when-updated: false` to prevent auto removal of stale labels
N/A - Bug fix for workflow automation

fix: modify stale issues action to correctly detect stale issues

---

packages/rtn-web-browser/src/apis/openAuthSessionAsync.ts

Remove expo-go check in isChromebook as it is currently causing test failures https://github.com/aws-amplify/amplify-js/actions/runs/17952411844/job/51072716020

fix: remove failing expo check
