aws-amplify/amplify-js

packages/datastore-storage-adapter/__tests__/SQLiteAdapter.test.ts
The SQLite testing adapter had the wrong callback contract needed for `batchSave` and `batchQuery`. This fixes the testing adapter. The associated LOC were uncovered, and are now *covered*.
Added tests.
=> chore: fixed sqlite testing adapter, add sanity checks for batchSave, batchQuery

package.json
A fresh clone from `main` is failing to build.
```
amazon-cognito-identity-js: TypeError: /workspace/amplify-js/packages/amazon-cognito-identity-js/src/AuthenticationDetails.js: isTopicReference is not a function
amazon-cognito-identity-js:     at Scope.isStatic (/workspace/amplify-js/node_modules/@babel/traverse/lib/scope/index.js:439:52)
amazon-cognito-identity-js:     at Scope.maybeGenerateMemoised (/workspace/amplify-js/node_modules/@babel/traverse/lib/scope/index.js:457:14)
amazon-cognito-identity-js:     at DestructuringTransformer.init (/workspace/amplify-js/node_modules/@babel/plugin-transform-destructuring/lib/index.js:298:31)
amazon-cognito-identity-js:     at convertVariableDeclaration (/workspace/amplify-js/node_modules/@babel/plugin-transform-destructuring/lib/index.js:385:21) …
```
=> chore: keep @babel/traverse on prior version to unblock build

packages/datastore/__tests__/mutation.test.ts, packages/datastore/src/datastore/datastore.ts, packages/datastore/src/sync/index.ts, packages/datastore/src/sync/processors/mutation.ts, packages/datastore/src/sync/processors/subscription.ts, packages/datastore/src/sync/processors/sync.ts, packages/datastore/src/sync/utils.ts, packages/datastore/src/types.ts
Rework error handler to catch more errors as well as providing more useful information to the customer.
To do:
* Add additional error mappings
* Add information to docs on what errors mean
* Add unit testing
Create the scenario where the error should appear and check the error is in the console. For example, 
1. Create an App with API + DataStore
2. Add a model
```
type BrokenModel @model {
id: ID!
value: String
}
```
4. amplify push
5. Launch the app
6. Attempt to save.
=> feat: rework error handler

packages/aws-amplify-react-native/src/InAppMessaging/components/ModalMessage/__tests__/ModalMessage.spec.tsx
Merging introduced an error where `INITIAL_IMAGE_DIMENSIONS ` was not found and so was not able to import it. Replaced it with default `{ height: null, width: null }`
yarn run test -u
yarn run lint
=> fix(in-app-messaging): replace unused constant in test file

packages/amazon-cognito-identity-js/README.md, packages/datastore-storage-adapter/__tests__/SQLiteAdapter.test.ts, packages/datastore-storage-adapter/__tests__/helpers.ts, packages/datastore-storage-adapter/package.json, packages/datastore-storage-adapter/src/common/CommonSQLiteAdapter.ts, packages/datastore-storage-adapter/tslint.json, packages/datastore/__tests__/AsyncStorageAdapter.test.ts, packages/datastore/__tests__/IndexedDBAdapter.test.ts, packages/datastore/__tests__/commonAdapterTests.ts, packages/datastore/__tests__/helpers.ts, packages/datastore/package.json, packages/datastore/src/storage/adapter/InMemoryStore.ts
This PR fixes a regression in one of the fixes in #9813 and improves testing.
The original PR addressed several bugs. The fix for the bad mutation entries was red/green validated. However, the testing didn't go deep enough, and one of the related fixes would have produced the exact same red -> green test transition. Hence, either of two fixes satisfy the same test, meaning that a regression in either fix would go unnoticed.
A subsequent refactor of the SQLite adapter failed to carry the fix forward during merge conflict resolution.
Reported out of band.
This PR extends the adapter tests to validate mutations more deeply, and shares tests between adapters to better ensure the adapters share correct behavior.
By submitting this pull request, I confirm that my contribution is made under the …
=> fix(@aws-amplify/datastore-storage-adapter): remove extra, invalid sqlite mutations again

packages/aws-amplify-react-native/package.json, packages/aws-amplify/package.json, packages/notifications/package.json
Increment `notifications` and `aws-amplify-react-native` versions and update used internal dep versions for tagged branch release 
NA
`yarn clean && yarn && yarn build`
=> chore(in-app-messaging): version bump

package.json
A new release of error-stack-parser introduced a build-blocking error. There is already [an issue in that repo](https://github.com/stacktracejs/error-stack-parser/issues/80) for the bug.  This PR resolves the dep to a known working version, 2.0.6.
Mirrors [`amplify-ui` PR](https://github.com/aws-amplify/amplify-ui/pull/2039/files) for the same breakage.
`yarn setup-dev` was failing on a fresh clone and is **now succeeding**.
=> fix: resolve error-stack-parser, new bug blocking builds

packages/geo/__tests__/util.test.ts
This PR adds additional unit tests for the `validateGeofenceId` function as part of the Geofences feature. These tests are useful to be able to identify regressions with changes to the function required to resolve #9951.
#9951 
1. `yarn && yarn build` to initialize the packages
2. `cd packages/geo && yarn test` to validate all tests pass.
=> test(geo): Add unit tests for validateGeofenceId

.circleci/config.yml
Restores xcode version to 13.2.1 for main macos executor
=> ci: restore xcode version for macos executor

packages/datastore/__tests__/DataStore.ts, packages/datastore/__tests__/util.test.ts, packages/datastore/src/datastore/datastore.ts, packages/datastore/src/util.ts
Merge patches to be applied to a model on consecutive calls of `copyOf`. 
* Given model A
* make a copy from A -> B, creates patchesAB
* make a copy from B -> C, creates patchesBC
* DataStore.save(C)
Previously the save would only use patchesBC even though other changes exist in patchesAB. This change now combines patchesAB and patchesBC to patchesAC so that all patches are applied on the save.
Resolves #9891
* Unit tests
Created an app with the following:
```typescript
const obj = await DataStore.query(MyModel, 'id'); // { foo: 'original', bar: 'original' }
const newObject = MyModel.copyOf(obj, draft => {
draft.foo = 'foo1';
draft.bar = 'bar1';
});
const newObject2 = MyModel.copyOf(newObject, draft => {
draft.foo = 'foo2';
});
await DataStore.save(newObject2);
```
Then I checked in local …
=> fix: merge patches for consecutive copyOf

packages/datastore-storage-adapter/__tests__/SQLiteAdapter.test.ts, packages/datastore/__tests__/AsyncStorageAdapter.test.ts, packages/datastore/__tests__/DataStore.ts, packages/datastore/__tests__/IndexedDBAdapter.test.ts, packages/datastore/__tests__/commonAdapterTests.ts, packages/datastore/src/datastore/datastore.ts, packages/datastore/src/storage/adapter/AsyncStorageAdapter.ts
`observe` and `observeQuery` were returning results that didn't contain all necessary fields and did not load related records the same way `query` does.
TODO:
#9682
Added failing tests. Made the tests pass.
=> fix(@aws-amplify/datastore): adds missing fields to items sent through observe/observeQuery

package.json
Adding `publish:fix/auth-debouncing` on `package.json` to release this tag on npm
=> Adding publish:fix/auth-debouncing to release this tag on npm

packages/auth/__tests__/hosted-ui.test.ts, packages/auth/src/Auth.ts, packages/auth/src/urlListener.ts
Using named export instead of the default export from JS to reduce bundle size
N/A
`yarn build && yarn test`
=> fix: Update Auth to import JS using named export 

.circleci/config.yml, packages/aws-amplify/__tests__/withSSRContext-test.ts, packages/datastore/__tests__/authStrategies.test.ts, packages/datastore/__tests__/mutation.test.ts, packages/datastore/__tests__/sync.test.ts, packages/datastore/src/authModeStrategies/multiAuthStrategy.ts, packages/datastore/src/datastore/datastore.ts, packages/datastore/src/sync/index.ts, packages/datastore/src/sync/processors/mutation.ts, packages/datastore/src/sync/processors/subscription.ts, packages/datastore/src/sync/processors/sync.ts, packages/datastore/src/types.ts
The Amplify library exports the `withSSRContext` function (https://docs.amplify.aws/lib/ssr/q/platform/js/#withssrcontext) that allows a Next.js application to use client-side credentials in an isolated context on the server. The function creates new instances of the Auth, API, Credentials, and DataStore classes and configures this instance of Auth with the client-side cookies injected into it from the client-side request.
Currently, a library bug is preventing DataStore from using these instances of Auth and API while running in an SSR Context. The reference to the instance does not get preserved in the DataStore implementation. Therefore, DataStore simply imports new default instances of these classes lacking the client-side auth configuration. This breaks all SSR flows that depend on …
=> fix(datastore): preserve ssr context

packages/analytics/__tests__/Analytics.test.ts, packages/analytics/src/Analytics.ts, packages/analytics/src/index.ts, packages/analytics/src/types/Analytics.ts, packages/analytics/src/types/Providers/AmazonPersonalizeProvider.ts
Added types for `event` for 'AmazonPersonalize' provider
fixes #9943
`yarn build && yarn test`
Verified Typescript compiler doesn't complain about wrong type anymore with AmazonPersonalizeProvider specific event type
=> fix: Update AmazonPersonalizeProvider Analytics typings

packages/auth/__tests__/auth-unit-test.ts, packages/auth/src/Auth.ts, packages/auth/src/Errors.ts, packages/auth/src/common/AuthErrorStrings.ts, packages/auth/src/types/Auth.ts, packages/core/__tests__/parseMobileHubConfig-test.ts, packages/core/src/Parser.ts
Changes add confirm sign up listener to initiate auto sign in once account is confirmed. It happens if autoSignIn is set to true in params for SignUp function.
Since customers can choose either code, link, or autoConfirm, the solution use three different ways to auto sign in. autoConfirm implementation immediately calls on confirmSignUp function. Link implementation uses polling to sign user in since there is no explicit way to know if user clicked the link. Polling is done within 3 minutes (time verification link is valid) every 5 seconds. Code implementation is using hub listening event. Once user confirms account with code, it dispatches listening event. SignUp function is listening for this event to initiate SignIn process.
https://github.com/aws-amplify/amplify-js/issues/6320 …
=> feat(@aws-amplify/auth): Auto sign in after sign up

packages/analytics/src/Analytics.ts, packages/analytics/src/Providers/AWSKinesisProvider.ts, packages/analytics/src/types/Analytics.ts, packages/analytics/src/types/Providers/AWSKinesisProvider.ts, packages/analytics/src/types/Providers/AmazonPersonalizeProvider.ts
Fix some type issues in analytics category. 
Issues that is fixed,
- https://github.com/aws-amplify/amplify-js/issues/9707
- https://github.com/aws-amplify/amplify-js/issues/9943
- Sample react ts app created to test the change and typescript issue is removed and able to make requests successfully
=> Fix: Analytics Type issue

package.json
Currently when we publish the package we automatically create the release tag on github but need to [manually create a release](https://github.com/aws-amplify/amplify-js/releases/tag/aws-amplify%404.3.30).
Update package.json to include the `--create-release github` flag to automatically create a release ([reference lerna docs](https://github.com/lerna/lerna/blob/main/commands/version/README.md#--create-release-type)) 
- Created a [sample repo](https://github.com/ashwinkumar6/lerna-poc) to test this. It's a monorepo with multiple packages  which are managed by lerna, like amplify-js's project structure
- When creating a release/publish, lerna only updates the package versions of the packages which are changed, creates a tag and a release on github
- The sample repo also uses the [same …
=> build(release): automate github release with lerna

packages/aws-amplify-angular/package.json, packages/interactions/__tests__/Interactions-unit-test.ts, packages/interactions/src/Interactions.ts
When configuring a bot using default V1 provider, we can configure it using manual configuration / aws-exports config.
When using aws-exports with default provider, configure bot on the category class and call the provider's configure method. Currently with default V1 provider, provider's configure isn't called sometimes
Steps to reproduce
1. Default V1 provider is used
2. bot is configured using aws-exports 
3. Interaction’s configure is called only once
Add following unit tests
- Configure bot with default provider (AWSLexProvider) using manual config
- Configure bot with default provider (AWSLexProvider) using aws-exports config
This fix should pass the current interactions integration tests
Unit test added for the change
Tested change in the sample app
Tested using integration tests …
=> fix(interactions): fix configure default provider

packages/interactions/__tests__/Interactions-unit-test.ts, packages/interactions/src/Interactions.ts
Plugins can be added using `Amplify.addPluggable()` or `<Category>.addPluggable()`
`Amplify.addPluggable()` calls addPluggable() of all category classes.
Update Interaction's addPluggable to not throw any error if the category doesn't match
#10249
- Unit test added for the change
- Tested change in the sample app
=> fix(interactions): fix addPluggable API

packages/interactions/src/Providers/AWSLexProvider.ts, packages/interactions/src/Providers/AWSLexProviderHelper/commonUtils.ts, packages/interactions/src/Providers/AWSLexProviderHelper/utils.native.ts, packages/interactions/src/Providers/AWSLexProviderHelper/utils.ts, packages/interactions/src/Providers/AWSLexV2Provider.ts
- In lexV1 add support to send audio in `Uint8Array` format
Tested on web and RN sample app
=> feat(interactions): add audio type Uint8Array to lexV1

packages/interactions/__tests__/providers/AWSLexProvider-unit-test.ts, packages/interactions/__tests__/providers/AWSLexV2Provider-unit-test.ts, packages/interactions/package.json, packages/interactions/src/Providers/AWSLexProvider.ts, packages/interactions/src/Providers/AWSLexProviderHelper/commonUtils.ts, packages/interactions/src/Providers/AWSLexProviderHelper/convert.native.ts, packages/interactions/src/Providers/AWSLexProviderHelper/convert.ts, packages/interactions/src/Providers/AWSLexV2Provider.ts
fflat lib is used in interactions to gzip data. 
This lib uses `.cjs` files which would throw an error during build in RN apps. RN apps would need to resolve this by adding the following in metro config file 
```
resolver: {
sourceExts: [...sourceExts, "cjs"]
}
```
To avoid this, use an alternative lib pako instead of fflate in RN. For web continue using fflate since it's bundle size is much smaller than pako
=> fix(interactions): use pako instead of fflate in RN

packages/pubsub/src/Providers/MqttOverWSProvider.ts, packages/pubsub/src/Providers/constants.ts, packages/pubsub/src/index.ts
There is an issue related to the object load order that impacts the Vite build process (and maybe others). This [stack overflow](https://stackoverflow.com/questions/53122751/typeerror-object-prototype-may-only-be-an-object-or-null-undefined) question helped identify the nature of the problem.  In this case, the PubSub `index` files loads providers, which in turn load `CONNECTION_STATE_CHANGE` from further down `index` creating a cycle.
Moving this constant to a file so that the load order is acyclic fixes the issue.
#10295
#10287
#10260
I was able to reproduce the issue by following the Vue project instructions from #10287, however had trouble getting linking working to test a fix. The example React project from #10295 was very helpful in proving and testing that this fix works.
By …
=> fix(pubsub): Fix vite build issue

packages/aws-amplify/src/index.ts
We're currently exporting the default import of `Cache` from `aws-amplify`.
When customers use the Cache category:
```ts
import {Cache} from 'aws-amplify'
```
They get the following TS error
This PR replaces the default import from the Cache module with a named import and lines up Cache with how we expose all other categories via the `aws-amplify` package.
https://discord.com/channels/705853757799399426/707328986077855836/1017533084532486217
=> fix(cache): use named import when exporting from aws-amplify

packages/datastore/__tests__/storage.test.ts, packages/datastore/src/storage/storage.ts
The relevant change is in `packages/datastore/src/storage/storage.ts` - exit early when there are no changes introduced in the update mutation, instead of adding the PK to the mutation input when no other fields have been changed.
The changes to the `storage.test.ts` test file are there simply to allows us to run tests individually (via `.only`) without side-effects
=> fix: correct no-op write detection

packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider/index.ts
Follow up to https://github.com/aws-amplify/amplify-js/pull/10235.
In previous change, AppSyncRealTimeProvider blocks the GraphQL connection error to the subscribers. This breaks in the integration test [when subscription is disabled](https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/14982/workflows/93104c1c-ba16-432a-8d71-19831b335d37/jobs/155531). This fixes the unintended breaking change.
Validated the change in the Cypress integ test locally.
=> fix(pubsub): surface graphql connection failure error to observers

.circleci/config.yml
This change updates our CircleCI configuration to use the `next-major-version/5` branch of `amplify-js-samples-staging` to allow us to make breaking integ test changes ahead of our v5 release without breaking `main` tests.
https://github.com/aws-amplify/amplify-js-samples-staging/tree/next-major-version/5
NA
Need to merge to test CircleCI config.
=> Updated CircleCI config to use `next-major-version/5` branch of `amplify-js-samples-staging`

packages/api-rest/package.json, packages/api/package.json, packages/auth/package.json, packages/aws-amplify/package.json, packages/cache/package.json, packages/interactions/package.json, packages/xr/package.json
This change restores `tslib` dependencies that appear to have been dropped with a recent merge.
Original PR with testing details: https://github.com/aws-amplify/amplify-js/pull/10435
See original PR.
=> fix: Restore `tslib` dependencies for v5

packages/datastore-storage-adapter/__tests__/SQLiteAdapter.test.ts, scripts/build.js
`*.d.ts` files are generated twice in `lib` and `lib-esm` folder. Only the ones in `lib-esm` are referred by customers. This change skip generating the `*.d.ts` file for the `lib` folder. This change improves library building speed by ~30%:
* before: 817.55s user 41.86s system 388% cpu 3:41.35 total
* after: 544.91s user 28.45s system 335% cpu 2:51.07 total
Unit test.
Manually tested importing types from `@aws-amplify/datastore/ssr`
=> chore: stop generating unused dts in lib folder

packages/analytics/package.json, packages/analytics/tsconfig.build.json, packages/api-graphql/package.json, packages/api-graphql/tsconfig.build.json, packages/api-rest/package.json, packages/api-rest/tsconfig.build.json, packages/api/package.json, packages/api/tsconfig.build.json, packages/auth/package.json, packages/auth/tsconfig.build.json, packages/aws-amplify/package.json, packages/aws-amplify/tsconfig.build.json, packages/cache/package.json, packages/cache/tsconfig.build.json, packages/core/package.json, packages/core/tsconfig.build.json, packages/datastore-storage-adapter/package.json, packages/datastore-storage-adapter/tsconfig.build.json, packages/datastore/package.json, packages/datastore/tsconfig.build.json, packages/geo/package.json, packages/geo/tsconfig.build.json, packages/interactions/package.json, packages/interactions/tsconfig.build.json, packages/predictions/package.json, packages/predictions/tsconfig.build.json, packages/pubsub/package.json, packages/pubsub/tsconfig.build.json, packages/storage/package.json, packages/storage/tsconfig.build.json
- Analyses internal typescript usage
- Adds a 0 threshold for ts-coverage per package
- Adds ts-coverage script to tests 
=> feat: add ts-coverage threshold to categories

packages/amplify-ui-components/tsconfig.json, packages/amplify-ui-vue/tsconfig.json, packages/amplify-ui/tsconfig.json, packages/core/src/Util/BackgroundProcessManager.ts, packages/pushnotification/tsconfig.json
The "settlement" guarantees PR inadvertently broke the customer-facing surface area by exposing es2020 promises. However, this is not intended to be a customer facing API: https://github.com/aws-amplify/amplify-js/pull/10450
This PR casts the return value in question to `any` so customers do not need to require `es2020.promise`.
`es2020.promise` has also been from the adjacent internal package libs to help ensure this doesn't regress.
=> fix: remove dep on es2020.promise lib additions

packages/aws-amplify/package.json
Previous change dropped `@aws-amplify/notifications` package dependency in `aws-amplify` causing integ test failures.
=> fix: Re-add notifications to aws-amplify deps

package.json
Merge [build fix](https://github.com/aws-amplify/amplify-js/pull/10548) across from `main`.
The build started failing on numerous babel deps, each looking for a isTSSatisfiesExpression function that doesn't exist.
Added three bad deps (each updated within the last few hours of this PR) to resolutions.
-----
=> chore: fix build on next, resolve babel deps

.circleci/config.yml
Removes amplify-authenticator-legacy sample from circleci config due to vulnerable version of angular required for use with legacy authenticator.
=> chore: removes angular authenticator legacy from circleci config

.circleci/config.yml
Remove vue 2 integration test with legacy UI. This change is to unblock the integration test.
The legacy auth UI test is intact in Angular and React. We plan to remove them later. The new auth UI doesn't support Vue 2. So we don't expect to add new integ test to cover this exact use case.
The signIn/signUp/signOut test on new UI test case is already covered.
Next major version integ pipeline blocked:
https://app.circleci.com/pipelines/github/aws-amplify/amplify-js?branch=next-major-version%2F5
[Integ test](https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/16274/workflows/7cecf210-cf0d-4758-a32c-e81e6338dc68)
=> test(integ): remove vue 2 test on legacy Auth UI

.circleci/config.yml, packages/analytics/package.json, packages/api-graphql/package.json, packages/api-rest/package.json, packages/api/package.json, packages/auth/package.json, packages/aws-amplify/package.json, packages/cache/package.json, packages/core/package.json, packages/datastore/package.json, packages/geo/package.json, packages/interactions/package.json, packages/notifications/package.json, packages/predictions/package.json, packages/pubsub/package.json, packages/storage/package.json, packages/xr/package.json
* Since #10473 removes the artifacts in `dist` folder, the folder can be removed from `sideEffects` list of `package.json`.
* The `src` folder doesn't contain the JS code to be bundled, they can also be removed from `sideEffects` list.
=> chore: remove sideeffects mark on non-code artifacts

.circleci/config.yml
Remove firefox from test runs. Adding to testing branch to test ahead of #10580
=> fix: Remove firefox from reconnect integ tests

.circleci/config.yml
Current build command fails with
```
error @aws-sdk/types@3.201.0: The engine "node" is incompatible with this module. Expected version ">=14.0.0". Got "12.22.8"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
This change unblocks the issue but in long term we need to update CCI image.
Unit test
=> chore: use --ignore-engines option in CI

.circleci/config.yml, packages/analytics/package.json, packages/api-graphql/package.json, packages/api-rest/package.json, packages/api/package.json, packages/auth/package.json, packages/aws-amplify/package.json, packages/cache/package.json, packages/core/package.json, packages/datastore/package.json, packages/geo/package.json, packages/interactions/package.json, packages/notifications/package.json, packages/predictions/package.json, packages/pubsub/package.json, packages/pubsub/src/types/Provider.ts, packages/storage/package.json, packages/xr/package.json
fix(pubsub): Remove browser param from reconnect integ tests
=> fix(pubsub): Remove browser param from reconnect integ tests

packages/analytics/src/Analytics.ts, packages/core/__tests__/Credentials-test.ts, packages/core/src/Credentials.ts
Removing dependency on Auth for getting guest credentials
Sample app that will be included on samples staging repo in short, it was probe to be working with Analytics category on a react app.
```javascript
import { Amplify } from '@aws-amplify/core';
import { Analytics } from '@aws-amplify/analytics';
import awsconfig from './aws-exports';
Amplify.configure(awsconfig);
function App() {
Analytics.record({
name: 'working'
})
// ....
```
=> fix(@aws-amplify/core): Fix guest credentials without Auth module

packages/storage/__tests__/Storage-unit-test.ts, packages/storage/src/providers/AWSS3Provider.ts, packages/storage/src/types/AWSS3Provider.ts
fix(storage): Fix storage api to have correct typing of .list response
When using `Storage.list`, the response type did not have `nextToken` as expected.  Updating the types so that `Storage` has the correct response type and adding a test that would need to be fix to reflect the underlying typing problem.
Test updated and passing.
=> fix(storage): Fix storage api to have correct typing of .list response

packages/datastore/__tests__/Predicate.ts, packages/datastore/src/predicates/next.ts
Predicates with `.not()` conditions containing multiple related-table join conditions were selecting the wrong sets. E.g., a query like this:
```
DataStore.query(Post, negation =>
negation.not(c =>
c.and(post => [
post.blog.or(blog => [
blog.name.contains('Bob'),
blog.name.contains('Donut'),
]),
post.or(post => [
post.title.contains('post 2'),
post.title.contains('post 3'),
]),
])
)
),
```
`not()`'s apply De Morgan's Laws to retrieve inverse sets on nested groups. The propagation of this law down the chain was inadvertently added to join conditions as well. **This has been removed.**
1. Multiple additional tests added.
2. Tested with local sample app. (This will be added to the integ test suite as well.)
By submitting this pull request, I confirm that my contribution is made under the …
=> fix(@aws-amplify/datastore): fix join conditions on predicate not groups

packages/datastore/__tests__/Predicate.ts, packages/datastore/src/predicates/next.ts
Adds red squiggles and prevents TS builds if `and`/`or`/`not` predicate functions return invalid results. I.e., `and` and `or` predicates should return an array of "completed" child predicates. `not` should return a single, completed child predicate.
Along with this change, I removed some unused union members from predicate builder types. The removed members were cruft from prototyping other predicate options.
The runtime error for `and` and `or` conditions was also un-instructive and a more instructive error has been made explicit.
1. Added tests.
2. Built and verified intellisense in IDE. (See screenshots.)
=> fix(@aws-amplify/datastore): Fix predicate group types

packages/datastore/__tests__/connectivityHandling.test.ts, packages/datastore/__tests__/helpers.ts, packages/datastore/src/datastore/datastore.ts, packages/datastore/src/types.ts
1. Swaps new predicate syntax types in place of old predicate types for sync expressions.
2. Fixes missing functional support for "shorthand" syntax.
Two idiosyncrasies:
1. TS cannot determine in "shorthand" syntax that the predicate builder is always defined. This will require a `?.` at the start of the shorthand builder, like so:
```
syncExpression(Post, post => post?.title.contains('cleaning'))
```
2. TS successfully gates return values from `async` "condition producers", but cannot provide auto-completion in this context. E.g.,
```
syncExpression(Post, async () => post => post.title.contains('cleaning'))
```
TS identifies this as correct and complains if it becomes incorrect, but does not provide autocompletion.
In my testing, the noted idiosyncrasies are consistent with the legacy …
=> fix: sync expression types and shorthand handling

packages/storage/__tests__/providers/AWSS3Provider-unit-test.ts, packages/storage/src/providers/AWSS3Provider.ts, packages/storage/src/types/AWSS3Provider.ts
fix(storage): Storage.list receives nextToken to align with API
Storage list pagination should work the same as [API Pagination](https://docs.amplify.aws/guides/api-graphql/graphql-pagination/q/platform/js/), which uses `nextToken` as both the input and output attribute name.
Prior to this change getting the first to pages would look like:
```
const res1 = Storage.list('');
const res2 = Storage.list('', {pageToken: res1.nextToken);
```
After this change getting the first to pages will look like:
```
const res1 = Storage.list('');
const res2 = Storage.list('', {nextToken: res1.nextToken);
```
=> fix(storage): Storage.list receives nextToken to align with API

package.json
We want to release v5 without incrementing the version and with manual control over the CHANGE_LOG.
This will be rolled back as the first commit after the release.
Tested by running against verdaccio locally to confirm behavior
=> chore: Update release command to enable v5 release

packages/datastore/src/datastore/datastore.ts, packages/datastore/src/predicates/next.ts, packages/datastore/src/types.ts
Exposes DataStore predicate types to allow customers to easily write type-safe wrapper functions. E.g.,
1. Created a new DataStore project
2. Linked the build
3. Imported the newly exported types from `@aws-amplify/datastore`
4. Wrote a simple wrapper
5. Observed that IDE autocomplete and type checking was correct.
=> fix: export DataStore predicate types

README.md
Re-reading the README update and making updates to language that reads awkwardly.
=> fix: README grammer/wording

packages/datastore/__tests__/DataStore.ts, packages/datastore/__tests__/Predicate.ts, packages/datastore/__tests__/helpers.ts, packages/datastore/__tests__/model.ts, packages/datastore/__tests__/schema.ts, packages/datastore/src/predicates/next.ts
Predicate filtering logic (used by `observe` and `observeQuery`) was not working correctly against bools, because we were casting field values to strings before comparison. This appears to be cruft from POC work &mdash; I can't otherwise tell why this cast would have been in place.
Added tests that were red. Made the change. Tests turned green.
=> fix: predicate logic against bools

packages/datastore/__tests__/commonAdapterTests.ts, packages/datastore/__tests__/helpers.ts, packages/datastore/src/storage/adapter/IndexedDBAdapter.ts
=> fix(datastore): optional hasOne #10685

packages/auth/__tests__/state-machine-nested-test.ts, packages/auth/__tests__/state-machine-single-test.ts, packages/auth/__tests__/utils/dummyMachine.ts, packages/auth/src/Auth.ts, packages/auth/src/stateMachine/invocation.ts, packages/auth/src/stateMachine/machine.ts, packages/auth/src/stateMachine/machineState.ts, packages/auth/src/stateMachine/types.ts, packages/auth/src/types/AuthProvider.ts
This PR adds the initial implementation of our state machine utility classes and types, along with tests.
There are several Todos left here:
- "listener" and "notification" mechanism (including communicating null transitions or guard failure)
- event queuing
- error handling for state map creation
- validation of state and transition uniqueness
- tests for "invocations"... and honestly, invocations will probably be changed a fair amount anyway.
These todos  can be captured in a separate PR. Creating this state machine will likely require several iterations.
Also, please note that some of my type naming was influenced by a desire to avoid collisions with other pre-existing types in the JS ecosystem like "Event" or "State".
Also again, I know there is some fancy new syntax for annotating …
=> feat(auth): initial state machine attempt

packages/storage/src/types/Storage.ts
Adding Storage generics type clarification.
Without this fix. TS Strict is expressing issues in VSCode and Angular 15 fails to build.
#10687
Running tests and linking this change to an existing project.
=> fix: Storage interface types

packages/aws-amplify-react-native/package.json
Update the peerDependency graphql to 15.8.0 - in line with the other packages in the repository
https://github.com/aws-amplify/amplify-js/issues/10728
Unfortunately there are no tests currently in this package - but tracing the code through it looked to be referencing the version of graphql from root
=> Build/Chore - update peerDep graphql in line with other packages

packages/datastore/__tests__/DataStore.ts, packages/datastore/src/datastore/datastore.ts
DataStore does not update PK values on existing records. This behavior is by design, but has proven to be confusing when customers are not aware of it. This PR attempts to inform customers by logging a warning when a `copyOf` invocation attempts to update a PK field.
Warnings will look similar to this:
```
[WARN] 32:03.272 DataStore - copyOf() does not update PK fields. The 'id' update is being ignored. {
source: Model {
field1: 'something',
dateCreated: '2022-12-09T16:32:03.272Z',
id: 'b47c45a9-7ac4-405b-a07f-152fda83813c',
_version: undefined,
_lastChangedAt: undefined,
_deleted: undefined
}
}
```
We considered changes to this `save()` behavior to update the item, create a new item, or throw an error. But, these have been deemed breaking changes. This change will provide some guidance …
=> chore: log a warning when DataStore is ignoring an attempted PK update

packages/amazon-cognito-identity-js/src/Client.js, packages/core/__tests__/Credentials-test.ts, packages/core/__tests__/Util-test.ts, packages/core/src/Credentials.ts, packages/core/src/Util/CognitoIdentityClient.ts
Adds the cache-control 'no-store' header via middleware to the various instantiations of the Cognito Identity Pool Client.
Please note: the `Credentials` file instantiates the cognito client multiple times - most likely needlessly. I've left this in place, though, to minimize the scope of the change.
Manual testing.
=> fix(core): add cache-control header to cognito identity client

.circleci/config.yml, packages/datastore/src/datastore/datastore.ts
NextJS 13 enables SWC by default, which sometimes mangles the the build. This PR does two things:
1. Adds integ tests for sample apps that attempt to trigger bad nextjs builds
2. Adds a workaround for one known case, where SWC was over-aggressively dropping a variable declaration, resulting in an exception several lines later.
Note: Depends on https://github.com/aws-amplify/amplify-js-samples-staging/pull/494
#10732
Runtime failures were seen as in #10732 with NextJS@13 *prod* builds. The breakage was isolated by inserting dummy console logs with unique strings to help us determine where we were in the resulting minified build. By doing so, we could see that a variable declaration and later assignment were being eliminated entirely. Setting the var to a default value caused SWC to leave …
=> fix(@aws-amplify/datastore): nextjs/swc broken build workaround

.circleci/config.yml, package.json
Introduce a process to publish changes to the `stable-4` tag on npm, triggered by merges to the `v4-stable` branch.
Tested by setting up verdaccio and using the new publish command.
```sh
yarn publish:v4-stable
```
(Ensured `origin` was set to my repo to be confident that no github tag issues where introduced)
Outcome:
=> fix: Add v4-stable release process

packages/pubsub/__tests__/PubSub-unit-test.ts, packages/pubsub/src/PubSub.ts
Remove old `AppSyncProvider` to be loaded from `PubSub` module. This reduces bundle size in `9.8KB` when using `API.graphql`.
This is not a breaking change because since version`@aws-amplify/api@2.x` that provider has not been used by `API` category anymore. 
Tested on local App.
=> Removes old AppSyncProvider to load automatically on PubSub

packages/auth/__tests__/auth-cognito-provider-unit-test.ts, packages/auth/src/Providers/AmazonCognitoProvider.ts, packages/auth/src/types/aws-plugins/cognito-plugin/types/models/authOptions.ts, packages/auth/src/types/models/index.ts
adds clientMetadata from auth config to sign up function
=> Adds config client metadata to sign up function

packages/auth/__tests__/state-machine-manager-test.ts, packages/auth/__tests__/state-machine-single-test.ts, packages/auth/__tests__/utils/tickTockMachine.ts, packages/auth/package.json, packages/auth/src/stateMachine/machine.ts, packages/auth/src/stateMachine/stateMachineManager.ts, packages/auth/src/stateMachine/types.ts
* Remove the statemachines from the manager contructor, and add an `addMachineIfAbsent()` to support adding statemachine dynamically. We can add the state machines to the class contructor later of there's an use case
* Add more unit tests and make sure the unit test passes. There will be followup PR to unblock the CI
* Fix formatting.
```bash
cd packages/auth && yarn jest __tests__/state-machine-*.ts
yarn run v1.22.19
$ .../amplify-js/node_modules/.bin/jest __tests__/state-machine-manager-test.ts __tests__/state-machine-single-test.ts
PASS  __tests__/state-machine-single-test.ts
PASS  __tests__/state-machine-manager-test.ts (10.972s)
````
=> feat(auth): implement addMachineIfAbsent and pass unit test

package.json, packages/pubsub/__tests__/PubSub-unit-test.ts, packages/pubsub/src/PubSub.ts
chore: Update preId for unstable release (#10844)
chore: no-op commit to trigger CICD (#10843)
fix(@aws-amplify/pubsub): Removes old AppSyncProvider to load automatically on PubSub (#10840)
=> Amplify JS release

packages/auth/src/Auth.ts
Adds temporary, commented-out class members in Auth.ts that will allow the full library to build. 
The reasoning for making these commented out is that we want integration tests in other packages to continue failing until the requisite changes have been made in them using the new Auth methods.
Ran `yarn build` at root while uncommented.
=>  chore(auth): temporary class members to enable library build success

packages/datastore/__tests__/IndexedDBAdapter.test.ts
Some IndexedDB time limit clamps were too aggressive for the CI execution environment. I had hesitations about including some of these as straight-up time limits. I favored this for some of the scenarios to keep test times down -- the alternative was to run scenarios twice on different schemas to demonstrate an increase in performance due to index usage.
For now, I'm bumping the time limits up for the CI execution environment.
Re-ran the tests. We'll have to see whether integ tests pass. If they don't, I'll temporarily disable the tests until I can rewrite them as comparative tests.
=> chore: inc idb time clamps in tests due to CI slowness

packages/datastore/__tests__/commonAdapterTests.ts, packages/datastore/__tests__/helpers.ts, packages/datastore/src/storage/adapter/AsyncStorageAdapter.ts, packages/datastore/src/storage/adapter/IndexedDBAdapter.ts
Fixes bug when deleting a record of a model with > 1 nested Has Many descendants
Ex:
```graphql
type Blog @model {
id: String!
posts: [Post] @hasMany
}
type Post @model {
id: String!
comments: [Comment] @hasMany
}
type Comment @model {
id: String!
}
```
Behavior before the change in this PR:
1. `await DataStore.delete(Blog, 'some-id')`
2. `deleteTraverse` retrieves all `Post` records from the client database that are related to the Blog record and recursively calls `deleteTraverse`, passing the retrieved post records as POJOs ([link to code](https://github.com/aws-amplify/amplify-js/pull/10880/files#diff-75c76069840355a3f346f2f35c443018e4a5716ed128191602499c3b39935cfcR1076-R1080))
3. since `Post` has a Has Many relationship to `Comment`, `deleteTraverse` attempts to retrieve the related …
=> fix(datastore): cascade deleted for nested Has Many

CONTRIBUTING.md, package.json, packages/datastore/package.json
This change adds more documentation on debugging bundle size regressions and adds a dependency that was missed from the original PR. It also slightly loosens the `datastore` category limits in anticipation of a pending customer PR.
=> chore: Updated bundle size debugging documantation & datastore limits

packages/datastore/package.json
This change aligns the `datastore` UUID dependency with the rest of the repository to improve dependency flattening and remove one of our install warnings.
```
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
```
Local testing in React Native, creating & reading entries from Datastore.
=> chore: Align datastore UUID dependency with rest of repo.

package.json, packages/analytics/package.json, packages/api-graphql/package.json, packages/api-rest/package.json, packages/api/package.json, packages/auth/package.json, packages/cache/package.json, packages/core/package.json, packages/datastore/package.json, packages/geo/package.json, packages/interactions/package.json, packages/notifications/package.json, packages/predictions/package.json, packages/pubsub/package.json, packages/storage/package.json, packages/xr/package.json
Adds some more bundle size utility scripts and updates limits to reflect downstream Terser updates (which `sizelimit` uses) which slightly increased the size of generated bundles . Also cleaned up some unused `bundlewatch` configuration.
Context: https://github.com/terser/terser/issues/1338
Relevant `yarn.lock` diff:
```
<   version "5.16.3"
<   resolved "https://registry.yarnpkg.com/terser/-/terser-5.16.3.tgz#3266017a9b682edfe019b8ecddd2abaae7b39c6b"
<   integrity sha512-v8wWLaS/xt3nE9dgKEWhNUFP6q4kngO5B8eYFUuebsu7Dw/UNAnpUod6UHo04jSSkv8TzKHjZDSd7EXdDQAl8Q==
---
>   version "5.16.2"
>   resolved "https://registry.yarnpkg.com/terser/-/terser-5.16.2.tgz#8f495819439e8b5c150e7530fc434a6e70ea18b2"
>   integrity sha512-JKuM+KvvWVqT7muHVyrwv7FVRPnmHDwF6XwoIxdbF5Witi0vu99RYpxDexpJndXt3jbZZmmWr2/m …
```
=> chore: Add `clean:bundle` commands & update limits

packages/datastore-storage-adapter/__tests__/SQLiteUtils.test.ts, packages/datastore/__tests__/DataStore.ts, packages/datastore/__tests__/Merger.test.ts, packages/datastore/__tests__/Predicate.ts, packages/datastore/__tests__/commonAdapterTests.ts, packages/datastore/__tests__/connectivityHandling.test.ts, packages/datastore/__tests__/helpers.ts, packages/datastore/src/datastore/datastore.ts, packages/datastore/src/predicates/next.ts, packages/datastore/src/storage/adapter/IndexedDBAdapter.ts, packages/datastore/src/sync/processors/mutation.ts
Reverts aws-amplify/amplify-js#10915
Some tests are failing. It appears that sending `null` explicitly in the `owner` field appears to break mutations *sometimes*. The affected scenarios are failing in this integ run:
https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/17837/workflows/b338faaf-ff4a-437f-a7fc-d63c1d8ffca4
=> Revert "fix(@aws-amplify/datastore): strictly define `null` vs `undefined` behavior on models"

packages/datastore-storage-adapter/__tests__/SQLiteUtils.test.ts, packages/datastore/__tests__/DataStore.ts, packages/datastore/__tests__/Merger.test.ts, packages/datastore/__tests__/Predicate.ts, packages/datastore/__tests__/commonAdapterTests.ts, packages/datastore/__tests__/connectivityHandling.test.ts, packages/datastore/__tests__/helpers.ts, packages/datastore/src/datastore/datastore.ts, packages/datastore/src/predicates/next.ts, packages/datastore/src/storage/adapter/IndexedDBAdapter.ts, packages/datastore/src/sync/processors/mutation.ts
Reverts aws-amplify/amplify-js#10932
This PR caused explicit timestamp fields to fall into required field validation, which they were not previously. The fields are marked as `required` fields, and the TS types requires they be provided. But, in JS, they haven't strictly been required. Nor are they technically required at sync time.
Rolling back for now while we determine how to handle these.
=> Revert "fix(@aws-amplify/datastore): strictly define null vs undefined behavior on models"

.circleci/config.yml
Pins the tag of the verdaccio/verdaccio Docker image to mitigate this issue: https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/18011/workflows/84e64b56-a4a2-4f42-a1fd-2bbf05a9a8fe/jobs/232466
integ jobs start up fine after pinning the version: https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/18014/workflows/5f94f47a-7ced-4a07-9cc0-22fabd0e2a4c/jobs/232687
=> ci: pin verdaccio image version

packages/xr/src/Providers/SumerianProvider.ts, packages/xr/src/XR.ts
Adds some more XR deprecation warnings to the Sumerian provider & class.
=> chore: Added more XR deprecation warnings

packages/notifications/src/PushNotification/PushNotification.native.ts, packages/notifications/src/PushNotification/PushNotification.ts, packages/notifications/src/PushNotification/types.ts, packages/notifications/src/PushNotification/utils.ts, packages/rtn-push-notification/android/src/main/kotlin/com/amazonaws/amplify/rtnpushnotification/PushNotificationAWSPinpointUtils.kt, packages/rtn-push-notification/android/src/main/kotlin/com/amazonaws/amplify/rtnpushnotification/PushNotificationFirebaseMessagingService.kt, packages/rtn-push-notification/android/src/main/kotlin/com/amazonaws/amplify/rtnpushnotification/PushNotificationModule.kt, packages/rtn-push-notification/src/types.ts
This PR adds the `getPermissionStatus` API which is the companion API to `requestPermissions`.
Previously, the latter API directly returned either a granted or denied status. But this failed to enable use cases where developers may want to display rationale UIs before attempting to request permissions. The `getPermissionStatus` API will give them additional insight into the current permission state and enable them to better control their permission workflow.
Tested locally against React Native Android app on API 33
=> feat(notifications): Add getPermissionStatus API

packages/rtn-push-notification/android/src/main/AndroidManifest.xml
This PR fixes an issue where our module launch activity did not always get created when the app was previously awoken in the background via headless service.
Validated changes allowed sample app to function as expected in various states.
=> fix(notifications): Intermediary activty not always created

packages/notifications/src/Notifications.ts
This PR adds the `identifyUser` API to the Notifications category as a convenience function for calling registered subcategories' (i.e. channels) respective `identifyUser` APIs.
Validated changes locally - calling `Notifications.identifyUser` will call `InAppMessaging.identifyUser` and `Push.identifyUser`
=> feat(notifications): Add Notifications-level identifyUser

packages/datastore/__tests__/Predicate.ts, packages/datastore/__tests__/commonAdapterTests.ts, packages/datastore/__tests__/helpers.ts, packages/datastore/src/storage/adapter/IndexedDBAdapter.ts
Queries against indexed fields in IDB were being queried as strings for `eq` matches due to a bad cast, causing missing results. This PR removes the cast.
Due to the removed cast, this also adds filters `null` and `undefined` conditions out of indexed queries, which would otherwise incorrectly be accepted as IDB key lookup values.
#11018
Red-greened tested.
=> fix(@aws-amplify/datastore): fix for queries against numeric indexes in IDB

packages/notifications/src/PushNotification/PushNotification.native.ts, packages/notifications/src/PushNotification/PushNotification.ts, packages/notifications/src/PushNotification/types.ts, packages/rtn-push-notification/src/types.ts
This PR adds badge count APIs to Push Notification:
* getBadgeCount
* setBadgeCount
These APIs were already added to the native module but were missed earlier during integration
Tested with both iOS and Android to see that APIs behave as expected
=> feat(notifications): Add badge count APIs

packages/rtn-push-notification/android/src/main/kotlin/com/amazonaws/amplify/rtnpushnotification/PushNotificationModule.kt
This PR updates the Android module's `onNewIntent` block to expect an intent. When this function is called, it will always have an intent.
Tested with sample app locally to see behavior remained as expected.
=> chore(notifications): Remove unnecessary let block

packages/datastore/src/sync/processors/subscription.ts
`errorType` is an enum, which can have value `0`. Conditional was doing a falsey check. Check for `undefined` instead.
=> fix(datastore): rtf errorType conditional

packages/aws-amplify/__tests__/exports-test.ts, packages/aws-amplify/package.json, packages/aws-amplify/src/index.ts, packages/aws-amplify/webpack-utils.js
This change removes XR from the `aws-amplify` umbrella package to fix an issue where multiple versions of core were being included in the project.
=> Fix: Removed the XR package from `aws-amplify`

.circleci/config.yml
This PR prevents a flaky Firefox integ test from running.
The root cause of the frequent test failure is that, at times, the UI component used in the test fails to load due to the following error: `Cstr is undefined`
This error is coming from [Stencil](https://github.com/ionic-team/stencil) which was a dependency of the chatbot inside a deprecated `@aws-amplify/ui-components` package. 
Rather than trying to debug an unsupported component in a deprecated package we are disabling this test from running on Firefox.
Validated that the updated circle configuration is valid
```sh
$ circleci config validate
```
=> test(integ): Disable Vue Interactions Firefox test

packages/notifications/src/PushNotification/NotEnabledError.ts, packages/notifications/src/PushNotification/Providers/AWSPinpointProvider/index.ts, packages/notifications/src/PushNotification/PushNotification.native.ts, packages/notifications/src/PushNotification/PushNotification.ts, packages/notifications/src/PushNotification/types.ts
This PR adds an `enable` API which enables notification APIs. The intent of this API is both for registering listeners for react native module events and to give developers an explicit API to call in order to bootstrap the feature outside of the React Native application context.
Tested locally on iOS and Android
* APIs now throw error if called before `enable`
=> feat(notifications): Add init API

packages/datastore/src/storage/adapter/AsyncStorageAdapter.ts, packages/datastore/src/storage/adapter/AsyncStorageDatabase.ts, packages/datastore/src/storage/adapter/IndexedDBAdapter.ts, packages/datastore/src/storage/adapter/StorageAdapterBase.ts
Adds an abstract base class - `StorageAdapterBase` that encapsulates common storage adapter business logic.
Individual storage adapters, e.g. IndexedDBStorageAdapter extend the base class and only implement platform-specific business logic
This PR migrates IndexedDB and AsyncStorage to this pattern. I would like to get a sanity check from the team on the soundness of this approach before migrating the remaining 2 adapters (SQLite and Expo SQLite)
* unit tests
* manual testing
=> refactor(datastore): storage adapters

packages/datastore/__tests__/DataStore.ts, packages/datastore/__tests__/commonAdapterTests.ts, packages/datastore/__tests__/helpers/fakes/graphqlService.ts, packages/datastore/__tests__/helpers/schemas/default.ts, packages/datastore/src/datastore/datastore.ts, packages/datastore/src/util.ts
Relevant impl change is only in `datastore.ts` ([link to block](https://github.com/aws-amplify/amplify-js/pull/11119/files#diff-10866b5ac7d469b38dd9928d9d7056a3a402904fef591ea8cfe773b4d75d63efR2311-R2318)) remaining changes are for testing purposes.
We were applying `sort` before merging existing and changed snapshot items into the new snapshot.
This was causing stale items to surface in the snapshot.
New PR applies sort after we merge items, fixing the issue.
#11101 
* Manual
* Unit test
=> fix(datastore): stale observeQuery snapshot with sort param

packages/core/package.json, packages/core/src/Credentials.ts, packages/core/src/OAuthHelper/FacebookOAuth.ts, packages/core/src/OAuthHelper/GoogleOAuth.ts, packages/core/src/StorageHelper/reactnative.ts, packages/core/tsconfig.build.json, packages/core/tsconfig.json
This is the first commit to lay the ground for the custom clients work. Bump the core to ts 5.0 so we can utilize the better type resolution compared to ts3.8. It is not a breaking change because we are not exporting any ts interfaces differently than main branch.
The bundle size increased because the ts config `importHelpers` is turned off. Otherwise the build error is show:
```bash
error TS2343: This syntax requires an imported helper named '__spreadArray' which does not exist in 'tslib'. Consider upgrading your version of 'tslib'.
```
This is because ts3.x generates spread helper function `__spread`. The helper function was deprecated in ts4.x and new helper function `__spreadArray` from tslib 2.x is favored. We cannot bump tslib version yet because the tslib version misalignment with …
=> chore(core): bump to ts 5.0

packages/datastore/__tests__/connectivityHandling.test.ts, packages/datastore/src/sync/index.ts, packages/datastore/src/sync/processors/mutation.ts
[`outboxMutationProcessed`](https://docs.amplify.aws/lib/datastore/datastore-events/q/platform/js/#outboxmutationprocessed) Hub events were being dropped for mutations that were being raced against reconnect activities. A fringe case, but during reconnect, this could lead to customer code waiting for `outboxMutationProcessed` events that would never arrive.
This PR fixes the issue by properly removing the observer from the mutation processor during an unsubscribe or `stop()`. An `undefined` observer signals to the mutation processor not to immediately resume on mutation, but instead wait for an observer (the sync engine) to register itself and re-`start()` the mutation processor.
This PR also incidentally tamps down on `console.warn` noise in the scope of `connectivityHandler.test.ts`. …
=> fix(@aws-amplify/datastore): mutation hub event drops during reconnect

packages/datastore/__tests__/Predicate.ts, packages/datastore/__tests__/helpers/fakes/graphqlService.ts, packages/datastore/src/predicates/index.ts
AFAIK, this only affects test mocks which need to execute predicates. Whereas DataStore API's normally short-circuit when `Predicate.ALL` is supplied, the test mocks can't always do this reliably.
This PR adds a branch to allow empty predicates (`model => model`) to be serialized in a way that can just be executed like a normal storage predicate.
Added a test. Made the test pass.
=> fix(@aws-amplify/datastore): adds serialization for empty predicates

packages/datastore/__tests__/IndexedDBAdapter.test.ts, packages/datastore/__tests__/helpers/datastoreFactory.ts, packages/datastore/__tests__/helpers/schemas/default.ts, packages/datastore/src/storage/adapter/AsyncStorageAdapter.ts, packages/datastore/src/storage/adapter/IndexedDBAdapter.ts, packages/datastore/src/storage/adapter/StorageAdapterBase.ts, packages/datastore/src/util.ts
Before the change in this PR our business logical for performing cascading deletes only worked correctly when we could retrieve child relations using an index. This worked in most cases, but was not flexible enough, e.g. for the schema in the linked issue where the child index does not map back to the parent due to a different number of key fields in the index.
This PR leverages existing predicate logic in the storage adapters to attempt to use an index for retrieval when possible, but fall back to a scan when an appropriate index does not exist.
#10864 
* red/green unit test with schema from linked issue
* manual testing
=> fix(datastore): normalize deleteTraverse 1:M

packages/notifications/__tests__/PushNotification/PushNotification.native.test.ts, packages/notifications/src/PushNotification/PushNotification.native.ts
This PR fixes an issue where, upon a fresh install, the Android module will send off two token received events (from the service onNewToken and module launch). This triggers a race condition where both events are handled in parallel and ends up creating two separate endpoints.
Tested locally with sample app and verified only one endpoint is created on fresh install
=> fix(notifications): Fix double registration issue

.circleci/config.yml, packages/datastore/__tests__/IndexedDBAdapter.test.ts, packages/datastore/__tests__/helpers/datastoreFactory.ts, packages/datastore/__tests__/helpers/schemas/default.ts, packages/datastore/src/storage/adapter/AsyncStorageAdapter.ts, packages/datastore/src/storage/adapter/IndexedDBAdapter.ts, packages/datastore/src/storage/adapter/StorageAdapterBase.ts
Refactors and simplifies cascading delete business logic using `ModelRelationship` class. 
Fixes issues caused by strict reliance on indexes for cascading deletes. Fetching related models will now gracefully fall back to a table scan when we can't match on an index (e.g. for the schema in the linked issue).
https://github.com/aws-amplify/amplify-js/issues/10864
* red/green unit test with schema from linked issue
* manual testing
* e2e test run: https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/18699/workflows/c42b16da-cdc7-4930-8b32-4940ca623142
=> fix(datastore): normalize deleteTraverse

packages/core/__tests__/clients/composeTransferHandler-test.ts, packages/core/__tests__/clients/retry-middleware-test.ts, packages/core/package.json, packages/core/src/clients/internal/composeTransferHandler.ts, packages/core/src/clients/middleware/retry.ts, packages/core/src/clients/types/core.ts
* Propose a function composing HTTP handler(fetch transfer handler) and middleware into a transfer handler.
* Minor update to the middleware interface
* Propse a general retry middleware implementation for client side. Removing overly complexed retry token mechanism from AWS SDK.
This change is intended to replace the current [`Core/Util/Retry.ts`](https://github.com/aws-amplify/amplify-js/blob/0fa40e6efb67def43f0eb912b3f2ed34da883f5f/packages/core/src/Util/Retry.ts#L21) and standardize the retry behaviors across the board.
Unit test
=> feat(clients): compose transfer handler with middleware & retry middleware

packages/pushnotification/src/PushNotification.ts
This PR marks the previous version of Amplify Push Notifications as being on deprecation path. This only adds comments to the APIs and makes no breaking changes to the functionality itself.
Validated the deprecation messages show up in IDE
`yarn test`
=> chore(notifications): Deprecate previous push notifications

packages/notifications/src/Notifications.ts
If customer is trying to use Amplify Push Notifications but did not install the required native module, the library is supposed to throw an error. However, if the getter for `Notifications.Push` returns `null`, accessing a function on `null` will supersede and bury the native module error - customers will not know their issue stems from a missing module. This PR updates the `Push` getter to return an empty object instead of null, so that the error will be surfaced to give them some direction.
Tested locally with sample app
=> fix(notifications): Surface missing native module error

packages/core/__tests__/clients/retry-middleware-test.ts, packages/core/package.json, packages/core/src/clients/middleware/retry.ts, packages/core/src/clients/types/core.ts, packages/core/src/clients/types/index.ts
AWS SDK response and error object contains metadata to indicate how many retries the handler had conducted, like `{$metadata: { attempts: 3 }}`. This change adds the same feature to the transfer handler's retry middleware. If retry middleware is added, the thrown error or response would contain the retry information.
See [MetadataBearer interface](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/interfaces/_aws_sdk_types.MetadataBearer.html)
Unit test
=> [Custom Clients]fix(retry): add metadata to returns from retry middldeware

packages/notifications/src/PushNotification/types.ts
This PR fixes an issue with typing on the PN Permission request
`yarn build` locally and see that the `*.d.ts` file is now clean
=> fix(notifications): Fix permissions type

packages/rtn-push-notification/ios/AmplifyPushNotification.m
This PR updates the iOS Push Notification native module to look for the generated umbrella Swift header in a namespaced location if `use_frameworks!` is in the `Podfile`
Addresses #11246
Validated this change now builds for both types of projects - with or without `use_frameworks!`
=> fix(notifications): Support use_frameworks!

packages/storage/src/types/AWSS3Provider.ts
Adds type documentation for put and copy S3 config objects noting that `acl` is not recommended.
N/A
=> updated storage config type doc

packages/datastore/__tests__/connectivityHandling.test.ts, packages/datastore/__tests__/helpers/datastoreFactory.ts, packages/datastore/__tests__/helpers/fakes/graphqlService.ts, packages/datastore/src/sync/processors/errorMaps.ts, packages/datastore/src/sync/processors/mutation.ts, packages/datastore/src/sync/processors/sync.ts
Adds missing `errorHandler` events for "top level" unauthorized errors in AppSync resolvers (i.e., when resolver VTL calls `$util.unauthorized()`).
To support the testing for this, this PR adds:
1. Ability to hook into `errorHandler` using an `Observable` from the `getDatastore()` test factory.
2. Ability to inject a single `intercept` method into the graphql fake, so that individual responses can be faked in the context of a full sync. (Helpful if/when we clamp on what a single failed sync, mutation, or subscription means to the overall state of DataStore.)
#11042
Added protocol tests based on:
1. Forcing relevant resolvers to call `$util.unauthorize`.
3. Capturing responses.
4. Added simulated responses to protocol test.
5. Add assertion for `errorHandler` to trigger an `Unauthorized` …
=> fix(datastore): add missing errorHandler errors for sync and mutation unauth responses 

packages/core/__tests__/clients/middleware/signing/signer/signatureV4/presignUrl-test.ts, packages/core/__tests__/clients/middleware/signing/signer/signatureV4/signRequest-test.ts, packages/core/__tests__/clients/middleware/signing/signer/signatureV4/utils/dataHashHelpers-test.ts, packages/core/__tests__/clients/middleware/signing/signer/signatureV4/utils/getCanonicalRequest-test.ts, packages/core/__tests__/clients/middleware/signing/signer/signatureV4/utils/getHashedPayload-test.ts, packages/core/__tests__/clients/middleware/signing/signer/signatureV4/utils/getSignature-test.ts, packages/core/__tests__/clients/middleware/signing/signer/signatureV4/utils/getSigningKey-test.ts, packages/core/__tests__/clients/middleware/signing/signer/signatureV4/utils/getStringToSign-test.ts, packages/core/src/clients/middleware/signing/signer/signatureV4/presignUrl.ts, packages/core/src/clients/middleware/signing/signer/signatureV4/signRequest.ts, packages/core/src/clients/middleware/signing/signer/signatureV4/utils/dataHashHelpers.ts, packages/core/src/clients/middleware/signing/signer/signatureV4/utils/getCanonicalRequest.ts, packages/core/src/clients/middleware/signing/signer/signatureV4/utils/getHashedPayload.ts, packages/core/src/clients/middleware/signing/signer/signatureV4/utils/getSignature.ts, packages/core/src/clients/middleware/signing/signer/signatureV4/utils/getSigningKey.ts
In order to limit the impact of updating our existing Signer to use the updated signing functions, the underlying signing functions need to be synchronous calls as well. We will revisit this in the future in a breaking change.
Tested that signing functions now generate the same output without being `await`ed.
=> chore(clients): Make signing functions synchronous

packages/core/src/clients/middleware/signing/signer/signatureV4/utils/dataHashHelpers.ts, packages/core/src/clients/middleware/signing/signer/signatureV4/utils/getCanonicalHeaders.ts, packages/core/src/clients/middleware/signing/signer/signatureV4/utils/getCanonicalQueryString.ts, packages/core/src/clients/middleware/signing/signer/signatureV4/utils/getCanonicalRequest.ts, packages/core/src/clients/middleware/signing/signer/signatureV4/utils/getCanonicalUri.ts, packages/core/src/clients/middleware/signing/signer/signatureV4/utils/getCredentialScope.ts, packages/core/src/clients/middleware/signing/signer/signatureV4/utils/getFormattedDates.ts, packages/core/src/clients/middleware/signing/signer/signatureV4/utils/getHashedPayload.ts, packages/core/src/clients/middleware/signing/signer/signatureV4/utils/getSignature.ts, packages/core/src/clients/middleware/signing/signer/signatureV4/utils/getSignedHeaders.ts, packages/core/src/clients/middleware/signing/signer/signatureV4/utils/getSigningKey.ts, packages/core/src/clients/middleware/signing/signer/signatureV4/utils/getSigningValues.ts, packages/core/src/clients/middleware/signing/signer/signatureV4/utils/getStringToSign.ts
This PR adds `@internal` annotations to various utility functions designed to be used internally only
=> chore(clients): Add @internal annotation

packages/analytics/package.json, packages/api-graphql/package.json, packages/api-rest/package.json, packages/api/package.json, packages/auth/package.json, packages/cache/package.json, packages/core/__tests__/clients/endpoints-test.ts, packages/core/package.json, packages/core/src/AwsClients/CognitoIdentity/base.ts, packages/core/src/clients/endpoints/getDnsSuffix.ts, packages/core/src/clients/endpoints/index.ts, packages/core/src/clients/endpoints/partitions.ts, packages/core/src/clients/types/aws.ts, packages/core/src/clients/types/index.ts, packages/datastore/package.json, packages/geo/package.json, packages/interactions/package.json, packages/notifications/package.json, packages/pubsub/package.json, packages/storage/package.json
Make sure the custom endpoint resolver can resolve endpoint suffix to `amazonaws.com.cn` when region is in CN partition.
Unit test
=> feat(clients): support CN partition by adding DNS suffix resolver

packages/core/__tests__/AwsClients/Pinpoint/getInAppMessages-test.ts, packages/core/__tests__/AwsClients/Pinpoint/updateEndpoint-test.ts, packages/core/__tests__/AwsClients/testUtils/data.ts, packages/core/src/AwsClients/Pinpoint/getInAppMessages.ts, packages/core/src/AwsClients/Pinpoint/index.ts
This PR adds the Pinpoint client `getInAppMessages` API
Locally replaced API calls from Notifications.InAppMessaging and verified network request performed as expected
=> feat(clients) Add getInAppMessages API

packages/datastore/__tests__/connectivityHandling.test.ts, packages/datastore/__tests__/helpers/fakes/graphqlService.ts
feat(data): add assertions to test queried versions for DataStore's single-client consecutive update consistency unit tests; update fake GraphQL service to accept latency overrides for individual requests; create utils for performing consecutive updates and making common assertions; refactor existing tests to use new helpers 
=> feat(data): refactor single-client consecutive update unit tests; fake GraphQL service updates

packages/analytics/__tests__/Providers/AWSPinpointProvider.test.ts, packages/analytics/__tests__/Providers/EventBuffer.test.ts, packages/analytics/package.json, packages/analytics/src/Providers/AWSPinpointProvider.ts, packages/analytics/src/Providers/EventBuffer.ts, packages/notifications/__mocks__/data.ts, packages/notifications/__tests__/InAppMessaging/Providers/AWSPinpointProvider/index.test.ts, packages/notifications/__tests__/InAppMessaging/Providers/AWSPinpointProvider/utils.test.ts, packages/notifications/__tests__/PushNotification/Providers/AWSPinpointProvider/index.test.ts, packages/notifications/__tests__/common/AWSPinpointProviderCommon/index.test.ts, packages/notifications/package.json, packages/notifications/src/InAppMessaging/Providers/AWSPinpointProvider/index.ts, packages/notifications/src/InAppMessaging/Providers/AWSPinpointProvider/utils.ts, packages/notifications/src/PushNotification/Providers/AWSPinpointProvider/index.ts, packages/notifications/src/PushNotification/Providers/AWSPinpointProvider/utils.ts, packages/notifications/src/common/AWSPinpointProviderCommon/index.ts, packages/notifications/src/common/AWSPinpointProviderCommon/types.ts
This PR replaces the Pinpoint client vended by the AWS SDK with internally crafted APIs
Updated unit tests without changing test expectations. Tested the execution of `updateEndpoint`, `putEvents` and `getInAppMessages` in Analytics (with and without buffer) and Notification categories. Tested using sample NextJS app on web + React Native on both Android and iOS.
=> chore(clients): Replace SDK Pinpoint Client

.circleci/config.yml
This reverts commit c19590e51500f3f00da28611e52bb2ac869f10d0.
Adds basic Next.js App Router canaries. Removed the `@canary` Page Router canary considering App Router will be the default going forward.
Local test workspace will same commands.
=> chore: Added Next.js App Router canaries

packages/predictions/package.json, packages/predictions/src/Providers/AmazonAIConvertPredictionsProvider.ts
Add the missing buffer dependency used by the Predictions transcribe component: https://github.com/aws-amplify/amplify-js/blob/0fa40e6efb67def43f0eb912b3f2ed34da883f5f/packages/predictions/src/Providers/AmazonAIConvertPredictionsProvider.ts#L293
The `buffer` dependency is the same version used in `amazon-cognito-identity-js` package:
https://github.com/aws-amplify/amplify-js/blob/88b5c26daf30304e9f4b2bf5064bfce545ad06b7/packages/amazon-cognito-identity-js/package.json#L67
React Native customer seeing `ReferenceError: Property 'Buffer' doesn't exist` error when following the [doc code snippet](https://docs.amplify.aws/lib/predictions/transcribe/q/platform/react-native/)
P88158994
Manual test on RN.
By submitting this pull request, I confirm that my contribution is made under the terms of …
=> chore(predictions): add missing buffer dependency

packages/analytics/package.json, packages/api-graphql/package.json, packages/api-rest/package.json, packages/api/package.json, packages/auth/package.json, packages/core/__tests__/clients/fetch-test.ts, packages/core/internals/aws-client-utils/package.json, packages/core/internals/aws-clients/pinpoint/package.json, packages/core/package.json, packages/core/src/clients/handlers/fetch.ts, packages/datastore/package.json, packages/pubsub/package.json, packages/storage/package.json
Cache the payload of a response body when accessor is called(`body.json()`, `body.blob()`, `body.text()`, etc.). It allows multiple calls to the body accessors, for example, when reading the body in both retry decider and error deserializer. Otherwise, the API will throw the body has been read error.
Caching body is allowed here because customers will keep a reference to the data in memory anyway without the cache when they use these accessors.
This change also add a `react-native` entry point for cross-category internal components.(cc @erinleigh90 )
Unit tests, Integration test
=> feat(clients): allow fetch handler to read body multiple times

.circleci/config.yml
=> chore: Disable geo tests

packages/storage/package.json, packages/storage/src/Storage.ts, packages/storage/src/types/Provider.ts
Release 5.2.3 brought a braking change by introducing a getProperties required field in the StorageProvider interface. The solution was to make this field optional
=> fix(storage): make getProperties param optional

packages/predictions/package.json, packages/storage/__tests__/Storage-unit-test.ts, packages/storage/__tests__/providers/AWSS3Provider-unit-test.ts, packages/storage/package.json, packages/storage/src/Storage.ts, packages/storage/src/providers/AWSS3Provider.ts, packages/storage/src/types/AWSS3Provider.ts, packages/storage/src/types/Provider.ts, packages/storage/src/types/Storage.ts
This change reverts the following commits related to `getProperties` due to type errors.
https://github.com/aws-amplify/amplify-js/commit/5d00b1fc2839a8f1bbd4338a0aa805e48e4e56c0
https://github.com/aws-amplify/amplify-js/commit/3bed12b6960c676095689ee895c60ae55a041c8c
Build.
=> fix: Revert `getProperties` API

package.json, packages/core/.gitignore, packages/core/package.json, packages/core/polyfills/URL/index.ts, packages/core/polyfills/URL/tsconfig.json, packages/core/polyfills/URL/webpack.config.js, packages/core/src/clients/middleware/signing/signer/signatureV4/index.native.ts, packages/notifications/__tests__/InAppMessaging/SessionTracker/SessionTracker.native.test.ts, packages/notifications/__tests__/PushNotification/PushNotification.native.test.ts, packages/notifications/jest.native.config.js, packages/notifications/package.json, packages/predictions/package.json, packages/storage/__tests__/Storage-unit-test.ts, packages/storage/__tests__/providers/AWSS3Provider-unit-test.ts, packages/storage/package.json, packages/storage/src/Storage.ts, packages/storage/src/providers/AWSS3Provider.ts, packages/storage/src/types/AWSS3Provider.ts, packages/storage/src/types/Provider.ts, packages/storage/src/types/Storage.ts
previous release [#11407](https://github.com/aws-amplify/amplify-js/pull/11407)  
=> release(required): Amplify JS release

packages/core/__tests__/clients/composeTransferHandler-test.ts, packages/core/src/clients/internal/composeTransferHandler.ts
This change fixes a bug that the order of middleware in a transfer handler reverts in-place after each API invocation. This would cause the x-amz-user-agent header not being signed in every other API calls.
This bug does not cause issue with existing Pinpoint client because it does not require the header to be signed. It does not affect Cognito Identity client either because it does not need a signer. This bug would cause issue for S3 WIP client as it requires the header to be signed.
Unit test. Manual integration test with WIP S3 client
=> fix(clients): middleware chain revert after every invocation

packages/api-graphql/package.json, packages/core/src/Platform/types.ts, packages/storage/__tests__/common/S3ClientUtils-unit-test.ts, packages/storage/__tests__/providers/CustomUserAgent.test.ts, packages/storage/src/common/S3ClientUtils.ts, packages/storage/src/providers/AWSS3Provider.ts, packages/storage/src/providers/AWSS3ProviderManagedUpload.ts
Add Storage category with specific actions for the custom user agent in all Storage S3 calls.
***Note on Actions:** Instead of using the exact action names currently used in JS, I have aligned the action names with the other platforms (Android/iOS/Flutter) so that the action numbering can be shared across all platforms immediatly instead of having one-off action names for JS that don't align with the other platforms.*
Unit test augmentation. I'll be going through manual testing for storage before this is merged to main.
=> feat: Custom user agent improvements for Storage

packages/api-graphql/package.json, packages/core/src/Platform/types.ts, packages/predictions/__tests__/Providers/AWSAIConvertPredictionsProvider-unit-test.ts, packages/predictions/__tests__/Providers/AWSAIIdentifyPredictionsProvider-unit-test.ts, packages/predictions/__tests__/Providers/AWSAIInterpretPredictionsProvider-unit-test.ts, packages/predictions/src/Providers/AmazonAIConvertPredictionsProvider.ts, packages/predictions/src/Providers/AmazonAIIdentifyPredictionsProvider.ts, packages/predictions/src/Providers/AmazonAIInterpretPredictionsProvider.ts
Add Predictions category with specific actions for the custom user agent in all predictions call *except "convert" for voice to text (transcription), which uses websocket streams and doesn't currently support custom user agent.*
Unit tests added to cover user agent detection in sdk client. I'll be going through manual testing for predictions before this is merged to main.
=> feat: Add custom user agent enhancements for Predictions

packages/auth/__tests__/providers/cognito/signInWithCustomSRPAuth.test.ts, packages/auth/__tests__/providers/cognito/testUtils/authApiTestParams.ts, packages/auth/src/providers/cognito/apis/signIn.ts, packages/auth/src/providers/cognito/apis/signInWithCustomSRPAuth.ts, packages/auth/src/providers/cognito/utils/signInHelpers.ts, packages/auth/src/providers/cognito/utils/srp/AuthenticationHelper.ts
This PR includes the following:
High level sign-in API that delegates to the signInWithCustomSRPAuth API if `CUSTOM_WITH_SRP` AuthFlowType is passed in the request.
Low level signInWithCustomSRPAuth API
- created createAuthChallenge, defineAuthChallenge and verifyAuthChallenge lambda functions
- created a sample app where signIn API returned a `CONFIRMN_SIGN_IN_WITH_CUSTOM_CHALLENGE` when authFlow is `CUSTOM_WITH_SRP`
=> feat(auth): add signInWithCustomSRPAuth API

packages/storage/package.json, packages/storage/tsconfig.json
similar to #11077; This change adds 5.8kB to bundle size limit because it disables importHelpers to keep tslib version aligned. We may need to revisit whether to bump tslib to 2.x. For now the bundle size increase is temporary because it will decrease after the S3 AWS SDK client is removed.
=> chore(storage): upgrade typescript to 5.0.2

packages/analytics/src/Analytics.ts, packages/analytics/src/Providers/EventBuffer.ts, packages/core/package.json, packages/core/src/Platform/detection/React.ts, packages/geo/package.json
React 18 makes complicated most types of detection. Using a common root element lookup wasn't working consistently. This adds a more robust search mechanism that works on the 3 react 18 apps I've tested.
Also, Analytics batch events where missing the user agent action, which this fixes.
Tested snippets manually, then by linking changes into a test app.
=> fix: React detection and Analytics batch upload

packages/core/internals/aws-client-utils/package.json, packages/storage/__tests__/AwsClients/testUtils/mocks.ts, packages/storage/__tests__/AwsClients/testUtils/types.ts, packages/storage/__tests__/AwsClients/xhrTransferHandler-util-test.ts, packages/storage/package.json, packages/storage/src/AwsClients/S3/utils/xhrTransferHandler.ts
An XHR based HTTP transfer handler to be used by custom S3 client. This is to replace the current Axios based handler injected to AWS SDK S3 client. Like Axios handler, this handler also supports abort and download & upload progress events. The thrown error and events to intentionally compatible with Axios ones.
This xhr handler is 1/4 the size of Axios handler
```
Axios handler
Size:       8.66 kB with all dependencies, minified and gzipped
XHR handler
Size:       2.07 kB with all dependencies, minified and gzipped
```
Manually tested on React Native, browsers.
=> feat(s3): custom xhr transfer handler

packages/api-rest/__tests__/RestAPI-test.ts, packages/api-rest/package.json, packages/api-rest/src/RestClient.ts
Reverts most x-amz-user-agent-related changes to api-rest category, with the exception of ceasing to override the UserAgent for ReactNative customers.
yarn tests passing.
=> fix: remove x-amz-user-agent header from api-rest calls to prevent CORS failures

packages/api-rest/package.json, packages/auth/package.json, packages/pubsub/package.json
This change pins the version of `url` that we're using in the library to temporarily resolve a bundle size regression.
Ran `yarn test:size`
=> chore: Pins the version of `url` used in the library

packages/geo/package.json, packages/interactions/package.json, packages/storage/package.json, scripts/dts-bundler/package.json
Update the SDK patch versions to reflect it's internal upgrade to fast-xml-parser version 4.2.4
npm ls fast-xml-parser includes only fast-xml-parser version 4.2.4
```
amplify-js
├─┬ @aws-amplify/geo@2.0.34 -> ./packages/geo
│ └─┬ @aws-sdk/client-location@3.186.2
│   └─┬ @aws-sdk/client-sts@3.186.2
│     └── fast-xml-parser@4.2.4 deduped
└─┬ @aws-amplify/storage@5.4.0 -> ./packages/storage
└─┬ @aws-sdk/client-s3@3.6.3
└── fast-xml-parser@4.2.4
```
AND yarn test passes
=> chore: update sdk client patch versions for fast-xml-parser security update

packages/core/src/Platform/detection/Angular.ts, packages/core/src/Platform/detection/Expo.ts, packages/core/src/Platform/detection/Next.ts, packages/core/src/Platform/detection/Nuxt.ts, packages/core/src/Platform/detection/React.ts, packages/core/src/Platform/detection/helpers.ts
In the latest version of Angular, it is protecting its updates to window from being visible in code outside of Angular. Maybe this is zones?  Either way, I've added a fallback approach that leverages the dom. From what I'm reading using both of these together should cover all recent versions of Angular.
Also expanded variable names per a comment from Chris earlier and added tsignore in a bunch of places. Angular was happy with no warnings until I started importing internal pieces.  When it is compiling the detection code for itself, it warns on these without the annotations. Should have been fine, but resolved on the off chance that a different strict build environment is rebuilding this code.
Retested with angular using linking (earlier verification was done by injecting the angular code …
=> fix(core): Angular web detection and other minor changes

packages/analytics/package.json, packages/api-rest/package.json, packages/auth/src/Auth.ts, packages/core/package.json, packages/core/src/AwsClients/CognitoIdentity/base.ts, packages/core/src/Platform/detectFramework.ts, packages/core/src/Platform/index.ts, packages/geo/package.json, packages/interactions/package.json, packages/notifications/package.json
**Problem:** In testing we are observing that Angular passes no framework for all Cognito and Analytics calls.  I can verify that framework detection is working, but only after the DOM is rendered. Some of our calls are depending upon a cached/default/primed version of the user agent, which isn't maintained.
**Solution:**
For the `defaultConfig` and the Auth platform, add upkeep to keep the platform current when this value is updated.
This value gets updated because sometimes the first calls to detect happen earlier than the framework can be detected. There is a timed invalidation and second run to ensure we are working with accurate framework information for as many calls as possible.
Caching the initial framework call for cases where it is unknown makes all future framework references …
=> fix: Add upkeep to platform/framework caches

package.json
@octokit/core@4.2.2 introduces a breaking change by upgrading their dependency on @octokit/request-error to v4, which no longer supports the use of node@16. This PR sets a resolution for octokit/request-error to unblock our pipeline until octokit fixes their issue.
yarn succeeds locally
=> build: set resolution for octokit/request-error due to breaking change in v4 for node@16 users

packages/core/src/clients/middleware/signing/signer/signatureV4/index.native.ts
Fix a bug found in RN manual test of S3 client. The `getHashedPayload()` is exported in the browser path but missed in the RN path.
Manual test on RN app.
=> fix(clients): add missing export for getHashedPayload in RN

.github/workflows/aws-amplify-dependency-check.yml, .github/workflows/codeql.yml, .github/workflows/issue-pending-response.yml, .github/workflows/lock.yaml, .github/workflows/snyk-security.yml
Following the UI teams best practices, this fixes every GH Action used to a specific commit to avoid accepting any unintended security changes across external committer changes.
Tested on a fork to confirm jobs continue to work.
=> chore: Fix Github action step versions

packages/amazon-cognito-identity-js/__tests__/UserAgent.test.js, packages/amazon-cognito-identity-js/src/Client.js, packages/amazon-cognito-identity-js/src/UserAgent.js, packages/analytics/src/utils/UserAgent.ts, packages/api-graphql/src/internals/InternalGraphQLAPI.ts, packages/auth/__tests__/oauth-test.ts, packages/auth/src/OAuth/OAuth.ts, packages/core/__tests__/Platform-test.ts, packages/core/src/AwsClients/CognitoIdentity/base.ts, packages/core/src/AwsClients/Pinpoint/base.ts, packages/core/src/Platform/index.ts, packages/core/src/Providers/AWSCloudWatchProvider.ts, packages/core/src/index.ts, packages/datastore/__tests__/mutation.test.ts, packages/datastore/__tests__/subscription.test.ts, packages/geo/src/Providers/AmazonLocationServiceProvider.ts, packages/interactions/src/Providers/AWSLexProvider.ts, packages/interactions/src/Providers/AWSLexV2Provider.ts, packages/notifications/src/common/AWSPinpointProviderCommon/index.ts, packages/predictions/__tests__/Providers/AWSAIConvertPredictionsProvider-unit-test.ts, packages/predictions/__tests__/Providers/AWSAIIdentifyPredictionsProvider-unit-test.ts, packages/predictions/__tests__/Providers/AWSAIInterpretPredictionsProvider-unit-test.ts, packages/predictions/src/Providers/AmazonAIConvertPredictionsProvider.ts, packages/predictions/src/Providers/AmazonAIIdentifyPredictionsProvider.ts, packages/predictions/src/Providers/AmazonAIInterpretPredictionsProvider.ts, packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider/index.ts, packages/storage/__tests__/common/S3ClientUtils-unit-test.ts, packages/storage/src/common/S3ClientUtils.ts
Custom user agent enhancements changed the interface for `getAmplifyUserAgent` from returning a string to returning an object. This changes it back at introduces `getAmplifyUserAgentObject` to keep our public interface consistent.
https://github.com/aws-amplify/amplify-ui/issues/4142
Validating with unit tests, manual testing and integration testing (testing flight parallel to this PR)
=> fix: Update getAmplifyUserAgent to retain original interface

packages/core/__tests__/clients/middleware/retry/middleware-test.ts, packages/core/package.json, packages/core/src/clients/middleware/retry/middleware.ts, packages/core/src/clients/serde/responseInfo.ts, packages/storage/__tests__/AwsClients/S3/cases/completeMultipartUpload.ts, packages/storage/__tests__/AwsClients/S3/cases/putObject.ts, packages/storage/__tests__/AwsClients/S3/cases/uploadPart.ts, packages/storage/__tests__/AwsClients/testUtils/mocks.ts, packages/storage/__tests__/AwsClients/xhrTransferHandler-util-test.ts, packages/storage/src/AwsClients/S3/completeMultipartUpload.ts, packages/storage/src/AwsClients/S3/putObject.ts, packages/storage/src/AwsClients/S3/runtime/xhrTransferHandler.ts, packages/storage/src/AwsClients/S3/uploadPart.ts
Fixed 3 compatible issues:
* The retry middleware return `max attempts exhausted` error instead of last error or response. This is a breaking change of behavior compared to AWS SDK
* `Blob.text()` is not available RN. Replace it with `FileReader` based implementation. It's supported in both browsers and RN
* [`uploadPart`](https://github.com/aws/aws-sdk-js-v3/blob/7ed7101dcc4e81038b6c7f581162b959e6b33a04/clients/client-s3/src/protocols/Aws_restXml.ts#L3770), [`completeMultipartUpload`](https://github.com/aws/aws-sdk-js-v3/blob/7ed7101dcc4e81038b6c7f581162b959e6b33a04/clients/client-s3/src/protocols/Aws_restXml.ts#L474) and [`putObject`](https://github.com/aws/aws-sdk-js-v3/blob/7ed7101dcc4e81038b6c7f581162b959e6b33a04/clients/client-s3/src/protocols/Aws_restXml.ts#L3302) each need change …
=> fix(s3): add missing default content-type & support body.text() in RN & optimize retry

packages/analytics/package.json, packages/core/__tests__/clients/middleware/signing/signer/signatureV4/presignUrl-test.ts, packages/core/__tests__/clients/middleware/signing/signer/signatureV4/signRequest-test.ts, packages/core/__tests__/clients/middleware/signing/signer/signatureV4/utils/getCanonicalUri-test.ts, packages/core/__tests__/clients/middleware/signing/signer/signatureV4/utils/getSigningValues-test.ts, packages/core/package.json, packages/core/src/clients/middleware/signing/middleware.ts, packages/core/src/clients/middleware/signing/signer/signatureV4/types/signer.ts, packages/core/src/clients/middleware/signing/signer/signatureV4/utils/getCanonicalRequest.ts, packages/core/src/clients/middleware/signing/signer/signatureV4/utils/getCanonicalUri.ts, packages/core/src/clients/middleware/signing/signer/signatureV4/utils/getSignature.ts, packages/core/src/clients/middleware/signing/signer/signatureV4/utils/getSigningValues.ts, packages/notifications/package.json, packages/pubsub/package.json, packages/storage/src/AwsClients/S3/base.ts
Similar to [AWS SDK](https://github.com/aws/aws-sdk-js-v3/blob/9ba012dfa3a3429aa2db0f90b3b0b3a7a31f9bc3/packages/signature-v4/src/SignatureV4.ts#L76-L83), by default the SigV4 signer URI encodes the already encoded request path when generating canonical request. However, this behavior must be omitted for S3. 
Added a new `uriEscapePath` config to SigV4 signing for this behavior. It's `true` by default so the signer automatically double encodes the request paths. For S3 only, this config should be disabled.
Unit test; Integration test.
=> feat(s3): omit double encoding of path for S3 when signing

packages/storage/__tests__/AwsClients/S3/cases/listParts.ts, packages/storage/__tests__/providers/AWSS3UploadTask-unit-test.ts, packages/storage/src/AwsClients/S3/listParts.ts, packages/storage/src/providers/AWSS3UploadTask.ts
* Fix multipart upload doesn't complete on resume when all parts have been uploaded previously
* Fix custom S3 client `listParts` output doesn't include the `Size` property
* Local testing
* Unit testing
=> fix(storage): missing Size in listParts output

packages/core/package.json
The isomorphic-unfetch dependency re-exports artifacts from node-fetch package in its .d.ts file. However, the node-fetch package does not contain any .d.ts file with itself. So the exported artifacts can not be resolved by tsc. It's not an issue before possibly because the client-s3 contains transitive runtime dependency of @types/node-fetch. Since it's removed now, we are encountered with this error.
Adding the dependency to runtime instead of dev or peer deps to prevent brokage for customers
* https://github.com/aws-amplify/amplify-ui/actions/runs/5407197729/jobs/9824935017?pr=4182
* https://github.com/developit/unfetch/issues/96
Local test
=> fix(core): add @types/node-fetch to runtime dependency

.circleci/config.yml, package.json, packages/storage/package.json, packages/storage/src/AwsClients/S3/utils/serializeHelpers.ts
2 changes in this PR:
1. `serializeObjectSsecOptionsToHeaders` passes the `input` to output in some code path causing the input like `Bucket` or `Key` serialized to headers, hence the signer throws encountering non-string headers
2. Pin the associated `minipass` dependency to unblock the integration tests. In a few integration test cases, we are stucked on older Cypress and Node.js. The minipass made a major version bump and made into
the dependency graph. It deprecates the Node.js 14 hence broke the integration test in older image. See [failed build](see: https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/20379/workflows/74a58937-dfe4-4d09-b676-7ac79bc59708/jobs/301782)
Integration test; Unit test
- [] Tests are [changed or …
=> fix(storage): not pass the input to SSE-C serializer output

.envrc, packages/api/src/API.ts
- Create a test `aws-exports.js` file that includes a model-introspection schema
- Verify that adding an introspection schema does NOT break the any validation logic within the JS library.
- `API.generateClient()` returns an "empty" object without any implementation fully hooked up yet. (Just stubbed out)
- Available stubs are:
- graphql
- models
- `generateClient` accepts a generic that extends a "stubbed" Schema type and can represent it internally. For now, we can pass in "`{}`" or "`any`" into `generateClient<T>`.
- the generated client is aware of the model-introspection schema and "can print" the model introspection schema upon client generation.
- Generates a GraphQL document given model name and operation (create, update, delete, list, get)
- Allows customers to pass in input …
=> Bare-bones api client v6

packages/analytics/__tests__/Analytics.test.ts
Adds a basic unit test to exercise custom `AnalyticsProvider` functionality.
Local run.
=> chore: Added custom AnalyticsProvider test

packages/auth/__tests__/providers/cognito/auth-token-migration.test.ts, packages/auth/src/storage/DeviceKeyTokenManager.ts, packages/auth/src/storage/LegacyDeviceKeyTokenManager.ts, packages/auth/src/storage/LegacyUserPoolManager.ts, packages/auth/src/storage/UserPoolTokenManager.ts, packages/auth/src/storage/helpers.ts, packages/auth/src/storage/keys.ts, packages/auth/src/storage/types/models.ts
This PR adds auth token migration flows for legacy user pool and device key tokens.
The migration flow will start on a single `load` tokens action and then will set up a version flag in storage. 
This flaw is to avoid running the migration flow if it was already ran. This flag [strategy](https://github.com/aws-amplify/amplify-flutter/blob/main/packages/auth/amplify_auth_cognito_dart/lib/src/state/machines/credential_store_state_machine.dart#L309) was already implemented in Flutter's migration plan
Pending:
- log possible errors in the token migration flow.
- RN migration flow.
=> feat: add auth token migration

package.json, scripts/set-preid-versions.sh
This change introduces a script to enable reliable pre-release testing with the new `peerDependencies` configuration. When publishing a release that specifies a pre-release ID, the peer dependencies on `@aws-amplify/core` across the library will be updated to point to the version of `@aws-amplify/core` being published. If a pre-release ID is not specified (such as during our production releases), this process will be skipped. The process is triggered automatically via the NPM `prepare` lifecycle hook, which Lerna will invoke when required.
This script requires that `jq` be installed. This is available by default on Linux hosts and via `brew install jq` for OSX. This script was already required for other ops processes including our roll-back procedure.
Other changes:
- Removed unneeded …
=> feature: Add script for supporting pre-release IDs

.circleci/config.yml, license_config.json, package.json, packages/api-rest/__tests__/RestAPI-test.ts, packages/api-rest/package.json, packages/api-rest/src/RestClient.ts, packages/core/__tests__/Platform-test.ts, packages/core/package.json, packages/core/src/Platform/index.ts, packages/core/src/Platform/types.ts, packages/geo/package.json, packages/notifications/package.json, packages/predictions/package.json, packages/pubsub/src/Providers/AWSAppSyncRealTimeProvider/index.ts, packages/storage/package.json, packages/storage/src/AwsClients/S3/putObject.ts, packages/storage/src/AwsClients/S3/uploadPart.ts, packages/storage/src/Storage.ts, packages/storage/src/common/MD5utils.native.ts, packages/storage/src/common/MD5utils.ts, packages/storage/src/providers/AWSS3ProviderManagedUpload.ts
Previous release: https://github.com/aws-amplify/amplify-js/pull/11622
=> release: Amplify JS release

packages/storage/package.json
Moves the `typescript` dependency in Storage to dev dependencies to avoid installing it in consuming apps.
The `tsconfig.tsbuildinfo` confirms that the package is being built with `5.0.2`:
```
{"program": { ... }, ..., "version":"5.0.2"}
```
=> chore: Move Storage TS dependency to `devDependencies`

package.json
This is ok because the AWS SDK and crypto dependencies have been pinned already
Unblock the main branch if underlying issue is not resolved in smithy-typescript repo.
Related to: https://github.com/awslabs/smithy-typescript/issues/845
build passes
=> chore: pin @smtihy/types to 1.1.0 to prevent build failure in TS3.8

package.json
This PR removes the smithy type resolution that was causing the build process to fail. The AWS-SDK has released a new version of the aws-sdk/types which fixes the previous issue.
=> chore: remove smithy resolution

package.json, packages/api-graphql/__tests__/v6-test.ts, packages/api-graphql/src/types/index.ts, packages/api/package.json, packages/api/src/API.ts, packages/api/src/internals/InternalAPI.ts, packages/api/src/types/index.ts
Fixes type map for `generateClient` result to include v5 style type overrides. Both of these queries should be correctly typed:
```ts
const listResult = client.graphql<GraphQLQuery<ListThreadsQuery>>({ ... });
// items is correctly typed
const items = result.data?.listThreads;
const subResult = client.graphql<GraphQLSubscription<OnCreateThreadSubscription>>({ ... });
const sub = subResult.subscribe?.({
// message is correctly typed
next(message) { ... }
});
```
Added tests.
=> fix: support v5 style type overrides in v6 graphql method

.github/integ-config/integ-all.yml
Disabling the Auth Next RSC test in Firefox.
https://github.com/aws-amplify/amplify-js/actions/runs/5754429667
The test is passing in circle and passes in Chrome. Locally, I see Firefox failures when running a dev build, but it passes for a production app build. It appears that somewhere between versions of Cypress and Firefox we are seeing issues specific to this test that don't occur for me when manually stepping through the test actions.
Recommend we disable the test on firefox pending further research.
=> chore: Disable RSC test for firefox

.circleci/android-rn.sh, .circleci/config.yml, .circleci/duplicates-npm.sh, .circleci/retry-yarn-script.sh
Reintroduce circle without deploy/post-release steps
=> chore: Reintroduce circle without deploy/post-release steps

.github/canary-config/canary-all.yml, .github/workflows/callable-canary-e2e-runner.yml, .github/workflows/callable-canary-e2e-tests.yml, .github/workflows/callable-canary-e2e.yml, .github/workflows/callable-canary-sampleapp-tests.yml, .github/workflows/cron-canary-test.yml, .github/workflows/on-schedule-canary-test.yml
Addition of automated canary tests which run on intervals of 60m as well as on post-release.
By executing workflow runs through GitHub Actions to ensure everything is running smoothly.
=> chore: add canary tests

packages/rtn-push-notification/ios/AmplifyRTNPushNotification.xcodeproj/project.pbxproj, packages/rtn-push-notification/ios/AmplifyRTNPushNotification.xcodeproj/project.xcworkspace/contents.xcworkspacedata, packages/rtn-push-notification/ios/AmplifyRTNPushNotification.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Add `.xcodeproj` file for the `AmplifyRTNPushNotification` iOS module.
When installing `@aws-amplify/rtn-push-notification` in a react-native project that uses react-native version < 0.69, the native iOS module pod cannot be autolinked. The root cause is that the older version of `@react-native-community/cli` tooling doesn't support recognizing the `.xcworkspace` file of the a module for autolinking. 
=> fix(notifications): ios module pod cannot be autolinked in RN version < 0.69

packages/amazon-cognito-identity-js/package.json, packages/amazon-cognito-identity-js/webpack.config.js, packages/auth/package.json, packages/datastore/package.json, packages/pubsub/package.json, packages/pushnotification/package.json, packages/storage/package.json, yarn.lock
This change upgrades `amazon-cognito-identity-js` to use Webpack 5 to resolve a lingering `glob-parent` alert. With this change the entire library will be aligned on Webpack 5 for UMD artifact generation. Also updated the clean script to remove `dist` and removed some unused `babel` imports in `pushnotification`.
**On the `buffer` dependencies**
Without these dependencies we observed a bundle size regression as Buffer 5.7.1 was being preferred for categories that directly or transitively use `buffer`. It appears that when a sub-category has a dependency on Webpack v4, the package manager was correctly hoisting buffer v4.9.2. However with the removal of Webpack v4, the resolution logic was preferring v5.7.1 (from `react-native-url-polyfill` in `core`) instead resulting in a duplicated …
=> chore: Update `amazon-cognito-identity-js` to use Webpack 5

packages/api/package.json, yarn.lock
Attempting to fix [these failures](https://github.com/aws-amplify/amplify-js/actions/runs/5823328865/job/15799195403).
```
Error: [0] Error: node_modules/@aws-amplify/api/lib-esm/API.d.ts:6:33 - error TS2307: Cannot find module '@aws-amplify/types-package-alpha' or its corresponding type declarations.
[0] 
[0] 6 import type { ModelTypes } from '@aws-amplify/types-package-alpha';
[0]                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Updated, linked, and ran the affected sample locally.
=> fix: missing types-package-alpha dep

package.json
Pins `@smithy/types` to version 2.1.0 to resolve a backwards compatibility error in TS 3.4 type artifacts.
=> fix: Pin Smithy resolution for now

packages/api-graphql/package.json, packages/api/package.json, packages/core/__tests__/Platform-test.ts, packages/core/src/Platform/detectFramework.ts, packages/geo/package.json, packages/interactions/package.json, packages/predictions/package.json, packages/pubsub/package.json, packages/storage/package.json
Added logic to clean up the Framework detection observers, and ignore new incoming observers after the detection completes.
https://github.com/aws-amplify/amplify-js/issues/11770
Unit tests.
=> fix(core): fail to clean up framework observers

packages/analytics/package.json, packages/api-graphql/package.json, packages/datastore/package.json, packages/notifications/package.json, packages/predictions/package.json, packages/pubsub/package.json
This change upgrades us to UUID v9. This upgrade will require that customers install the `react-native-random-values` polyfill, which is being tracked with our overall RN v6 story. This change will also resolve one of Amplify's long standing deprecation warnings:
```
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
```
Unit tests
=> chore: Upgrade to UUID v9

packages/auth/src/providers/cognito/types/index.ts, packages/auth/src/types/index.ts, packages/auth/src/types/models.ts, packages/auth/src/types/requests.ts
This PR adds missing type exports
**Other changes**
- It adds default generic parameters to requests and models. This will help to import and use these types without passing any generic type parameters.
```typescript
import {AuthNextSignInStep} from 'aws-amplify/auth'
// before
const signInStep:AuthNextSignInStep // --> Typescript will yell it needs a generic type param
// after
const signInStep:AuthNextSignInStep // --> Typescript is happy
```
yarn build & yarn test works
=> chore(auth): adding missing type exports

packages/storage/__tests__/providers/s3/downloadData.test.ts, packages/storage/__tests__/providers/s3/getProperties.test.ts, packages/storage/__tests__/providers/s3/getUrl.test.ts, packages/storage/package.json, packages/storage/server/package.json, packages/storage/src/providers/s3/apis/copy.ts, packages/storage/src/providers/s3/apis/downloadData.ts, packages/storage/src/providers/s3/apis/getProperties.ts, packages/storage/src/providers/s3/apis/getUrl.ts, packages/storage/src/providers/s3/apis/internal/getProperties.ts, packages/storage/src/providers/s3/apis/internal/getUrl.ts, packages/storage/src/providers/s3/apis/internal/list.ts, packages/storage/src/providers/s3/apis/internal/remove.ts, packages/storage/src/providers/s3/apis/remove.ts, packages/storage/src/providers/s3/apis/server/getProperties.ts, packages/storage/src/providers/s3/apis/server/getUrl.ts, packages/storage/src/providers/s3/apis/server/index.ts, packages/storage/src/providers/s3/apis/server/list.ts, packages/storage/src/providers/s3/apis/server/remove.ts, packages/storage/src/providers/s3/utils/getKeyWithPrefix.ts, packages/storage/src/providers/s3/utils/resolveCredentials.ts, packages/storage/src/providers/s3/utils/resolveStorageConfig.ts, packages/storage/src/server.ts
- Moved the original APIs implementation into `/internal` with adding a positional parameter `amplify: AmplifyClassV6`
- Added the APIs that are supposed to run on the client side with the original function signatures
- Added the APIs that are supposed to run on the server side, with adding a positional parameter `contextSpect: AmplifyServer.Context`
- Updated util functions allow injecting an `AmplifyClassV6` instance instead of hardcoding the look up of the Amplify singleton
- Exported the server side APIs via `@aws-amplify/storage/server` subpath
- ~~Fixed the expiration assertion for the getUrl API~~ got the fix after rebasing
=> feat(storage): make storage apis runnable with the server context

packages/adapter-nextjs/package.json
- The node:http usage breaks webpack bundling process of size-limit, condiering the helpers of this package are running on the server primarily, building the code into a webpack bundle to check the bundle size doesn't create much value. Disabling size-limit for for now.
Disabling `test:size` script. Reasoning see the commit message.
=> chore(adapter-nextjs): disbale size-limit test

packages/auth/__tests__/providers/cognito/fetchUserAttributes.test.ts, packages/auth/__tests__/providers/cognito/getCurrentUser.test.ts, packages/auth/src/providers/cognito/apis/fetchUserAttributes.ts, packages/auth/src/providers/cognito/apis/internal/fetchUserAttributes.ts, packages/auth/src/providers/cognito/apis/internal/getCurrentUser.ts, packages/auth/src/providers/cognito/apis/server/fetchUserAttributes.ts, packages/auth/src/providers/cognito/apis/server/getCurrentUser.ts, packages/auth/src/providers/cognito/apis/server/index.ts, packages/auth/src/server.ts, packages/core/src/libraryUtils.ts
* Removed `**/package.json` from the `files` field in the `package.json`
* Now export the low level `fetchAuthSession` from the `/internals` subpath
Made the following APIs to be callable with Amplify server context.
* `getCurrentUser`
* `fetchUserAttributes`
* Updated relevant unit tests
* Unit tests
* Making API call in Next.js server.
=> feat(auth): make a subset of auth apis runnable with the server context

packages/storage/src/providers/s3/apis/copy.ts, packages/storage/src/providers/s3/apis/internal/copy.ts, packages/storage/src/providers/s3/apis/internal/getProperties.ts, packages/storage/src/providers/s3/apis/internal/getUrl.ts, packages/storage/src/providers/s3/apis/internal/list.ts, packages/storage/src/providers/s3/apis/internal/remove.ts, packages/storage/src/providers/s3/apis/server/copy.ts, packages/storage/src/providers/s3/apis/server/index.ts
Make the storage `copy` API runnable with the server context.
=> feat(storage): make the copy API runnable with server context

packages/core/src/singleton/Auth/index.ts
guest credentials obtained only if isMandatorySignIn is false
=> fix(auth): guest credentials obtained only if isMandatorySignIn is false

packages/auth/src/OAuth/OAuth.ts, packages/core/src/Credentials.ts, packages/core/src/libraryUtils.ts, packages/core/src/singleton/Amplify.ts, packages/pubsub/src/Providers/constants.ts, packages/storage/src/common/StorageConstants.ts
* Removed the external usage warning from Hub caused by the Amplify singleton `configure`
* Export `AMPLIFY_SYMBOL` from the `@aws-amplify/core/internals/utils` subpath and use across packages
=> chore(repo): use single AMPLIFY_SYMBOL definition

packages/storage/__tests__/AwsClients/xhrTransferHandler-util-test.ts, packages/storage/__tests__/providers/s3/uploadData/multipartHandlers.test.ts, packages/storage/src/AwsClients/S3/runtime/index.browser.ts, packages/storage/src/AwsClients/S3/runtime/index.native.ts, packages/storage/src/AwsClients/S3/runtime/index.ts, packages/storage/src/AwsClients/S3/runtime/xhrTransferHandler.ts, packages/storage/src/AwsClients/S3/utils/index.ts, packages/storage/src/errors/CanceledError.ts, packages/storage/src/index.ts, packages/storage/src/providers/s3/apis/uploadData/multipart/uploadCache/index.ts, packages/storage/src/providers/s3/apis/uploadData/multipart/uploadHandlers.ts, packages/storage/src/providers/s3/index.ts, packages/storage/src/providers/s3/utils/transferTask.ts
This issue mainly fixes the following issues:
1. An error thrown by canceling a task should be an instance of  `StorageError`
2. Fixed an error that a task cannot be canceled if it's paused.
* Unit test
* Integration test
=> fix(storage): CanceledError not a StorageError; cannot cancel paused task

.github/canary-config/canary-all.yml
Temporary disable CPK tests that are timing out. And related model tests that are missing on the samples repo
=> Disable datastore cpk canary

.github/workflows/callable-canary-e2e-tests.yml, .github/workflows/callable-canary-sampleapp-tests.yml
- Replaces `.circleci` script reference with `scripts`
- VSCode/Prettier did a bunch of whitespace changes
=> fix: Canary workflows

packages/adapter-nextjs/__tests__/utils/createCookieStorageAdapterFromNextServerContext.test.ts, packages/adapter-nextjs/src/utils/createCookieStorageAdapterFromNextServerContext.ts
Remove the usage of `http`, it was used to detect the input instances. 
* Build with the sample Next.js app
* Running the sample Next.js app manually
=> fix(adapter-nextjs): remove usage of node http

packages/storage/__tests__/providers/s3/apis/copy.test.ts, packages/storage/__tests__/providers/s3/apis/downloadData.test.ts, packages/storage/__tests__/providers/s3/apis/getProperties.test.ts, packages/storage/__tests__/providers/s3/apis/getUrl.test.ts, packages/storage/__tests__/providers/s3/apis/list.test.ts, packages/storage/__tests__/providers/s3/apis/remove.test.ts, packages/storage/__tests__/providers/s3/apis/uploadData/multipartHandlers.test.ts, packages/storage/__tests__/providers/s3/apis/uploadData/putObjectJob.test.ts, packages/storage/__tests__/providers/s3/apis/utils/resolveS3ConfigAndInput.test.ts, packages/storage/src/providers/s3/utils/resolveS3ConfigAndInput.ts
* Make `resolveS3ConfigAndInput` use the `fetchAuthSession` from the injected `Amplify` instance instead of the singleton
* Unit tests
* Local `yarn link` tested with the Next.js sample App
=> fix(storage): resolveS3ConfigAndInput not using injected fetchAuthSession

packages/storage/src/providers/s3/apis/internal/getUrl.ts
Fix assertion for maxUrlExpiration in getUrl api
=> fix(storage):  assertion for maxUrlExpiration in getUrl api

packages/core/__tests__/UniversalStorage-browser-test.ts, packages/core/src/UniversalStorage/index.ts
https://github.com/aws-amplify/amplify-js/issues/11945
* Decode the cookie header before using the value to create a cookie store
**Context**
When `Amplify.configure({ ssr: true })`, the Cognito auth tokens will be stored in cookie store. This is handled by the package `amazon-cognito-identity-js` using `js-cookie` under the hood.
Per RFC 6265 [section 4.1.1](https://datatracker.ietf.org/doc/html/rfc6265#section-4.1.1) and RFC 2616 [section 2.2](https://datatracker.ietf.org/doc/html/rfc2616#section-2.2), a cookie name must be a `token` that doesn't contain any separators. 
In the situation described in the linked issue, the cookie name contains `'@'` as a part of user email address, hence, `js-cookie` encodes it following above the aforementioned standard. However, the `UniversalStorage` …
=> fix(core): decode encoded cookie name while creating universal storage

packages/core/src/parseAWSExports.ts
The default configuration starts with an empty oauth object, however the parse logic only checks for oauth to be undefined. This is a tiny fix to not proceed if there the oauth object is empty.
```
const awsmobile = {
...
oauth: {},
...
};
Amplify.configure(awsmobile) // does not error out
```
=> fix(core): parse empty oauth param

packages/storage/__tests__/providers/s3/apis/list.test.ts, packages/storage/src/providers/s3/apis/internal/list.ts, packages/storage/src/types/requests.ts
- Storage `list` request would expose `prefix` instead of `path`. 
- No change in the behavior of the API
**DX**
From
```
await list({ path: "photo" });
```
To
```
await list({ prefix: "photo" });
```
- updated unit tests
- validated on sample app
=> fix(storage): rename list request path to prefix

packages/auth/cognito/server/package.json, packages/auth/package.json, packages/aws-amplify/auth/cognito/server/package.json, packages/aws-amplify/package.json, packages/aws-amplify/src/auth/cognito/server/index.ts, packages/storage/package.json
This change adds missing export path for `aws-amplify/auth/cognito/server` as well as some missing `typesVersions` configurations which were missed.
Tested in Verdaccio
=> chore: Set up missing exports & `typesVersions` specification

packages/adapter-nextjs/__tests__/utils/getAmplifyConfig.test.ts, packages/adapter-nextjs/__tests__/withAmplify.test.ts, packages/adapter-nextjs/src/utils/getAmplifyConfig.ts, packages/adapter-nextjs/src/withAmplify.ts
* Added a fallback in the `getAmplifyConfig` function to ensure get the amplify config in the Next.js Pages Router.
* Local testing with a Next.js sample app using the Pages Router
=> fix(adapter-nextjs): getAmplifyConfig may not return config in the pages router

packages/core/__tests__/singleton/Singleton.test.ts, packages/core/src/singleton/Auth/index.ts, packages/core/src/singleton/Auth/types.ts
Disable check for `allowGuestAccess: true` in order to call `credentialsProvider` when no tokens are present
=> fix(core): allow credentials to be called without token provider and no guest mode

packages/auth/src/providers/cognito/apis/signInWithRedirect.ts
* Ensure `urlListener()` should be called only in browser environment. (the underlying usage of `localStorage` breaks `npx next build`)
=> fix(auth): signInWithRedirect urlListner attaches for non-browser env

packages/adapter-nextjs/__tests__/utils/getAmplifyConfig.test.ts, packages/adapter-nextjs/__tests__/withAmplify.test.ts, packages/adapter-nextjs/src/utils/getAmplifyConfig.ts, packages/adapter-nextjs/src/withAmplify.ts, packages/aws-amplify/__tests__/exports.test.ts, packages/aws-amplify/__tests__/initSingleton.test.ts, packages/aws-amplify/package.json, packages/aws-amplify/src/adapterCore/index.ts, packages/aws-amplify/src/index.ts, packages/aws-amplify/src/initSingleton.ts, packages/core/__tests__/singleton/Singleton.test.ts, packages/core/src/index.ts, packages/core/src/libraryUtils.ts, packages/core/src/singleton/Amplify.ts, packages/core/src/singleton/types.ts
* Made the `Amplify.configure` function accept both legacy config object and the config object with the new shape.
* Removed the need of calling `parseAmplifyConfig` function.
* Now export `parseAWSExports` function from the `internals/util` subpath from the core package.
* Updated relevant implementation of `adapter-nextjs`
* Unit tests
* Manual integration tests with the Next.js sample app
=> feat: make Amplify.configure accept both new and legacy config objects

packages/auth/src/providers/cognito/apis/signInWithRedirect.ts, packages/aws-amplify/package.json, packages/core/src/Hub/types/AuthTypes.ts
Dispatches the `customOAuthState` hub event when `customState` is passed in the `signInRequest` and when the state has been validated.
**Other changes:**
Increase bundle size for `signInWithRedirect` API as it is using a util function to decode the oauth state.
Listened for this hub event in a sample app using the `implicit` and `code` oauth flows.
=> feat(auth): add `customOAuthState` missing hub event

packages/auth/src/providers/cognito/utils/signInHelpers.ts, packages/aws-amplify/package.json, yarn.lock
`@smithy/util-base64` has been removed from `packages/auth`. Using the home baked `base64Encoder` instead.
* Updated `yarn.lock` and size limits
=> fix(auth): use base64Encoder instead of smithy base64 tool

packages/api-graphql/package.json
1. Re-enabled jest diagnostics.
1. Updated the `testPathIgnorePatterns` to include `<rootDir>/`.
1. Added `<rootDir>/__tests__` to coverage ignore paths.
1. Added a type mismatch and ensured `jest` gave a TS error.
1. Removed the type mismatch and watched tests pass again.
1. Confirmed with eyeballs that code coverage now shows in my working copy that lives under a `.../lib/...` path. (Previously not working.)
=> chore: api-graphql enable jest diagnostics, fixed ignore paths

packages/core/__tests__/singleton/Auth/utils/index.test.ts, packages/core/src/singleton/Auth/utils/index.ts
Removed the usage of `TextDecoder`, with the native friendly, the `decodeJWT` util function should work in react-native out of box.
=> chore(core): update decodeJWT impl. not using TextDecoder

packages/rtn-web-browser/ios/AmplifyRTNWebBrowser.m, packages/rtn-web-browser/ios/AmplifyRTNWebBrowser.swift, packages/rtn-web-browser/src/apis/openAuthSessionAsync.ts, packages/rtn-web-browser/src/types.ts
This PR fixes an issue in iOS where deeplinking back to the app is blocked when a redirect scheme is not matched.
* `yarn test`
* Tested in a React Native app on iOS and Android
* Tested in an Expo app on iOS and Android (*not* Expo Go)
=> fix(web-browser): pass callbackURLScheme to auth session

packages/auth/src/providers/cognito/apis/deleteUser.ts, packages/auth/src/providers/cognito/utils/clients/CognitoIdentityProvider/index.ts
The DELETE rest API call does not contain a body in the response. Parsing it will cause a `SyntaxError: Unexpected end of JSON input`. Create a separate Deserializer for handling this scenario  
- Success case: calling deleteUser should 
- Should NOT throw a `SyntaxError: Unexpected end of JSON input` on sampleApp
- delete the user on cognito console
- clear deviceToken on `localStore`
- sign-out successfully, fetchAuthSession() to make sure there aren't any access tokens
- Fail case: provide invalid access token to make sure errors are not swallowed  
=> fix(auth): deleteUser client resp parsing

packages/analytics/__tests__/providers/kinesis-firehose/apis/record.test.ts, packages/analytics/__tests__/providers/kinesis-firehose/utils/getEventBuffer.test.ts, packages/analytics/__tests__/providers/kinesis-firehose/utils/resolveConfig.test.ts, packages/analytics/__tests__/providers/kinesis/apis/record.test.ts, packages/analytics/src/providers/kinesis-firehose/apis/record.ts, packages/analytics/src/providers/kinesis-firehose/types/buffer.ts, packages/analytics/src/providers/kinesis-firehose/types/index.ts, packages/analytics/src/providers/kinesis-firehose/types/inputs.ts, packages/analytics/src/providers/kinesis-firehose/utils/constants.ts, packages/analytics/src/providers/kinesis-firehose/utils/getEventBuffer.ts, packages/analytics/src/providers/kinesis-firehose/utils/index.ts, packages/analytics/src/providers/kinesis-firehose/utils/resolveConfig.ts, packages/analytics/src/providers/kinesis/apis/record.ts, packages/analytics/src/providers/kinesis/types/index.ts, packages/analytics/src/providers/kinesis/types/inputs.ts, packages/analytics/src/utils/eventBuffer/EventBuffer.ts, packages/aws-amplify/__tests__/exports.test.ts, packages/core/src/providers/kinesis-firehose/types/index.ts, packages/core/src/providers/kinesis-firehose/types/kinesis-firehose.ts, packages/core/src/singleton/Analytics/types.ts
Add `record` API for Analytics service provider Kinesis Data Firehose.
=> feat(analytics): add record API for service provider kinesis firehose

packages/core/src/singleton/Auth/utils/index.ts
This is a small change in assertion value changing from `cognitoConfig.userPoolClientId`  to `cognitoConfig.userPoolId` to avoid duplicacy in checking.
=> fix(core): change userPoolClientId to userPoolId in assertion

packages/analytics/__tests__/providers/kinesis-firehose/apis/record.test.ts, packages/analytics/__tests__/providers/kinesis/apis/record.test.ts, packages/analytics/__tests__/providers/kinesis/utils/getEventBuffer.test.ts, packages/analytics/__tests__/providers/personalize/apis/record.test.ts, packages/analytics/__tests__/providers/personalize/utils/cachedSession.test.ts, packages/analytics/__tests__/providers/personalize/utils/getEventBuffer.test.ts, packages/analytics/__tests__/providers/personalize/utils/resolveConfig.test.ts, packages/analytics/__tests__/testUtils/mockConstants.test.ts, packages/analytics/src/errors/assertValidationError.ts, packages/analytics/src/errors/validation.ts, packages/analytics/src/providers/personalize/apis/record.ts, packages/analytics/src/providers/personalize/types/buffer.ts, packages/analytics/src/providers/personalize/types/index.ts, packages/analytics/src/providers/personalize/types/inputs.ts, packages/analytics/src/providers/personalize/utils/autoTrackMedia.ts, packages/analytics/src/providers/personalize/utils/cachedSession.ts, packages/analytics/src/providers/personalize/utils/constants.ts, packages/analytics/src/providers/personalize/utils/getEventBuffer.ts, packages/analytics/src/providers/personalize/utils/index.ts, packages/analytics/src/providers/personalize/utils/resolveConfig.ts, packages/analytics/src/utils/eventBuffer/EventBuffer.ts, packages/aws-amplify/__tests__/exports.test.ts, packages/aws-amplify/package.json, packages/core/src/providers/personalize/types/index.ts, packages/core/src/providers/personalize/types/personalize.ts, packages/core/src/singleton/Analytics/types.ts
- add `record` API for Analytics service provider Amazon Personalize.
=> feat(analytics): add record API for Analytics service provider Personalize

packages/api-graphql/__tests__/utils/expects.ts, packages/api-graphql/src/internals/InternalGraphQLAPI.ts
Fixes a regression in InternalGraphQL client introduced in #12142 & fixes unit tests to support abort controller.
=> fix: Fix regression in InternalGraphQL client & broken tests

lerna.json, package.json, packages/aws-amplify/package.json, packages/notifications/package.json, packages/rtn-push-notification/package.json, yarn.lock
Fixes the absent notifications dependency to aws-amplify this allows the notifications packages to show up in the scoped `@aws-amplify` package in the final publish
- setup verdaccio 
- install on a sample app
- can access notifications APIs
=> fix(notifications): add notifications as dependency to aws-amplify

packages/storage/package.json, packages/storage/src/providers/s3/utils/client/runtime/package.json
Added appropriate `react-native` root fields to ensure the module resolution picks up correct code path of `packages/storage` in a react-native app.
=> fix(storage): react-native picks up wrong utils/client/runtime

packages/auth/__tests__/providers/cognito/signOut.test.ts, packages/auth/src/providers/cognito/apis/signInWithRedirect.ts, packages/auth/src/providers/cognito/apis/signOut.ts, packages/auth/src/providers/cognito/utils/signInWithRedirectStore.ts, packages/auth/src/providers/cognito/utils/types.ts, packages/auth/src/types/inputs.ts, packages/auth/src/utils/openAuthSession.native.ts, packages/auth/src/utils/openAuthSession.ts, packages/auth/src/utils/types.ts, packages/rtn-web-browser/ios/AmplifyRTNWebBrowser.m, packages/rtn-web-browser/ios/AmplifyRTNWebBrowser.swift, packages/rtn-web-browser/src/apis/openAuthSessionAsync.ts, packages/rtn-web-browser/src/types.ts
This PR adds ~~prop drilling~~ an option `preferPrivateSession` which adds the ability to toggle the underlying `prefersEphemeralSession` flag when opening an ASWebAuthenticationSession on iOS during `signInWithRedirect`.
* Tested against React Native app on iOS
* `yarn test`
=> feat: add ability to set ephemeral session

packages/auth/src/providers/cognito/apis/signInWithRedirect.ts
Removed the pathname check in the `signInWithRedirect` that causes issue when
* Specify redirect URI as `rntest://`
* Cognito redirect back to `rntest:///?code=xxx&state=yyy`
=> chore(auth): remove unnecessary pathname check that may cause issue

packages/storage/src/providers/s3/apis/uploadData/index.ts, packages/storage/src/types/inputs.ts
This change involves removing `File` type from `uploadData` api input.
Some Observation while uploading to S3 in WEB (Time take in milliseconds):
Before [Having File Type]
4 MB (Small):  977 ms
100 MB (Medium):   10,265 ms
1 GB (Large):  55,633 ms
10 GB (Very Large):   5,99,674 ms
After [Removing File type]
4 MB (Small):   744 ms
100 MB (Medium):   9,316 ms
1 GB (Large): 54,393 ms
10 GB (Very Large):   6,02,375 ms
=> chore(storage): remove File type from uploadInput type

packages/auth/__tests__/providers/cognito/tokenProvider.test.ts, packages/auth/src/providers/cognito/tokenProvider/TokenOrchestrator.ts, packages/auth/src/providers/cognito/tokenProvider/TokenStore.ts, packages/auth/src/providers/cognito/tokenProvider/types.ts, packages/auth/src/providers/cognito/utils/signInHelpers.ts
device metadata for multiple users on single device
user1 (has encoded username)
user2 (has not encoded username)
user1 -> signIn -> confirmSignIn() -> rememberdevice()
user1 -> signIn (bypass MFA )
user1 -> signOut
user2 -> signIn -> confirmSignIn() -> rememberdevice()
user2 -> signIn (bypass MFA)
user2 -> signOut
user1 -> signIn (bypass MFA) -> signOut
user2 -> signIn (bypass MFA) -> signOut
user1 -> signIn (bypass MFA) -> signOut
user2 -> signIn (bypass MFA) -> signOut
confirmed localStore deviceMetadata for both users co-exist   
=> fix: device metadata for multiple users on single device

.github/workflows/push-integ-test.yml, packages/aws-amplify/package.json
Turn on integ test execution for `next/main`
I've run this locally. It's not [currently passing](https://github.com/stocaaro/amplify-js/actions/runs/6421070921).  This won't block anything, just an opportunity for signal on our changes while we're building towards GA.
=> chore: Turn on integ tests on next/main

packages/storage/src/providers/s3/apis/internal/getUrl.ts
Fixes an invalid UA-related import path in the `getUrl` API.
=> fix: Fixed UA import path

.github/workflows/pr.yml
Temporarily disables bundle tests in PRs while things stabilize. 
=> chore: Disable bundle size tests in CI

packages/analytics/src/providers/kinesis-firehose/types/buffer.ts, packages/analytics/src/providers/kinesis/types/buffer.ts, packages/analytics/src/providers/personalize/types/buffer.ts, packages/core/src/libraryUtils.ts, packages/core/src/providers/pinpoint/apis/flushEvents.ts, packages/core/src/singleton/Auth/types.ts, packages/storage/__tests__/providers/s3/apis/copy.test.ts, packages/storage/__tests__/providers/s3/apis/downloadData.test.ts, packages/storage/__tests__/providers/s3/apis/getProperties.test.ts, packages/storage/__tests__/providers/s3/apis/getUrl.test.ts, packages/storage/__tests__/providers/s3/apis/list.test.ts, packages/storage/__tests__/providers/s3/apis/remove.test.ts, packages/storage/__tests__/providers/s3/apis/uploadData/multipartHandlers.test.ts, packages/storage/__tests__/providers/s3/apis/uploadData/putObjectJob.test.ts, packages/storage/src/providers/s3/types/options.ts
Exports `AWSCredentials` type for internal uses and updates references to the AWS SDK credentials type to use this instead.
=> chore: Exported `AWSCredentials` for internal use

packages/auth/__tests__/providers/cognito/refreshToken.test.ts, packages/auth/src/providers/cognito/utils/refreshAuthTokens.ts
The `refreshToken` originated from login was cleared after `refreshAuthTokens` was triggered, and any subsequent call would end up in an `AuthError`.
This PR returns the original `refreshToken`, that was issued during sign-in, when calling `refreshAuthTokens`.
- added a unit test to check the same refreshToken is return
- test in a sample app that multiple calls to `fetchAuthSession({forceRefresh:true})` would not result in an AuthError
=> fix(auth): returns refreshToken from login 

packages/adapter-nextjs/__tests__/utils/createCookieStorageAdapterFromNextServerContext.test.ts, packages/adapter-nextjs/src/utils/createCookieStorageAdapterFromNextServerContext.ts, packages/adapter-nextjs/tsconfig.json, packages/core/__tests__/storage/CookieStorage.test.ts
As of today, `signIn` is handled by the client side API, which uses js-cookie to operate the underlying cookie storage in a SSR use case (i.e. `Amplify.configure(config, {ssr: true})`).
According to [js-cookie document](https://github.com/js-cookie/js-cookie#encoding), it encodes cookie name.
In Amplify, we encode cookie name in the case of using `username` as a part of the cookie names, where the `username` can be an email address, for example, cookie name `test@email.com` will be encoded as `test%40email.com`.
When store the item into cookie store via js-cookie, the cookie name gets double encoded as `test%2540email.com`. 
In adapte-nextjs, we need to handle this ensure the sever side functionality can extra tokens from cookies. 
By submitting this pull request, I confirm that my …
=> fix(adapter-nextjs): align with js-cookie on the client handling double encoded cookie names

packages/auth/__tests__/providers/cognito/tokenProvider.test.ts, packages/auth/src/providers/cognito/tokenProvider/TokenStore.ts, packages/auth/src/providers/cognito/utils/refreshAuthTokens.ts
Currently the library create auth keys to store tokens and uses the `username` as identifier. E.g 
`CognitoIdentityServiceProvider.${userPoolClientId}.${username}.idToken`
This username is encoded when setting tokens and decoded when getting tokens. This works fine in `LocalStorage`. The issue happens in Cookies as `js-cookie`(the package used by the library) will encode the keys and if username is an `email` it will double encode the `@` symbol.
This removes the encoding logic and attaches the plain username in the keys.
**NOTE:**
This change when published to `console-preview` will log out any users that were authenticated with the encoded key format.
=> fix(auth): remove username en/decode logic 

packages/aws-amplify/package.json, packages/aws-amplify/src/storage/s3/utils.ts, packages/aws-amplify/storage/s3/utils/package.json, packages/storage/__tests__/providers/s3/apis/utilityApis/accessLevelAndIdentityAwarePrefixResolver.test.ts, packages/storage/package.json, packages/storage/s3/utils/package.json, packages/storage/src/providers/s3/apis/utilityApis/accessLevelAndIdentityAwarePrefixResolver.ts, packages/storage/src/providers/s3/utilityApis.ts, packages/storage/src/types/inputs.ts, packages/storage/src/utils/resolvePrefix.ts
Expose a util function from the `aws-amplify/storage/s3/utils` subpath. Developers can use this util function to determine the full path of an object in the S3 bucket.
* unit tests
* manual testing with a next.js app
=> feat(storage): expose the defaultPrefixResolver from storage/s3/utils subpath

.github/integ-config/integ-all.yml
Depends on https://github.com/aws-amplify/amplify-js-samples-staging/pull/637
V6 migration of the following datastore tests
- owner-custom-field-default
- owner-custom-claim-default
- public-auth-iam
- public-auth-default
- private-auth-iam
- private-auth-default
- dynamic-user-pool-groups-owner-based-default
- dynamic-user-pool-groups-default
Tested locally, app by app, then on a run for all against my repo fork: https://github.com/stocaaro/amplify-js/actions/runs/6512430947
Individual test success links:
- [owner-custom-field-default](https://github.com/stocaaro/amplify-js/actions/runs/6512430947/job/17690232305)
- [owner-custom-claim-default](https://github.com/stocaaro/amplify-js/actions/runs/6512430947/job/17690230890)
- [public-auth-iam](https://github.com/stocaaro/amplify-js/actions …
=> chore: v6 re-enable DataStore tests - batch 1

packages/datastore/__tests__/mutation.test.ts, packages/datastore/__tests__/sync.test.ts, packages/datastore/package.json, packages/datastore/src/sync/processors/errorMaps.ts, packages/datastore/src/sync/processors/sync.ts, packages/datastore/src/sync/utils.ts
The retry bahavior in datastore requires Axios-specific error messages for error messages: `Request failed with status code xxx`, hence determine which failure to retry. 
With this change, the status code are retrieved from the `response.$metadata.httpStatusCode` of the custom HTTP handlers.
This change unblockes te v2/private-auth-iam-v2 integration test.
Manual test, Unit test
=> fix(datastore): parse error status code without axios-specific error message

packages/api-graphql/__tests__/fixtures/modeled/schema.ts, packages/api-graphql/__tests__/generateClient.test.ts, packages/api-graphql/src/internals/generateModelsProperty.ts
Changes the return types on graphql client models to return `{data, errors, nextToken, extensions}`, so that these properties will be accessible to callers.
=> feat: change `client.models` return to include data, errors, nextToken

packages/notifications/src/inAppMessaging/providers/pinpoint/apis/initializeInAppMessaging.ts, packages/notifications/src/inAppMessaging/providers/pinpoint/utils/messageProcessingHelpers.ts, packages/notifications/src/inAppMessaging/providers/pinpoint/utils/resolveConfig.ts, packages/notifications/src/inAppMessaging/sessionTracker/SessionTracker.ts
Corrects the use of isBrowser that checks if the env is a browser or not. This fixes a bug that blocks from running on Next js apps where the default is server side component until a client component is rendered where the InApp APIs are intended to work. 
- amplify-ui repo's next app works as expected
- custom next app can use InApp APIs
=> fix(inapp): make the correct isBrowser check 

.github/integ-config/integ-all.yml
Unable the following tests:
- `integ_angular_auth_angular_authenticator`
- `integ_angular_auth_angular_custom_authenticator`
- `integ_vue_auth_legacy_vue_authenticator`
- `integ_vue_auth_vue_3_authenticator`
These tests are currently testing some UI Authenticator functionality and some basic auth flow, which is already tested by the `functional-auth` spec, which currently works for react only. However to enable this spec for angular/vue we need to create custom components for each platform. As previously discussed, this is something that the UI team might be testing on their end. However we can still test this flow at a later point so we can detect any amplify build issues before hand.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
=> chore: unable angular and vue auth integ tests

packages/core/src/Cache/StorageCacheCommon.ts, packages/core/src/I18n/I18n.ts, packages/core/src/index.ts, packages/core/src/singleton/types.ts
Removes I18n & Cache from global library configuration in favor of configuring the instances directly.
=> chore: Remove I18n & Cache from global configuration

packages/core/src/Reachability/Reachability.ts
Makes the `Reachability` utility node safe to allow it to be built on Next.js applications, even when not using SSR.
Previously this behavior was enforced by this check which was removed to avoid a dependency on `process`: https://github.com/aws-amplify/amplify-js/blob/main/packages/core/src/Util/Reachability.ts#L16
Tested `Reachability` in a Web application to make sure the observable was still firing by disconnecting/reconnecting my network. Associated DS integ test now passing.
=> fix: Make Reachability node safe

packages/react-native/src/moduleLoaders/loadGetRandomValues.ts
Fixed the wrong package name used in `loadGetRandomValues` error.
=> fix(react-native): wrong package name used in the load error info

.github/integ-config/integ-all.yml
Reviewing the most recent [integ test run](https://github.com/aws-amplify/amplify-js/actions/runs/6569155198):
- Rremoving interactions tests, which haven't been worked on yet
- Adding the IoT reconnect test, which I have confirmed is working
I expect this to remove some noise and so we can focus effort on the remaining failures to either remove them as not relevant or fix them if they are good quality checks.
=> chore: Disable interactions tests and enable iot reconnect test

packages/api-graphql/package.json, packages/api-graphql/src/Providers/AWSAppSyncRealTimeProvider/index.ts, yarn.lock
Removes `url` dep from `api-graphql` to resolve install warning related to `querystring` and use the appropriate polyfill for RN.
```
b0f1d8581327:v6-install-test jablanch$ yarn install
yarn install v1.22.19
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 5.77s.
```
```
b0f1d8581327:v6-install-test jablanch$ npm install aws-amplify@unstable
added 162 packages, and audited 163 packages in 19s
6 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
```
Local build & install test.
=> chore: Replace `url` dep with `amplifyUrl`

packages/api-graphql/__tests__/utils/expects.ts, packages/api-graphql/src/GraphQLAPI.ts, packages/api/__tests__/API.test.ts
Small change to add user agent action info to GraphQL. DataStore is already setting the correct UA values.
Verified in sample app that correct headers are being sent for AppSync requests.
=> feat: Add GraphQL user agent info.

packages/react-native/AmplifyRTNCore.podspec
…ult)
Dropped the required ios platform deployment target to 12.4 (as the default of react-native 0.70.0)
=> chore(react-native): drop required ios platform to 12.4 (rn 0.70 default)

packages/adapter-nextjs/__tests__/runWithAmplifyServerContext.test.ts, packages/adapter-nextjs/internals/package.json, packages/adapter-nextjs/package.json, packages/adapter-nextjs/src/internals/index.ts, packages/adapter-nextjs/src/runWithAmplifyServerContext.ts, packages/adapter-nextjs/src/withAmplify.ts, packages/adapter-nextjs/with-amplify/package.json, packages/aws-amplify/adapter-core/package.json, packages/aws-amplify/internals/adapter-core/package.json, packages/aws-amplify/package.json
Made the `adapter-core` a non-internals prefixed subpath
=> chore(aws-amplify): make adapter-core a non-internal subpath

packages/analytics/__tests__/providers/kinesis-firehose/utils/getEventBuffer.test.ts, packages/analytics/__tests__/providers/kinesis/utils/getEventBuffer.test.ts, packages/analytics/__tests__/providers/personalize/utils/getEventBuffer.test.ts, packages/analytics/src/providers/kinesis-firehose/utils/getEventBuffer.ts, packages/analytics/src/providers/kinesis/utils/getEventBuffer.ts, packages/analytics/src/providers/personalize/utils/getEventBuffer.ts
- cache event buffer without session info
- the async calls on `fetchAuthSession` would cause several event buffers being created
- flush events in the old buffers before releasing them
=> fix(analytics): cache event buffer without session info

packages/api-graphql/__tests__/fixtures/modeled/amplifyconfiguration.js, packages/api-graphql/__tests__/fixtures/modeled/schema.ts, packages/api-graphql/__tests__/generateClient.test.ts, packages/api-graphql/__tests__/v6-test.ts, packages/api-graphql/src/internals/APIClient.ts, packages/api-graphql/src/internals/generateModelsProperty.ts, packages/api-graphql/src/utils/findIndexByFields.ts, packages/api-graphql/src/utils/index.ts, packages/api-graphql/src/utils/resolvePKFields.ts
1. Ability to `observeQuery()` on a model.
2. Fixes pagination (`nextToken` handling) in `list()` on a model.
For example, the following will call `setNotes` with the full list of notes we have access to in realtime as notes exposed in the query are added, updated, or removed via the API from any client.
```typescript
const sub = client.models.Note.observeQuery().subscribe({
next({ items }) {
setNotes(items);
},
});
```
1. new unit tests
3. sample app testing
=> feat(api-graphql):  observeQuery

packages/api-graphql/src/internals/InternalGraphQLAPI.ts
Re-introduce authMode passthrough to subscription
Linking to a test and verifying first that the problem existed without this fix and then is fixed by applying this change.
Manual testing for API subscriptions authmodes have been disabled. I will re-enable and update them in a followup PR.
=> fix(api-graphql): Subscription authtype overriding

.vscode/launch.json, packages/api-graphql/__tests__/GraphQLAPI.test.ts
feat(data): update and re-enable GraphQL API unit tests
=> feat(data): update and re-enable GraphQL API unit tests

package.json, packages/adapter-nextjs/package.json, packages/pubsub/package.json
This change prepares the repo for the v6 major version release. It uses the `from-package` Lerna feature for the `publish:release` script to ensure that the manually set versions are used for the initial release. After v6 goes out, we will revert this back to using conventional commits. Also bumped the version of `adapter-nextjs` to v1.0.0 for the release.
Tested `publish:release` in Verdaccio.
=> chore: Prepare for major version release

packages/aws-amplify/__tests__/initSingleton.test.ts, packages/aws-amplify/src/adapterCore/storageFactories/createKeyValueStorageFromCookieStorageAdapter.ts, packages/aws-amplify/src/initSingleton.ts
Context:
Currently we don't provide an interface to configure the sameSite values when Amplify.configure(config, { ssr: true })  on both client and server sides
We are planning to provide an interface to do so post GA.
Considering to support most of use cases of cookies, we decided to change this default value. This is aligned with how browsers handle cookies with sameSite unset.
=> chore(aws-amplify): change deafult sameSite value to 'lax'

packages/adapter-nextjs/__tests__/utils/getAmplifyConfig.test.ts, packages/adapter-nextjs/src/utils/getAmplifyConfig.ts
Added fallback for when `getConfig()` of Next. JS returns an `undefined` value to ensure the `getAmplifyConfig` util function always throws the `AmplifyServerContextError` instead of the JS runtime error, "reading undefined"
=> fix(adapter-nextjs): ensure to use meaningful exception on config resolution

packages/core/src/providers/kinesis-firehose/types/kinesis-firehose.ts, packages/core/src/providers/kinesis/types/kinesis.ts, packages/core/src/providers/personalize/types/personalize.ts, packages/core/src/providers/pinpoint/types/pinpoint.ts, packages/core/src/singleton/Analytics/types.ts
- disable `AnalyticsConfig` type to accept empty config `{}`
- tested at local
=> fix(core): disable type to accept empty config for analytics

packages/core/package.json, yarn.lock
Moves `@types/uuid` to dependencies from devDependencies to avoid skipLibCheck errors from `amplifyUuid`.
```
node_modules/@aws-amplify/core/lib-esm/utils/amplifyUuid/index.d.ts:2:75 - error TS7016: Could not find a declaration file for module 'uuid'. '/Users/cpollman/Amplify/v6-skip-lib-check/node_modules/uuid/dist/esm-browser/index.js' implicitly has an 'any' type.
Try `npm i --save-dev @types/uuid` if it exists or add a new declaration (.d.ts) file containing `declare module 'uuid';`
2 declare const amplifyUuid: (<T extends ArrayLike<number>>(options: import("uuid").V4Options | null | undefined, buffer: T, offset?: number | undefined) => T) & ((options?: import("uuid").V4Options | undefined) => string);
```
Verified `skipLibCheck: false` passes in a sample app using …
=> chore: Move `@types/uuid` to dependencies

packages/notifications/src/pushNotifications/types/index.ts, packages/notifications/src/pushNotifications/types/inputs.ts, packages/notifications/src/pushNotifications/types/module.ts, packages/notifications/src/pushNotifications/types/pushNotifications.ts, packages/react-native/src/index.ts, packages/rtn-push-notification/src/types/module.ts
This PR duplicates the Push Notification types from the native module as it is unfortunately not feasible to rely on an optional package as a source of truth since typescript will attempt to fully analyze all types whether used or not when `skipLibCheck` is disabled.
* Published to Verdaccio and verified that app previously failing `tsc` is now passing
=> fix(notifications): Duplicate types from optional packages

packages/core/__tests__/parseAWSExports.test.ts, packages/core/src/parseAWSExports.ts
Checks for OAuth URLs before splitting, defaulting to empty arrays if they're not present in the CLI generated config.
=> fix: Check for OAuth URLs before splitting

packages/predictions/src/types/Predictions.ts
I noticed a gap in our typings: a return type had a generic object type that was difficult to work with. I added definition to what object we are expecting from IdentifyEntity.metadata
Tested in sample app with celebrity and collection. Unit tests pass.
=> feat(predictions): specify identifyEntity metadata type

packages/auth/src/providers/cognito/apis/signInWithRedirect.ts, packages/core/src/singleton/Auth/index.ts
This change fixes a bug where promises weren't being resolved when in-flight OAuth flows are cancelled, leading to `getCurrentUser` to hang indefinitely.
Tested in reproduction sample apps (Angular & Next.js).
=> fix: Resolving in-flight OAuth promises when sign-in flow cancelled

packages/adapter-nextjs/src/api/generateServerClient.ts, packages/adapter-nextjs/src/createServerRunner.ts
* removed unused import
* updated inline docs for the public apis
=> chore(adapter-nextjs): update public APIs inline docs

packages/adapter-nextjs/package.json, packages/adapter-nextjs/src/api/generateServerClient.ts, packages/api/src/internals/generateServerClient.ts, packages/api/src/internals/index.ts, packages/api/src/server.ts
* Fixed missing `api` in `adapter-nextjs` packages.json `files`
* Hide `generateClient` from `aws-amplify/api/server`
=> chore(api): hide generateClient from api/server subpath

packages/adapter-nextjs/__tests__/createServerRunner.test.ts, packages/adapter-nextjs/src/createServerRunner.ts
* Removed the blocking exception as no harm to call this function more than once
=> fix(adapter-nextjs): remove the constraint of calling createServerRunner only once

packages/api-graphql/__tests__/generateClient.test.ts, packages/api-graphql/__tests__/server/generateClient.test.ts, packages/api-graphql/src/internals/APIClient.ts
E.g.
```typescript
({ data: listed, nextToken } = await client.models.Note.list({
nextToken,
limit: 5,
}));
```
Or this:
```typescript
({ data: listed, nextToken } = await todo.notes({
nextToken,
limit: 5,
}));
```
1. Added tests.
2. Manually in app
=> feat(api-graphql): limit, nextToken on list and lazy loaded lists

packages/core/__tests__/clients/middleware/signing/utils/getUpdatedSystemClockOffset.test.ts
Add extra unit test to make validate the error mentioned in https://github.com/aws-amplify/amplify-js/issues/12450#issuecomment-1787945008 is handled in v6
Tandem with https://github.com/aws-amplify/amplify-js/pull/12488
=> test(core): unit validating clockskew offset is updated when client clock back and forth

packages/auth/src/index.ts, packages/auth/src/providers/cognito/apis/internal/getCurrentUser.ts, packages/auth/src/providers/cognito/index.ts, packages/auth/src/providers/cognito/types/index.ts, packages/auth/src/providers/cognito/types/models.ts, packages/auth/src/providers/cognito/types/outputs.ts, packages/auth/src/providers/cognito/utils/signInHelpers.ts, packages/auth/src/types/index.ts, packages/auth/src/types/models.ts
- rename internal auth category type `AuthUser` to `AWSAuthUser`
- rename public auth provider type `CognitoAuthUser` to `AuthUser`
- expose `AuthUser` from the following path
```
import { AuthUser } from "aws-amplify/auth/cognito";
import { AuthUser } from "aws-amplify/auth";
```
validated the `AuthUser` is exposed in the above paths
=> fix(auth): rename type CognitoAuthUser to AuthUser

packages/core/src/Hub/index.ts, packages/core/src/constants.ts, packages/core/src/libraryUtils.ts
* Removed usage of `Symbol.for` as the symbol that is supposed to use internally can be overridden
* Removed unused the symbol constant
=> fix(core): remove used symbol and remove usage of Symbol.for

packages/api-rest/__tests__/RestAPI-test.ts, packages/api-rest/package.json, packages/api-rest/src/RestClient.ts
This change makes sure when updating the clock skew offset, always compare to raw client clock instead the one adjusted by clock skew offset.
For more details on why this happens: https://github.com/aws-amplify/amplify-js/issues/12450#issuecomment-1787945008
Unit test
=> fix(api-rest): infinite retry when clock skew go back and forth

packages/auth/__tests__/utils/openAuthSession.native.test.ts, packages/auth/src/utils/openAuthSession.native.ts, packages/react-native/src/index.ts, packages/react-native/src/moduleLoaders/index.ts, packages/react-native/src/moduleLoaders/loadAmplifyWebBrowser.ts, packages/rtn-web-browser/src/apis/index.ts, packages/rtn-web-browser/src/constants.ts, packages/rtn-web-browser/src/index.ts, packages/rtn-web-browser/src/nativeModule.ts, packages/rtn-web-browser/src/types/index.ts, packages/rtn-web-browser/src/types/native.ts
This PR refactors the Amplify Web Browser native module loading to use the module loading pattern introduced in `@aws-amplify/react-native`. This was necessary given that Expo applications by default do not lazy load modules and was thusly throwing an error even when `signInWithRedirect` was not used by the application.
* `yarn test`
* Tested against EAS built Android and iOS apps - importing the native module should now only be required if executing `signInWithRedirect`
=> fix: add module loader for web browser native module

packages/api-graphql/__tests__/generateClient.test.ts, packages/api-graphql/src/internals/generateModelsProperty.ts, packages/api/__tests__/API.test.ts, packages/aws-amplify/package.json
Gracefully handle the error my throwing an informative handling message:
"The API configuration is missing. This is likely due to Amplify.configure() not being called prior to generateClient()."
Validated by adding unit testing and testing in a sample app
=> fix: Add clear error when API GraphQl isn't configured

packages/auth/__tests__/providers/cognito/autoSignIn.test.ts, packages/auth/__tests__/providers/cognito/confirmSignInHappyCases.test.ts, packages/auth/__tests__/providers/cognito/fetchAuthSession.test.ts, packages/auth/__tests__/providers/cognito/signInErrorCases.test.ts, packages/auth/__tests__/providers/cognito/signInStateManagement.test.ts, packages/auth/__tests__/providers/cognito/signInWithCustomAuth.test.ts, packages/auth/__tests__/providers/cognito/signInWithCustomSRPAuth.test.ts, packages/auth/__tests__/providers/cognito/signInWithSRP.test.ts, packages/auth/__tests__/providers/cognito/signInWithUserPassword.test.ts, packages/auth/src/providers/cognito/apis/signInWithRedirect.ts, packages/auth/src/providers/cognito/index.ts, packages/auth/src/providers/cognito/tokenProvider/index.ts, packages/aws-amplify/__tests__/exports.test.ts, packages/aws-amplify/__tests__/initSingleton.test.ts, packages/aws-amplify/src/initSingleton.ts
Use camel-case naming for the `cognitoUserPoolsTokenProvider` instance.
=> chore(auth|aws-amplify): fix instance naming (use camel-case)

packages/auth/__tests__/providers/cognito/tokenProvider/tokenOrchestrator.test.ts, packages/auth/src/providers/cognito/tokenProvider/TokenOrchestrator.ts
* await for the `storeTokens` operation to complete the `refreshTokens` operation to avoid unexpected race condition between returning result of `fetchAuthSession` (when token expired) and store the tokens into token store.
This caused unexpected warning for attempting set `SetCookie` header after operation has completed
* added relevant unit test
=> fix(auth): refreshToken unawaited async operation caused race condition

.github/workflows/callable-npm-publish-release.yml, package.json
Flips our normal releases back to use `conventional-commits` and makes some improvements to the `required-release` flow to make it a little less fragile.
Tested `yarn publish:release` in Verdaccio with some `fix` & `chore` commits.
```
﻿Successfully published:
- @aws-amplify/adapter-nextjs@1.0.2
- @aws-amplify/analytics@7.0.2
- @aws-amplify/api@6.0.2
- @aws-amplify/api-graphql@4.0.2
- @aws-amplify/api-rest@4.0.2
- @aws-amplify/auth@6.0.2
- @aws-amplify/core@6.0.2
- @aws-amplify/datastore@5.0.2
- @aws-amplify/datastore-storage-adapter@2.1.2
- @aws-amplify/geo@3.0.2
- @aws-amplify/interactions@6.0.2
- @aws-amplify/notifications@2.0.2
- @aws-amplify/predictions@6.0.2
- @aws-amplify/pubsub@6.0.2
- @aws-amplify/react-native@1.0.2
- @aws-amplify/rtn-push-notification@1.2.2
- …
```
=> chore: Release improvements

packages/adapter-nextjs/src/api/index.ts, packages/api-graphql/__tests__/generateClient.test.ts, packages/api-graphql/package.json, packages/api-graphql/src/internals/generateModelsProperty.ts, packages/api-graphql/src/internals/server/generateModelsProperty.ts, packages/api-graphql/src/utils/resolveConfig.ts, packages/api/src/index.ts, yarn.lock
* export generateClient return types
* don't throw error if genClient is called before Amplify.configure. Silent return instead
* Bump data-schema dep versions
=> fix: export generateClient return types; don't throw error in genClient

packages/adapter-nextjs/src/api/index.ts, packages/api/src/index.ts
Resolves "TS2589: Type instantiation is excessively deep and possibly infinite." error when `Client` type is used without a type arg, e.g.
```ts
let client: Client;
```
=> fix: Client type explicit default type arg

package.json, packages/api-graphql/__tests__/generateClient.test.ts, packages/api-graphql/package.json, packages/api-graphql/src/internals/InternalGraphQLAPI.ts, packages/api-graphql/src/internals/v6.ts, yarn.lock
We don't utilize the `defaultAuthMode` inside of `_graphql`, which prevents us from signing the request correctly when IAM is the default auth mode
This PR defaults `authMode` to `defaultAuthMode` unless an explicit `authMode` was passed in at the client or call site.
* ~Also: updates `pretty-quick` dep. Necessary after Prettier was upgraded to unblock pre-commit husky hook.~ Nvm. pretty-quick doesn't seem to support prettier@3 at all. We'll need to find modify the pre-commit hook with a shell command to run prettier or use a newer pretty-quick equivalent tool
=> graphql: utilize default auth

packages/datastore/__tests__/commonAdapterTests.ts
fix(datastore): Make ds tests run on M1 by using uuid for randomness
By running the unit tests on both intel and M1 macbooks. This PR will prompt an ubuntu run to ensure we're covered.
=> fix(datastore): Make ds tests run on M1 by using uuid for randomness

packages/aws-amplify/__tests__/adapterCore/runWithAmplifyServerContext.test.ts, packages/aws-amplify/src/adapterCore/runWithAmplifyServerContext.ts
Fix `destroyAmplifyServerContext` may no be called when the `operation` executed by `runWithAmplifyServerContext` throws.
=> fix(aws-amplify): destroyAmplifyServerContext may not be called

packages/analytics/src/providers/pinpoint/types/inputs.ts, packages/analytics/src/types/inputs.ts, packages/auth/src/providers/cognito/tokenProvider/CognitoUserPoolsTokenProvider.ts, packages/auth/src/providers/cognito/tokenProvider/cacheTokens.ts, packages/auth/src/providers/cognito/tokenProvider/index.ts, packages/auth/src/providers/cognito/tokenProvider/tokenProvider.ts, packages/notifications/src/inAppMessaging/providers/pinpoint/types/inputs.ts, packages/notifications/src/inAppMessaging/types/inputs.ts
This PR updates import paths which reference index files within the current directory via the relative `'.'` path to avoid doing so. Babel module resolvers configured with `root: ['.']` are unable to resolve this path correctly.
https://github.com/aws-amplify/amplify-js/issues/12622
Tested locally with an React Native app with the above configuration to verify that changes resolved issue.
=> fix: refactor to avoid importing from current index

packages/core/src/clients/middleware/retry/middleware.ts
Updates timeoutId type to account for differences in Node vs browser environment.
Builds successfully locally without type errors.
=> fix: determine timeoutid type based on return type of setTimeout

.github/canary-config/canary-all.yml, .github/workflows/callable-canary-sampleapp-tests.yml
- Removing `integ_vue_auth_legacy_vue_authenticator`  as it needs 0'ver-Engineering.
[integ_vue_auth_legacy_vue_authenticator workflow 🏃‍♀️](https://github.com/aws-amplify/amplify-js/actions/runs/7007562018/job/19062107148#step:9:623)
=> Fix: remove `integ_vue_auth_legacy_vue_authenticator` failing canary test

packages/core/src/adapterCore/serverContext/types/cookieStorage.ts
Made SetCookieOptions fields optional
=> fix(core): adapter-core: make SetCookieOptions fields optional

packages/aws-amplify/src/initSingleton.ts
=> chore(aws-amplify): add inline docs for Amplify configure and getConfig methods

packages/auth/__tests__/providers/cognito/signInWithRedirect.test.ts, packages/auth/src/providers/cognito/apis/signInWithRedirect.ts, packages/aws-amplify/package.json, packages/core/src/Hub/types/AuthTypes.ts
In case of an oauth exception: 
- Web: Avoids Uncaught exception and dispatches a hub event
- RN: throws an error and dispatches a hub event
created a sample app in web and validated that the  library dispatches a `signInWithRedirect_failure` under the following circumstances: 
- `responseType` is `code` and there is an error returned from hostedUI 
- `responseType` is `code` and the oauth state is not valid
- `responseType` is `token` and there is an error returned from hostedUI 
- `responseType` is `token` and the oauth state is not valid
PR was validated in RN with the same testing criteria as above.
=> fix(auth): dispatch signInWithRedirect error

packages/api-graphql/__tests__/APIClient.test.ts, packages/api-graphql/__tests__/__snapshots__/generateClient.test.ts.snap, packages/api-graphql/__tests__/fixtures/modeled/amplifyconfiguration.js, packages/api-graphql/__tests__/fixtures/modeled/schema.ts, packages/api-graphql/src/internals/APIClient.ts
Enum fields were missing from default selection sets due to field filtering which was intended to only filter out related model fields.
Also adds the missing `tags` field to the model intro schema test fixture.
1. Red/Green testing.
2. Manually confirmed in a sample app
=> fix(api-graphql): fix missing model enum in default selection sets

packages/adapter-nextjs/src/api/generateServerClient.ts, packages/api-graphql/__tests__/internals/server/generateClient.test.ts, packages/api-graphql/__tests__/server/generateClient.test.ts, packages/api-graphql/package.json, packages/api-graphql/server/package.json, packages/api-graphql/src/internals/server/generateClientWithAmplifyInstance.ts, packages/api-graphql/src/server/generateClient.ts, packages/api-graphql/src/server/index.ts, packages/api-graphql/src/types/index.ts, packages/api/src/internals/index.ts, packages/api/src/server.ts
Exposed the `generateClient` from the subpath `aws-amplify/api/server` to support use cases with the generic SSR framework adapter `runWithAmplifyServerContext` exported from the subpath `aws-amplify/adapter-core`
This PR includes all relevant changes.
Supporting: https://github.com/aws-amplify/docs/pull/6591
1. unit tests
2. local tests with:
* with a Next.js sample app to test the functionalities provided by `adapter-nextjs` originally
* with a Nuxt sample app to test the newly expose `generateClient`
=> feat(api): expose generateClient from /server subpath

.github/actions/node-and-build/action.yml, .github/workflows/callable-canary-e2e-tests.yml, jest.config.js, packages/aws-amplify/package.json, packages/core/package.json
Requires: https://github.com/aws-amplify/amplify-js-samples-staging/pull/754
CI Checks sample: https://github.com/aws-amplify/amplify-js/actions/runs/7174539999
=> chore(repo): upgrade action node version to 18

.github/integ-config/integ-all.yml
Adds the e2e from [this samples PR](https://github.com/aws-amplify/amplify-js-samples-staging/pull/759) to the ci/cd pipeline
* Manually tested sample app in Chrome and FF
* Ran cypress against dev and prod build in Chrome
* Ran into issues with Cypress on FF. Seems to be related to [this issue](https://github.com/cypress-io/cypress/issues/18690). I noticed that our other Next.js e2es only run on Chrome as well, so I'm assuming it's a known limitation. The sample works as expected when I manually exercise it in FF.
For reference, here are the warnings I see in the console when Cypress calls `Auth.signIn` in FF:
This does not occur when manually running the sample in FF. It logs in and sets the cookies successfully. 
By submitting this pull request, I confirm that my contribution is made …
=> ci: add next.js data client e2e

packages/datastore/__tests__/conflictResolutionBehavior.test.ts, packages/datastore/__tests__/connectivityHandling.test.ts, packages/datastore/__tests__/helpers/UpdateSequenceHarness.ts, packages/datastore/__tests__/helpers/datastoreFactory.ts, packages/datastore/__tests__/helpers/fakes/graphqlService.ts, packages/datastore/__tests__/helpers/util.ts
Outcome: 
- ~1300 lines -> ~700 lines aimed at maintaining readability. All assertions are the same as they where before this refactor.
- All test assertions are maintained with the same expected result for each test
We want to add OCC tests in a subsequent change. Rather than duplicating these tests as they where, I have refactored them, extracting out shared logic that isn't core to the testing story into a test harness aimed to enable/clarify these tests specifically.
The test suite continues to run to success
1. https://github.com/aws-amplify/amplify-js/pull/12728
2. :seedling:  **refactor(datastore): Refactor conflict resolution tests towards readability**
3. https://github.com/stocaaro/amplify-js/pull/85
4. https://github.com/stocaaro/amplify-js/pull/86
5. …
=> refactor(datastore): Refactor conflict resolution tests optimize for concise/readable

packages/auth/__tests__/providers/cognito/signInWithRedirect.test.ts, packages/auth/__tests__/providers/cognito/utils/oauth/attemptCompleteOAuthFlow.test.ts, packages/auth/src/providers/cognito/utils/oauth/attemptCompleteOAuthFlow.ts, packages/auth/src/providers/cognito/utils/oauth/enableOAuthListener.ts
Moved the origin call of `cognitoUserPoolsTokenProvider.setWaitForInflightOAuth()` in the `enableOAuthListener` side effect into the `attemptCompleteOAuthFlow` function.
The latter ensures the `oAuthStore` gets configured before using. 
=> fix(auth): oAuthStore is used before a valid OAuth config is confirmed

.github/integ-config/integ-all.yml
Corrects the sample path the script searches when running the GH action for the in-app e2e test.
Running the below command on the staging repo passes all tests validating the correct path and eventual success of it on GH action
`node scripts/test.js react in-app-messaging in-app-messaging-app in-app-messaging chrome dev `
=> fix(integ-test): correct integ sample path

.github/dependency-review/dependecy-review-config.yml
GH actions workflow `aws-amplify-dependency-check.yml` checks for license of newly added packages on the PR. 
Package [tslib](https://www.npmjs.com/package/tslib) licensed under `0BSD` [is flagged](https://github.com/aws-amplify/amplify-js/actions/runs/7342179815/attempts/1#summary-19991088882) since this isn't present in the list of allowed licenses. Update to allow the same
reference: [Open Source Licenses for Distribution wiki](https://w.amazon.com/bin/view/Open_Source/Distributions/Process/License_Instructions_for_Distribution/)
=> feat(ci): allow 0BSD license

packages/api/__tests__/API.test.ts, packages/api/src/index.ts, packages/aws-amplify/__tests__/exports.test.ts
rather than as a type
It looks like a simple oversight, that CONNECTION_STATE_CHANGE was included in an `export type` statement rather than in a plain `export` statement.
[12756](https://github.com/aws-amplify/amplify-js/issues/12756)
Writing a failing unit test, writing the fix, seeing the unit test pass.
=> fix(api): issue 12756 by exporting CONNECTION_STATE_CHANGE as a value

packages/core/__tests__/I18n.test.ts, packages/core/src/I18n/I18n.ts
Fixes a regression that was introduced with some v6 refactoring that prevented the default browser language from being set in the i18n utility.
https://github.com/aws-amplify/amplify-js/issues/12767
Tested in sample application.
=> fix: i18n default language resolution

packages/auth/__tests__/auth-unit-test.ts, packages/auth/src/Auth.ts
changes the overridden `window.history.state` by the current session's browser `state`
- Smoked test changes in a sample app
=> fix(auth): replace window history with current browser session's state

packages/datastore/__tests__/conflictResolutionBehavior.test.ts, packages/datastore/src/sync/outbox.ts, packages/datastore/src/util.ts
Outcome:
- To allow multiple partial updates, outbox checks compare all updated fields for deep equality with the returned object, but ignore extra returned fields when gating outbox `_version` maintenance.
- As a result, our rapid update use-cases will not drop updates
- https://github.com/aws-amplify/amplify-js/issues/12729
- https://github.com/aws-amplify/amplify-js/issues/9979
Validated by updating tests and testing against sample apps manaully for both Automerge and OCC usecases
1. https://github.com/aws-amplify/amplify-js/pull/12728
2. https://github.com/aws-amplify/amplify-js/pull/12732
3. https://github.com/aws-amplify/amplify-js/pull/12740
4. https://github.com/aws-amplify/amplify-js/pull/12795
6. :seedling:  **fix(datastore): Update outbox comparison logic to fix update …
=> fix(datastore): Update outbox comparison logic to fix update versioning problems

.github/workflows/callable-npm-publish-release.yml, packages/auth/__tests__/providers/cognito/utils/oauth/attemptCompleteOAuthFlow.test.ts, packages/auth/src/providers/cognito/utils/oauth/attemptCompleteOAuthFlow.ts
Bug: `cognitoUserPoolsTokenProvider.setWaitForInflightOAuth` sets a function that creates and returns a new promise every time.
Correction: The function sets by `cognitoUserPoolsTokenProvider.setWaitForInflightOAuth` should return the same promise.
https://github.com/aws-amplify/amplify-js/issues/12814
* Unit tests (updated the unit tests to verify the correction)
* Next.js sample app - redirect to provider hosted UI, closing the tab, reopening the web app, `fetchAuthSession` should resolve.
=> release(required): fix fetchAuthSession may hang on OAuth cancel

packages/core/__tests__/utils/queuedStorage/queuedStorage.test.ts, packages/core/src/utils/queuedStorage/constants.ts, packages/core/src/utils/queuedStorage/createQueuedStorage.native.ts, packages/core/src/utils/queuedStorage/createQueuedStorage.ts, packages/core/src/utils/queuedStorage/getAddItemBytesSize.ts, packages/core/src/utils/queuedStorage/index.ts, packages/core/src/utils/queuedStorage/types.ts
Add implementation of a queued storage for the upcoming logger. Backed by the IndexedDB on Web.
=> feat(core): queued storage (Web) for logger

packages/core/__tests__/utils/queuedStorage/queuedStorage.native.test.ts, packages/core/src/utils/queuedStorage/createQueuedStorage.native.ts, packages/core/src/utils/queuedStorage/createQueuedStorage.ts, packages/core/src/utils/queuedStorage/types.ts
Implementation of the queued storage for react-native.
Depends on https://github.com/aws-amplify/amplify-js/pull/12791
NOTE: Please do NOT click the update branch button.
=> feat(core): queued storage (react-native) for logger

.github/workflows/callable-npm-publish-release.yml
This reverts commit c8c3a9f50482795af986efd9bd54fc7f88e22de6.
=> Revert "chore(repo): disable force push release to main for 6.0.11"

.github/workflows/callable-get-package-list.yml, .github/workflows/callable-unit-tests.yml
Enable the codecov flow again.
Temporarily disabled the the cache check on the generate `package-list.json` file during GH Action run, to let the Action run successfully with this PR. A separate PR is required to turn the cache check back on after merging this PR.
* Tested GH Action with a feature branch with codecov enabled: https://github.com/aws-amplify/amplify-js/pull/12874#issuecomment-1904774516
=> chore: enable codecov

packages/analytics/src/providers/kinesis-firehose/apis/record.ts, packages/analytics/src/providers/kinesis/apis/record.ts, packages/analytics/src/providers/personalize/apis/record.ts, packages/analytics/src/providers/pinpoint/apis/record.ts, packages/analytics/tslint.json, packages/auth/src/providers/cognito/tokenProvider/tokenProvider.ts, packages/core/src/singleton/Auth/index.ts
Add in-line documentation for some public apis. 
=> docs(auth,analytics): adding in-line docs for public apis

.github/actions/setup-samples-staging/action.yml, .github/workflows/push-preid-release.yml
This PR fixes an issue where default branch selection sometimes fails in situations where a `foo/branch` branch also exists in the sample staging repo. This is frequently encountered, for example, when running releases from the `release` branch which conflicts with `next/release`.
Tested various scenarios in CI:
- No matching `$BRANCH` (default to `main`): https://github.com/aws-amplify/amplify-js/actions/runs/7673370302/job/20915856173
- Matching `$BRANCH` (use that branch): https://github.com/aws-amplify/amplify-js/actions/runs/7673370302/job/20915935775
- No matching `$BRANCH` but `next/$BRANCH` exists (default to `main`): https://github.com/aws-amplify/amplify-js/actions/runs/7673370302/job/20916014564 <- The common friction point during releases
- Both `$BRANCH` & `next/$BRANCH` …
=> fix: Default branch resolution when running E2E tests

packages/core/src/parseAWSExports.ts
Both CLI & Gen2 emit Lambda auth config for GraphQL as `AWS_LAMBDA`, but we were looking for `LAMBDA` when parsing the config object. As a result the library was not respecting the default auth mode when it was configured as Lambda.
=> fix: Lambda auth config value

packages/core/__tests__/singleton/Singleton.test.ts, packages/core/src/singleton/Amplify.ts
=> fix(core): Amplify.configure dispatches Hub event with unparsed config object

packages/core/__tests__/parseAWSExports.test.ts, packages/core/src/parseAWSExports.ts
When parsing the aws exports file, Push Notification config will now be appended to the existing config rather than replacing it. 
https://github.com/aws-amplify/amplify-js/issues/12913
- Linked the library and a sample app locally
- Added InApp and Push to the sample app
- Observe no error
- [] Relevant documentation is changed or added (and PR referenced)
=> fix(core): not appending notification configs properly

rollup/common.mjs
Disabled sourceMap option in the tsconfig for the rollup typescript plugin, and let rollup to handle it. (this is the original setup, but got altered in this commit: https://github.com/aws-amplify/amplify-js/commit/8b3b20461289873f53f6c77bb231d2dea3a39743#diff-6db54c94dcda26ffae248a497178e6aa322cce7d7619738c5675bd382a5752cf)
Build locally and tested built artifacts with the smoke-testing app, warnings regarding sourcemap are gone.
=> fix(repo): rollup generated sourcemap has wrong src path

packages/api-graphql/__tests__/fixtures/schema-models/with-custom-primary-key/models.ts, packages/api-graphql/__tests__/internals/APIClient.test.ts, packages/api-graphql/src/internals/APIClient.ts
Append `!` to the generated arguments in the GraphQL document for a GET operation of a model that has custom primary key defined.
* Unit testing
* Manual integration test in a sample app
=> fix(api-graphql): wrong arguments for GET operation of a CPK model

.github/integ-config/integ-all.yml
These tests have been isolated due to past flakiness. I have run them many times and observe sufficient stability that I recommend we remove their special treatment.
Process: [Link](https://github.com/stocaaro/amplify-js/actions/runs/7746613180)
- Setup e2e execution on my for that runs this subset of the suite 6x in parallel
- Reduce these tests to 1 retry (current config default is for 3 retries)
- Rerun this suite with this configuration 5 times
Observation: Across this test pattern, one test failed twice in a row such that only 1 out of the 5 tests runs was a failure.
The [test that failed](https://github.com/stocaaro/amplify-js/actions/runs/7746613180/job/21126252595) 2 consecutive runs to cause the failure (`integ_datastore_auth_v2-owner-and-group-different-models-default`) runs on …
=> fix: Remove special e2e treatment for validated tests

packages/api-graphql/src/internals/APIClient.ts
- caused by the incomplete GraphQL documents caching
Remove the incomplete cache implementation. This particular caching is not optimizing much.
=> fix(api-graphql): same results returned for queries on the same model with different selection sets

.github/integ-config/integ-all.yml, package.json, packages/adapter-nextjs/package.json, packages/analytics/package.json, packages/api-graphql/__tests__/fixtures/schema-models/with-custom-primary-key/models.ts, packages/api-graphql/__tests__/internals/APIClient.test.ts, packages/api-graphql/package.json, packages/api-graphql/src/internals/APIClient.ts, packages/api-rest/package.json, packages/api/package.json, packages/auth/package.json, packages/aws-amplify/package.json, packages/core/package.json, packages/datastore-storage-adapter/package.json, packages/datastore/__tests__/outbox.test.ts, packages/datastore/package.json, packages/datastore/src/sync/outbox.ts, packages/geo/package.json, packages/interactions/package.json, packages/notifications/package.json, packages/notifications/src/inAppMessaging/errors/validation.ts, packages/predictions/package.json, packages/pubsub/package.json, packages/react-native/package.json, packages/rtn-push-notification/package.json, packages/rtn-web-browser/package.json, packages/storage/package.json, rollup/common.mjs, yarn.lock
=> release: Amplify JS release 2024-02-06

.github/actions/node-and-build/action.yml, .github/actions/setup-samples-staging/action.yml, .github/workflows/aws-amplify-dependency-check.yml, .github/workflows/callable-bundle-size-tests.yml, .github/workflows/callable-canary-e2e-runner.yml, .github/workflows/callable-canary-e2e-tests.yml, .github/workflows/callable-canary-sampleapp-tests.yml, .github/workflows/callable-e2e-test-detox.yml, .github/workflows/callable-e2e-test-headless.yml, .github/workflows/callable-e2e-test.yml, .github/workflows/callable-e2e-tests.yml, .github/workflows/callable-get-package-list.yml, .github/workflows/callable-npm-publish-lts-release.yml, .github/workflows/callable-npm-publish-preid.yml, .github/workflows/callable-npm-publish-release.yml, .github/workflows/callable-prebuild-amplify-js.yml, .github/workflows/callable-prebuild-samples-staging.yml, .github/workflows/callable-test-github-actions.yml, .github/workflows/callable-test-license.yml, .github/workflows/callable-test-tsc-compliance.yml, .github/workflows/callable-unit-tests.yml, .github/workflows/codeql.yml, .github/workflows/pr.yml, .github/workflows/snyk-security.yml
Resolves warning such as
NOTE: the GH action used for codecov integration `codecov/codecov-action` will still cause this warning. Their fix should come any time soon.
=> chore(repo): update GH actions (upgrade to node20 based actions)

packages/api-graphql/__tests__/internals/generateClient.test.ts, packages/api-graphql/__tests__/internals/utils/generateEnumsProperty.test.ts, packages/api-graphql/package.json, packages/api-graphql/src/internals/generateClient.ts, packages/api-graphql/src/internals/utils/generateEnumsProperty.ts, packages/api-graphql/src/internals/utils/generateModelsProperty.ts, packages/api-graphql/src/internals/utils/isApiGraphQLProviderConfig.ts, packages/api-graphql/src/internals/utils/isConfigureEventWithResourceConfig.ts, packages/api-graphql/src/types/index.ts, packages/api-graphql/tsconfig.json, packages/aws-amplify/package.json, packages/core/src/index.ts, packages/core/src/libraryUtils.ts, yarn.lock
Added `.enums` property generation for the `client` returned by `generateClient()`.
* Reorganized/refactored the source code
* Unit testing
* Manual testing in a Next.js sample app
=> feat(api-graphql): add `.enums` property to the GQL client

packages/api-graphql/__tests__/GraphQLAPI.test.ts, packages/api-graphql/__tests__/internals/__snapshots__/generateClient.test.ts.snap, packages/api-graphql/__tests__/internals/generateClient.test.ts, packages/api-graphql/__tests__/internals/server/generateClientWithAmplifyInstance.test.ts, packages/api-graphql/__tests__/utils/expects.ts, packages/api-graphql/src/internals/InternalGraphQLAPI.ts, packages/api-rest/src/internals/index.ts, packages/datastore/__tests__/mutation.test.ts
1. Changed the api-rest exported internal `post` function for api-graphql to make it server side usable (can inject the instance of `AmplifyClassV6` from the server context)
2. Changed the api-graphql server `graphql` method `wrapper` implementation to ensure it's an `await` -able function so Amplify server context can ensure destroying context only after this function has completed
3. Updated test suites
https://github.com/aws-amplify/amplify-js/issues/12984
https://github.com/aws-amplify/amplify-js/issues/12931
https://github.com/aws-amplify/amplify-js/issues/12867
=> fix(api-graphql): server side iam auth mode is ineffective

packages/core/src/singleton/Auth/types.ts
The `CustomScope` should be a string `type CustomScope = string & {}` was used to ensure `OAuthScope` won't resolve as a `string`.
The eslint migration required change of using `{}`, and the change was wrong.
=> fix(core): eslint migration caused wrong CustomScope type

packages/auth/__tests__/providers/cognito/utils/dispatchSignedInHubEvent.test.ts, packages/auth/src/errors/constants.ts, packages/auth/src/providers/cognito/apis/confirmSignIn.ts, packages/auth/src/providers/cognito/apis/signInWithCustomAuth.ts, packages/auth/src/providers/cognito/apis/signInWithCustomSRPAuth.ts, packages/auth/src/providers/cognito/apis/signInWithSRP.ts, packages/auth/src/providers/cognito/apis/signInWithUserPassword.ts, packages/auth/src/providers/cognito/utils/dispatchSignedInHubEvent.ts, packages/auth/src/providers/cognito/utils/oauth/completeOAuthFlow.ts, packages/aws-amplify/package.json
This is an action item came out while triaging issue: https://github.com/aws-amplify/amplify-js/issues/12873
Now it handles error that may be thrown from the `getCurrentUser()` call used by dispatching the `signedIn` Auth Hub event, and convert the error to be more contextual.
Error message wording is open for suggestion.
Before:
After:
* Unit tests
* Sample app testing locally observing the error handling behavior
=> chore(auth): improve error message on failure of getCurrentUser while dispatching signedIn event

yarn.lock
Update our yarn.lock file in v5 to pickup the latest version of `ip`. This should resolve the CVE once GitHub updates their advisory database.
=> chore: Update yarn.lock file

packages/api-graphql/__tests__/fixtures/modeled/amplifyconfiguration.ts, packages/api-graphql/__tests__/internals/APIClient.test.ts, packages/api-graphql/__tests__/internals/generateClient.test.ts, packages/api-graphql/src/internals/APIClient.ts
* Updated the function for generating the default selection set for non-model types to be capable to generate selection set for nested custom types
* Updated the internal `dotNotationToObject` function so it can resolve `fields` from `modelIntrospection.nonModels` to handle `trackingMeta.productMeta.status` where:
1. `trackingMeta` is a field of a model
2. `trackingMeta` field is a custom type
3. `productMeta` is a filed of `trackingMeta`'s custom type
4. `productMeta` field is a custom type
* Unit tests
* Manual E2E testing in a sample app
=> fix(api-graphql): cannot generate selection set for nested custom types

yarn.lock
Regenerates xml2js in our yarn.lock file to resolve publish failures, e.g. https://github.com/aws-amplify/amplify-js/actions/runs/8176950274/job/22359566096
Generated by running `yarn install` on a clean repository.
Local testing, yarn audit
```
b0f1d8581327:amplify-js jablanch$ yarn why xml2js
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "xml2js"...?
[2/4] 🚚  Initialising dependency graph...
warning Resolution field "path-scurry@1.10.0" is incompatible with requested version "path-scurry@^1.10.1"
warning Resolution field "minipass@6.0.2" is incompatible with requested version "minipass@^4.2.4"
warning Resolution field "xml2js@0.5.0" is incompatible with requested version "xml2js@0.4.23"
warning Resolution field "minipass@6.0.2" is incompatible with requested version …
```
=> chore: Regenerate xml2js in yarn.lock file

packages/storage/__tests__/providers/s3/apis/utils/isInputWithPath.test.ts, packages/storage/src/providers/s3/utils/index.ts, packages/storage/src/providers/s3/utils/isInputWithPath.ts, packages/storage/src/providers/s3/utils/validateStorageOperationInput.ts, packages/storage/src/types/inputs.ts
Extract `isInputWithPath` from `validateStorageOperationInput` to a separate file of it's own to reuse across other APIs
added unit test
=> chore(storage): extract isInputWithPath into separate file

packages/aws-amplify/package.json, packages/core/src/singleton/Storage/types.ts, packages/storage/__tests__/providers/s3/apis/utils/validateStorageOperationInput.test.ts, packages/storage/src/errors/types/validation.ts, packages/storage/src/providers/s3/utils/resolveS3ConfigAndInput.ts, packages/storage/src/providers/s3/utils/validateStorageOperationInput.ts
- Adds deprecation warning for prefix resolver
- Adds validation on `path` parameter in input 
- Unit tests
- Manual Validation in sample app
=> Feat: Prefix resolver & Path input validation

packages/auth/__tests__/providers/cognito/tokenOrchestrator.test.ts
`tokenOrchestrator` test is failing [because of an expired token](https://github.com/aws-amplify/amplify-js/actions/runs/8260151082/job/22622337696?pr=13104#step:4:434) 
- Add required mock objects directly in `tokenOrchestrator` file rather than importing from another util file authAPITestParams
- Hardcode expiredDate and futureDate instead of calling `decodeJWT()` util
Alternative:
Spying on `decodeJWT()` in authAPITestParams to achieve the same is complex because 
- authAPITestParams get's complied before the spy in test gets added to it. Would need to dynamically import authAPITestParams again in the test
- decodeJWT gets called multiple times in a test, sometimes we can't have a standard mock value 
By submitting this pull request, I confirm that my contribution is made under the …
=> chore(auth): update tokenOrchestrator unit test exp token

packages/core/src/libraryUtils.ts, packages/core/src/singleton/Auth/types.ts, packages/core/src/singleton/Auth/utils/index.ts, packages/core/src/types/index.ts, packages/core/src/types/utils.ts, packages/core/src/utils/WordArray.ts
This PR introduces some minor cleanup to improve consistency and structural semantics in `core`:
1. Export `WordArray` as module member so it can be re-exported directly by `libraryUtils.ts`
2. Extract `StrictUnion` to core root level types since it is not actually coupled to Auth (and will be used by Storage in future PRs)
```
$ yarn clean && yarn && yarn build && yarn test
```
=> chore: Small cleanup to internal core utils

packages/storage/__tests__/providers/s3/apis/copy.test.ts, packages/storage/__tests__/providers/s3/apis/downloadData.test.ts, packages/storage/__tests__/providers/s3/apis/utils/validateStorageOperationInput.test.ts, packages/storage/src/errors/types/validation.ts, packages/storage/src/providers/s3/types/options.ts, packages/storage/src/providers/s3/utils/validateStorageOperationInput.ts
- Fixes Path assertion to validate `path` to not start with leading slash
- Updates test
- Unit tests and manual testing 
=> Update Path assertion

.vscode/settings.json, packages/api-graphql/__tests__/fixtures/modeled/amplifyconfiguration.ts, packages/api-graphql/__tests__/fixtures/modeled/schema.ts, packages/api-graphql/__tests__/internals/generateClient.test.ts, packages/api-graphql/__tests__/internals/server/generateClientWithAmplifyInstance.test.ts, packages/api-graphql/package.json, packages/api-graphql/src/internals/APIClient.ts, packages/api-graphql/src/internals/generateClient.ts, packages/api-graphql/src/internals/generateCustomOperationsProperty.ts, packages/api-graphql/src/internals/operations/custom.ts, packages/api-graphql/src/internals/server/generateModelsProperty.ts, packages/api-graphql/src/internals/utils/clientProperties/generateModelsProperty.ts, packages/api-graphql/src/types/index.ts, packages/core/src/singleton/API/types.ts, yarn.lock
~Draft until this is merged: https://github.com/aws-amplify/amplify-api-next/pull/131~
TODO: 
Adds custom subscriptions support to data-client.
Given this schema
```ts
const schema = a.schema({
...,
onPostLiked: a
.subscription()
.for(a.ref('likePostReturnPost'))
.returns(a.ref('Post'))
.handler(a.handler.custom({ entry: './jsResolver_base.js' })),
onPostUpdated: a
.subscription()
.for(a.ref('Post').mutations(['update']))
.arguments({ postId: a.string() })
.returns(a.ref('Post'))
.handler(a.handler.custom({ entry: './jsResolver_base.js' })),
}).authorization([a.allow.private()]),
```
data-client makes the following subscription functions available:
```ts
const sub = client.subscriptions.onPostLiked().subscribe({ next: ..., error: ... })
const sub2 = client.subscriptions.onPostUpdated({ …
```
=> feat(api-graphql): custom subscriptions

.github/workflows/push-integ-test.yml, .github/workflows/push-preid-release.yml
Enable pre-id publication and continuous E2E tests for the Gen2 storage branch. Changes will be published to `gen2-storage` when E2E tests pass.
=> chore: Enable pre-id publication for gen2-storage

packages/api-graphql/__tests__/fixtures/modeled/amplifyconfiguration.ts, packages/api-graphql/__tests__/fixtures/modeled/schema.ts, packages/api-graphql/__tests__/internals/generateClient.test.ts, packages/api-graphql/__tests__/internals/implicit-auth-fields.test.ts, packages/api-graphql/__tests__/internals/server/generateClientWithAmplifyInstance.test.ts, packages/api-graphql/__tests__/utils/expects.ts, packages/api-graphql/__tests__/utils/index.ts, packages/api-graphql/src/utils/resolveOwnerFields.ts
Adds implied group fields from auth rules to selection sets. (Implicit owner fields were already being included.)
Added models and tests.
=> feat: implicit group auth fields in selection sets

packages/auth/src/providers/cognito/tokenProvider/TokenOrchestrator.ts, packages/aws-amplify/package.json
* fix(auth): add inflight promise in token orchestrator
The issue was caused due to the `oAuthStore` not having the AuthConfig available. This change will set the config to the oAuthStore
- e2e [tests](https://github.com/aws-amplify/amplify-js/actions/runs/8420957701) are passing
=> fix(auth): set auth config to `oAuthStore`

packages/aws-amplify/package.json, packages/storage/__tests__/providers/s3/apis/utils/validateStorageOperationInput.test.ts, packages/storage/src/errors/types/validation.ts, packages/storage/src/providers/s3/utils/validateStorageOperationInput.ts
Adds runtime validation to ensure that key & path aren't specified at the same time to protect JavaScript customers from undefined behavior.
Local testing
=> chore: Add validation to ensure key & path not specified at the same time

packages/aws-amplify/package.json
Tweaks bundle limit for `getUrl`.
=> chore: Update bundle size limit for `getUrl`

packages/api-graphql/__tests__/GraphQLAPI.test.ts, packages/api-graphql/src/internals/InternalGraphQLAPI.ts, packages/api-graphql/src/internals/utils/runtimeTypeGuards/isGraphQLResponseWithErrors.ts, packages/api-graphql/src/utils/errors/constants.ts, packages/api-graphql/src/utils/errors/createGraphQLResultWithError.ts, packages/api-graphql/src/utils/errors/index.ts, packages/api-graphql/src/utils/errors/repackageAuthError.ts, packages/api-graphql/tsconfig.json, packages/api-rest/src/apis/common/internalPost.ts, packages/api-rest/src/internals/index.ts, packages/api-rest/src/utils/createCancellableOperation.ts, packages/aws-amplify/package.json
See the commit message.
1. unit tests
2. manual tests in a sample app
=> fix(api-graphql): update error handling

packages/api-graphql/__tests__/fixtures/modeled/amplifyconfiguration.ts, packages/api-graphql/__tests__/fixtures/modeled/schema.ts, packages/api-graphql/__tests__/internals/generateClient.test.ts, packages/api-graphql/__tests__/resolveOwnerFields.test.ts, packages/api-graphql/src/utils/resolveOwnerFields.ts
When generating the default selection set for a model, we were attempting to inject the `groupsField` of a static group auth rule e.g. `a.allow.specificGroup('Admin')`. Only dynamic group model introspection auth attributes contain a `groupsField` value, so we were inadvertently adding an explicit `undefined` to the default selection set, which was causing unexpected behavior.
This PR adds an additional check to make sure we're only adding the `groupsField` value when it's defined.
* Red/green TDD
* Manual e2e testing
=> fix(api-graphql): default selection set regression

packages/api-graphql/__tests__/fixtures/modeled/amplifyconfiguration.ts, packages/api-graphql/__tests__/fixtures/modeled/schema.ts, packages/api-graphql/__tests__/internals/generateClient.test.ts, packages/api-graphql/__tests__/resolveOwnerFields.test.ts, packages/api-graphql/src/utils/resolveOwnerFields.ts
When generating the default selection set for a model, we were attempting to inject the `groupsField` of a static group auth rule e.g. `a.allow.specificGroup('Admin')`. Only dynamic group model introspection auth attributes contain a `groupsField` value, so we were inadvertently adding an explicit `undefined` to the default selection set, which was causing unexpected behavior.
This PR adds an additional check to make sure we're only adding the `groupsField` value when it's defined.
* Red/green TDD
* Manual e2e testing
=> release(required): api-graphql - default selection set regression

packages/api-graphql/__tests__/internals/__snapshots__/generateClient.test.ts.snap, packages/api-graphql/__tests__/internals/server/__snapshots__/generateClientWithAmplifyInstance.test.ts.snap, packages/api-graphql/src/internals/APIClient.ts
fix(data): conditional inclusion of sort keys / sortDirection for list
=> fix(data): conditional inclusion of sort keys / `sortDirection` for list

packages/aws-amplify/package.json, packages/core/src/clients/middleware/retry/defaultRetryDecider.ts
aws-sdk@3 updated the error code location to `name` instead of `code`, therefore we were not catching the clock skew error message and triggering a retry. This PR fixes retry on API (Rest) calls when a clock-skew error is encountered by checking the `name` property if `code` is undefined.
https://github.com/aws-amplify/amplify-js/issues/13192
Tested in a sample app using Verdaccio.
=> release(required): check error name as well as code for clock skew

packages/auth/__tests__/providers/cognito/signInWithRedirect.test.ts, packages/auth/src/providers/cognito/apis/signInWithRedirect.ts, packages/auth/src/providers/cognito/tokenProvider/TokenOrchestrator.ts, packages/aws-amplify/package.json
Currently we are only setting the [OAuthInflight flag](https://github.com/aws-amplify/amplify-js/blob/main/packages/auth/src/providers/cognito/apis/signInWithRedirect.ts#L90) and waiting for it in the [TokenOrchestrator](https://github.com/aws-amplify/amplify-js/blob/main/packages/auth/src/providers/cognito/tokenProvider/TokenOrchestrator.ts#L35) to get resolved(success/error/cancellation). This flow works well for web. However, for RN, we do not need this OAuthInflight flag to be set nor do we need to wait for it to get resolved. This fix involves removing both these actions for RN using the isBrowser() method.
https://github.com/aws-amplify/amplify-js/issues/13191
=> release(required): fix inflight promise on RN

packages/aws-amplify/package.json, packages/storage/src/providers/s3/apis/copy.ts, packages/storage/src/providers/s3/apis/downloadData.ts, packages/storage/src/providers/s3/apis/getProperties.ts, packages/storage/src/providers/s3/apis/getUrl.ts, packages/storage/src/providers/s3/apis/list.ts, packages/storage/src/providers/s3/apis/remove.ts, packages/storage/src/providers/s3/apis/server/copy.ts, packages/storage/src/providers/s3/apis/server/getProperties.ts, packages/storage/src/providers/s3/apis/server/getUrl.ts, packages/storage/src/providers/s3/apis/server/list.ts, packages/storage/src/providers/s3/apis/server/remove.ts, packages/storage/src/providers/s3/apis/uploadData/index.ts, packages/storage/src/providers/s3/utils/isInputWithPath.ts, packages/storage/src/providers/s3/utils/validateStorageOperationInput.ts, packages/storage/src/types/index.ts, packages/storage/src/types/inputs.ts
- The overloads for the storage APIs were missing type for unionized input.
- Remove un-used type
- Refactor type name
- Unit and Integ tests were run
- Manually tested it
=> [Fix] Update API overload types

.github/workflows/callable-npm-publish-lts-release.yml, .github/workflows/callable-npm-publish-release.yml
- Lerna causes a patch version bump on all packages irrespective of the packages that have changed. 
- package [CHANGELOG](https://github.com/aws-amplify/amplify-js/blob/main/packages/api-graphql/CHANGELOG.md#4027-2024-04-02) does not capture changes
- lerna publish log: ["lerna info Assuming all packages changed"](https://github.com/aws-amplify/amplify-js/actions/runs/8427545861/job/23079687360#step:4:41).
- Lerna only bumps the version of the packages that are changed and their dependent packages
- Example a feat commit on auth causes a minor version bump on auth, patch version bump on aws-amplify
(auth is a dependency in aws-amplify) 
before `lerna publish` checkout with `fetch-depth: 0`see [Lerna issue on GH actions](https://github.com/lerna/lerna/issues/2542)
[Current …
=> chore: fix lerna package bump issue

packages/core/__tests__/amplify_outputs.json, packages/core/__tests__/parseAmplifyOutputs.test.ts, packages/core/src/parseAmplifyOutputs.ts, packages/core/src/singleton/AmplifyOutputs/types.ts
Relax types of `AmplifyOutputs` to prevent TypeScript problems while importing JSON file, also updating with latests schema.
```json
{
"$schema": "https://json-schema.org/draft/2020-12/schema",
"$id": "https://amplify.aws/2024-02/outputs-schema.json",
"title": "AWS Amplify Backend Outputs",
"description": "Config format for Amplify Gen 2 client libraries to communicate with backend services.",
"type": "object",
"additionalProperties": false,
"properties": {
"$schema": {
"description": "JSON schema",
"type": "string"
},
"version": {
"description": "Version of this schema",
"const": "1"
},
"analytics": {
"description": "Outputs manually specified by developers for use with frontend library",
"type": "object",
"additionalProperties": false,
"properties": {
"amazon_pinpoint": {
"type": …
```
=> Fix: relax config for AmplifyOutputs

packages/api-graphql/__tests__/fixtures/modeled/amplifyconfiguration.ts, packages/api-graphql/__tests__/fixtures/modeled/schema.ts, packages/api-graphql/__tests__/internals/APIClient.test.ts, packages/api-graphql/__tests__/internals/__snapshots__/generateClient.test.ts.snap, packages/api-graphql/__tests__/internals/generateClient.test.ts, packages/api-graphql/src/internals/APIClient.ts, packages/api-graphql/src/internals/operations/custom.ts
* Updated the logic of generating selection set when custom selection set is used in conjunction of `field.*`
* Updated the unit test fixture
* Added a unit test for the issue that this PR fixes
**Context**
The error was:
For (breaking at `trackingMeta.*`)
```
"query($filter: ModelWarehouseFilterInput,$limit: Int,$nextToken: String) {
listWarehouses(filter: $filter,limit: $limit,nextToken: $nextToken) {
items {
id name products {
items {
sku factoryId description trackingMeta.* warehouseProductsId createdAt updatedAt owner
}
}
}
nextToken __typename
}
}"
```
=> fix(api-graphql): incorrect custom selection set for nested model.model.customType

packages/api-graphql/__tests__/internals/APIClient.test.ts, packages/api-graphql/__tests__/internals/__snapshots__/generateClient.test.ts.snap, packages/api-graphql/src/internals/APIClient.ts, packages/aws-amplify/package.json
We were generating list query arguments for sort keys using the underlying field's primitive type as the argument type.
List queries on models with composite primary keys expect a _condition_ input argument type for the sort key(s).
See this diff for current vs expected behavior: https://github.com/aws-amplify/amplify-js/compare/data-fix-sk-args?expand=1#diff-fa24101f776e07b54f8416746bbed348b96dd7e855c0eed2e5609bcb501a9b46L4095-R4095
* updated e2e test to include this use case - https://github.com/aws-amplify/amplify-js-samples-staging/pull/845
=> fix(api-graphql): incorrect list sk arg type

packages/core/__tests__/parseAmplifyOutputs.test.ts, packages/core/src/singleton/AmplifyOutputs/types.ts
below is the ref for backend schema that generates geo amplifyOutputs
```
"geo": {
"description": "Outputs manually specified by developers for use with frontend library",
"type": "object",
"additionalProperties": false,
"properties": {
"aws_region": {
"description": "AWS Region of Amazon Location Service resources",
"$ref": "#/$defs/aws_region"
},
"maps": {
"description": "Maps from Amazon Location Service",
"type": "object",
"additionalProperties": false,
"properties": {
"items": {
"type": "object",
"additionalProperties": false,
"propertyNames": {
"description": "Amazon Location Service Map name",
"type": "string"
},
"patternProperties": {
".*": {
"$ref": "#/$defs/amazon_location_service_config"
}
}
},
"default": {
"type": "string"
}
},
"required": ["items", "default"]
}, …
```
=> fix(geo): update amplify config geo schema

README.md, packages/aws-amplify/README.md
Cleans up some awkward language in the README file.
=> chore: Clean up awkward langauge in README

packages/aws-amplify/package.json, packages/core/__tests__/providers/pinpoint/apis/updateEndpoint.test.ts, packages/core/__tests__/providers/pinpoint/utils/createEndpointId.test.ts, packages/core/src/providers/pinpoint/apis/updateEndpoint.ts, packages/core/src/providers/pinpoint/utils/createEndpointId.ts, packages/core/src/providers/pinpoint/utils/index.ts
Currently, when an endpoint is created by `updateEndpoint`, it is not cached until a full network round trip to the service. This results in a large window during which additional `updateEndpoint` calls will create new endpoint ids due to none being found in the cache.
This PR adds a utility which will hold created endpoint ids in memory until it is successfully cached or if the endpoint updating has failed.
https://github.com/aws-amplify/amplify-js/issues/13272
* `yarn test`
* Added thrown error expectation to original code and asserted the resulting behavior of the `updateEndpoint` function is the same (async void which throws uncaught)
* Tested in sample app and validated that network race condition was mitigated - the `updateEndpoint` calls triggered by `initializePushNotifications` …
=> fix: Prevent creating multiple endpoint ids

packages/datastore/src/types.ts
Adds deprecation flag and docstring to the `Schema` type exported from `DataStore`. Customers should not be using this type directly. And, it shows up in autocompletion when customers are looking for the `Schema` type exported from gen2 API's, which can lead to some confusion.
The primary concern is whether any lint rules might prohibit an app from using a deprecated type. To alleviate that concern:
1. Ran e2e's in a tagged release to confirm no failed builds.
2. Manually created a nextjs app with default eslint rules and built. (No errors or warnings emitted.)
=> chore: add deprecation notice to DataStore exported Schemaa type

.github/integ-config/integ-all.yml, .github/workflows/callable-e2e-test.yml, .github/workflows/callable-e2e-tests.yml, .github/workflows/push-integ-test.yml
Updates GH actions to take in additional `backend` parameter and call the sample staging app with it. 
Subsequent tests that need to be added for Gen2 only needs to add a new test case with the value `backend: gen2` similar to what's shown [here](https://github.com/aws-amplify/amplify-js/compare/gen2-storage...feat/rest-gen2?expand=1#diff-de7af17f58a9a20d1ba99ef81f437aa28789d38c98ebbd2529f32feacdc79193).
Passing GH actions on this branch.
=> feat(gh-actions): gen2 e2e rest api

.github/integ-config/integ-all.yml
enables web auth gen2 e2e tests on CI with the exception of  `integ_react_credentials_different_region` . This test doesn't have a gen2 config. Gen2 doesn't support setting an identity pool in a different region yet.
Enabled auth tests running on CI:
https://github.com/aws-amplify/amplify-js/actions/runs/8901181083
=> feat(auth): enable auth gen2

packages/auth/__tests__/providers/cognito/fetchDevices.test.ts, packages/auth/src/providers/cognito/apis/fetchDevices.ts, packages/auth/src/providers/cognito/utils/signInHelpers.ts, packages/aws-amplify/package.json, packages/core/src/libraryUtils.ts, packages/core/src/utils/deviceName/getDeviceName.native.ts, packages/core/src/utils/deviceName/getDeviceName.ts, packages/core/src/utils/deviceName/index.ts, packages/core/src/utils/deviceName/types.ts
- Add a default deviceName for web and RN when making a [ConfirmDevice](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ConfirmDevice.html) service call
- The `navigator.userAgent` API [causes a warning in Chrome DevTools](https://blog.chromium.org/2021/05/update-on-user-agent-string-reduction.html) (Issues tab) starting with version 92
- Use `navigator.userAgentData` (when available) instead of `navigator.userAgent`
Note:
The `navigator.userAgentData` API involves introducing randomness by adding a string `Not_A_Brand | Not_A Brand | Not A(Brand |  ...` to prevent user fingerprinting. The deviceName passed to the `ConfirmDevice` service API is called every time the user signs-in until the `rememberDevice` API is called, after which it just updates the …
=> feat(auth): add a default deviceName when remembering device

packages/aws-amplify/package.json, packages/core/__tests__/providers/pinpoint/apis/testUtils/getExpectedInput.ts, packages/core/__tests__/providers/pinpoint/apis/updateEndpoint.test.ts, packages/core/__tests__/providers/pinpoint/testUtils/data.ts, packages/core/src/providers/pinpoint/apis/updateEndpoint.ts
When calling `initializePushNotifications`, the library calls an internal `updateEndpoint` API. Anytime `updateEndpoint` is called, it automatically populates the `demographic` property with client info and the `userId` with the identity id. When calling `identifyUser`, these values can be provided explicitly but will always be pre-populated. This can have unexpected consequences since `initializePushNotifications` is typically called on every app launch - and it will opaquely overwrite existing values previously set on the endpoint.
This PR updates the `updateEndpoint` API to only pre-populate these fields when **creating** an endpoint to avoid repeatedly overwriting the endpoint with the default/fallback values.
https://github.com/aws-amplify/amplify-js/issues/13174
* `yarn test`
* …
=> fix: Prevent overwriting with fallbacks when updating endpoint

package.json, packages/api-graphql/__tests__/fixtures/with-types/API.ts, packages/api-graphql/__tests__/fixtures/with-types/mutations.ts, packages/api-graphql/__tests__/fixtures/with-types/queries.ts, packages/api-graphql/__tests__/fixtures/with-types/subscriptions.ts, packages/api-graphql/__tests__/fixtures/without-types/API.ts, packages/api-graphql/__tests__/fixtures/without-types/mutations.ts, packages/api-graphql/__tests__/fixtures/without-types/queries.ts, packages/api-graphql/__tests__/fixtures/without-types/subscriptions.ts, packages/api-graphql/package.json, packages/api-rest/package.json, packages/datastore-storage-adapter/.npmignore, packages/datastore/.npmignore, packages/datastore/__tests__/DataStore/sanityCheck.test.ts, packages/notifications/package.json, packages/predictions/__tests__/providers/AWSAIIdentifyPredictionsProvider.test.ts, packages/react-native/package.json, packages/rtn-web-browser/package.json, yarn.lock
=> chore(repo): 👋🥺 tslint

packages/core/src/providers/pinpoint/index.ts, packages/notifications/__tests__/pushNotifications/providers/pinpoint/apis/identifyUser.native.test.ts, packages/notifications/__tests__/pushNotifications/providers/pinpoint/apis/initializePushNotifications.native.test.ts, packages/notifications/__tests__/pushNotifications/providers/pinpoint/utils/inflightDeviceRegistration.test.ts, packages/notifications/src/pushNotifications/providers/pinpoint/apis/identifyUser.native.ts, packages/notifications/src/pushNotifications/providers/pinpoint/apis/initializePushNotifications.native.ts, packages/notifications/src/pushNotifications/providers/pinpoint/types/index.ts, packages/notifications/src/pushNotifications/providers/pinpoint/types/pushNotifications.ts, packages/notifications/src/pushNotifications/providers/pinpoint/utils/index.ts, packages/notifications/src/pushNotifications/providers/pinpoint/utils/inflightDeviceRegistration.ts
When the Push Notification category is first creating a Pinpoint endpoint upon receiving a device token, it is possible for an `identifyUser` call to be attempting to update the endpoint to be resolved first over the network. This is troublesome for at least two known reasons:
1. The `identifyUser` call could be attempting to set the `OptOut` property to `'NONE'` and if it is resolved first by the service, the service will reject the request due to the `Address` not having yet been set.
2. The `identifyUser` call could contain `userId` or `demographic` information and if it resolved first by the service, the request made by the library to register the device token would contain default values which would unintentionally overwrite the ones set by `identifyUser`
This PR mitigates this by …
=> fix: Wait for endpoint creation to identify user

packages/auth/src/providers/cognito/index.ts, packages/auth/src/providers/cognito/tokenProvider/index.ts, packages/auth/src/providers/cognito/utils/refreshAuthTokens.ts, packages/aws-amplify/__tests__/adapterCore/authProvidersFactories/cognito/createUserPoolsTokenProvider.test.ts, packages/aws-amplify/__tests__/exports.test.ts, packages/aws-amplify/src/adapter-core/authProvidersFactories/cognito/createUserPoolsTokenProvider.ts
1. Exported a non-deduped token refresher function 
2. Updated the SSR adapter to use the non-deduped token refresher function to create context
3. Fixed that in a `getServerSideProps` context, refresh tokens were not being sent back to client cookie store
1. unit tests
2. manual testing with Next.js sample apps
=> fix(ssr-adapter): refreshToken may return the same tokens across requests

packages/adapter-nextjs/__tests__/utils/createCookieStorageAdapterFromNextServerContext.test.ts, packages/adapter-nextjs/src/utils/createCookieStorageAdapterFromNextServerContext.ts
* Fixed to use `appendHeader` to add `Set-Cookie` header values
=> fix(adapter-nextjs): Set-Cookie headers incorrectly set with getServerSideProps context

.eslintrc.js, packages/api-rest/__tests__/apis/common/internalPost.test.ts, packages/api-rest/__tests__/apis/common/publicApis.test.ts, packages/api-rest/__tests__/index.test.ts, packages/api-rest/__tests__/server.test.ts
See each commit message for details.
=> chore: (api-rest) enable linting on __tests__ 

.eslintrc.js, packages/analytics/__tests__/providers/kinesis-firehose/apis/flushEvents.test.ts, packages/analytics/__tests__/providers/kinesis-firehose/apis/record.test.ts, packages/analytics/__tests__/providers/kinesis-firehose/utils/resolveConfig.test.ts, packages/analytics/__tests__/providers/kinesis/apis/flushEvents.test.ts, packages/analytics/__tests__/providers/kinesis/apis/record.test.ts, packages/analytics/__tests__/providers/kinesis/utils/getEventBuffer.test.ts, packages/analytics/__tests__/providers/kinesis/utils/resolveConfig.test.ts, packages/analytics/__tests__/providers/personalize/apis/flushEvents.test.ts, packages/analytics/__tests__/providers/personalize/apis/record.test.ts, packages/analytics/__tests__/providers/personalize/utils/cachedSession.test.ts, packages/analytics/__tests__/providers/personalize/utils/getEventBuffer.test.ts, packages/analytics/__tests__/providers/personalize/utils/resolveConfig.test.ts, packages/analytics/__tests__/providers/pinpoint/apis/flushEvents.test.ts, packages/analytics/__tests__/providers/pinpoint/apis/identifyUser.test.ts, packages/analytics/__tests__/providers/pinpoint/apis/record.test.ts, packages/analytics/__tests__/providers/pinpoint/utils/resolveConfig.test.ts, packages/analytics/__tests__/providers/pinpoint/utils/resolveCredentials.test.ts, packages/analytics/__tests__/utils/eventBuffer/EventBuffer.test.ts, packages/analytics/__tests__/utils/groupBy.test.ts, packages/analytics/__tests__/utils/resolveCredentials.test.ts, packages/analytics/__tests__/utils/statusHelpers.test.ts
See each commit message for details.
=> chore(analytics): enable linting on __tests__

.github/actions/load-verdaccio-with-amplify-js/action.yml
Stores NPM logs as artifacts in the event of a test failure.
=> chore: Store NPM logs as artifacts in CI

.github/actions/node-and-build/action.yml
Pins the version of Node expected in e2e integ test setup. npm-cli-adduser fails with node version 18.20.3.
Reproduced error locally with node version 18.20.3 and validated that the error did not show up when using earlier versions of node. Pinned node version in my forked repository resulting in this test run in which e2e tests are failing: https://github.com/erinleigh90/amplify-js/actions/runs/9309095374
Note that in the test run above there is an unrelated unit test failure which was not impacted by this change: it was failing before and after pinning node and is not failing in the main repository, so I believe this is unrelated. `yarn test` passes locally.
=> fix: pin node version in gh actions

packages/storage/__tests__/providers/s3/utils/md5.native.test.ts, packages/storage/__tests__/providers/s3/utils/md5.test.ts, packages/storage/src/providers/s3/utils/client/runtime/base64/index.browser.ts, packages/storage/src/providers/s3/utils/client/runtime/base64/index.native.ts, packages/storage/src/providers/s3/utils/client/runtime/index.browser.ts, packages/storage/src/providers/s3/utils/client/runtime/index.native.ts, packages/storage/src/providers/s3/utils/client/runtime/index.ts, packages/storage/src/providers/s3/utils/client/utils/index.ts, packages/storage/src/providers/s3/utils/md5.native.ts, packages/storage/src/providers/s3/utils/md5.ts
When `isObjectLockEnabled` is set to `true` in configuration, the Amplify library calculates and appends `ContentMD5` automatically. However, as a customer discovered, this MD5 calculation was not always being performed correctly and the upload task results in a BadDigest error from the service.
Upon investigation, it appears that the category went under a refactor which saw the MD5 calculations utilities be renamed and relocated. However, during this refactor, the implementations intended for web and native were accidentally flipped:
* MD5Utils -> utils/md5.native
* MD5Utils.native -> utils/md5
After undoing this switch, the library behaved as expected on Web but the native implementations continued to fail. Upon further deep dive, it was discovered that the `readAsArrayBuffer` gap which …
=> fix(storage): Fix MD5 calculation

.github/workflows/callable-canary-e2e.yml, .github/workflows/callable-e2e-test-detox.yml, .github/workflows/callable-e2e-tests.yml, .github/workflows/callable-release-verification.yml
Pinning the version down on macOS to unblock release. 
We need to backport the detox version 20 update in v6 to v5 branch in samples staging repo as long term fix.
Successful run : https://github.com/aws-amplify/amplify-js/actions/runs/9388518491/job/25856630610
=> [V5-Stable] Pin macOS version

packages/aws-amplify/package.json, packages/core/__mocks__/configMocks/amplify_outputs.json, packages/core/__mocks__/configMocks/amplifyconfiguration.json, packages/core/__tests__/parseAWSExports.test.ts, packages/core/src/parseAmplifyOutputs.ts
The `parseAmplifyOutputs` function does not take into account any custom oAuth Provider and this lead to providers in oAuth config having undefined values breaking the UI Authenticator component.
In additon to the fix for Amplify outputs, the PR loosens up the OAuth config type.  Since looking into the issue, realized our parse utility provided for adding custom oAuth as string to list of providers outside of our `CustomProvider` in `OAuthConfig`. 
https://github.com/aws-amplify/amplify-js/issues/13466
- unit tests
=> release(required): Parsing custom oAuth in amplify_outputs

packages/adapter-nextjs/__tests__/utils/isValidCognitoToken.test.ts, packages/adapter-nextjs/src/utils/isValidCognitoToken.ts
When a token has valid signature but expired, it should be considered a valid token.
https://github.com/aws-amplify/amplify-js/issues/13456
* Next.js sample app testing
=> release(required): an expired token that has valid signature is not considered a valid token

packages/storage/src/providers/s3/types/options.ts, packages/storage/src/storage-browser/createLocationCredentialsHandler.ts, packages/storage/src/storage-browser/index.ts, packages/storage/src/storage-browser/listCallerAccessGrants.ts, packages/storage/src/storage-browser/locationCredentialsStore/createLocationCredentialsStore.ts, packages/storage/src/storage-browser/types.ts
Add types so far for StorageBrowser.
No implemenation added.
=> feat(storage): add base types for storage browser

packages/react-native/package.json
The purpose of this PR is to downgrade the `react-native-get-random-values` peer dependency in the library from >=1.9.0 to >=1.8.0. Expo@50 (current latest is 51) [specifies 1.8.0 as the dependency target](https://github.com/expo/expo/blob/sdk-50/packages/expo/bundledNativeModules.json#L90) while amplify-js specifies a peer dependency target of >=1.9.0. This produces installation friction when getting started via the recommended workflow, i.e. `npx expo install ...`
Dropping the peer dependency version will remove installation friction while having no impact on current library functionality.
Tested change on following targets:
* RN CLI targeting RN v74
* RN CLI targeting RN v73
* Expo CLI targeting RN v74
* Expo CLI targeting RN v73
For each above target, confirm no installation friction …
=> downgrade react-native-get-random-values from >=1.9.0 to >=1.8.0

packages/aws-amplify/package.json, packages/storage/__tests__/providers/s3/apis/uploadData/index.test.ts, packages/storage/__tests__/providers/s3/apis/uploadData/multipartHandlers.test.ts, packages/storage/__tests__/providers/s3/apis/uploadData/putObjectJob.test.ts, packages/storage/__tests__/providers/s3/apis/utils/resolveS3ConfigAndInput.test.ts, packages/storage/src/providers/s3/apis/downloadData.ts, packages/storage/src/providers/s3/apis/internal/copy.ts, packages/storage/src/providers/s3/apis/internal/getProperties.ts, packages/storage/src/providers/s3/apis/internal/getUrl.ts, packages/storage/src/providers/s3/apis/internal/list.ts, packages/storage/src/providers/s3/apis/internal/remove.ts, packages/storage/src/providers/s3/apis/internal/types/index.ts, packages/storage/src/providers/s3/apis/internal/uploadData.ts, packages/storage/src/providers/s3/apis/uploadData/index.ts, packages/storage/src/providers/s3/apis/uploadData/multipart/uploadHandlers.ts, packages/storage/src/providers/s3/apis/uploadData/putObjectJob.ts, packages/storage/src/providers/s3/types/options.ts, packages/storage/src/providers/s3/utils/config.ts, packages/storage/src/providers/s3/utils/constructors.ts, packages/storage/src/providers/s3/utils/index.ts, packages/storage/src/providers/s3/utils/resolveS3ConfigAndInput.ts
The following changes decouple internal Storage `utils` and the `uploadData` API from the Amplify singleton. This refactor will allow the high-level APIs, the ones exposed to customers, to manage and create a Storage configuration based on an API input or Amplify configuration. Then the obtained config will be accessed by the low level implementation functionalities, e.g `putObjectJob`, `getMultipartUploadHandlers`, and `resolveS3ConfigAndInput` utils.
- PR doesn't refactor the functionality of the internal Storage utils
- Decouple additional Storage APIs other than `uploadData` 
All of the storage APIs will follow this pattern
=> refactor(storage): decouple utils from Amplify singleton

packages/storage/__tests__/storageBrowser/locationCredentialsStore/registry.test.ts, packages/storage/src/storageBrowser/index.ts, packages/storage/src/storageBrowser/locationCredentialsStore/registry.ts, packages/storage/storage-browser/package.json
2 changes are included in this PR:
1. Use `WeakMap` instead of `Map` for store regitry. This is inspired by the Amplify context store implemenation. The nice thing of `WeakMap` is that the entry in the WeakMap is not referred to prevent it from GC. So as long as the store is no longer referred in the code scope, it can be GC'd. Whereas with `Map`, we always depend on `destroy()` to de-reference the store. thanks @HuiSF 
2. Moving the storage browser exports to `@aws-amplify/storage/storage-browser` subpath. We are using this subpath to differentiate it from APIs will be reexported publicly in umbrella package(e.g. `/s3` subpath), and APIs that entirely internal to the library(e.g. `/internals` subpath). This subpath is called out to be only consumable by UI.
Unit test; Manual Validation …
=> feat(storage): use WeakMap for store registry

packages/aws-amplify/package.json, packages/core/src/Platform/types.ts, packages/interactions/package.json, packages/storage/__tests__/storageBrowser/apis/listCallerAccessGrants.test.ts, packages/storage/__tests__/storageBrowser/managedAuthAdapter/createListLocationsHandler.test.ts, packages/storage/src/storageBrowser/apis/constants.ts, packages/storage/src/storageBrowser/apis/listCallerAccessGrants.ts, packages/storage/src/storageBrowser/apis/types.ts, packages/storage/src/storageBrowser/managedAuthConfigAdapter/createListLocationsHandler.ts
This change adds handler calling the new S3 list locations API, and integrate it to the adapter.
Unit test
=> feat(storage): implement listLocations API and creation handler

packages/storage/src/providers/s3/apis/internal/list.ts, packages/storage/src/providers/s3/types/options.ts, packages/storage/src/providers/s3/types/outputs.ts
The `subpathStrategy` option is currently added to the `prefix` input of the `list`, which is deprecated already. This change is excluding the `subpathStrategy` key when the `list` API has `prefix` as part of the input.
- smoke test
***before***:
***after***:
=> fix(storage): omit subPathStrategy when prefix is defined

packages/storage/package.json
Expose path `@aws-amplify/storage/storage-browser` on Storage package
Tested on sampleApp
=>  chore: expose path storage-browser from scoped package

packages/storage/src/providers/s3/apis/internal/list.ts, packages/storage/src/providers/s3/types/options.ts, packages/storage/src/providers/s3/types/outputs.ts
The current change is breaking a type from an e2e [test](https://github.com/aws-amplify/amplify-js/actions/runs/9996810032/job/27636498826#logs). I need to chase down the root cause 
=> Revert "fix(storage): omit subPathStrategy when prefix is defined 

.github/workflows/push-preid-release.yml, packages/storage/src/providers/s3/apis/internal/copy.ts
- This PR enables integ test and tagged release on Multi-bucket branch
- Also adds minor comment improvement on copy assertion to make it clear
=> [Chore] Enable Integ test and tagged release on Multi-bucket work

packages/storage/__tests__/providers/s3/apis/utils/resolveS3ConfigAndInput.test.ts, packages/storage/src/errors/constants.ts, packages/storage/src/providers/s3/apis/downloadData.ts, packages/storage/src/providers/s3/apis/internal/copy.ts, packages/storage/src/providers/s3/apis/internal/getProperties.ts, packages/storage/src/providers/s3/apis/internal/getUrl.ts, packages/storage/src/providers/s3/apis/internal/list.ts, packages/storage/src/providers/s3/apis/internal/remove.ts, packages/storage/src/providers/s3/apis/uploadData/multipart/uploadHandlers.ts, packages/storage/src/providers/s3/apis/uploadData/putObjectJob.ts, packages/storage/src/providers/s3/types/inputs.ts, packages/storage/src/providers/s3/types/options.ts, packages/storage/src/providers/s3/utils/resolveIdentityId.ts, packages/storage/src/providers/s3/utils/resolveS3ConfigAndInput.ts, packages/storage/src/providers/s3/utils/validateStorageOperationInput.ts, packages/storage/src/providers/s3/utils/validateStorageOperationInputWithPrefix.ts, packages/storage/src/types/inputs.ts
The following PR enables the location credentials provider on the `resolveS3ConfigAndInput` helper. This helper is used by all of the storage APIs.
- Removed `identityId` assertion in the `resolveS3ConfigAndInput` helper  — doubled check with @AllanZhengYP already. The assertion of the `identityId` is not needed by the underlying service APIs. 
- The `credentialsProvider` in the `resolveS3ConfigAndInput` function is asserting for a `deprecated` input or a callback `path` if and only if a `locationCredentialsProvider` is passed in the Storage option inputs.
- unit tests
=> feat(storage): enables location credentials provider

packages/aws-amplify/package.json, packages/core/__tests__/parseAmplifyOutputs.test.ts, packages/core/src/parseAmplifyOutputs.ts, packages/core/src/singleton/AmplifyOutputs/types.ts, packages/core/src/singleton/Storage/types.ts, packages/core/src/singleton/types.ts, packages/interactions/package.json, packages/storage/__tests__/providers/s3/apis/copy.test.ts, packages/storage/__tests__/providers/s3/apis/downloadData.test.ts, packages/storage/__tests__/providers/s3/apis/getProperties.test.ts, packages/storage/__tests__/providers/s3/apis/getUrl.test.ts, packages/storage/__tests__/providers/s3/apis/list.test.ts, packages/storage/__tests__/providers/s3/apis/remove.test.ts, packages/storage/__tests__/providers/s3/apis/uploadData/multipartHandlers.test.ts, packages/storage/__tests__/providers/s3/apis/uploadData/putObjectJob.test.ts, packages/storage/__tests__/providers/s3/apis/utils/resolveS3ConfigAndInput.test.ts, packages/storage/src/errors/types/validation.ts, packages/storage/src/providers/s3/apis/internal/copy.ts, packages/storage/src/providers/s3/types/index.ts, packages/storage/src/providers/s3/types/inputs.ts, packages/storage/src/providers/s3/types/options.ts, packages/storage/src/providers/s3/utils/resolveS3ConfigAndInput.ts, packages/storage/src/types/inputs.ts
Merge the multibucket support to the storagebrowser branch. The only manual change is: https://github.com/aws-amplify/amplify-js/pull/13635/commits/6e5b3c58fe2d1c3e01eed99fd53036ddeb075a35
Unit test
=> feat(storage): sync multibucket to storagebrowser

packages/storage/package.json
Expose `"storage-browser"` types for TS >= v4.2
NA
Build `@aws-amplify/storage`, `npm pack` tarball, install/verify types in `@aws-amplify/ui-react-storage`
=> fix(storage): export storage-browser types for TS v4.2+

yarn.lock
This change is backporting the fix from [#13654](https://github.com/aws-amplify/amplify-js/pull/13654) PR
=> chore: backport fast-xml-parser update to v5

.github/integ-config/integ-all.yml
The purpose of this pull request is to disable the firefox Next.js storage integration test. There exists several issues between Firefox and Cypress that cause issues when testing using secure cookies (which are required in the Next.js context). These issues can be mitigated locally but not in CI without additional effort.
Failing on Firefox and succeeding on Chrome in CI.
https://github.com/jjarvisp/amplify-js/actions/runs/10113370892
Cypress / Firefox issues:
https://github.com/cypress-io/cypress/issues/18690
https://github.com/cypress-io/cypress/issues/18217
https://github.com/jjarvisp/amplify-js/actions/runs/10148754990
=> [Multi-bucket] fix - disable firefox browser test for nextjs auth

packages/storage/src/storageBrowser/index.ts, packages/storage/src/storageBrowser/managedAuthConfigAdapter/createListLocationsHandler.ts, packages/storage/src/storageBrowser/managedAuthConfigAdapter/createManagedAuthConfigAdapter.ts, packages/storage/src/storageBrowser/managedAuthConfigAdapter/index.ts
Return named function from `createListLocationsHandler`, export store and credentials related types from _@aws-amplify/storage/storage-browser_:
- `LocationCredentialsStore`
- `LocationCredentialsProvider`
- `CreateManagedAuthConfigAdapterInput`
- `AuthConfigAdapter`
- `SubpathStrategy`
Providing the above types prevents the need for manually declarations in consumers, e.g.:
```ts
import { ListPaginateWithPathInput } from 'aws-amplify/storage';
type ListInput = NonNullable<ListPaginateWithPathInput>;
export type LocationCredentialsProvider = NonNullable<
NonNullable<ListInput['options']>['locationCredentialsProvider']
>;
```
NA
Build storage package, install and build Amplify UI monorepo
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
=> chore(storage-browser): export store and credentials related types, update createListLocationsHandler

package.json, yarn.lock
This PR adds the fast-xml-parser dep as a resolution to fix the ongoing depandabot [alert](https://github.com/aws-amplify/amplify-js/security/dependabot/86)
=> chore(deps): add fast-xml-parser resolution to v5

packages/storage/__tests__/storageBrowser/apis/getDataAccess.test.ts, packages/storage/__tests__/storageBrowser/locationCredentialsStore/create.test.ts, packages/storage/__tests__/storageBrowser/locationCredentialsStore/registry.test.ts, packages/storage/__tests__/storageBrowser/locationCredentialsStore/store.test.ts, packages/storage/src/providers/s3/types/options.ts, packages/storage/src/storageBrowser/apis/getDataAccess.ts, packages/storage/src/storageBrowser/locationCredentialsStore/registry.ts, packages/storage/src/storageBrowser/locationCredentialsStore/store.ts, packages/storage/src/storageBrowser/types.ts
Following interface changes are made:
1. `locationCredentialsProvider` is required to return temperary credentials with `expiration` and `sessionToken`.
2. location-specific credentials from getLocationCredentials is required to be temperary credentials with `expiration` and `sessionToken`.
3. credentials used by managed auth adpater is required to be temperary credentials with `expiration` and `sessionToken`.
=> feat(storage): require temporary credentials for storage browser interfaces

packages/storage/__tests__/providers/s3/utils/client/S3/cases/listCallerAccessGrants.ts, packages/storage/src/providers/s3/utils/client/s3control/listCallerAccessGrants.ts
- The listCallerAccessGrantsDeserializer does not handle parsing multiple `AccessGrantsInstance`.
- When the XML response from service contains a single `AccessGrantsInstance` items it's parsed into an object; while it's parsed into an array if there are multiple items 
**Output log before fix**
xml parsed
```
// 1 item
{
"CallerAccessGrantsList": {
"AccessGrantsInstance": {
"ApplicationArn": "ALL",
"Permission": "READWRITE",
"GrantScope": "s3://ashwin-portcullis-test1/*"
}
}
}
// 2 items
{
"CallerAccessGrantsList": {
"AccessGrantsInstance": [
{
"ApplicationArn": "ALL",
"Permission": "READWRITE",
"GrantScope": "s3://ashwin-portcullis-test1/*"
},
{
"ApplicationArn": "ALL",
"Permission": "READWRITE",
"GrantScope": "s3://ashwin-portcullis-test2/*"
}
]
}
}
```
Deserializer output
```
// 1 …
```
=> fix(storage-browser): listCallerAccessGrantsDeserializer not parsing multiple AccessGrant instances

packages/datastore/__tests__/mutation.test.ts, packages/datastore/src/sync/processors/mutation.ts, packages/storage/__tests__/providers/s3/utils/client/xhrTransferHandler-util.test.ts, packages/storage/src/providers/s3/utils/client/runtime/constants.ts
Fixed the constant mapped for network failure to say network error, not connection abort
=> chore: Fix misleading error string mapping in XHR client

packages/storage/__tests__/storageBrowser/apis/listCallerAccessGrants.test.ts, packages/storage/src/storageBrowser/apis/listCallerAccessGrants.ts, packages/storage/src/storageBrowser/apis/types.ts, packages/storage/src/storageBrowser/index.ts, packages/storage/src/storageBrowser/locationCredentialsStore/create.ts, packages/storage/src/storageBrowser/types.ts
Expose additional input output types on path `@aws-amplify/storage/storage-browser`.
The additional exposed types are:
```
CreateLocationCredentialsStoreInput,
LocationCredentials,
ListLocationsInput,
ListLocationsOutput,
GetLocationCredentialsInput,
GetLocationCredentialsOutput,
Permission as AccessGrantPermission,
```
=> chore(storage-browser): expose additional input output types

packages/storage/__tests__/providers/s3/utils/client/S3/cases/listCallerAccessGrants.ts, packages/storage/src/providers/s3/utils/client/s3control/listCallerAccessGrants.ts, packages/storage/src/providers/s3/utils/client/s3control/types.ts, packages/storage/src/providers/s3/utils/client/utils/deserializeHelpers.ts, packages/storage/src/storageBrowser/apis/listCallerAccessGrants.ts
* Fix server side breaking change `<AccessGrantInstance>...</AccessGrantInstance>` to `<AccessGrant>...</AccessGrant>`
* Incorporate latest generated .d.ts change by AWS SDK. All the enum string types used to be `EnumType|string` is changed to more strict `EnumType`.  Moving the enum value validation from the API to custom client.
* Update tests.
Functional test
=> chore(storage): update s3 control model

packages/auth/__tests__/providers/cognito/signOut.test.ts, packages/auth/__tests__/providers/cognito/tokenOrchestrator.test.ts, packages/auth/__tests__/providers/cognito/tokenProvider/tokenOrchestrator.test.ts, packages/auth/__tests__/providers/cognito/utils/oauth/completeOAuthFlow.test.ts, packages/auth/__tests__/providers/cognito/utils/oauth/handleOAuthSignOut.test.ts, packages/auth/src/providers/cognito/apis/signOut.ts, packages/auth/src/providers/cognito/tokenProvider/TokenOrchestrator.ts, packages/auth/src/providers/cognito/tokenProvider/TokenStore.ts, packages/auth/src/providers/cognito/tokenProvider/types.ts, packages/auth/src/providers/cognito/utils/oauth/completeOAuthFlow.ts, packages/auth/src/providers/cognito/utils/oauth/handleOAuthSignOut.ts
This change adds oauth metadata into the token orchestrator. This metadata is set after the user has authenticated via OAuth, and it can be accessed from the current `KeyValueStorage` (LocalStorage, SessionStorage, CookieStorage, etc).
=> chore(auth): add oauth metadata into token orchestrator

packages/auth/__tests__/providers/cognito/signOut.test.ts, packages/auth/__tests__/providers/cognito/tokenOrchestrator.test.ts, packages/auth/__tests__/providers/cognito/tokenProvider/tokenOrchestrator.test.ts, packages/auth/__tests__/providers/cognito/utils/oauth/completeOAuthFlow.test.ts, packages/auth/__tests__/providers/cognito/utils/oauth/handleOAuthSignOut.test.ts, packages/auth/src/providers/cognito/apis/signOut.ts, packages/auth/src/providers/cognito/tokenProvider/TokenOrchestrator.ts, packages/auth/src/providers/cognito/tokenProvider/TokenStore.ts, packages/auth/src/providers/cognito/tokenProvider/types.ts, packages/auth/src/providers/cognito/utils/oauth/completeOAuthFlow.ts, packages/auth/src/providers/cognito/utils/oauth/handleOAuthSignOut.ts
* chore: add oauth metadata into token orchestrator
* chore: add unit tests
* chore: address feedback
=> chore(auth): add oauth metadata into token orchestrator (#13712)

packages/api-graphql/__tests__/AWSAppSyncRealTimeProvider.test.ts, packages/api-graphql/__tests__/GraphQLAPI.test.ts, packages/api-graphql/__tests__/internals/generateClient.test.ts, packages/api-graphql/src/Providers/AWSAppSyncRealTimeProvider/index.ts, packages/api-graphql/src/internals/v6.ts
Today custom request headers set via:
```ts
// client level
generateClient<Schema>({
headers: {
'My-Custom-Header': 'my value',
},
});
// OR
// request level
await client.models.Blog.get(
{ id: 'myBlogId' },
{
headers: {
'My-Custom-Header': 'my value',
},
}
);
```
Get applied to GraphQL requests for queries and mutations. ([Docs link](https://docs.amplify.aws/react/build-a-backend/data/connect-to-API/#set-custom-request-headers))
However, the headers are ignored for subscription connection requests to AppSync, becuase the WebSocket API does not support setting headers directly.
The AppSync team is asking us to give customers a way to pass these through as query string params instead.
E.g.
```ts
await client.models.Blog.onCreate(
{
headers: {
'My-Custom-Header': 'my value',
},
}
);
``` …
=> feat(api-graphql): AppSync realtime - include custom headers as query string params

packages/auth/__tests__/providers/cognito/confirmSignInErrorCases.test.ts, packages/auth/__tests__/providers/cognito/confirmSignInHappyCases.test.ts, packages/auth/src/common/AuthErrorStrings.ts, packages/auth/src/providers/cognito/utils/clients/CognitoIdentityProvider/types.ts, packages/auth/src/providers/cognito/utils/signInHelpers.ts, packages/auth/src/types/models.ts
The purpose of this pull request is to add support for the `CONFIRM_SIGN_IN_WITH_EMAIL_CODE` challenge and selecting `EMAIL` as the delivery destination during the `CONTINUE_SIGN_IN_WITH_MFA_SELECTION` challenge. 
MFA_SETUP challenge will be handled separately.
- Manual testing
- Unit tests
=> [Email MFA] Add support for EMAIL_OTP during sign in flows

packages/aws-amplify/package.json, packages/storage/__tests__/providers/s3/utils/client/s3Data/putObject.test.ts, packages/storage/__tests__/providers/s3/utils/validateObjectUrl.test.ts, packages/storage/src/errors/IntegrityError.ts, packages/storage/src/providers/s3/utils/client/s3data/putObject.ts, packages/storage/src/providers/s3/utils/validateObjectUrl.ts
- Implementing a common error for Durability Issues
- Function to check durability between a presigned url and the source bucket and key.
- Add logic inside PutObject operation to check the durability status.
- Executed environment with `yarn dev`
- Executed unit tests
=> chore(storage): add durability check for presigned urls in put object

packages/aws-amplify/package.json, packages/storage/__tests__/providers/s3/utils/client/S3/cases/getDataAccess.ts, packages/storage/__tests__/providers/s3/utils/client/S3/cases/listCallerAccessGrants.ts, packages/storage/__tests__/providers/s3/utils/client/S3/utils/createRetryDecider.test.ts, packages/storage/__tests__/providers/s3/utils/client/testUtils/types.ts, packages/storage/src/providers/s3/utils/client/s3control/base.ts, packages/storage/src/providers/s3/utils/client/s3control/getDataAccess.ts, packages/storage/src/providers/s3/utils/client/s3control/listCallerAccessGrants.ts, packages/storage/src/providers/s3/utils/client/s3data/abortMultipartUpload.ts, packages/storage/src/providers/s3/utils/client/s3data/base.ts, packages/storage/src/providers/s3/utils/client/s3data/completeMultipartUpload.ts, packages/storage/src/providers/s3/utils/client/s3data/copyObject.ts, packages/storage/src/providers/s3/utils/client/s3data/createMultipartUpload.ts, packages/storage/src/providers/s3/utils/client/s3data/deleteObject.ts, packages/storage/src/providers/s3/utils/client/s3data/getObject.ts, packages/storage/src/providers/s3/utils/client/s3data/headObject.ts, packages/storage/src/providers/s3/utils/client/s3data/listObjectsV2.ts, packages/storage/src/providers/s3/utils/client/s3data/listParts.ts, packages/storage/src/providers/s3/utils/client/s3data/putObject.ts, packages/storage/src/providers/s3/utils/client/s3data/uploadPart.ts, packages/storage/src/providers/s3/utils/client/utils/createRetryDecider.ts, packages/storage/src/providers/s3/utils/client/utils/index.ts, packages/storage/src/providers/s3/utils/client/utils/parsePayload.ts
This change fixes a bug where the S3 control plane API error response not parsed correctly.
Unlike the S3 data plane API, the S3 control plane API wraps the error code and message inside an `<Error>` element. For example:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ErrorResponse>
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
</Error>
<RequestId>123</RequestId>
<HostId>123</HostId>
</ErrorResponse>
```
Whereas the S3 data plane error response looks like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>123</RequestId>
<HostId>123</HostId>
</Error>
```
This difference is modeled by the [`noErrorWraping` API trait](https://smithy.io/2.0/aws/protocols/aws-restxml-protocol.html#restxml-errors …
=> fix(storage-browser): missing error wrapping for s3 control responses

packages/aws-amplify/package.json, packages/storage/__tests__/providers/s3/utils/client/s3Data/abortMutipartUpload.test.ts, packages/storage/__tests__/providers/s3/utils/client/s3Data/deleteObject.test.ts, packages/storage/__tests__/providers/s3/utils/client/s3Data/getObject.test.ts, packages/storage/__tests__/providers/s3/utils/client/s3Data/headObject.test.ts, packages/storage/__tests__/providers/s3/utils/client/s3Data/uploadPart.test.ts, packages/storage/src/providers/s3/utils/client/s3data/abortMultipartUpload.ts, packages/storage/src/providers/s3/utils/client/s3data/deleteObject.ts, packages/storage/src/providers/s3/utils/client/s3data/getObject.ts, packages/storage/src/providers/s3/utils/client/s3data/headObject.ts, packages/storage/src/providers/s3/utils/client/s3data/uploadPart.ts
- Add `validateObjectUrl` function to:
- abortMultipartUpload
- deleteObject
- uploadPart
- getObject
- headObject
- Executed environment with `yarn dev`
- Executed unit tests
=> feat: adding object url checks

.github/integ-config/integ-all.yml, .github/workflows/callable-e2e-test.yml, .github/workflows/callable-e2e-tests.yml, .github/workflows/push-integ-test.yml
The purpose of this pull request is to enable E2E tests for the Email MFA feature as well as introduce a mechanism to allow the test definition to specify which backend configuration the underlying application should use.
Test Run: https://github.com/jjarvisp/amplify-js/actions/runs/10856005455
=> feat(auth): [EMAIL MFA] enable integ tests with backend configuration swapping

.github/CODEOWNERS
=> chore: add ui to storage browser co-owner

packages/storage/__tests__/internals/apis/remove.test.ts, packages/storage/src/internals/apis/remove.ts, packages/storage/src/internals/index.ts, packages/storage/src/internals/types/inputs.ts, packages/storage/src/internals/types/outputs.ts, packages/storage/src/providers/s3/apis/internal/remove.ts
Add new Internal remove API
Tested new internal remove API on testApp locally
=> feat(storage): add new internal remove api

packages/storage/package.json
https://github.com/aws-amplify/amplify-js/issues/13853
When using the library with Expo, and run `npx expo start`, observed that the Storage uses `fetch` instead of `xhr` for making network requests. This caused that the `Storage.get()` returns a non `Blob`, `response.Body`. 
The metro bundler respect the `browser` module in `package.json`, but observed it didn't pick up the resolution during testing. The cause is that the module entry doesn't contain an extension name.
=> fix(storage): browser module resoltuion is not picked up by metro web

packages/storage/__tests__/internals/apis/getUrl.test.ts, packages/storage/src/internals/apis/getUrl.ts, packages/storage/src/internals/index.ts, packages/storage/src/internals/types/inputs.ts, packages/storage/src/internals/types/outputs.ts, packages/storage/src/providers/s3/apis/internal/getUrl.ts
Adds the internal `getUrl` API with credential provider support.
=> chore: Add internal getUrl API

packages/storage/__tests__/internals/apis/downloadData.test.ts, packages/storage/src/internals/apis/downloadData.ts, packages/storage/src/internals/apis/getProperties.ts, packages/storage/src/internals/apis/remove.ts, packages/storage/src/internals/index.ts, packages/storage/src/internals/types/inputs.ts, packages/storage/src/internals/types/outputs.ts, packages/storage/src/providers/s3/apis/downloadData.ts, packages/storage/src/providers/s3/apis/internal/downloadData.ts
- moves existing downloadData implementation from `src/providers/s3/apis/downloadData.ts` to `src/providers/s3/apis/internal/downloadData.ts`
- contains no public interface changes for standard downloadData API
- Adds new **internals/** API at `src/internals/apis/downloadData.ts`
- integ tests locally
- testApp locally
=> feat(storage): add new internal downloadData api

.github/integ-config/integ-all.yml
Temporarily disable failing integ test to unblock pipeline.
=> fix: temporarily disable failing test to unblock pipeline

packages/storage/__tests__/internals/apis/copy.test.ts, packages/storage/__tests__/internals/apis/list.test.ts, packages/storage/src/internals/apis/copy.ts, packages/storage/src/internals/apis/list.ts, packages/storage/src/internals/index.ts, packages/storage/src/internals/types/inputs.ts, packages/storage/src/internals/types/outputs.ts, packages/storage/src/providers/s3/apis/internal/list.ts
Adds an internal wrapper copy function with the new Input type. Type updates were already in place from an earlier PR.
=> feat(storage): add remaining copy changes for internals

packages/storage/src/internals/apis/list.ts, packages/storage/src/internals/index.ts, packages/storage/src/internals/types/inputs.ts
Adds function overloading to list to correct its input output typings. 
Used it in the UI repo
=> fix(storage): internals list function not able to decide which output types to use

packages/storage/__tests__/providers/s3/apis/uploadData/index.test.ts, packages/storage/src/providers/s3/apis/uploadData/index.ts
Check `dataByteLength !== undefined` instead of consuming the falsy 0
- unit tests
=> fix(storage): multipart upload is firing on 0 bytes data

packages/storage/__tests__/internals/apis/copy.test.ts, packages/storage/__tests__/internals/apis/downloadData.test.ts, packages/storage/__tests__/internals/apis/getProperties.test.ts, packages/storage/__tests__/internals/apis/getUrl.test.ts, packages/storage/__tests__/internals/apis/list.test.ts, packages/storage/__tests__/internals/apis/remove.test.ts, packages/storage/__tests__/internals/apis/uploadData.test.ts, packages/storage/src/internals/apis/copy.ts, packages/storage/src/internals/apis/downloadData.ts, packages/storage/src/internals/apis/getProperties.ts, packages/storage/src/internals/apis/getUrl.ts, packages/storage/src/internals/apis/list.ts, packages/storage/src/internals/apis/remove.ts, packages/storage/src/internals/apis/uploadData.ts
Adds the expected bucket owner option to the remaining internal APIs. Also removes doc-strings from some internal APIs to discourage use.
Local testing.
=> feat: Add expectedBucketOwner to remaining internal APIs

packages/storage/__tests__/providers/s3/apis/list.test.ts, packages/storage/src/providers/s3/apis/internal/list.ts
It is a legit case that `ListObjectV2` returns a result that contains only `CommonPrefix[]` and without a `Content`, and `NextContinuationToken` can be returned as well.
The current implementation omits `nextToken` for this case, and makes listing next page impossible.
Fix: surface the `nextToken`
- manual test with a sample app
- unit tests
=> fix(storage): nextToken is not surfaced when list result contain only CommonPrefix

packages/auth/__tests__/providers/cognito/tokenProvider/tokenOrchestrator.test.ts, packages/auth/src/providers/cognito/tokenProvider/TokenOrchestrator.ts, packages/aws-amplify/package.json, packages/core/__tests__/clients/middleware/retry/defaultRetryDecider.test.ts, packages/core/src/clients/middleware/retry/defaultRetryDecider.ts
1. the `isConnectionError` of the `defaultRetryDecider` now detects network errors by looking up the `name` property to match either one of the `[NetworkError, ERR_NETWORK]`
* `NetworkError` is thrown from the fetch transfer handler Core
* `ERR_NETWORK` is thrown from the XHR transfer handler resides in Storage 
2. the `tokenOrchestrator.handleErrors` method now detects network errors by looking up the `name` property to match `NetworkError`, `clearTokens()` shall not be called when the error is a network error
* https://github.com/aws-amplify/amplify-js/issues/13930 (over clearing auth tokens on network error)
* https://github.com/aws-amplify/amplify-js/issues/13908 (retry is not being applied on network errors)
1. manual testing with a Next.js app and a react-native app
2. unit tests
By …
=> release(required): network error has not been properly detected

packages/api-graphql/package.json, packages/api/package.json, packages/auth/package.json, packages/core/package.json, packages/datastore/package.json, yarn.lock
The purpose of this PR is to bump up `universal-cookie` to version `7.2.0` (uses 0.7.2 `cookie`) to avoid vulnerability issue that was discovered on `cookie` with version < `0.7.0`.
=> chore: upgrade universal-cookie version

packages/storage/__tests__/providers/s3/apis/internal/uploadData/index.test.ts, packages/storage/__tests__/providers/s3/apis/internal/uploadData/multipartHandlers.test.ts, packages/storage/__tests__/providers/s3/apis/internal/uploadData/putObjectJob.test.ts, packages/storage/__tests__/providers/s3/utils/getCombinedCrc32.test.ts, packages/storage/src/providers/s3/apis/internal/uploadData/byteLength.ts, packages/storage/src/providers/s3/apis/internal/uploadData/index.ts, packages/storage/src/providers/s3/apis/internal/uploadData/multipart/initialUpload.ts, packages/storage/src/providers/s3/apis/internal/uploadData/multipart/uploadHandlers.ts, packages/storage/src/providers/s3/apis/internal/uploadData/putObjectJob.ts
- Simplify string size evaluation in `byteLength` to align with upload part generator. When validating parts, it's required to have the same size calculation. Other data types are already aligned.
- Before sending CompleteMultipartUpload, validate that we have all expected parts based on object size.
- New unit tests mocking cache to create invalid parts
=> feat: validate uploaded parts before completing upload

packages/api-graphql/__tests__/AWSAppSyncEventProvider.test.ts, packages/api-graphql/__tests__/helpers.ts, packages/api-graphql/src/Providers/AWSAppSyncEventsProvider/index.ts, packages/api-graphql/src/Providers/AWSWebSocketProvider/index.ts, packages/api-graphql/src/internals/events/index.ts
`events.closeAll()` is intended to close the WS connection, disconnect listeners and reconnect observers. However, the underlying `AWSWebSocketProvider.close()` method does all of the above, except for close the WS connection. 
To limit the blast radius of this change, this PR only modifies the `AWSAppSyncEventProvider` sub class, closing the WS connection on `close()` and leaves the AppSyncRealTimeProvider unchanged.
https://github.com/aws-amplify/amplify-js/issues/13984
* Manual
* Added fn test
=> fix(api-graphql): close WS on events.closeAll

packages/api-graphql/src/Providers/AWSAppSyncEventsProvider/index.ts, packages/api-graphql/src/Providers/AWSWebSocketProvider/index.ts
Applying change from #13989 to the base class. 
Verified that this does not affect the Realtime provider. `.close()` is not accessible publicly and is not invoked internally on that provider. 
* Code review
* Unit tests pass
* E2Es pass: https://github.com/aws-amplify/amplify-js/actions/runs/11709500317
=> refactor(api-graphql): apply WS.close to base class

packages/core/src/clients/internal/composeServiceApi.ts, packages/storage/src/providers/s3/utils/client/s3control/base.ts
=> fix(core): support endpoint resolver accepting both input and config

packages/api-graphql/src/Providers/AWSAppSyncEventsProvider/index.ts, packages/api-graphql/src/Providers/AWSAppSyncRealTimeProvider/index.ts, packages/api-graphql/src/Providers/AWSWebSocketProvider/index.ts
Sigv4 calculation for Event API WS Connect was incorrectly appending a `/connect` path to the request URL. This is required for GQL Realtime WS Connect, but breaks for Event API. 
https://github.com/aws-amplify/amplify-js/issues/14001
* Manual - events & graphql realtime WS connect & sub with IAM/IdP
* E2Es: https://github.com/aws-amplify/amplify-js/actions/runs/11804564727
=> fix(api-graphql): events ws connect sig

packages/storage/__tests__/providers/s3/apis/internal/list.test.ts, packages/storage/__tests__/providers/s3/utils/client/S3/cases/listObjectsV2.ts, packages/storage/src/providers/s3/apis/internal/list.ts, packages/storage/src/providers/s3/types/options.ts, packages/storage/src/providers/s3/utils/client/s3data/listObjectsV2.ts, packages/storage/src/providers/s3/utils/index.ts, packages/storage/src/providers/s3/utils/urlDecoder.ts
- Set [encoding type](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html#AmazonS3-ListObjectsV2-response-EncodingType) to `url` for list requests.
- Decode output values.
- Added unit tests
=> feat: use url encoding type for list calls

packages/core/__tests__/parseAmplifyOutputs.test.ts, packages/core/src/singleton/AmplifyOutputs/types.ts
Amplify configure with auth user groups throws a type error `not assignable to type 'Record<string, UserGroupPrecedence>[]'`. This PR loosens this type to avoid this error.
#14045
- Tested that the following with `amplify.configure` does not throw any type error
```
"auth": {
"groups": [
{
"ADMIN": { "precedence": 0 },
"USER": { "precedence": 1 }
},
{
"USER": { "precedence": 0 }
},
{
"TEST": { "precedence": 2 },
"USER": { "precedence": 1 },
"ADMIN": { "precedence": 0 }
}
],
```
- `amplify.getConfig` returns the correct config
=> fix: amplify configure with auth userGroups

packages/rtn-push-notification/android/build.gradle
Fix wrong namespace.
https://github.com/aws-amplify/amplify-js/issues/14059
Manually build android app with installing the locally modified `@aws-amplify/rtn-push-notification` package and verify that `npm run android` can build the native Android host app with react-native versions:
1. 0.73.6 
2. 0.70.0
=> fix(rtn-push-notification): wrong namespace is being used

.github/workflows/callable-canary-e2e.yml, .github/workflows/callable-e2e-test-detox.yml, .github/workflows/callable-release-verification.yml
=> chore: downgrade to macos-13 runner to let test passing with older detox version

.github/workflows/callable-canary-sampleapp-tests.yml
With the release of[ npm 11.0.0](https://github.com/npm/cli/releases/tag/v11.0.0), canary builds started failing with 
```Run npm install -g npm@latest
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: npm@11.0.0
npm ERR! notsup Not compatible with your version of node/npm: npm@11.0.0
npm ERR! notsup Required: {"node":"^20.17.0 || >=22.9.0"}
npm ERR! notsup Actual:   {"npm":"[10](https://github.com/aws-amplify/amplify-js/actions/runs/12356454590/job/34494840473#step:16:11).5.0","node":"v18.20.2"}
```
We don't need to install the latest version of npm, as we're setting up required node/npm versions earlier in the action. Removing `npm install -g npm@latest` fixes the issue.
- Run build script locally
- Run tests …
=> fix(ci): canary test failure on npm install

packages/adapter-nextjs/src/auth/createAuthRouteHandlersFactory.ts, packages/adapter-nextjs/src/auth/types.ts
Make the public handler function type as any to let the single function to be compatible with the type checks that happens in both the App router and Pages router.
* Runtime validation on the handler parameters are enforced.
* `npx next build`
=> fix(adapter-nextjs): make createAuthRouteHandlers interface work in both App and Pages routers

packages/adapter-nextjs/__tests__/auth/handlers/handleSignInCallbackRequest.test.ts, packages/adapter-nextjs/__tests__/auth/handlers/handleSignInCallbackRequestForPagesRouter.test.ts, packages/adapter-nextjs/__tests__/auth/handlers/handleSignInSignUpRequest.test.ts, packages/adapter-nextjs/__tests__/auth/handlers/handleSignInSignUpRequestForPagesRouter.test.ts, packages/adapter-nextjs/__tests__/auth/handlers/handleSignOutCallbackRequest.test.ts, packages/adapter-nextjs/__tests__/auth/handlers/handleSignOutCallbackRequestForPagesRouter.test.ts, packages/adapter-nextjs/__tests__/auth/handlers/handleSignOutRequest.test.ts, packages/adapter-nextjs/__tests__/auth/handlers/handleSignOutRequestForPagesRouter.test.ts, packages/adapter-nextjs/__tests__/auth/utils/authFlowProofCookies.test.ts, packages/adapter-nextjs/__tests__/auth/utils/tokenCookies.test.ts, packages/adapter-nextjs/__tests__/utils/createCookieStorageAdapterFromNextServerContext.test.ts, packages/adapter-nextjs/src/auth/constant.ts, packages/adapter-nextjs/src/auth/utils/authFlowProofCookies.ts, packages/adapter-nextjs/src/auth/utils/tokenCookies.ts, packages/adapter-nextjs/src/types/NextServer.ts, packages/adapter-nextjs/src/utils/cookie/serializeCookie.ts, packages/aws-amplify/__tests__/adapterCore/storageFactories/createKeyValueStorageFromCookieStorageAdapter.test.ts, packages/aws-amplify/src/adapter-core/constants.ts, packages/aws-amplify/src/adapter-core/index.ts, packages/aws-amplify/src/adapter-core/storageFactories/createKeyValueStorageFromCookieStorageAdapter.ts
Use `maxAge` cookie attribute to set cookies from the server side to avoid clock drift issues.
Since the access token usage are carried onto the server-side, and tokens expiries check and refresh are all performed on the server side of a Next.js app, the client-side incorrect system time becomes irrelevant. 
* unit tests
* manual tests with a Next.js sample app
=> refactor(adapter-nextjs): use maxAge attribute to set cookie from server to avoid clock drift

packages/adapter-nextjs/__tests__/auth/handleAuthApiRouteRequestForAppRouter.test.ts, packages/adapter-nextjs/__tests__/auth/handleAuthApiRouteRequestForPagesRouter.test.ts, packages/adapter-nextjs/__tests__/auth/handlers/handleSignInCallbackRequest.test.ts, packages/adapter-nextjs/__tests__/auth/handlers/handleSignInCallbackRequestForPagesRouter.test.ts, packages/adapter-nextjs/__tests__/auth/handlers/handleSignOutCallbackRequest.test.ts, packages/adapter-nextjs/__tests__/auth/handlers/handleSignOutCallbackRequestForPagesRouter.test.ts, packages/adapter-nextjs/__tests__/auth/utils/cognitoHostedUIEndpoints.test.ts, packages/adapter-nextjs/__tests__/auth/utils/getRedirectOrDefault.test.ts, packages/adapter-nextjs/src/auth/handleAuthApiRouteRequestForAppRouter.ts, packages/adapter-nextjs/src/auth/handleAuthApiRouteRequestForPagesRouter.ts, packages/adapter-nextjs/src/auth/handlers/handleSignInCallbackRequest.ts, packages/adapter-nextjs/src/auth/handlers/handleSignInCallbackRequestForPagesRouter.ts, packages/adapter-nextjs/src/auth/handlers/handleSignOutCallbackRequest.ts, packages/adapter-nextjs/src/auth/handlers/handleSignOutCallbackRequestForPagesRouter.ts, packages/adapter-nextjs/src/auth/utils/getRedirectOrDefault.ts, packages/adapter-nextjs/src/auth/utils/index.ts
Remove wrong usage of nullish coalescing.
- unit tests
=> fix(adapter-nextjs): wrong use of nullish coalescing

packages/adapter-nextjs/__tests__/auth/createAuthRouteHandlersFactory.test.ts, packages/adapter-nextjs/src/auth/createAuthRouteHandlersFactory.ts
Check app origin env var and required auth configuration only when the `createAuthRouteHandlers` function gets called to create the Auth API routes. 
The original spot for checking these was too early and breaks `createServerRunner` function call during build step.
With this change - if app origin env var is not provided, or Auth config is incorrect, the error can still be surfaced during the build step (when `createAuthRouteHandlers` is actually used).
- unit tets
- manual test with a sample app
=> fix(adapter-nextjs): wrong spot for checking app origin and auth config

packages/adapter-nextjs/__tests__/auth/utils/predicates.test.ts, packages/adapter-nextjs/src/auth/handleAuthApiRouteRequestForAppRouter.ts, packages/adapter-nextjs/src/auth/types.ts, packages/adapter-nextjs/src/auth/utils/predicates.ts
Removed the actual callsite of the Next.js `params` API that turned into async since Next.js 15. The callsite was a type assertion, which was actually unnecessary as we expected the `slug` is a property of the `params`.
Also updated the necessary callsite of `params` with `await`.
- unit tests
- manual test with a Next.js v15/v14 sample app
=> fix(adapter-nextjs): not await params async API in Next.js 15

.github/integ-config/integ-all.yml
Adds [multi-endpoint e2e](https://github.com/aws-amplify/amplify-js-samples-staging/pull/1036) to workflow
E2E was tested in GHA in the samples repo ([run](https://github.com/aws-amplify/amplify-js-samples-staging/actions/runs/12692896606/job/35379295594))
=> chore(data): add multi endpoint e2e to workflow

.github/workflows/push-preid-release.yml, packages/auth/package.json
Added missing dependencies
https://github.com/aws-amplify/amplify-js/issues/13024
- replicated issue using npm@8 & vite starter template
- npm install aws-amplify preid version `6.12.1-crypto-dep-fix.c868501.0`
- install works
- app runs
=> fix(deps): avoid using implicit dependencies for auth

packages/auth/__tests__/providers/cognito/signInWithRedirect.test.ts, packages/auth/src/providers/cognito/apis/signInWithRedirect.ts, packages/auth/src/types/inputs.ts
This adds support for the login_hint, lang and nonce parameters, which are supported by cognito as of the official documentation https://docs.aws.amazon.com/cognito/latest/developerguide/authorization-endpoint.html 
The way to pass them is by adding them as extra options under the input parameters on the `signInWithRedirect` function
```js
await signInWithRedirect({
provider: 'Google',
options: {
loginHint: 'someone@gmail.com',
lang: 'en',
nonce: '88388838883',
},
});
```
Adding login_hint would fix #8951
Possible fix by adding nonce #4998
Support lang attribute #14040 
- I added a unit tests to verify that when the parameters are passed they end up in the URL
- I created a sample app to test the changes and verified that they are working against 2 providers, Okta and Azure.
By submitting …
=> feat(Auth): Allow sending login_hint, lang and nonce on signInWithRedirects

packages/core/__tests__/utils/generateRandomString.test.ts, packages/core/src/utils/generateRandomString.ts
Update the existing `generateRandomString()` implementation to use `crypto.getRandomValues()`.
- unit tests
- manual testing with a sample app integrating Hosted UI.
=> fix(core): generateRandomString uses Math.random()

packages/amazon-cognito-identity-js/package.json
Currently all packages published from the `v5-stable` branch are using the `--dist-tag v5-stable`, however, for the legacy `amazon-cognito-identity-js` package, the newly published version should use `--dist-tag latest`. 
Added a `postpublish` script to point the last released version to the `latest` tag.
=> fix(amazon-cognito-identity-js): not using latest tag

packages/aws-amplify/package.json, packages/storage/__tests__/providers/s3/apis/internal/uploadData/multipartHandlers.test.ts, packages/storage/src/providers/s3/apis/internal/uploadData/multipart/uploadCache.ts, packages/storage/src/providers/s3/apis/internal/uploadData/multipart/uploadHandlers.ts
From https://github.com/aws-amplify/amplify-js/pull/13931, we added a internally-injected option `resumableUploadsCache ` for public uploadData API. However, the default value of this option `KeyValueStorage` has a reference to the `LocalStorage` instance. 
This causes that the hash value of uploadData options keeps changing, as the `LocalStorage` value keep changing. This fix adds a list of options that should NOT be hashed when calculating the options hash. Any new options will be added options hash by default.
#14149 
Unit test; Manual integ test
=> fix(storage): omit unserializable properties when hash uploadDataOptions

packages/adapter-nextjs/__tests__/auth/handlers/handleSignOutCallbackRequest.test.ts, packages/adapter-nextjs/__tests__/auth/handlers/handleSignOutCallbackRequestForPagesRouter.test.ts, packages/adapter-nextjs/src/auth/handlers/handleSignOutCallbackRequest.ts, packages/adapter-nextjs/src/auth/handlers/handleSignOutCallbackRequestForPagesRouter.ts
Generating `Set-Cookie` headers for only previous set cookies in server-side auth signOut flow. 
In particular:
1. `.accessToken`
2. `.idToken`
3. `.refreshToken`
4. `.LastAuthUser`
5. `isSigningOut` flag
=> fix(adapter-nextjs): removing only tokens and LastAuthUser cookies

packages/adapter-nextjs/src/types/NextServer.ts
=> chore(adapter-nextjs): update tsdoc of the public APIs

CONTRIBUTING.md
Update the recommended node version in contributing.md
Currently the recommended version is `16.19.0` which throws the following error.
```
error @eslint/compat@1.2.0: The engine "node" is incompatible with this module. Expected version "^18.18.0 || ^20.9.0 || >=21.1.0". Got "16.19.0"
error Found incompatible module.
```
=> chore: update node version in contributing

packages/adapter-nextjs/package.json, packages/core/package.json, packages/core/src/adapterCore/serverContext/types/cookieStorage.ts, yarn.lock
Remove the `cookie` and `@types/cookie` (has been deprecated) dependencies and build-in the `CookieSerializeOptions` type definition.
https://github.com/aws-amplify/amplify-js/issues/14212
- Run codebase build
- Publish the package to local registry and test with a next.js sample app
=> fix(core): build in CookieSerializeOptions def

packages/auth/__tests__/foundation/factories/serviceClients/cognitoIdentityProvider/shared/serde/createUserPoolDeserializer.test.ts, packages/auth/__tests__/providers/cognito/credentialsProvider.test.ts, packages/auth/__tests__/providers/cognito/identityIdProvider.test.ts, packages/auth/src/foundation/factories/serviceClients/cognitoIdentityProvider/shared/serde/createUserPoolDeserializer.ts, packages/auth/src/providers/cognito/credentialsProvider/IdentityIdProvider.ts, packages/auth/src/providers/cognito/credentialsProvider/credentialsProvider.ts, packages/core/__tests__/awsClients/cognitoIdentity/getCredentialsForIdentity.test.ts, packages/core/__tests__/awsClients/cognitoIdentity/getId.test.ts, packages/core/src/clients/serde/json.ts, packages/core/src/clients/types/aws.ts, packages/core/src/clients/types/index.ts, packages/core/src/errors/AmplifyError.ts, packages/core/src/types/errors.ts
* Add an optional `metadata` property to the base `AmplifyError` class and `AuthError` class. So customers can inspect the requestId if an AuthError is caused by a service error response.
* Update the error parser to populate the `metadata` property when parsing error responses from services. Previously it sets  purely internal`$metadata` property. 
* Fix the 2 identity pool APIs(`GetId`, `GetCredentialsForId`) to throw AuthError. Previously, the 2 APIs throw the base `Error` instance.
* Update the unit test for identity pool and user pool APIs to verify they all throw `AuthError`.
Unit tests
=> feat(auth): throw extended AuthError for service errors from user pool & id pool

packages/adapter-nextjs/__tests__/auth/handlers/handleSignInCallbackRequest.test.ts, packages/adapter-nextjs/__tests__/auth/handlers/handleSignInCallbackRequestForPagesRouter.test.ts, packages/adapter-nextjs/__tests__/auth/handlers/handleSignInSignUpRequest.test.ts, packages/adapter-nextjs/__tests__/auth/handlers/handleSignInSignUpRequestForPagesRouter.test.ts, packages/adapter-nextjs/__tests__/auth/handlers/handleSignOutRequest.test.ts, packages/adapter-nextjs/__tests__/auth/handlers/handleSignOutRequestForPagesRouter.test.ts, packages/adapter-nextjs/__tests__/auth/utils/authFlowProofCookies.test.ts, packages/adapter-nextjs/__tests__/auth/utils/tokenCookies.test.ts, packages/adapter-nextjs/src/auth/handlers/handleSignInCallbackRequest.ts, packages/adapter-nextjs/src/auth/handlers/handleSignInCallbackRequestForPagesRouter.ts, packages/adapter-nextjs/src/auth/handlers/handleSignInSignUpRequest.ts, packages/adapter-nextjs/src/auth/handlers/handleSignInSignUpRequestForPagesRouter.ts, packages/adapter-nextjs/src/auth/handlers/handleSignOutRequest.ts, packages/adapter-nextjs/src/auth/handlers/handleSignOutRequestForPagesRouter.ts, packages/adapter-nextjs/src/auth/utils/authFlowProofCookies.ts, packages/adapter-nextjs/src/auth/utils/tokenCookies.ts
* Move the `secure` cookie attribute value calculation into the functions that actually generate the cookie attributes to prevent misses
- local testing with a Next.js sample app running on localhost
- e2e test
=> fix(adapter-nextjs): secure: false is not set for localhost on sign-in

packages/storage/__tests__/providers/s3/utils/client/S3/cases/completeMultipartUpload.ts, packages/storage/__tests__/providers/s3/utils/client/S3/cases/getDataAccess.ts, packages/storage/__tests__/providers/s3/utils/client/S3/cases/listCallerAccessGrants.ts, packages/storage/__tests__/providers/s3/utils/client/S3/cases/listObjectsV2.ts, packages/storage/__tests__/providers/s3/utils/client/s3Data/createMultipartUpload.test.ts, packages/storage/__tests__/providers/s3/utils/client/testUtils/types.ts, packages/storage/src/errors/IntegrityError.ts, packages/storage/src/internals/apis/getDataAccess.ts, packages/storage/src/internals/apis/listCallerAccessGrants.ts, packages/storage/src/providers/s3/apis/internal/list.ts, packages/storage/src/providers/s3/apis/internal/uploadData/multipart/uploadHandlers.ts, packages/storage/src/providers/s3/utils/client/s3control/getDataAccess.ts, packages/storage/src/providers/s3/utils/client/s3control/listCallerAccessGrants.ts, packages/storage/src/providers/s3/utils/client/s3data/abortMultipartUpload.ts, packages/storage/src/providers/s3/utils/client/s3data/completeMultipartUpload.ts, packages/storage/src/providers/s3/utils/client/s3data/copyObject.ts, packages/storage/src/providers/s3/utils/client/s3data/createMultipartUpload.ts, packages/storage/src/providers/s3/utils/client/s3data/deleteObject.ts, packages/storage/src/providers/s3/utils/client/s3data/getObject.ts, packages/storage/src/providers/s3/utils/client/s3data/headObject.ts, packages/storage/src/providers/s3/utils/client/s3data/listObjectsV2.ts, packages/storage/src/providers/s3/utils/client/s3data/listParts.ts, packages/storage/src/providers/s3/utils/client/s3data/putObject.ts, packages/storage/src/providers/s3/utils/client/s3data/uploadPart.ts, packages/storage/src/providers/s3/utils/client/utils/deserializeHelpers.ts
* Add `metadata` to `StorageError`, and make sure all the error thrown caused by erroneous responses includes `metadata`.
* Remove extra `recoverySuggestion` from 404 error
Unit test
=> feat(storage): emit response metadata in applicable error throw sites

packages/api-rest/__tests__/apis/common/publicApis.test.ts, packages/api-rest/src/apis/common/publicApis.ts, packages/api-rest/src/types/index.ts
This PR changes the placement of `retryStrategy` within the individual `api` calls. 
Before: 
```
get(amplify, {
apiName: 'restApi1',
path: 'items',
retryStrategy: {
strategy: 'no-retry',
}
}
```
After: 
```
get(amplify, {
apiName: 'restApi1',
path: 'items',
options: {
retryStrategy: {
strategy: 'no-retry',
}
}
}
```
=> release(required): fix retryStrategy parameter location

packages/adapter-nextjs/__tests__/auth/utils/createUrlSearchParams.test.ts, packages/adapter-nextjs/src/auth/utils/createUrlSearchParams.ts
Now support appending a `lang` query parameter to the generated `/sign-in` and `sign-up` routes for changing [the localization of the Amazon Cognito Managed Login page](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-managed-login.html). 
https://github.com/aws-amplify/amplify-js/issues/14316
- unit tests
- manual testing with Next.js sample apps built with App Router and Pages Router respectively
=> feat(adapter-nextjs): support sending lang param to managed login

.github/workflows/on-schedule-canary-test.yml
The purpose of this PR is reschedule canary to run 1 hour earlier to determine whether installation failures due to server errors are caused by GH action throttling.
=> chore: reschedule canary

package.json, packages/analytics/package.json, packages/api-graphql/package.json, packages/api-rest/package.json, packages/api/package.json, packages/auth/package.json, packages/aws-amplify/package.json, packages/core/package.json, packages/geo/package.json, packages/interactions/package.json, packages/notifications/package.json, packages/pubsub/package.json, packages/storage/package.json
React native 0.79 now resolves module by looking up the `exports` define in the `package.json` by default. Amplify packages that required subpath aliases have set up the `exports` fields with adding `react-native` condition. However, it appears to that the `react-native` condition has to be placed on before `import` so that metro bundler can resolve modules from correct paths.
https://github.com/aws-amplify/amplify-js/issues/14352
=> release(required): fix react-native exports condition order

package.json, packages/adapter-nextjs/package.json, packages/analytics/package.json, packages/api-graphql/package.json, packages/api-rest/package.json, packages/api/__tests__/API.test.ts, packages/api/package.json, packages/auth/__tests__/mockData.ts, packages/auth/package.json, packages/auth/src/providers/cognito/utils/oauth/getRedirectUrl.ts, packages/aws-amplify/package.json, packages/core/package.json, packages/datastore-storage-adapter/package.json, packages/datastore/__tests__/conflictResolutionBehavior.test.ts, packages/datastore/package.json, packages/geo/package.json, packages/interactions/package.json, packages/notifications/package.json, packages/predictions/package.json, packages/pubsub/package.json, packages/react-native/package.json, packages/rtn-push-notification/package.json, packages/rtn-web-browser/package.json, packages/storage/package.json, yarn.lock
We can now use typescript 5.3.x across the workspace.
=> chore(workspace): use typescript ^5.3.0 across the workspace

packages/api-graphql/__tests__/AWSAppSyncEventProvider.test.ts, packages/api-graphql/src/Providers/AWSAppSyncEventsProvider/index.ts
This PR fix the race condition between web socket connection and subsequent publish event while using AppSyncEvents. 
Before this change, the web socket connection Promise is resolve while the connection is still being established. It allows subsequent publish event calls to the web socket connection is ready.
Now the web socket connection Promise will be resolved only when the connection is established completely.
Run [unit, E2E tests](https://github.com/aws-amplify/amplify-js/actions/runs/15758916563) and verified manually that WebSocket connection is established before any event is being published.
=> fix: await AppSyncEvent WebSocket connection establishment

packages/adapter-nextjs/__tests__/auth/utils/predicates.test.ts, packages/adapter-nextjs/src/auth/utils/predicates.ts
The instanceof Request type guard check fails in AWS Lambda environments (specifically with OpenNext/SST 
deployments). The problem causes authentication API routes to work on cold Lambda starts but fail on subsequent warm invocations with a 500 error: "Invalid request and context/response 
combination. The request cannot be handled." This PR changes the check to use duck typing to prevent possible constructor references to differ between invocations.
[14455](https://github.com/aws-amplify/amplify-js/issues/14455)
* Units tests
* Deployed sample app and verified manually
* [E2E test](https://github.com/aws-amplify/amplify-js/actions/runs/16265824550) run successfull
**  Failing tests unrelated
By submitting this pull request, I confirm that my contribution is made under the terms of the …
=> fix: next request check for serverless environments

.github/actions/node-and-build/action.yml
This PR updates Node to version 22 for our workflows. Currently, the build is failing due to metro-config requiring node 22.
* Run [E2E tests](https://github.com/aws-amplify/amplify-js/actions/runs/16366007132)
- [] Unit Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
=> chore: update node version in node and build workflow

packages/auth/__tests__/providers/cognito/signInWithRedirect.test.ts, packages/auth/src/providers/cognito/apis/signInWithRedirect.ts, packages/auth/src/types/inputs.ts
This PR adds support for the optional  prompt parameter ([authorization-endpoint.html](https://docs.aws.amazon.com/cognito/latest/developerguide/authorization-endpoint.html)) to signInWithRedirect. 
The prompt parameter is a part of the OpenID Connect (OIDC) specification and allows clients to request specific authentication flows from the authorization server. It requires that the managed branding (and not hosted ui classic) to be set in the user pool.
We already had a PR that was adding the `login` prompt but decided to support all prompt values.
The signInWithRedirect works by generating an URL that is invoked. We can add the prompt parameter to that URL by appending it to the dictionary. 
Also, as we currently block requests to signInWithRedirect if the user is already logged in, we …
=> feat(auth): add prompt parameter to signInWithRedirect

packages/auth/__tests__/providers/cognito/signInWithRedirect.test.ts, packages/auth/src/providers/cognito/apis/signInWithRedirect.ts, packages/auth/src/types/inputs.ts
This PR introduces a new option to the `signInWithRedirect` function.
The option is called `authSessionOpener` and allows customization on how to manage opening the authentication url for external identity providers.
https://github.com/aws-amplify/amplify-js/issues/12895
**Documentation PR**
https://github.com/aws-amplify/docs/pull/8376
In a sample app i have used external identity providers setup in my cognito configuration and overidden the URL handling using the new option, by opening a popup.
```ts title="src/example.js"
import { signInWithRedirect } from 'aws-amplify/auth';
await signInWithRedirect({
provider: 'Google',
options: {
authSessionOpener: (url: string) => {
window.open(url, "_blank", "popup")
}
}
});
```
By submitting this pull request, I confirm that my contribution is …
=> feat: make authSessionOpener configurable

packages/api-rest/__tests__/utils/resolveHeaders.test.ts, packages/api-rest/src/utils/resolveHeaders.ts
This PR enables setting json compatible content types.
#14092 
Unit tests, [E2E tests](https://github.com/aws-amplify/amplify-js/actions/runs/16592882592)
=> feat: allow setting json compatible content types

.github/workflows/pr-approved.yml, .github/workflows/pr-community-response.yml, .github/workflows/pr-maintainer-feedback.yml, .github/workflows/pr-opened.yml
=> Add PR labeling workflows for testing

package.json, yarn.lock
Fix vulnerability in tmp package by forcing non-vulnerable version in package.json
https://github.com/aws-amplify/amplify-js/security/dependabot/127
Ran `yarn audit`
=> chore(deps): tmp@^0.2.4

packages/api-graphql/__tests__/AWSAppSyncEventProvider.test.ts, packages/api-graphql/src/Providers/AWSWebSocketProvider/index.ts, packages/api-graphql/src/Providers/constants.ts
AppSync Events subscribe_error messages (like authorization failures) weren't being handled, so error callbacks never fired. Subscriptions failed silently.
Added EVENT_SUBSCRIBE_ERROR to the error handling logic so these messages properly trigger the observer's error callback.
Before:
```typescript
const sub = channel.subscribe({
error: (err) => console.error('error', err), // Never called
})
```
After:
```typescript
const sub = channel.subscribe({
error: (err) => console.error('error', err), // Now properly called on subscribe errors
})
```
e2e, yarn test
- [ x] PR description included
- [x ] `yarn test` passes
- [ x] Unit Tests are added
=> fix: account for EVENT_SUBSCRIBE_ERROR in AppSync

packages/storage/__tests__/providers/s3/utils/client/runtime/xhrTransferHandler-util.test.ts, packages/storage/src/providers/s3/utils/client/runtime/xhrTransferHandler.ts
This PR attempts to mitigate an issue caused by a bug in Expo 53 ( https://github.com/expo/expo/issues/37526 ) by clamping the values for `event.loaded` so as to not exceed the total, while we dig deeper to investigate the root cause in Expo for Android.
Note: This can be reproduced [without using Amplify](https://github.com/pranavosu/expo-bug-onprogress-repro).
https://github.com/aws-amplify/amplify-js/issues/14421
Tested locally using an Android simulator, and added unit tests.
=> fix(storage): upload progress exceeds total in Expo/RN

.github/actions/setup-samples-staging/action.yml, .github/integ-config/integ-all.yml, .github/workflows/push-integ-test.yml
Enable retries for e2e tests, as well as yarn install step for sample staging repo, which fails occasionally.
Run e2e tests with the updated github workflow: https://github.com/aws-amplify/amplify-js/actions/runs/17043975986
=> chore: enable retry for e2e tests

.github/workflows/close-stale-issues.yml
- Adding a bot to close stale issues with the `pending-community-response`
- I added a `debug-only` flag to dry-run the workflow first to verify it. I will remove that flag in a follow-up PR once I confirm it runs successfully.
=> chore: add stale issue bot
